// Auto-generated from yplot.yaml - DO NOT EDIT
// Uniform accessors - read from uniforms struct generated by binder
// Buffer accessors - read from storage buffer

// Uniform accessors

fn yplot_get_bounds_x() -> f32 {
    return uniforms.yplot_bounds_x;
}

fn yplot_get_bounds_y() -> f32 {
    return uniforms.yplot_bounds_y;
}

fn yplot_get_bounds_w() -> f32 {
    return uniforms.yplot_bounds_w;
}

fn yplot_get_bounds_h() -> f32 {
    return uniforms.yplot_bounds_h;
}

fn yplot_get_x_min() -> f32 {
    return uniforms.yplot_x_min;
}

fn yplot_get_x_max() -> f32 {
    return uniforms.yplot_x_max;
}

fn yplot_get_y_min() -> f32 {
    return uniforms.yplot_y_min;
}

fn yplot_get_y_max() -> f32 {
    return uniforms.yplot_y_max;
}

fn yplot_get_flags() -> u32 {
    return uniforms.yplot_flags;
}

fn yplot_get_function_count() -> u32 {
    return uniforms.yplot_function_count;
}

fn yplot_get_colors(idx: u32) -> u32 {
    // Array uniform: yplot_colors_0 through yplot_colors_7
    // Access via switch since WGSL doesn't support dynamic struct field access
    switch idx {
        case 0u: { return uniforms.yplot_colors_0; }
        case 1u: { return uniforms.yplot_colors_1; }
        case 2u: { return uniforms.yplot_colors_2; }
        case 3u: { return uniforms.yplot_colors_3; }
        case 4u: { return uniforms.yplot_colors_4; }
        case 5u: { return uniforms.yplot_colors_5; }
        case 6u: { return uniforms.yplot_colors_6; }
        case 7u: { return uniforms.yplot_colors_7; }
        default: { return uniforms.yplot_colors_0; }
    }
}

// `time` — server-side uniform, written CPU-side by a companion
// TU straight into the instance RS (never on the wire). Always present in
// the uniform buffer; reads its zero-default until something writes it.
fn yplot_get_time() -> f32 {
    return uniforms.yplot_time;
}

// ---- storage layout helpers (merged storage region) ----

// Length of the bytecode block (in u32 words); data starts right after
// its length word.
fn yplot_bytecode_len() -> u32 {
    return storage_buffer[0u];
}
fn yplot_bytecode_offset() -> u32 {
    return 0u + 1u;
}

// Word index of the data_count u32 (right after the fixed blocks).
fn yplot_data_count_offset() -> u32 {
    return yplot_bytecode_offset() + yplot_bytecode_len();
}

// Number of data buffers carried by this instance (0 is valid).
fn yplot_data_count() -> u32 {
    return storage_buffer[yplot_data_count_offset()];
}

// Buffer data is in storage_buffer (binding 1+)
// Access via: storage_buffer[offset]

