/*
 * ygui-widget.c — base widget class.
 *
 * Every widget inherits from this class. It owns:
 *   - geometry: rect (absolute target pixels)
 *   - layout struct (flex / CSS authoring values)
 *
 * Declares public stubs for the widget-level virtual methods (on_press,
 * on_release, on_motion, emit_container, emit_body, paint) and provides
 * default implementations driven by the class's `figure_kind`:
 *
 *   - emit_container default: if figure_kind != 0, write CREATE_CHILD
 *     into the container records stream. Else no-op.
 *   - emit_body default: if figure_kind == 0, open CMD_GROUP in the
 *     ygrid body, invoke paint, close. Else no-op (the figure widget
 *     overrides emit_body to write figure-specific bytes).
 *   - paint default: no-op.
 *   - on_press / on_release / on_motion default: not-consumed (returns 0).
 */

#include "internal.h"

#include <yetty/yfigure/wire.h>
#include <string.h>

/*===========================================================================
 * Widget per-class data slice.
 *=========================================================================*/

struct yetty_ygui_widget_data {
    struct yetty_ycore_rectangle rect;
    struct yetty_ygui_layout layout;
};

/*===========================================================================
 * Method stubs — public addresses that serve as method ids.
 *
 * Each stub's signature is unique (different arg lists, different return
 * types), so the boilerplate is written out by hand per method rather
 * than auto-generated by macro.
 *=========================================================================*/

struct yetty_ycore_int_result yetty_ygui_widget_on_press(struct yetty_ygui_object *obj, float x,
                                                         float y, int button)
{
    static yetty_ygui_method_slot slot = YETTY_YGUI_METHOD_SLOT_UNDEFINED;
    if (slot == YETTY_YGUI_METHOD_SLOT_UNDEFINED) {
        slot = yetty_ygui_method_slot_get((yetty_ygui_method_id_t)yetty_ygui_widget_on_press);
    }
    if (!obj) {
        return YETTY_ERR(yetty_ycore_int, "yetty_ygui_widget_on_press: NULL obj");
    }
    yetty_ygui_impl_t impl = yetty_ygui_class_dispatch_lookup(obj->klass, slot);
    if (!impl) {
        return YETTY_OK(yetty_ycore_int, 0);
    }
    typedef struct yetty_ycore_int_result (*fn_t)(struct yetty_ygui_object *, float, float, int);
    return ((fn_t)impl)(obj, x, y, button);
}

struct yetty_ycore_int_result yetty_ygui_widget_on_release(struct yetty_ygui_object *obj, float x,
                                                           float y, int button)
{
    static yetty_ygui_method_slot slot = YETTY_YGUI_METHOD_SLOT_UNDEFINED;
    if (slot == YETTY_YGUI_METHOD_SLOT_UNDEFINED) {
        slot = yetty_ygui_method_slot_get((yetty_ygui_method_id_t)yetty_ygui_widget_on_release);
    }
    if (!obj) {
        return YETTY_ERR(yetty_ycore_int, "yetty_ygui_widget_on_release: NULL obj");
    }
    yetty_ygui_impl_t impl = yetty_ygui_class_dispatch_lookup(obj->klass, slot);
    if (!impl) {
        return YETTY_OK(yetty_ycore_int, 0);
    }
    typedef struct yetty_ycore_int_result (*fn_t)(struct yetty_ygui_object *, float, float, int);
    return ((fn_t)impl)(obj, x, y, button);
}

struct yetty_ycore_int_result yetty_ygui_widget_on_motion(struct yetty_ygui_object *obj, float x,
                                                          float y)
{
    static yetty_ygui_method_slot slot = YETTY_YGUI_METHOD_SLOT_UNDEFINED;
    if (slot == YETTY_YGUI_METHOD_SLOT_UNDEFINED) {
        slot = yetty_ygui_method_slot_get((yetty_ygui_method_id_t)yetty_ygui_widget_on_motion);
    }
    if (!obj) {
        return YETTY_ERR(yetty_ycore_int, "yetty_ygui_widget_on_motion: NULL obj");
    }
    yetty_ygui_impl_t impl = yetty_ygui_class_dispatch_lookup(obj->klass, slot);
    if (!impl) {
        return YETTY_OK(yetty_ycore_int, 0);
    }
    typedef struct yetty_ycore_int_result (*fn_t)(struct yetty_ygui_object *, float, float);
    return ((fn_t)impl)(obj, x, y);
}

struct yetty_ycore_void_result yetty_ygui_widget_emit_container(struct yetty_ygui_object *obj,
                                                                struct yetty_ygui_emit_ctx *ctx)
{
    static yetty_ygui_method_slot slot = YETTY_YGUI_METHOD_SLOT_UNDEFINED;
    if (slot == YETTY_YGUI_METHOD_SLOT_UNDEFINED) {
        slot = yetty_ygui_method_slot_get((yetty_ygui_method_id_t)yetty_ygui_widget_emit_container);
    }
    if (!obj) {
        return YETTY_ERR(yetty_ycore_void, "yetty_ygui_widget_emit_container: NULL obj");
    }
    yetty_ygui_impl_t impl = yetty_ygui_class_dispatch_lookup(obj->klass, slot);
    if (!impl) {
        return YETTY_OK_VOID();
    }
    typedef struct yetty_ycore_void_result (*fn_t)(struct yetty_ygui_object *,
                                                   struct yetty_ygui_emit_ctx *);
    return ((fn_t)impl)(obj, ctx);
}

struct yetty_ycore_void_result yetty_ygui_widget_emit_body(struct yetty_ygui_object *obj,
                                                           struct yetty_ygui_emit_ctx *ctx)
{
    static yetty_ygui_method_slot slot = YETTY_YGUI_METHOD_SLOT_UNDEFINED;
    if (slot == YETTY_YGUI_METHOD_SLOT_UNDEFINED) {
        slot = yetty_ygui_method_slot_get((yetty_ygui_method_id_t)yetty_ygui_widget_emit_body);
    }
    if (!obj) {
        return YETTY_ERR(yetty_ycore_void, "yetty_ygui_widget_emit_body: NULL obj");
    }
    yetty_ygui_impl_t impl = yetty_ygui_class_dispatch_lookup(obj->klass, slot);
    if (!impl) {
        return YETTY_OK_VOID();
    }
    typedef struct yetty_ycore_void_result (*fn_t)(struct yetty_ygui_object *,
                                                   struct yetty_ygui_emit_ctx *);
    return ((fn_t)impl)(obj, ctx);
}

struct yetty_ycore_void_result yetty_ygui_widget_paint(struct yetty_ygui_object *obj,
                                                       struct yetty_ygui_emit_ctx *ctx)
{
    static yetty_ygui_method_slot slot = YETTY_YGUI_METHOD_SLOT_UNDEFINED;
    if (slot == YETTY_YGUI_METHOD_SLOT_UNDEFINED) {
        slot = yetty_ygui_method_slot_get((yetty_ygui_method_id_t)yetty_ygui_widget_paint);
    }
    if (!obj) {
        return YETTY_ERR(yetty_ycore_void, "yetty_ygui_widget_paint: NULL obj");
    }
    yetty_ygui_impl_t impl = yetty_ygui_class_dispatch_lookup(obj->klass, slot);
    if (!impl) {
        return YETTY_OK_VOID();
    }
    typedef struct yetty_ycore_void_result (*fn_t)(struct yetty_ygui_object *,
                                                   struct yetty_ygui_emit_ctx *);
    return ((fn_t)impl)(obj, ctx);
}

/*===========================================================================
 * Default implementations registered on the base widget class.
 *=========================================================================*/

static struct yetty_ycore_void_result widget_default_constructor(struct yetty_ygui_object *obj)
{
    struct yetty_ygui_widget_data *wd = yetty_ygui_data_get(obj, yetty_ygui_widget_class_get());
    /* Zero rect (will be set by app via set_rect / layout pass). */
    wd->rect.min.x = 0;
    wd->rect.min.y = 0;
    wd->rect.max.x = 0;
    wd->rect.max.y = 0;
    wd->layout = yetty_ygui_layout_default();
    return YETTY_OK_VOID();
}

static struct yetty_ycore_void_result widget_default_destructor(struct yetty_ygui_object *obj)
{
    (void)obj;
    return YETTY_OK_VOID();
}

static struct yetty_ycore_int_result widget_default_on_press(struct yetty_ygui_object *obj, float x,
                                                             float y, int button)
{
    (void)obj;
    (void)x;
    (void)y;
    (void)button;
    return YETTY_OK(yetty_ycore_int, 0);
}

static struct yetty_ycore_int_result widget_default_on_release(struct yetty_ygui_object *obj,
                                                               float x, float y, int button)
{
    (void)obj;
    (void)x;
    (void)y;
    (void)button;
    return YETTY_OK(yetty_ycore_int, 0);
}

static struct yetty_ycore_int_result widget_default_on_motion(struct yetty_ygui_object *obj,
                                                              float x, float y)
{
    (void)obj;
    (void)x;
    (void)y;
    return YETTY_OK(yetty_ycore_int, 0);
}

static struct yetty_ycore_void_result widget_default_paint(struct yetty_ygui_object *obj,
                                                           struct yetty_ygui_emit_ctx *ctx)
{
    (void)obj;
    (void)ctx;
    return YETTY_OK_VOID();
}

/* Default emit_container — true no-op on the base widget class.
 * Figure widget subclasses (yimage, yplot, …) override this to mint
 * their own receiver-side figure via yetty_ygui_emit_create_child
 * with their kind hardcoded. Primitive widgets don't touch the
 * container record stream. */
static struct yetty_ycore_void_result widget_default_emit_container(struct yetty_ygui_object *obj,
                                                                    struct yetty_ygui_emit_ctx *ctx)
{
    (void)obj;
    (void)ctx;
    return YETTY_OK_VOID();
}

/* Default emit_body — true no-op. The primitive_widget subclass
 * overrides this to dispatch to paint(); figure widgets override it
 * to ship their figure-specific bytes via yetty_ygui_emit_figure_body. */
static struct yetty_ycore_void_result widget_default_emit_body(struct yetty_ygui_object *obj,
                                                               struct yetty_ygui_emit_ctx *ctx)
{
    (void)obj;
    (void)ctx;
    return YETTY_OK_VOID();
}

/*===========================================================================
 * Layout setters / getters.
 *=========================================================================*/

struct yetty_ygui_layout yetty_ygui_layout_default(void)
{
    struct yetty_ygui_layout l = {0};
    l.direction = YETTY_YGUI_FLEX_ROW;
    l.justify = YETTY_YGUI_JUSTIFY_START;
    l.align = YETTY_YGUI_ALIGN_START;
    l.gap = 0;
    l.width = -1.0f;
    l.height = -1.0f;
    l.flex_grow = 0;
    l.flex_shrink = 0;
    l.min_width = -1.0f;
    l.max_width = -1.0f;
    l.min_height = -1.0f;
    l.max_height = -1.0f;
    l.absolute = 0;
    l.pos_x = 0.0f;
    l.pos_y = 0.0f;
    return l;
}

struct yetty_ycore_void_result yetty_ygui_widget_set_rect(struct yetty_ygui_object *obj,
                                                          struct yetty_ycore_rectangle rect)
{
    if (!obj) {
        return YETTY_ERR(yetty_ycore_void, "yetty_ygui_widget_set_rect: NULL obj");
    }
    struct yetty_ygui_widget_data *wd = yetty_ygui_data_get(obj, yetty_ygui_widget_class_get());
    wd->rect = rect;
    obj->dirty = 1;
    return YETTY_OK_VOID();
}

struct yetty_ycore_rectangle yetty_ygui_widget_rect(const struct yetty_ygui_object *obj)
{
    struct yetty_ycore_rectangle zero = {{0, 0}, {0, 0}};
    if (!obj) {
        return zero;
    }
    struct yetty_ygui_widget_data *wd =
        yetty_ygui_data_get((struct yetty_ygui_object *)obj, yetty_ygui_widget_class_get());
    return wd->rect;
}

struct yetty_ycore_void_result yetty_ygui_widget_layout_set(struct yetty_ygui_object *obj,
                                                            const struct yetty_ygui_layout *layout)
{
    if (!obj || !layout) {
        return YETTY_ERR(yetty_ycore_void, "yetty_ygui_widget_layout_set: NULL arg");
    }
    struct yetty_ygui_widget_data *wd = yetty_ygui_data_get(obj, yetty_ygui_widget_class_get());
    wd->layout = *layout;
    obj->dirty = 1;
    return YETTY_OK_VOID();
}

const struct yetty_ygui_layout *yetty_ygui_widget_layout_get(const struct yetty_ygui_object *obj)
{
    if (!obj) {
        return NULL;
    }
    struct yetty_ygui_widget_data *wd =
        yetty_ygui_data_get((struct yetty_ygui_object *)obj, yetty_ygui_widget_class_get());
    return &wd->layout;
}

/*===========================================================================
 * Class definition.
 *=========================================================================*/

static const struct yetty_ygui_op widget_ops[] = {
    YETTY_YGUI_OP(yetty_ygui_constructor, widget_default_constructor),
    YETTY_YGUI_OP(yetty_ygui_destructor, widget_default_destructor),
    YETTY_YGUI_OP(yetty_ygui_widget_on_press, widget_default_on_press),
    YETTY_YGUI_OP(yetty_ygui_widget_on_release, widget_default_on_release),
    YETTY_YGUI_OP(yetty_ygui_widget_on_motion, widget_default_on_motion),
    YETTY_YGUI_OP(yetty_ygui_widget_emit_container, widget_default_emit_container),
    YETTY_YGUI_OP(yetty_ygui_widget_emit_body, widget_default_emit_body),
    YETTY_YGUI_OP(yetty_ygui_widget_paint, widget_default_paint),
};

static const struct yetty_ygui_class_descriptor widget_desc = {
    .name = "yetty_ygui_widget",
    .type = YETTY_YGUI_CLASS_TYPE_REGULAR,
    .data_size = sizeof(struct yetty_ygui_widget_data),
};

YETTY_YGUI_DEFINE_CLASS(yetty_ygui_widget_class_get, &widget_desc, widget_ops, NULL, NULL)
