/*
 * poc/yvterm/shader.c — the text grid WGSL embedded as a C string.
 *
 * Mirror of text.wgsl. Keep the two in sync by hand; this copy is the one
 * the binary compiles (no runtime file IO).
 */
#include "shader.h"

const char poc_yvterm_text_wgsl[] =
    "struct Uniforms {\n"
    "    grid_size: vec2<f32>,\n"
    "    cell_size: vec2<f32>,\n"
    "    scale: f32,\n"
    "    baseline_y: f32,\n"
    "    glyph_left: f32,\n"
    "    pixel_range: f32,\n"
    "    root_row: u32,\n"
    "    pad0: u32,\n"
    "    pad1: u32,\n"
    "    pad2: u32,\n"
    "};\n"
    "\n"
    "@group(0) @binding(0) var<storage, read> cells: array<u32>;\n"
    "@group(0) @binding(1) var<storage, read> glyph_meta: array<u32>;\n"
    "@group(0) @binding(2) var atlas_tex: texture_2d<f32>;\n"
    "@group(0) @binding(3) var atlas_smp: sampler;\n"
    "@group(0) @binding(4) var<uniform> uni: Uniforms;\n"
    "\n"
    "struct VSOut {\n"
    "    @builtin(position) pos: vec4<f32>,\n"
    "    @location(0) @interpolate(linear) grid_pixel: vec2<f32>,\n"
    "};\n"
    "\n"
    "@vertex\n"
    "fn vs_main(@builtin(vertex_index) vid: u32) -> VSOut {\n"
    "    var corners = array<vec2<f32>, 6>(\n"
    "        vec2<f32>(-1.0, -1.0), vec2<f32>(1.0, -1.0), vec2<f32>(1.0, 1.0),\n"
    "        vec2<f32>(-1.0, -1.0), vec2<f32>(1.0, 1.0), vec2<f32>(-1.0, 1.0)\n"
    "    );\n"
    "    let ndc = corners[vid];\n"
    "    var out: VSOut;\n"
    "    out.pos = vec4<f32>(ndc, 0.0, 1.0);\n"
    "    let grid_w = uni.grid_size.x * uni.cell_size.x;\n"
    "    let grid_h = uni.grid_size.y * uni.cell_size.y;\n"
    "    out.grid_pixel = vec2<f32>((ndc.x * 0.5 + 0.5) * grid_w, (0.5 - ndc.y * 0.5) * grid_h);\n"
    "    return out;\n"
    "}\n"
    "\n"
    "fn median3(r: f32, g: f32, b: f32) -> f32 {\n"
    "    return max(min(r, g), min(max(r, g), b));\n"
    "}\n"
    "\n"
    "fn sample_glyph(glyph: u32, local_px: vec2<f32>) -> f32 {\n"
    "    let base = glyph * 10u;\n"
    "    let uv_min = vec2<f32>(bitcast<f32>(glyph_meta[base + 0u]), bitcast<f32>(glyph_meta[base + 1u]));\n"
    "    let uv_max = vec2<f32>(bitcast<f32>(glyph_meta[base + 2u]), bitcast<f32>(glyph_meta[base + 3u]));\n"
    "    let gsize = vec2<f32>(bitcast<f32>(glyph_meta[base + 4u]), bitcast<f32>(glyph_meta[base + 5u]));\n"
    "    let bear = vec2<f32>(bitcast<f32>(glyph_meta[base + 6u]), bitcast<f32>(glyph_meta[base + 7u]));\n"
    "    if (gsize.x <= 0.0 || gsize.y <= 0.0) { return 0.0; }\n"
    "    let scaled_size = gsize * uni.scale;\n"
    "    let scaled_bear = bear * uni.scale;\n"
    "    let gtop = uni.baseline_y - scaled_bear.y;\n"
    "    let gleft = uni.glyph_left + scaled_bear.x;\n"
    "    let gmin = vec2<f32>(gleft, gtop);\n"
    "    let gmax = vec2<f32>(gleft + scaled_size.x, gtop + scaled_size.y);\n"
    "    if (local_px.x < gmin.x || local_px.x >= gmax.x || local_px.y < gmin.y || local_px.y >= "
    "gmax.y) { return 0.0; }\n"
    "    let gl = (local_px - gmin) / scaled_size;\n"
    "    let uv = mix(uv_min, uv_max, gl);\n"
    "    let texel = textureSampleLevel(atlas_tex, atlas_smp, uv, 0.0);\n"
    "    let sd = median3(texel.r, texel.g, texel.b);\n"
    "    let screen_px_range = uni.pixel_range * uni.scale;\n"
    "    return clamp((sd - 0.5) * screen_px_range + 0.5, 0.0, 1.0);\n"
    "}\n"
    "\n"
    "@fragment\n"
    "fn fs_main(in: VSOut) -> @location(0) vec4<f32> {\n"
    "    let grid_w = uni.grid_size.x * uni.cell_size.x;\n"
    "    let grid_h = uni.grid_size.y * uni.cell_size.y;\n"
    "    let px = in.grid_pixel;\n"
    "    if (px.x < 0.0 || px.y < 0.0 || px.x >= grid_w || px.y >= grid_h) {\n"
    "        return vec4<f32>(0.0, 0.0, 0.0, 1.0);\n"
    "    }\n"
    "    let col = floor(px.x / uni.cell_size.x);\n"
    "    let row = floor(px.y / uni.cell_size.y);\n"
    "    let cell_index = (u32(row) + uni.root_row) * u32(uni.grid_size.x) + u32(col);\n"
    "    let local = vec2<f32>(px.x - col * uni.cell_size.x, px.y - row * uni.cell_size.y);\n"
    "    let glyph = cells[cell_index * 4u + 0u];\n"
    "    let w1 = cells[cell_index * 4u + 1u];\n"
    "    let w2 = cells[cell_index * 4u + 2u];\n"
    "    let fg = vec3<f32>(f32(w1 & 0xFFu) / 255.0, f32((w1 >> 8u) & 0xFFu) / 255.0, f32((w1 >> "
    "16u) & 0xFFu) / 255.0);\n"
    "    let bg = vec3<f32>(f32((w1 >> 24u) & 0xFFu) / 255.0, f32(w2 & 0xFFu) / 255.0, f32((w2 >> "
    "8u) & 0xFFu) / 255.0);\n"
    "    var alpha = 0.0;\n"
    "    if (glyph != 0u) { alpha = sample_glyph(glyph, local); }\n"
    "    let composed = mix(bg, fg, alpha);\n"
    "    return vec4<f32>(composed, 1.0);\n"
    "}\n";
