#!/usr/bin/env python3
"""Emit a C table of printable Unicode code-point ranges, matching Python's
str.isprintable() (which is what CPython's repr uses to decide escaping)."""
import sys

ranges = []
start = None
for cp in range(0x110000):
    try:
        printable = chr(cp).isprintable()
    except ValueError:
        printable = False
    if printable and start is None:
        start = cp
    elif not printable and start is not None:
        ranges.append((start, cp - 1))
        start = None
if start is not None:
    ranges.append((start, 0x10FFFF))

out = []
out.append("/* GENERATED by tools/gen_printable.py from str.isprintable(). */")
out.append("/* Printable Unicode code-point ranges, used by the AST dumper's repr. */")
out.append("static const unsigned printable_ranges[][2] = {")
for a, b in ranges:
    out.append("    {0x%X, 0x%X}," % (a, b))
out.append("};")
out.append("static const int n_printable_ranges = %d;" % len(ranges))
out.append("")
out.append("int pyp_is_printable(unsigned cp) {")
out.append("    int lo = 0, hi = n_printable_ranges - 1;")
out.append("    while (lo <= hi) {")
out.append("        int mid = (lo + hi) / 2;")
out.append("        if (cp < printable_ranges[mid][0]) hi = mid - 1;")
out.append("        else if (cp > printable_ranges[mid][1]) lo = mid + 1;")
out.append("        else return 1;")
out.append("    }")
out.append("    return 0;")
out.append("}")
sys.stdout.write("\n".join(out) + "\n")
