#!/usr/bin/env python3
"""Generate a libpython-free C AST from CPython's Python.asdl.

Emits ast.gen.h (node structs + constructor prototypes) and ast.gen.c
(constructor bodies + typed sequence allocators), matching CPython's type and
function names (expr_ty, _PyAST_BinOp, Name_kind, v.Name.id, asdl_expr_seq,
_Py_asdl_expr_seq_new) so the vendored parser can compile against it later, but
with plain-C leaf types (identifier = char*, no PyObject anywhere).

Usage: gen_ast.py <Python.asdl> <out_dir> <asdl_module_dir>
"""
import sys
import os

asdl_path, out_dir, asdl_mod_dir = sys.argv[1], sys.argv[2], sys.argv[3]
sys.path.insert(0, asdl_mod_dir)
import asdl  # the vendored CPython asdl.py

mod = asdl.parse(asdl_path)
if not asdl.check(mod):
    sys.exit("ASDL check failed")

BUILTIN_PTR = {"identifier", "string", "object", "constant"}


def is_simple_sum(value):
    return isinstance(value, asdl.Sum) and all(
        len(c.fields) == 0 for c in value.types
    )


# Classify every defined type.
simple_sums = set()   # represented as C enums
sums = {}             # name -> Sum (with fields)
products = {}         # name -> Product
for dfn in mod.dfns:
    v = dfn.value
    if is_simple_sum(v):
        simple_sums.add(dfn.name)
    elif isinstance(v, asdl.Sum):
        sums[dfn.name] = v
    else:
        products[dfn.name] = v

pointer_types = set(sums) | set(products)   # represented as struct _T *


def has_attrs(value):
    return bool(getattr(value, "attributes", None))


def field_ctype(f):
    """C type of a single (non-seq) field."""
    t = f.type
    if t == "int":
        return "int"
    if t in BUILTIN_PTR:
        return t            # identifier/string/object/constant typedefs
    return t + "_ty"        # enum (simple sum) or struct pointer


def seq_typename(t):
    """The asdl_*_seq typedef name for a sequence whose element type is t."""
    if t == "int":
        return "asdl_int_seq"
    if t == "identifier":
        return "asdl_identifier_seq"
    if t in simple_sums:
        return "asdl_int_seq"     # enums stored as ints
    return "asdl_%s_seq" % t      # generic-backed typed seq


def field_decl(f):
    if f.seq:
        return "%s *%s" % (seq_typename(f.type), f.name)
    return "%s %s" % (field_ctype(f), f.name)


def needs_required_check(f):
    # Pointer / enum fields that are mandatory get a NULL guard (matches asdl_c.py).
    return (not f.opt) and (not f.seq) and f.type != "int"


# Collect the element types that need a typed seq allocator (excludes the
# three base seqs defined in asdl.h: generic, identifier, int).
seq_elt_types = set()
for value in list(sums.values()) + list(products.values()):
    fields = list(value.types[0].fields) if False else []
seq_fields = []
for dfn in mod.dfns:
    v = dfn.value
    field_groups = []
    if isinstance(v, asdl.Sum):
        for c in v.types:
            field_groups.append(c.fields)
    else:
        field_groups.append(v.fields)
    for fields in field_groups:
        for f in fields:
            if f.seq:
                tn = seq_typename(f.type)
                if tn not in ("asdl_int_seq", "asdl_identifier_seq"):
                    seq_elt_types.add(f.type)

# --------------------------------------------------------------------------- #
# Header
# --------------------------------------------------------------------------- #
h = []
h.append("/* GENERATED by tools/gen_ast.py from Python.asdl — do not edit. */")
h.append("/* Plain-C AST: no PyObject, no libpython. */")
h.append("#ifndef PYP_AST_GEN_H")
h.append("#define PYP_AST_GEN_H")
h.append('#include "asdl.h"')
h.append("")

# Forward typedefs for all struct-pointer types.
for name in pointer_types:
    h.append("typedef struct _%s *%s_ty;" % (name, name))
h.append("")

# Enums for simple sums.
for dfn in mod.dfns:
    if dfn.name in simple_sums:
        labels = ", ".join("%s=%d" % (c.name, i + 1)
                           for i, c in enumerate(dfn.value.types))
        h.append("typedef enum _%s { %s } %s_ty;" % (dfn.name, labels, dfn.name))
h.append("")

# Typed sequence structs (element-typed so asdl_seq_GET returns the node type).
for t in sorted(seq_elt_types):
    h.append("typedef struct { _ASDL_SEQ_HEAD %s_ty typed_elements[1]; } asdl_%s_seq;"
             % (t, t))
h.append("")


def emit_attr_fields(out, value):
    if has_attrs(value):
        for a in value.attributes:
            out.append("    int %s;" % a.name)


# Struct definitions.
for dfn in mod.dfns:
    name = dfn.name
    v = dfn.value
    if name in simple_sums:
        continue
    if name in sums:
        # kind enum
        labels = ", ".join("%s_kind=%d" % (c.name, i + 1)
                           for i, c in enumerate(v.types))
        h.append("enum _%s_kind { %s };" % (name, labels))
        h.append("struct _%s {" % name)
        h.append("    enum _%s_kind kind;" % name)
        h.append("    union {")
        for c in v.types:
            if not c.fields:
                continue
            h.append("        struct {")
            for f in c.fields:
                h.append("            %s;" % field_decl(f))
            h.append("        } %s;" % c.name)
        h.append("    } v;")
        emit_attr_fields(h, v)
        h.append("};")
        h.append("")
    else:  # product
        h.append("struct _%s {" % name)
        for f in v.fields:
            h.append("    %s;" % field_decl(f))
        emit_attr_fields(h, v)
        h.append("};")
        h.append("")


def ctor_signature(ret_ty, fn_name, fields, value):
    args = [field_decl(f) for f in fields]
    if has_attrs(value):
        args += ["int %s" % a.name for a in value.attributes]
    args.append("PyArena *arena")
    return "%s %s(%s)" % (ret_ty, fn_name, ", ".join(args) if args else "void")


# Constructor prototypes + typed seq allocator prototypes.
for dfn in mod.dfns:
    name, v = dfn.name, dfn.value
    if name in simple_sums:
        continue
    if name in sums:
        for c in v.types:
            h.append(ctor_signature("%s_ty" % name, "_PyAST_%s" % c.name,
                                     c.fields, v) + ";")
    else:
        h.append(ctor_signature("%s_ty" % name, "_PyAST_%s" % name,
                                 v.fields, v) + ";")
h.append("")
for t in sorted(seq_elt_types):
    h.append("asdl_%s_seq *_Py_asdl_%s_seq_new(Py_ssize_t size, PyArena *arena);"
             % (t, t))
h.append("")
h.append("#endif /* PYP_AST_GEN_H */")

# --------------------------------------------------------------------------- #
# Source
# --------------------------------------------------------------------------- #
c = []
c.append("/* GENERATED by tools/gen_ast.py from Python.asdl — do not edit. */")
c.append('#include "ast.gen.h"')
c.append("")
for t in sorted(seq_elt_types):
    c.append("GENERATE_ASDL_SEQ_CONSTRUCTOR(%s, %s_ty)" % (t, t))
c.append("")


def emit_ctor(out, ret_ty, fn_name, ctor_name, fields, value, kind_label):
    out.append(ctor_signature(ret_ty, fn_name, fields, value))
    out.append("{")
    out.append("    %s p;" % ret_ty)
    for f in fields:
        if needs_required_check(f):
            out.append("    if (!%s) {" % f.name)
            out.append('        pyp_ast_error("field \'%s\' is required for %s");'
                       % (f.name, ctor_name))
            out.append("        return NULL;")
            out.append("    }")
    out.append("    p = (%s)_PyArena_Malloc(arena, sizeof(*p));" % ret_ty)
    out.append("    if (!p) return NULL;")
    if kind_label is not None:
        out.append("    p->kind = %s;" % kind_label)
        for f in fields:
            out.append("    p->v.%s.%s = %s;" % (ctor_name, f.name, f.name))
    else:
        for f in fields:
            out.append("    p->%s = %s;" % (f.name, f.name))
    if has_attrs(value):
        for a in value.attributes:
            out.append("    p->%s = %s;" % (a.name, a.name))
    out.append("    return p;")
    out.append("}")
    out.append("")


for dfn in mod.dfns:
    name, v = dfn.name, dfn.value
    if name in simple_sums:
        continue
    if name in sums:
        for con in v.types:
            emit_ctor(c, "%s_ty" % name, "_PyAST_%s" % con.name, con.name,
                      con.fields, v, "%s_kind" % con.name)
    else:
        emit_ctor(c, "%s_ty" % name, "_PyAST_%s" % name, name,
                  v.fields, v, None)

os.makedirs(out_dir, exist_ok=True)
with open(os.path.join(out_dir, "ast.gen.h"), "w") as fh:
    fh.write("\n".join(h) + "\n")
with open(os.path.join(out_dir, "ast.gen.c"), "w") as fh:
    fh.write("\n".join(c) + "\n")


# --------------------------------------------------------------------------- #
# Dumper: ast.dump()-style recursive printer over the plain-C AST.
# --------------------------------------------------------------------------- #
def emit_field_dump(out, f, access):
    """Emit C that prints the value of field f reached via the expression `access`."""
    if f.seq:
        out.append('    fputs("[", pyp_dump_fp);')
        out.append('    { asdl_generic_seq *_s = (asdl_generic_seq *)(%s); Py_ssize_t _i;'
                   % access)
        out.append('      for (_i = 0; _i < asdl_seq_LEN(_s); _i++) {')
        out.append('        if (_i) fputs(", ", pyp_dump_fp);')
        t = f.type
        if t == "int":
            out.append('        fprintf(pyp_dump_fp, "%d", ((asdl_int_seq *)_s)->typed_elements[_i]);')
        elif t in simple_sums:
            out.append('        dump_%s(((asdl_int_seq *)_s)->typed_elements[_i]);' % t)
        elif t == "identifier":
            out.append('        pyp_emit_identifier((PyObject *)_s->typed_elements[_i]);')
        elif t in ("string", "constant", "object"):
            out.append('        pyp_emit_constant((PyObject *)_s->typed_elements[_i]);')
        else:
            out.append('        { void *_e = _s->typed_elements[_i];')
            out.append('          if (_e) dump_%s((%s_ty)_e); else fputs("None", pyp_dump_fp); }' % (t, t))
        out.append('      } }')
        out.append('    fputs("]", pyp_dump_fp);')
        return
    t = f.type
    if t == "int":
        out.append('    fprintf(pyp_dump_fp, "%%d", %s);' % access)
    elif t in simple_sums:
        out.append('    dump_%s(%s);' % (t, access))
    elif t == "identifier":
        out.append('    pyp_emit_identifier(%s);' % access)
    elif t in ("string", "constant", "object"):
        out.append('    pyp_emit_constant(%s);' % access)
    else:  # node pointer
        out.append('    if (%s) dump_%s(%s); else fputs("None", pyp_dump_fp);' % (access, t, access))


d = []
d.append("/* GENERATED by tools/gen_ast.py — do not edit. ast.dump()-style printer. */")
d.append('#include "ast.gen.h"')
d.append('#include <stdio.h>')
d.append("")
d.append("FILE *pyp_dump_fp;                        /* dump sink; defaults to stdout */")
d.append("void pyp_emit_identifier(PyObject *o);   /* pyp_dump.c */")
d.append("void pyp_emit_constant(PyObject *o);      /* pyp_dump.c */")
d.append("")
# forward declarations
for name in pointer_types:
    d.append("static void dump_%s(%s_ty node);" % (name, name))
for name in simple_sums:
    d.append("static void dump_%s(int v);" % name)
d.append("")
# simple-sum label printers
for dfn in mod.dfns:
    if dfn.name in simple_sums:
        d.append("static void dump_%s(int v) {" % dfn.name)
        d.append("    switch (v) {")
        for con in dfn.value.types:
            d.append('    case %s: fputs("%s()", pyp_dump_fp); break;' % (con.name, con.name))
        d.append('    default: fputs("?()", pyp_dump_fp);')
        d.append("    }")
        d.append("}")
d.append("")
# node printers
for dfn in mod.dfns:
    name, v = dfn.name, dfn.value
    if name in simple_sums:
        continue
    d.append("static void dump_%s(%s_ty node) {" % (name, name))
    if name in sums:
        d.append("    switch (node->kind) {")
        for con in v.types:
            d.append("    case %s_kind: {" % con.name)
            d.append('        fputs("%s(", pyp_dump_fp);' % con.name)
            for i, f in enumerate(con.fields):
                if i:
                    d.append('        fputs(", ", pyp_dump_fp);')
                d.append('        fputs("%s=", pyp_dump_fp);' % f.name)
                emit_field_dump(d, f, "node->v.%s.%s" % (con.name, f.name))
            d.append('        fputs(")", pyp_dump_fp);')
            d.append("        break; }")
        d.append('    default: fputs("<?>", pyp_dump_fp);')
        d.append("    }")
    else:  # product
        d.append('    fputs("%s(", pyp_dump_fp);' % name)
        for i, f in enumerate(v.fields):
            if i:
                d.append('        fputs(", ", pyp_dump_fp);')
            d.append('        fputs("%s=", pyp_dump_fp);' % f.name)
            emit_field_dump(d, f, "node->%s" % f.name)
        d.append('    fputs(")", pyp_dump_fp);')
    d.append("}")
    d.append("")
d.append("void pyp_dump_mod(mod_ty mod) {")
d.append("    if (!pyp_dump_fp) pyp_dump_fp = stdout;")
d.append("    if (!mod) { fputs(\"None\\n\", pyp_dump_fp); return; }")
d.append("    dump_mod(mod);")
d.append("    putc('\\n', pyp_dump_fp);")
d.append("}")

with open(os.path.join(out_dir, "ast_dump.gen.h"), "w") as fh:
    fh.write('#ifndef PYP_AST_DUMP_GEN_H\n#define PYP_AST_DUMP_GEN_H\n#include "ast.gen.h"\n'
             "void pyp_dump_mod(mod_ty mod);\n#endif\n")
with open(os.path.join(out_dir, "ast_dump.gen.c"), "w") as fh:
    fh.write("\n".join(d) + "\n")

print("wrote ast.gen.h (%d lines), ast.gen.c (%d lines), ast_dump.gen.c (%d lines)"
      % (len(h), len(c), len(d)))
