/*
 * yjupyter:client — the live Jupyter Server connection: REST over libcurl to
 * create/delete a kernel, and a minimal RFC 6455 WebSocket client (plaintext,
 * JSON text frames — the protocol jupyter_server speaks when no binary
 * subprotocol is negotiated) to carry the v5 messages built by yjupyter:session.
 *
 * Synchronous by design: REST is a blocking libcurl easy handle; the WebSocket
 * is a blocking socket with poll()-based read timeouts. No event loop, so it is
 * driven with an explicit poll() loop and is directly testable against a real
 * kernel on loopback.
 *
 * The public interface is generated by yclass codegen from the annotations
 * below — never hand-write client.h.
 */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

#include <netdb.h>
#include <poll.h>
#include <sys/socket.h>

#include <curl/curl.h>
#include <yyjson.h>

#include <yetty/yclass/class.h>
#include <yetty/ycore/result.h>

#include <yetty/yjupyter/protocol.h> /* session + message classes */

/*=============================================================================
 * Class data
 *===========================================================================*/

struct YETTY_ANNOTATE("class@yjupyter:client") yetty_yjupyter_client {
    char *base_url;                      /* e.g. http://127.0.0.1:8899 (no trailing slash) */
    char *token;                         /* owned; may be "" */
    char *kernel_id;                     /* owned; set after open */
    char *ws_session;                    /* owned; session id used on the WebSocket */
    int sockfd;                          /* WebSocket socket; -1 when closed */
    struct yetty_yclass_object *session; /* yjupyter:session; owned */
};

YETTY_YRESULT_DECLARE(yetty_yjupyter_client_ptr, struct yetty_yjupyter_client *);

struct yetty_yclass_ptr_result yetty_yjupyter_client_class_get(void);
struct yetty_yclass_object_ptr_result yetty_yjupyter_client_create(struct yetty_yclass_ctx *ctx);

static struct yetty_yclass_void_ptr_result client_from_obj(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_ptr_result class_r = yetty_yjupyter_client_class_get();
    YETTY_RETURN_IF_ERR(yetty_yclass_void_ptr, class_r, "client from_obj: class_get");
    return yetty_yclass_object_data(obj, class_r.value);
}

/*=============================================================================
 * REST over libcurl
 *===========================================================================*/

struct curl_sink {
    char *data;
    size_t len;
    size_t cap;
};

static size_t curl_collect(void *ptr, size_t size, size_t nmemb, void *userdata)
{
    struct curl_sink *sink = userdata;
    size_t add = size * nmemb;
    if (sink->len + add + 1 > sink->cap) {
        size_t new_cap = sink->cap ? sink->cap * 2 : 1024;
        while (new_cap < sink->len + add + 1) {
            new_cap *= 2;
        }
        char *grown = realloc(sink->data, new_cap);
        if (!grown) {
            return 0;
        }
        sink->data = grown;
        sink->cap = new_cap;
    }
    memcpy(sink->data + sink->len, ptr, add);
    sink->len += add;
    sink->data[sink->len] = 0;
    return add;
}

/* Perform an HTTP request. On success returns the owned response body (caller
 * frees) and writes the HTTP status to *status. */
static struct yetty_ycore_char_ptr_result http_do(const char *method, const char *url,
                                                  const char *token, const char *body, long *status)
{
    CURL *curl = curl_easy_init();
    if (!curl) {
        return YETTY_ERR(yetty_ycore_char_ptr, "http_do: curl init failed");
    }

    struct curl_sink sink = {0};
    struct curl_slist *headers = NULL;
    char auth[512];
    if (token && token[0]) {
        snprintf(auth, sizeof(auth), "Authorization: token %s", token);
        headers = curl_slist_append(headers, auth);
    }
    if (body) {
        headers = curl_slist_append(headers, "Content-Type: application/json");
    }

    curl_easy_setopt(curl, CURLOPT_URL, url);
    curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, curl_collect);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, &sink);
    curl_easy_setopt(curl, CURLOPT_TIMEOUT, 30L);
    if (strcmp(method, "POST") == 0) {
        curl_easy_setopt(curl, CURLOPT_POST, 1L);
        curl_easy_setopt(curl, CURLOPT_POSTFIELDS, body ? body : "");
    } else if (strcmp(method, "DELETE") == 0) {
        curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "DELETE");
    }

    CURLcode rc = curl_easy_perform(curl);
    long code = 0;
    curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &code);
    curl_slist_free_all(headers);
    curl_easy_cleanup(curl);

    if (rc != CURLE_OK) {
        free(sink.data);
        return YETTY_ERR(yetty_ycore_char_ptr, "http_do: request failed");
    }
    if (status) {
        *status = code;
    }
    if (!sink.data) {
        sink.data = strdup("");
    }
    if (!sink.data) {
        return YETTY_ERR(yetty_ycore_char_ptr, "http_do: alloc failed");
    }
    return YETTY_OK(yetty_ycore_char_ptr, sink.data);
}

/*=============================================================================
 * Minimal RFC 6455 WebSocket client (plaintext)
 *===========================================================================*/

static long now_ms(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (long)ts.tv_sec * 1000 + ts.tv_nsec / 1000000;
}

static int send_all(int fd, const uint8_t *buf, size_t len)
{
    size_t sent = 0;
    while (sent < len) {
        ssize_t wrote = send(fd, buf + sent, len - sent, 0);
        if (wrote <= 0) {
            return -1;
        }
        sent += (size_t)wrote;
    }
    return 0;
}

static int read_n(int fd, uint8_t *buf, size_t len, long deadline)
{
    size_t got = 0;
    while (got < len) {
        long remaining = deadline - now_ms();
        if (remaining <= 0) {
            return -1;
        }
        struct pollfd pfd = {.fd = fd, .events = POLLIN};
        int pr = poll(&pfd, 1, (int)remaining);
        if (pr <= 0) {
            return -1;
        }
        ssize_t r = recv(fd, buf + got, len - got, 0);
        if (r <= 0) {
            return -1;
        }
        got += (size_t)r;
    }
    return 0;
}

/* Send one masked client frame. */
static int ws_send_frame(int fd, uint8_t opcode, const uint8_t *payload, size_t len)
{
    uint8_t header[14];
    size_t h = 0;
    header[h++] = (uint8_t)(0x80 | opcode);
    const uint8_t mask[4] = {0x21, 0x9a, 0x43, 0xf0};
    if (len < 126) {
        header[h++] = (uint8_t)(0x80 | len);
    } else if (len < 65536) {
        header[h++] = 0x80 | 126;
        header[h++] = (uint8_t)((len >> 8) & 0xff);
        header[h++] = (uint8_t)(len & 0xff);
    } else {
        header[h++] = 0x80 | 127;
        for (int i = 7; i >= 0; i--) {
            header[h++] = (uint8_t)((len >> (8 * i)) & 0xff);
        }
    }
    memcpy(header + h, mask, 4);
    h += 4;
    if (send_all(fd, header, h)) {
        return -1;
    }
    if (len) {
        uint8_t *masked = malloc(len);
        if (!masked) {
            return -1;
        }
        for (size_t i = 0; i < len; i++) {
            masked[i] = payload[i] ^ mask[i & 3];
        }
        int rc = send_all(fd, masked, len);
        free(masked);
        return rc;
    }
    return 0;
}

static int ws_send_text(int fd, const char *text)
{
    return ws_send_frame(fd, 0x1, (const uint8_t *)text, strlen(text));
}

/* Receive one complete text message (reassembling fragments). Returns an owned
 * NUL-terminated string, or NULL on timeout/close/error. Replies to pings. */
static char *ws_recv_text(int fd, int timeout_ms, int *out_closed)
{
    long deadline = now_ms() + timeout_ms;
    uint8_t *acc = NULL;
    size_t acc_len = 0;

    for (;;) {
        uint8_t header[2];
        if (read_n(fd, header, 2, deadline)) {
            free(acc);
            return NULL;
        }
        int fin = header[0] & 0x80;
        int opcode = header[0] & 0x0f;
        uint64_t len = header[1] & 0x7f;
        if (len == 126) {
            uint8_t ext[2];
            if (read_n(fd, ext, 2, deadline)) {
                free(acc);
                return NULL;
            }
            len = ((uint64_t)ext[0] << 8) | ext[1];
        } else if (len == 127) {
            uint8_t ext[8];
            if (read_n(fd, ext, 8, deadline)) {
                free(acc);
                return NULL;
            }
            len = 0;
            for (int i = 0; i < 8; i++) {
                len = (len << 8) | ext[i];
            }
        }

        uint8_t *payload = len ? malloc(len) : NULL;
        if (len && !payload) {
            free(acc);
            return NULL;
        }
        if (len && read_n(fd, payload, len, deadline)) {
            free(payload);
            free(acc);
            return NULL;
        }

        if (opcode == 0x8) { /* close */
            free(payload);
            free(acc);
            if (out_closed) {
                *out_closed = 1;
            }
            return NULL;
        }
        if (opcode == 0x9) { /* ping -> pong */
            ws_send_frame(fd, 0xA, payload, len);
            free(payload);
            continue;
        }
        if (opcode == 0xA) { /* pong */
            free(payload);
            continue;
        }

        /* text (0x1) or continuation (0x0) */
        uint8_t *grown = realloc(acc, acc_len + len + 1);
        if (!grown) {
            free(payload);
            free(acc);
            return NULL;
        }
        acc = grown;
        if (len) {
            memcpy(acc + acc_len, payload, len);
        }
        acc_len += len;
        free(payload);
        if (fin) {
            acc[acc_len] = 0;
            return (char *)acc;
        }
    }
}

/* Split "http://host:port" into host and port (defaulting port to 80). */
static void parse_base_url(const char *base_url, char *host, size_t host_cap, char *port,
                           size_t port_cap)
{
    const char *cursor = base_url;
    if (strncmp(cursor, "http://", 7) == 0) {
        cursor += 7;
    } else if (strncmp(cursor, "https://", 8) == 0) {
        cursor += 8;
    }
    const char *colon = strchr(cursor, ':');
    const char *slash = strchr(cursor, '/');
    const char *host_end = colon ? colon : (slash ? slash : cursor + strlen(cursor));
    size_t host_len = (size_t)(host_end - cursor);
    if (host_len >= host_cap) {
        host_len = host_cap - 1;
    }
    memcpy(host, cursor, host_len);
    host[host_len] = 0;
    if (colon) {
        const char *port_start = colon + 1;
        const char *port_end = slash ? slash : port_start + strlen(port_start);
        size_t port_len = (size_t)(port_end - port_start);
        if (port_len >= port_cap) {
            port_len = port_cap - 1;
        }
        memcpy(port, port_start, port_len);
        port[port_len] = 0;
    } else {
        snprintf(port, port_cap, "80");
    }
}

/* Open a TCP connection and perform the WebSocket upgrade handshake. */
static int ws_connect(const char *host, const char *port, const char *path, const char *token)
{
    struct addrinfo hints = {0};
    hints.ai_family = AF_UNSPEC;
    hints.ai_socktype = SOCK_STREAM;
    struct addrinfo *result = NULL;
    if (getaddrinfo(host, port, &hints, &result) != 0) {
        return -1;
    }

    int fd = -1;
    for (struct addrinfo *ai = result; ai; ai = ai->ai_next) {
        fd = socket(ai->ai_family, ai->ai_socktype, ai->ai_protocol);
        if (fd < 0) {
            continue;
        }
        if (connect(fd, ai->ai_addr, ai->ai_addrlen) == 0) {
            break;
        }
        close(fd);
        fd = -1;
    }
    freeaddrinfo(result);
    if (fd < 0) {
        return -1;
    }

    char request[2048];
    int n = snprintf(request, sizeof(request),
                     "GET %s HTTP/1.1\r\n"
                     "Host: %s:%s\r\n"
                     "Upgrade: websocket\r\n"
                     "Connection: Upgrade\r\n"
                     "Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==\r\n"
                     "Sec-WebSocket-Version: 13\r\n"
                     "Authorization: token %s\r\n"
                     "\r\n",
                     path, host, port, token ? token : "");
    if (n <= 0 || send_all(fd, (const uint8_t *)request, (size_t)n)) {
        close(fd);
        return -1;
    }

    /* Read the handshake response byte-by-byte up to the blank line, so we do
     * not consume any WebSocket frame bytes that follow it. */
    char response[2048];
    size_t used = 0;
    long deadline = now_ms() + 10000;
    while (used < sizeof(response) - 1) {
        uint8_t byte;
        if (read_n(fd, &byte, 1, deadline)) {
            close(fd);
            return -1;
        }
        response[used++] = (char)byte;
        if (used >= 4 && memcmp(response + used - 4, "\r\n\r\n", 4) == 0) {
            break;
        }
    }
    response[used] = 0;
    if (!strstr(response, " 101 ")) {
        close(fd);
        return -1;
    }
    return fd;
}

/*=============================================================================
 * client method slots
 *===========================================================================*/

static void client_reset_connection(struct yetty_yjupyter_client *client)
{
    if (client->sockfd >= 0) {
        ws_send_frame(client->sockfd, 0x8, NULL, 0);
        close(client->sockfd);
        client->sockfd = -1;
    }
}

/* open: create a kernel over REST and open its WebSocket channel. `token` may be
 * "" for a tokenless server. */
YETTY_ANNOTATE("virtual@yjupyter:client:client_open")
YETTY_ANNOTATE("local@yjupyter:client_open")
static struct yetty_ycore_void_result client_open(struct yetty_yclass_object *obj,
                                                  const char *base_url, const char *token)
{
    struct yetty_yclass_void_ptr_result client_r = client_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, client_r, "client_open: from_obj");
    struct yetty_yjupyter_client *client = client_r.value;
    if (!base_url || !base_url[0]) {
        return YETTY_ERR(yetty_ycore_void, "client_open: empty base_url");
    }

    /* trim a trailing slash */
    size_t url_len = strlen(base_url);
    while (url_len > 0 && base_url[url_len - 1] == '/') {
        url_len--;
    }
    char *url_copy = malloc(url_len + 1);
    char *token_copy = strdup(token ? token : "");
    char ws_session[64];
    snprintf(ws_session, sizeof(ws_session), "yetty-%d", (int)getpid());
    char *ws_session_copy = strdup(ws_session);
    if (!url_copy || !token_copy || !ws_session_copy) {
        free(url_copy);
        free(token_copy);
        free(ws_session_copy);
        return YETTY_ERR(yetty_ycore_void, "client_open: alloc failed");
    }
    memcpy(url_copy, base_url, url_len);
    url_copy[url_len] = 0;

    free(client->base_url);
    free(client->token);
    free(client->ws_session);
    client->base_url = url_copy;
    client->token = token_copy;
    client->ws_session = ws_session_copy;

    /* session object for msg-id generation + correlation */
    if (!client->session) {
        struct yetty_yclass_ctx ctx = {0};
        struct yetty_yclass_object_ptr_result session_r = yetty_yjupyter_session_create(&ctx);
        YETTY_RETURN_IF_ERR(yetty_ycore_void, session_r, "client_open: session create");
        client->session = session_r.value;
    }
    struct yetty_ycore_void_result init_r =
        yetty_yjupyter_session_init(client->session, ws_session);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, init_r, "client_open: session init");

    /* REST: create a kernel */
    char create_url[1024];
    snprintf(create_url, sizeof(create_url), "%s/api/kernels", client->base_url);
    long status = 0;
    struct yetty_ycore_char_ptr_result create_r =
        http_do("POST", create_url, client->token, "{\"name\":\"python3\"}", &status);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, create_r, "client_open: create kernel");
    if (status < 200 || status >= 300) {
        free(create_r.value);
        return YETTY_ERR(yetty_ycore_void, "client_open: kernel create HTTP error");
    }

    yyjson_doc *doc = yyjson_read(create_r.value, strlen(create_r.value), 0);
    free(create_r.value);
    if (!doc) {
        return YETTY_ERR(yetty_ycore_void, "client_open: kernel response parse failed");
    }
    yyjson_val *id = yyjson_obj_get(yyjson_doc_get_root(doc), "id");
    const char *id_str = id && yyjson_is_str(id) ? yyjson_get_str(id) : NULL;
    char *kernel_id = id_str ? strdup(id_str) : NULL;
    yyjson_doc_free(doc);
    if (!kernel_id) {
        return YETTY_ERR(yetty_ycore_void, "client_open: no kernel id in response");
    }
    free(client->kernel_id);
    client->kernel_id = kernel_id;

    /* WebSocket: open the kernel channels */
    char host[256];
    char port[16];
    parse_base_url(client->base_url, host, sizeof(host), port, sizeof(port));
    char path[1024];
    snprintf(path, sizeof(path), "/api/kernels/%s/channels?session_id=%s&token=%s",
             client->kernel_id, client->ws_session, client->token);
    client_reset_connection(client);
    int fd = ws_connect(host, port, path, client->token);
    if (fd < 0) {
        return YETTY_ERR(yetty_ycore_void, "client_open: websocket handshake failed");
    }
    client->sockfd = fd;
    return YETTY_OK_VOID();
}

/* execute: send an execute_request for `code` on the shell channel, correlated
 * to `tag`. Returns the request msg_id (owned; caller frees). */
YETTY_ANNOTATE("virtual@yjupyter:client:client_execute")
YETTY_ANNOTATE("local@yjupyter:client_execute")
static struct yetty_ycore_char_ptr_result client_execute(struct yetty_yclass_object *obj,
                                                         const char *code, const char *tag)
{
    struct yetty_yclass_void_ptr_result client_r = client_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_char_ptr, client_r, "client_execute: from_obj");
    struct yetty_yjupyter_client *client = client_r.value;
    if (client->sockfd < 0 || !client->session) {
        return YETTY_ERR(yetty_ycore_char_ptr, "client_execute: not connected");
    }

    /* build the execute_request content */
    yyjson_mut_doc *content_doc = yyjson_mut_doc_new(NULL);
    yyjson_mut_val *content = yyjson_mut_obj(content_doc);
    yyjson_mut_obj_add_strcpy(content_doc, content, "code", code ? code : "");
    yyjson_mut_obj_add_bool(content_doc, content, "silent", false);
    yyjson_mut_obj_add_bool(content_doc, content, "store_history", true);
    yyjson_mut_obj_add_val(content_doc, content, "user_expressions", yyjson_mut_obj(content_doc));
    yyjson_mut_obj_add_bool(content_doc, content, "allow_stdin", false);
    yyjson_mut_obj_add_bool(content_doc, content, "stop_on_error", true);
    yyjson_mut_doc_set_root(content_doc, content);
    char *content_json = yyjson_mut_write(content_doc, 0, NULL);
    yyjson_mut_doc_free(content_doc);
    if (!content_json) {
        return YETTY_ERR(yetty_ycore_char_ptr, "client_execute: content build failed");
    }

    struct yetty_yclass_object_ptr_result request_r = yetty_yjupyter_session_new_request(
        client->session, "execute_request", "shell", content_json, tag ? tag : "");
    free(content_json);
    YETTY_RETURN_IF_ERR(yetty_ycore_char_ptr, request_r, "client_execute: new_request");
    struct yetty_yclass_object *request = request_r.value;

    struct yetty_ycore_const_char_ptr_result id_r = yetty_yjupyter_message_msg_id(request);
    char *msg_id = strdup(YETTY_IS_OK(id_r) ? id_r.value : "");

    struct yetty_ycore_char_ptr_result wire_r = yetty_yjupyter_message_to_wire(request);
    if (YETTY_IS_ERR(wire_r)) {
        free(msg_id);
        yetty_yjupyter_message_destroy(request);
        return YETTY_ERR(yetty_ycore_char_ptr, "client_execute: to_wire", wire_r);
    }
    int rc = ws_send_text(client->sockfd, wire_r.value);
    free(wire_r.value);
    yetty_yjupyter_message_destroy(request);
    if (rc) {
        free(msg_id);
        return YETTY_ERR(yetty_ycore_char_ptr, "client_execute: websocket send failed");
    }
    if (!msg_id) {
        return YETTY_ERR(yetty_ycore_char_ptr, "client_execute: alloc failed");
    }
    return YETTY_OK(yetty_ycore_char_ptr, msg_id);
}

/* poll: wait up to `timeout_ms` for the next incoming message. Returns a
 * message object (caller owns) whose kernel status has already updated the
 * session; errors on timeout or a closed connection. */
YETTY_ANNOTATE("virtual@yjupyter:client:client_poll")
YETTY_ANNOTATE("local@yjupyter:client_poll")
static struct yetty_yclass_object_ptr_result client_poll(struct yetty_yclass_object *obj,
                                                         int timeout_ms)
{
    struct yetty_yclass_void_ptr_result client_r = client_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_yclass_object_ptr, client_r, "client_poll: from_obj");
    struct yetty_yjupyter_client *client = client_r.value;
    if (client->sockfd < 0 || !client->session) {
        return YETTY_ERR(yetty_yclass_object_ptr, "client_poll: not connected");
    }

    int closed = 0;
    char *frame = ws_recv_text(client->sockfd, timeout_ms, &closed);
    if (!frame) {
        if (closed) {
            close(client->sockfd);
            client->sockfd = -1;
            return YETTY_ERR(yetty_yclass_object_ptr, "client_poll: connection closed");
        }
        return YETTY_ERR(yetty_yclass_object_ptr, "client_poll: timeout");
    }
    struct yetty_yclass_object_ptr_result message_r =
        yetty_yjupyter_session_handle_wire(client->session, frame);
    free(frame);
    return message_r;
}

/* kernel_state: the tracked busy/idle/... state of the kernel. */
YETTY_ANNOTATE("virtual@yjupyter:client:client_kernel_state")
YETTY_ANNOTATE("local@yjupyter:client_kernel_state")
static struct yetty_ycore_const_char_ptr_result client_kernel_state(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result client_r = client_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_const_char_ptr, client_r, "client_kernel_state: from_obj");
    struct yetty_yjupyter_client *client = client_r.value;
    if (!client->session) {
        return YETTY_OK(yetty_ycore_const_char_ptr, "unknown");
    }
    return yetty_yjupyter_session_kernel_state(client->session);
}

/* tag_for: the caller tag correlated to a reply's parent_header.msg_id. */
YETTY_ANNOTATE("virtual@yjupyter:client:client_tag_for")
YETTY_ANNOTATE("local@yjupyter:client_tag_for")
static struct yetty_ycore_const_char_ptr_result client_tag_for(struct yetty_yclass_object *obj,
                                                               const char *parent_msg_id)
{
    struct yetty_yclass_void_ptr_result client_r = client_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_const_char_ptr, client_r, "client_tag_for: from_obj");
    struct yetty_yjupyter_client *client = client_r.value;
    if (!client->session) {
        return YETTY_OK(yetty_ycore_const_char_ptr, "");
    }
    return yetty_yjupyter_session_tag_for(client->session, parent_msg_id);
}

/* close: shut the WebSocket and delete the kernel over REST. */
YETTY_ANNOTATE("virtual@yjupyter:client:client_close")
YETTY_ANNOTATE("local@yjupyter:client_close")
static struct yetty_ycore_void_result client_close(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result client_r = client_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, client_r, "client_close: from_obj");
    struct yetty_yjupyter_client *client = client_r.value;
    client_reset_connection(client);
    if (client->base_url && client->kernel_id) {
        char delete_url[1024];
        snprintf(delete_url, sizeof(delete_url), "%s/api/kernels/%s", client->base_url,
                 client->kernel_id);
        long status = 0;
        struct yetty_ycore_char_ptr_result delete_r =
            http_do("DELETE", delete_url, client->token, NULL, &status);
        if (YETTY_IS_OK(delete_r)) {
            free(delete_r.value);
        }
    }
    return YETTY_OK_VOID();
}

/* destroy: close the connection, free the session, and the yclass allocation. */
YETTY_ANNOTATE("virtual@yjupyter:client:client_destroy")
YETTY_ANNOTATE("local@yjupyter:client_destroy")
static struct yetty_ycore_void_result client_destroy(struct yetty_yclass_object *obj)
{
    if (!obj) {
        return YETTY_OK_VOID();
    }
    struct yetty_yclass_void_ptr_result client_r = client_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, client_r, "client_destroy: from_obj");
    struct yetty_yjupyter_client *client = client_r.value;
    client_reset_connection(client);
    if (client->session) {
        yetty_yjupyter_session_destroy(client->session);
    }
    free(client->base_url);
    free(client->token);
    free(client->kernel_id);
    free(client->ws_session);
    client->base_url = NULL;
    client->token = NULL;
    client->kernel_id = NULL;
    client->ws_session = NULL;
    client->session = NULL;
    return yetty_yclass_object_free(obj);
}

#include "client.gen.c"
