/*
 * yjupyter protocol layer — the Jupyter v5 messaging wire, as yclass classes.
 *
 *   yjupyter:message  — one Jupyter message (the JSON WebSocket frame:
 *                       {header, parent_header, metadata, content, channel}).
 *                       Build a request, encode/decode the frame, inspect it.
 *   yjupyter:session  — a client session: session id + monotonic msg-id
 *                       generation, request->tag correlation keyed on the
 *                       reply's parent_header.msg_id, and kernel busy/idle
 *                       state tracked from IOPub `status` messages.
 *
 * This is the transport-independent protocol core (the design's "encode/decode
 * ... correlate replies with requests ... track kernel busy/idle" surface). It
 * rides over a WebSocket to Jupyter Server; the live socket I/O is a separate
 * boundary above this layer. Output routing never binds to a "currently
 * executing" cell — a reply belongs to the request whose msg_id equals its
 * parent_header.msg_id (see docs/ynotebook.md).
 *
 * The public interface is generated by yclass codegen from the annotations
 * below — never hand-write protocol.h. yyjson is used internally; the public
 * methods take and return JSON text, keeping the codec out of the header.
 */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <yyjson.h>

#include <yetty/yclass/class.h>
#include <yetty/ycore/result.h>

/*=============================================================================
 * Class data
 *===========================================================================*/

struct YETTY_ANNOTATE("class@yjupyter:message") yetty_yjupyter_message {
    yyjson_mut_doc *doc; /* owns the frame JSON */
    yyjson_mut_val *root;
};

struct yjupyter_pending {
    char *msg_id; /* owned; the request's msg_id */
    char *tag;    /* owned; the caller's correlation token (e.g. a cell id) */
};

struct YETTY_ANNOTATE("class@yjupyter:session") yetty_yjupyter_session {
    char *session_id; /* owned */
    unsigned long long msg_counter;
    char *kernel_state;               /* owned; "unknown"/"starting"/"idle"/"busy"/"dead" */
    struct yjupyter_pending *pending; /* owned vector: request msg_id -> tag */
    size_t pending_count;
    size_t pending_cap;
};

YETTY_YRESULT_DECLARE(yetty_yjupyter_message_ptr, struct yetty_yjupyter_message *);
YETTY_YRESULT_DECLARE(yetty_yjupyter_session_ptr, struct yetty_yjupyter_session *);

/* Defined in the appended protocol.gen.c. */
struct yetty_yclass_ptr_result yetty_yjupyter_message_class_get(void);
struct yetty_yclass_ptr_result yetty_yjupyter_session_class_get(void);
struct yetty_yclass_object_ptr_result yetty_yjupyter_message_create(struct yetty_yclass_ctx *ctx);
struct yetty_yclass_object_ptr_result yetty_yjupyter_session_create(struct yetty_yclass_ctx *ctx);

static struct yetty_yclass_void_ptr_result message_from_obj(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_ptr_result class_r = yetty_yjupyter_message_class_get();
    YETTY_RETURN_IF_ERR(yetty_yclass_void_ptr, class_r, "message from_obj: class_get");
    return yetty_yclass_object_data(obj, class_r.value);
}

static struct yetty_yclass_void_ptr_result session_from_obj(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_ptr_result class_r = yetty_yjupyter_session_class_get();
    YETTY_RETURN_IF_ERR(yetty_yclass_void_ptr, class_r, "session from_obj: class_get");
    return yetty_yclass_object_data(obj, class_r.value);
}

/*=============================================================================
 * yyjson read helpers
 *===========================================================================*/

static yyjson_mut_val *mobj_get(yyjson_mut_val *obj, const char *key)
{
    return obj ? yyjson_mut_obj_get(obj, key) : NULL;
}

static const char *mobj_str(yyjson_mut_val *obj, const char *key)
{
    yyjson_mut_val *val = mobj_get(obj, key);
    return (val && yyjson_mut_is_str(val)) ? yyjson_mut_get_str(val) : NULL;
}

/* Parse `json_text` (or "{}" when empty) and deep-copy the value into `doc`. */
static yyjson_mut_val *parse_into(yyjson_mut_doc *doc, const char *json_text)
{
    if (!json_text || !json_text[0]) {
        return yyjson_mut_obj(doc);
    }
    yyjson_doc *parsed = yyjson_read(json_text, strlen(json_text), 0);
    if (!parsed) {
        return yyjson_mut_obj(doc);
    }
    yyjson_mut_val *copy = yyjson_val_mut_copy(doc, yyjson_doc_get_root(parsed));
    yyjson_doc_free(parsed);
    return copy ? copy : yyjson_mut_obj(doc);
}

/*=============================================================================
 * message method slots
 *===========================================================================*/

/* build: populate this message as a Jupyter v5 frame. `content_json` is the
 * message content object as JSON text (or "" for an empty object);
 * `parent_msg_id` is "" for an originating request. Replaces any prior content. */
YETTY_ANNOTATE("virtual@yjupyter:message:message_build")
YETTY_ANNOTATE("local@yjupyter:message_build")
static struct yetty_ycore_void_result message_build(struct yetty_yclass_object *obj,
                                                    const char *msg_type, const char *channel,
                                                    const char *session_id, const char *msg_id,
                                                    const char *parent_msg_id,
                                                    const char *content_json)
{
    struct yetty_yclass_void_ptr_result message_r = message_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, message_r, "message_build: from_obj");
    struct yetty_yjupyter_message *message = message_r.value;

    yyjson_mut_doc *doc = yyjson_mut_doc_new(NULL);
    if (!doc) {
        return YETTY_ERR(yetty_ycore_void, "message_build: doc alloc failed");
    }
    yyjson_mut_val *root = yyjson_mut_obj(doc);
    yyjson_mut_val *header = yyjson_mut_obj(doc);
    yyjson_mut_val *parent = yyjson_mut_obj(doc);
    yyjson_mut_val *metadata = yyjson_mut_obj(doc);
    yyjson_mut_val *content = parse_into(doc, content_json);
    if (!root || !header || !parent || !metadata || !content) {
        yyjson_mut_doc_free(doc);
        return YETTY_ERR(yetty_ycore_void, "message_build: node alloc failed");
    }

    yyjson_mut_obj_add_strcpy(doc, header, "msg_id", msg_id ? msg_id : "");
    yyjson_mut_obj_add_strcpy(doc, header, "session", session_id ? session_id : "");
    yyjson_mut_obj_add_strcpy(doc, header, "username", "yetty");
    yyjson_mut_obj_add_strcpy(doc, header, "msg_type", msg_type ? msg_type : "");
    yyjson_mut_obj_add_strcpy(doc, header, "version", "5.3");
    if (parent_msg_id && parent_msg_id[0]) {
        yyjson_mut_obj_add_strcpy(doc, parent, "msg_id", parent_msg_id);
    }

    yyjson_mut_obj_add_val(doc, root, "header", header);
    yyjson_mut_obj_add_val(doc, root, "parent_header", parent);
    yyjson_mut_obj_add_val(doc, root, "metadata", metadata);
    yyjson_mut_obj_add_val(doc, root, "content", content);
    yyjson_mut_obj_add_strcpy(doc, root, "channel", channel ? channel : "shell");
    yyjson_mut_doc_set_root(doc, root);

    if (message->doc) {
        yyjson_mut_doc_free(message->doc);
    }
    message->doc = doc;
    message->root = root;
    return YETTY_OK_VOID();
}

/* from_wire: parse an incoming WebSocket JSON frame into this message. */
YETTY_ANNOTATE("virtual@yjupyter:message:message_from_wire")
YETTY_ANNOTATE("local@yjupyter:message_from_wire")
static struct yetty_ycore_void_result message_from_wire(struct yetty_yclass_object *obj,
                                                        const char *json)
{
    struct yetty_yclass_void_ptr_result message_r = message_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, message_r, "message_from_wire: from_obj");
    struct yetty_yjupyter_message *message = message_r.value;
    if (!json) {
        return YETTY_ERR(yetty_ycore_void, "message_from_wire: NULL json");
    }

    yyjson_doc *parsed = yyjson_read(json, strlen(json), 0);
    if (!parsed) {
        return YETTY_ERR(yetty_ycore_void, "message_from_wire: parse failed");
    }
    yyjson_mut_doc *doc = yyjson_doc_mut_copy(parsed, NULL);
    yyjson_doc_free(parsed);
    if (!doc) {
        return YETTY_ERR(yetty_ycore_void, "message_from_wire: mutable copy failed");
    }
    yyjson_mut_val *root = yyjson_mut_doc_get_root(doc);
    if (!root || !yyjson_mut_is_obj(root)) {
        yyjson_mut_doc_free(doc);
        return YETTY_ERR(yetty_ycore_void, "message_from_wire: frame is not an object");
    }

    if (message->doc) {
        yyjson_mut_doc_free(message->doc);
    }
    message->doc = doc;
    message->root = root;
    return YETTY_OK_VOID();
}

/* to_wire: serialize the message as a WebSocket JSON frame (owned; caller frees). */
YETTY_ANNOTATE("virtual@yjupyter:message:message_to_wire")
YETTY_ANNOTATE("local@yjupyter:message_to_wire")
static struct yetty_ycore_char_ptr_result message_to_wire(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result message_r = message_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_char_ptr, message_r, "message_to_wire: from_obj");
    struct yetty_yjupyter_message *message = message_r.value;
    if (!message->doc) {
        return YETTY_ERR(yetty_ycore_char_ptr, "message_to_wire: empty message");
    }
    char *text = yyjson_mut_write(message->doc, 0, NULL);
    if (!text) {
        return YETTY_ERR(yetty_ycore_char_ptr, "message_to_wire: write failed");
    }
    return YETTY_OK(yetty_ycore_char_ptr, text);
}

/* header/routing accessors (borrowed; valid while the message lives). */
YETTY_ANNOTATE("virtual@yjupyter:message:message_msg_type")
YETTY_ANNOTATE("local@yjupyter:message_msg_type")
static struct yetty_ycore_const_char_ptr_result message_msg_type(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result message_r = message_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_const_char_ptr, message_r, "message_msg_type: from_obj");
    struct yetty_yjupyter_message *message = message_r.value;
    const char *value = mobj_str(mobj_get(message->root, "header"), "msg_type");
    return YETTY_OK(yetty_ycore_const_char_ptr, value ? value : "");
}

YETTY_ANNOTATE("virtual@yjupyter:message:message_msg_id")
YETTY_ANNOTATE("local@yjupyter:message_msg_id")
static struct yetty_ycore_const_char_ptr_result message_msg_id(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result message_r = message_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_const_char_ptr, message_r, "message_msg_id: from_obj");
    struct yetty_yjupyter_message *message = message_r.value;
    const char *value = mobj_str(mobj_get(message->root, "header"), "msg_id");
    return YETTY_OK(yetty_ycore_const_char_ptr, value ? value : "");
}

YETTY_ANNOTATE("virtual@yjupyter:message:message_parent_msg_id")
YETTY_ANNOTATE("local@yjupyter:message_parent_msg_id")
static struct yetty_ycore_const_char_ptr_result message_parent_msg_id(
    struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result message_r = message_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_const_char_ptr, message_r, "message_parent_msg_id: from_obj");
    struct yetty_yjupyter_message *message = message_r.value;
    const char *value = mobj_str(mobj_get(message->root, "parent_header"), "msg_id");
    return YETTY_OK(yetty_ycore_const_char_ptr, value ? value : "");
}

YETTY_ANNOTATE("virtual@yjupyter:message:message_channel")
YETTY_ANNOTATE("local@yjupyter:message_channel")
static struct yetty_ycore_const_char_ptr_result message_channel(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result message_r = message_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_const_char_ptr, message_r, "message_channel: from_obj");
    struct yetty_yjupyter_message *message = message_r.value;
    const char *value = mobj_str(message->root, "channel");
    return YETTY_OK(yetty_ycore_const_char_ptr, value ? value : "");
}

YETTY_ANNOTATE("virtual@yjupyter:message:message_session")
YETTY_ANNOTATE("local@yjupyter:message_session")
static struct yetty_ycore_const_char_ptr_result message_session(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result message_r = message_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_const_char_ptr, message_r, "message_session: from_obj");
    struct yetty_yjupyter_message *message = message_r.value;
    const char *value = mobj_str(mobj_get(message->root, "header"), "session");
    return YETTY_OK(yetty_ycore_const_char_ptr, value ? value : "");
}

/* content_json: the message content object as JSON text (owned). */
YETTY_ANNOTATE("virtual@yjupyter:message:message_content_json")
YETTY_ANNOTATE("local@yjupyter:message_content_json")
static struct yetty_ycore_char_ptr_result message_content_json(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result message_r = message_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_char_ptr, message_r, "message_content_json: from_obj");
    struct yetty_yjupyter_message *message = message_r.value;
    yyjson_mut_val *content = mobj_get(message->root, "content");
    char *text = content ? yyjson_mut_val_write(content, 0, NULL) : NULL;
    if (!text) {
        text = strdup("{}");
    }
    if (!text) {
        return YETTY_ERR(yetty_ycore_char_ptr, "message_content_json: alloc failed");
    }
    return YETTY_OK(yetty_ycore_char_ptr, text);
}

/* content_string: a string field of the content object (e.g. "code", "text",
 * "name", "execution_state", "ename", "status"); owned, "" when absent. */
YETTY_ANNOTATE("virtual@yjupyter:message:message_content_string")
YETTY_ANNOTATE("local@yjupyter:message_content_string")
static struct yetty_ycore_char_ptr_result message_content_string(struct yetty_yclass_object *obj,
                                                                 const char *key)
{
    struct yetty_yclass_void_ptr_result message_r = message_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_char_ptr, message_r, "message_content_string: from_obj");
    struct yetty_yjupyter_message *message = message_r.value;
    const char *value = mobj_str(mobj_get(message->root, "content"), key);
    char *out = strdup(value ? value : "");
    if (!out) {
        return YETTY_ERR(yetty_ycore_char_ptr, "message_content_string: alloc failed");
    }
    return YETTY_OK(yetty_ycore_char_ptr, out);
}

/* content_int: an integer field of the content object (e.g. "execution_count");
 * -1 when absent or not an integer. */
YETTY_ANNOTATE("virtual@yjupyter:message:message_content_int")
YETTY_ANNOTATE("local@yjupyter:message_content_int")
static struct yetty_ycore_int_result message_content_int(struct yetty_yclass_object *obj,
                                                         const char *key)
{
    struct yetty_yclass_void_ptr_result message_r = message_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_int, message_r, "message_content_int: from_obj");
    struct yetty_yjupyter_message *message = message_r.value;
    yyjson_mut_val *value = mobj_get(mobj_get(message->root, "content"), key);
    if (value && yyjson_mut_is_int(value)) {
        return YETTY_OK(yetty_ycore_int, (int)yyjson_mut_get_sint(value));
    }
    return YETTY_OK(yetty_ycore_int, -1);
}

YETTY_ANNOTATE("virtual@yjupyter:message:message_destroy")
YETTY_ANNOTATE("local@yjupyter:message_destroy")
static struct yetty_ycore_void_result message_destroy(struct yetty_yclass_object *obj)
{
    if (!obj) {
        return YETTY_OK_VOID();
    }
    struct yetty_yclass_void_ptr_result message_r = message_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, message_r, "message_destroy: from_obj");
    struct yetty_yjupyter_message *message = message_r.value;
    if (message->doc) {
        yyjson_mut_doc_free(message->doc);
    }
    message->doc = NULL;
    message->root = NULL;
    return yetty_yclass_object_free(obj);
}

/*=============================================================================
 * session helpers
 *===========================================================================*/

static struct yetty_ycore_void_result session_record(struct yetty_yjupyter_session *session,
                                                     const char *msg_id, const char *tag)
{
    if (session->pending_count == session->pending_cap) {
        size_t new_cap = session->pending_cap ? session->pending_cap * 2 : 8;
        struct yjupyter_pending *grown = realloc(session->pending, new_cap * sizeof(*grown));
        if (!grown) {
            return YETTY_ERR(yetty_ycore_void, "session_record: pending grow failed");
        }
        session->pending = grown;
        session->pending_cap = new_cap;
    }
    char *msg_id_copy = strdup(msg_id);
    char *tag_copy = strdup(tag);
    if (!msg_id_copy || !tag_copy) {
        free(msg_id_copy);
        free(tag_copy);
        return YETTY_ERR(yetty_ycore_void, "session_record: dup failed");
    }
    session->pending[session->pending_count].msg_id = msg_id_copy;
    session->pending[session->pending_count].tag = tag_copy;
    session->pending_count++;
    return YETTY_OK_VOID();
}

/*=============================================================================
 * session method slots
 *===========================================================================*/

/* init: set the session id (a non-empty value is required — Jupyter Server keys
 * a kernel session on it). Resets counters, correlation, and kernel state. */
YETTY_ANNOTATE("virtual@yjupyter:session:session_init")
YETTY_ANNOTATE("local@yjupyter:session_init")
static struct yetty_ycore_void_result session_init(struct yetty_yclass_object *obj,
                                                   const char *session_id)
{
    struct yetty_yclass_void_ptr_result session_r = session_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, session_r, "session_init: from_obj");
    struct yetty_yjupyter_session *session = session_r.value;
    if (!session_id || !session_id[0]) {
        return YETTY_ERR(yetty_ycore_void, "session_init: empty session id");
    }

    char *id = strdup(session_id);
    char *state = strdup("unknown");
    if (!id || !state) {
        free(id);
        free(state);
        return YETTY_ERR(yetty_ycore_void, "session_init: alloc failed");
    }
    free(session->session_id);
    free(session->kernel_state);
    session->session_id = id;
    session->kernel_state = state;
    session->msg_counter = 0;
    return YETTY_OK_VOID();
}

YETTY_ANNOTATE("virtual@yjupyter:session:session_id")
YETTY_ANNOTATE("local@yjupyter:session_id")
static struct yetty_ycore_const_char_ptr_result session_id(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result session_r = session_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_const_char_ptr, session_r, "session_id: from_obj");
    struct yetty_yjupyter_session *session = session_r.value;
    return YETTY_OK(yetty_ycore_const_char_ptr, session->session_id ? session->session_id : "");
}

YETTY_ANNOTATE("virtual@yjupyter:session:session_kernel_state")
YETTY_ANNOTATE("local@yjupyter:session_kernel_state")
static struct yetty_ycore_const_char_ptr_result session_kernel_state(
    struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result session_r = session_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_const_char_ptr, session_r, "session_kernel_state: from_obj");
    struct yetty_yjupyter_session *session = session_r.value;
    return YETTY_OK(yetty_ycore_const_char_ptr,
                    session->kernel_state ? session->kernel_state : "unknown");
}

/* new_request: build a request message on `channel` with `content_json`,
 * assigning a fresh session-unique msg_id. When `tag` is non-empty, the
 * (msg_id -> tag) pair is recorded so replies can be correlated back with
 * tag_for(). Returns a message object the caller owns (destroy it). */
YETTY_ANNOTATE("virtual@yjupyter:session:session_new_request")
YETTY_ANNOTATE("local@yjupyter:session_new_request")
static struct yetty_yclass_object_ptr_result session_new_request(struct yetty_yclass_object *obj,
                                                                 const char *msg_type,
                                                                 const char *channel,
                                                                 const char *content_json,
                                                                 const char *tag)
{
    struct yetty_yclass_void_ptr_result session_r = session_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_yclass_object_ptr, session_r, "session_new_request: from_obj");
    struct yetty_yjupyter_session *session = session_r.value;
    if (!session->session_id) {
        return YETTY_ERR(yetty_yclass_object_ptr, "session_new_request: session not initialized");
    }

    char msg_id[320];
    snprintf(msg_id, sizeof(msg_id), "%s_%llu", session->session_id, session->msg_counter++);

    struct yetty_yclass_ctx ctx = {0};
    struct yetty_yclass_object_ptr_result message_r = yetty_yjupyter_message_create(&ctx);
    YETTY_RETURN_IF_ERR(yetty_yclass_object_ptr, message_r, "session_new_request: message create");
    struct yetty_yclass_object *message = message_r.value;

    struct yetty_ycore_void_result build_r =
        message_build(message, msg_type, channel, session->session_id, msg_id, "", content_json);
    if (YETTY_IS_ERR(build_r)) {
        message_destroy(message);
        return YETTY_ERR(yetty_yclass_object_ptr, "session_new_request: build failed", build_r);
    }

    if (tag && tag[0]) {
        struct yetty_ycore_void_result record_r = session_record(session, msg_id, tag);
        if (YETTY_IS_ERR(record_r)) {
            message_destroy(message);
            return YETTY_ERR(yetty_yclass_object_ptr, "session_new_request: record failed",
                             record_r);
        }
    }
    return YETTY_OK(yetty_yclass_object_ptr, message);
}

/* handle_wire: parse an incoming WebSocket frame into a message object (caller
 * owns it). When it is an IOPub `status` message, the kernel busy/idle state is
 * updated from its content.execution_state. */
YETTY_ANNOTATE("virtual@yjupyter:session:session_handle_wire")
YETTY_ANNOTATE("local@yjupyter:session_handle_wire")
static struct yetty_yclass_object_ptr_result session_handle_wire(struct yetty_yclass_object *obj,
                                                                 const char *json)
{
    struct yetty_yclass_void_ptr_result session_r = session_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_yclass_object_ptr, session_r, "session_handle_wire: from_obj");
    struct yetty_yjupyter_session *session = session_r.value;

    struct yetty_yclass_ctx ctx = {0};
    struct yetty_yclass_object_ptr_result message_r = yetty_yjupyter_message_create(&ctx);
    YETTY_RETURN_IF_ERR(yetty_yclass_object_ptr, message_r, "session_handle_wire: message create");
    struct yetty_yclass_object *message = message_r.value;

    struct yetty_ycore_void_result parse_r = message_from_wire(message, json);
    if (YETTY_IS_ERR(parse_r)) {
        message_destroy(message);
        return YETTY_ERR(yetty_yclass_object_ptr, "session_handle_wire: parse failed", parse_r);
    }

    struct yetty_yjupyter_message *decoded = message_from_obj(message).value;
    const char *msg_type = mobj_str(mobj_get(decoded->root, "header"), "msg_type");
    if (msg_type && strcmp(msg_type, "status") == 0) {
        const char *state = mobj_str(mobj_get(decoded->root, "content"), "execution_state");
        if (state) {
            char *state_copy = strdup(state);
            if (state_copy) {
                free(session->kernel_state);
                session->kernel_state = state_copy;
            }
        }
    }
    return YETTY_OK(yetty_yclass_object_ptr, message);
}

/* tag_for: the caller tag recorded for the request whose msg_id is
 * `parent_msg_id` (i.e. the reply's parent_header.msg_id). "" when unknown —
 * an orphan the caller should route to a diagnostic stream, never an arbitrary
 * request. */
YETTY_ANNOTATE("virtual@yjupyter:session:session_tag_for")
YETTY_ANNOTATE("local@yjupyter:session_tag_for")
static struct yetty_ycore_const_char_ptr_result session_tag_for(struct yetty_yclass_object *obj,
                                                                const char *parent_msg_id)
{
    struct yetty_yclass_void_ptr_result session_r = session_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_const_char_ptr, session_r, "session_tag_for: from_obj");
    struct yetty_yjupyter_session *session = session_r.value;
    if (parent_msg_id && parent_msg_id[0]) {
        for (size_t i = 0; i < session->pending_count; i++) {
            if (strcmp(session->pending[i].msg_id, parent_msg_id) == 0) {
                return YETTY_OK(yetty_ycore_const_char_ptr, session->pending[i].tag);
            }
        }
    }
    return YETTY_OK(yetty_ycore_const_char_ptr, "");
}

YETTY_ANNOTATE("virtual@yjupyter:session:session_destroy")
YETTY_ANNOTATE("local@yjupyter:session_destroy")
static struct yetty_ycore_void_result session_destroy(struct yetty_yclass_object *obj)
{
    if (!obj) {
        return YETTY_OK_VOID();
    }
    struct yetty_yclass_void_ptr_result session_r = session_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, session_r, "session_destroy: from_obj");
    struct yetty_yjupyter_session *session = session_r.value;
    for (size_t i = 0; i < session->pending_count; i++) {
        free(session->pending[i].msg_id);
        free(session->pending[i].tag);
    }
    free(session->pending);
    free(session->session_id);
    free(session->kernel_state);
    session->pending = NULL;
    session->pending_count = 0;
    session->pending_cap = 0;
    session->session_id = NULL;
    session->kernel_state = NULL;
    return yetty_yclass_object_free(obj);
}

#include "protocol.gen.c"
