steps:
  build:
    image: yetty-build
    commands:
      - apt-get update
      - apt-get install -y git git-lfs make cmake
      - git lfs install
      - git lfs fetch
      - make build-desktop-ytrace-release
