labels:
  platform: darwin/*

clone:
  git:
    depth: 50
    lfs: false

steps:
  build:
    commands:
      - git lfs install
      - git lfs fetch
      - git lfs checkout
      - make build-desktop-ytrace-release
