labels:
  platform: darwin/amd64

when:
  - event: [push, manual, pull_request, tag]

steps:
  build:
    image: bash
    commands:
      - git lfs install
      - git lfs fetch
      - git lfs checkout
      - make build-desktop-ytrace-release
