/*
 * vtermgrid.c — the independent yscene client terminal grid: class@yscene:vtermgrid.
 *
 * The Yetty-side (client) end of an ymux attachment (#699). It owns its OWN
 * libvterm instance, driven through the public SCREEN layer, and exposes the
 * resulting bounded cell grid to a dedicated packed cell-grid GPU pass. It is
 * a plain classical terminal endpoint: bytes in (ordinary terminal output —
 * text + escape/control sequences, tmux-style redraw), a cell grid out. No
 * history, no session authority, no rich content — those live elsewhere.
 *
 * This is NOT yvterm and does not reuse, wrap, extract, or link yvterm. It is
 * an independent libvterm consumer built fresh for yscene, and it is DOM-free:
 * cells never become DOM nodes or generic scene records.
 *
 * The public header (include/yetty/api/yscene/vtermgrid.h) is generated by
 * codegen from the annotations here.
 */
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include <vterm.h>
#include <webgpu/webgpu.h>

#include <yetty/yclass/class.h>
#include <yetty/ycore/result.h>
#include <yetty/ycore/types.h>
#include <yetty/yfont/ms-font.h>
#include <yetty/yframework/yframework.h>
#include <yetty/ytrace/ytrace.h>

#include "vtermgrid-store.h" /* cluster-preserving cell store (#699.5) */
#include <yetty/yevent/event-loop.h>
#include <yetty/yrender/gpu-resource-set.h>
#include <yetty/yrender/render-target.h>
#include <yetty/yrender/texture-format.h>

/*===========================================================================
 * Exposed cell model.
 *=========================================================================*/

/* Per-cell attribute bits exposed to the GPU packer / consumers. Kept as a
 * compact bitset (not the libvterm bitfield) so the packed GPU cell can carry
 * it in one 16-bit field. */
enum YETTY_ANNOTATE("expose") yetty_yscene_vtermgrid_cell_attr {
    YETTY_YSCENE_VTERMGRID_ATTR_BOLD = 1u << 0,
    YETTY_YSCENE_VTERMGRID_ATTR_UNDERLINE = 1u << 1,
    YETTY_YSCENE_VTERMGRID_ATTR_UNDERLINE2 = 1u << 2,
    YETTY_YSCENE_VTERMGRID_ATTR_ITALIC = 1u << 3,
    YETTY_YSCENE_VTERMGRID_ATTR_REVERSE = 1u << 4,
    YETTY_YSCENE_VTERMGRID_ATTR_BLINK = 1u << 5,
    YETTY_YSCENE_VTERMGRID_ATTR_STRIKE = 1u << 6,
    YETTY_YSCENE_VTERMGRID_ATTR_CONCEAL = 1u << 7,
    /* Review #19 endpoint semantics: SGR 2 dim, and the CURLY bit that —
     * combined with UNDERLINE2 — distinguishes the extended underline
     * styles (UNDERLINE=single, UNDERLINE2=double, UNDERLINE2|CURLY=curly)
     * instead of collapsing every style >= 2 into one form. */
    YETTY_YSCENE_VTERMGRID_ATTR_FAINT = 1u << 8,
    YETTY_YSCENE_VTERMGRID_ATTR_UNDERLINE_CURLY = 1u << 9,
};

/* One resolved terminal cell. `glyph` is the Unicode codepoint (the grid runs
 * libvterm with a NULL glyph resolver, so the cell's glyph index IS the
 * codepoint); the GPU packer maps it to an atlas slot. `fg`/`bg` are packed
 * 0xFFBBGGRR. `width` is 1 (normal), 2 (wide head) or 0 (wide continuation /
 * empty). */
struct YETTY_ANNOTATE("expose") yetty_yscene_vtermgrid_cell {
    uint32_t glyph;
    uint32_t fg;
    uint32_t bg;
    uint16_t attrs;
    uint8_t width;
    uint8_t pad;
};

/* Wide-glyph continuation sentinel the libvterm fork writes into the trailing
 * column of a double-width cell (screen.c GLYPH_WIDE_CONT). Not exposed in the
 * public header, so mirror the constant here. */
enum { YETTY_YSCENE_VTERMGRID_GLYPH_WIDE_CONT = 0xFFFEu };

/* Brand defaults (BRAND_BG / BRAND_TEXT_PRIMARY), packed 0xFFBBGGRR. */
enum {
    YETTY_YSCENE_VTERMGRID_DEFAULT_FG = 0xFFE4E5E0u,
    YETTY_YSCENE_VTERMGRID_DEFAULT_BG = 0xFF14100Bu,
};

/*===========================================================================
 * The grid — the yclass data block.
 *=========================================================================*/

struct YETTY_ANNOTATE("class@yscene:vtermgrid") YETTY_ANNOTATE("internal") yetty_yscene_vtermgrid {
    VTerm *vterm;
    /* The CLUSTER-PRESERVING cell store (#699.5): fed by STATE callbacks —
     * the fork's screen layer is not used (its 16-byte cell drops combining
     * marks). Semantics pinned by the yscene_vtermgrid_store contract test. */
    /* Selection (review #11): a linear cell span rendered inverted. */
    uint32_t sel_start_row, sel_start_col, sel_end_row, sel_end_col;
    int sel_active;
    struct yetty_yscene_vtermgrid_store store;     /* primary screen */
    struct yetty_yscene_vtermgrid_store alt_store; /* alternate screen (review #11) */
    int on_alt_screen;
    VTermState *state;

    uint32_t rows;
    uint32_t cols;

    uint32_t cursor_row;
    uint32_t cursor_col;
    int cursor_visible;
    int cursor_shape;
    int cursor_blink;

    int reverse_video; /* DECSCNM: swap fg/bg screen-wide */

    uint32_t default_fg;
    uint32_t default_bg;

    /* Content generation, bumped on every damage/cursor move so the render
     * side knows when to re-pack the cell buffer. */
    uint32_t generation;

    /* SGR blink (attr 5, #699.5): a slow per-grid event-loop timer toggles the
     * phase and bumps the generation, so blink cells re-pack hidden/shown on
     * the next frame. Lazy — the timer starts on the first pack that sees a
     * blink cell and its ticks no-op once none remain. NULL event_loop (no
     * runtime loop) leaves blink frozen visible — cosmetic, never fatal. */
    struct yetty_yevent_event_loop *event_loop; /* borrowed */
    /* Render kick installed by the owning scene: an animation tick must mark
     * the FIGURE dirty (the compositor's repaint gate), which the grid cannot
     * do itself — it has no figure context. NULL = raw request_render only. */
    void (*render_kick)(void *userdata);
    void *render_kick_userdata;
    struct yetty_yevent_event_listener blink_listener;
    yetty_yevent_timer_id blink_timer;
    int blink_timer_running;
    int blink_phase;     /* 1 = blink cells (and blinking cursor) hidden */
    int has_blink_cells; /* the last pack saw at least one blink cell */

    /* BEL arrivals in the fed byte stream (review #10: the callback table had
     * .bell = NULL, silently dropping them). The embedder polls the counter or
     * installs a hook to present the bell (audible/visual). */
    uint64_t bell_count;
    void (*bell_hook)(void *userdata);
    void *bell_hook_userdata;

    /* Terminal reply bytes the grid's libvterm generated (DA/DSR/CPR answers
     * to queries in the fed stream). ACCUMULATED (review #14/#15), no longer
     * discard-only: the scene exposes a scalar-word drain the bridge polls
     * and forwards through the attachment input path — the single
     * controlling attachment owns the answer. reply_discarded_bytes counts
     * only overflow past the bounded buffer. */
    uint64_t reply_discarded_bytes;
    /* Terminal replies (review #14, the #699 reply route): accumulated for
     * the embedder to TAKE and forward via attachment input/control. Bounded;
     * overflow counts into reply_discarded_bytes. */
    uint8_t *reply_buffer; /* growable (review #17); bounded at 1 MB */
    size_t reply_buffer_len;
    size_t reply_buffer_cap;

    /* Split-write UTF-8 guard: a feed chunk ending mid-sequence holds the
     * partial tail here and prepends it to the next chunk, so arbitrary wire
     * fragmentation cannot corrupt decoding. */
    uint8_t pending_utf8[4];
    uint8_t pending_utf8_len;

    /*--- GPU state (all NULL/0 in headless mode) ------------------------*/
    WGPUDevice device;
    WGPUQueue queue;
    WGPUTextureFormat target_format;
    struct yetty_yfont_ms_font *font; /* borrowed — resolves glyphs + atlas */

    WGPUShaderModule shader_module;
    WGPUBindGroupLayout bind_group_layout;
    WGPURenderPipeline pipeline;
    WGPUSampler sampler;

    WGPUBuffer cell_buffer;
    size_t cell_buffer_cells;
    WGPUBuffer uniform_buffer;

    WGPUBuffer meta_buffer;
    size_t meta_capacity;
    WGPUTexture atlas_texture;
    WGPUTextureView atlas_view;
    uint32_t atlas_width;
    uint32_t atlas_height;
    uint32_t atlas_format;
    uint32_t atlas_bytes_per_pixel;

    /* Optional FALLBACK face (#89): a raster ms-font whose FreeType chain
     * covers what the MSDF base face misses (CJK etc.). Cells that resolve
     * here carry face=1 in word3; the shader samples its cell-slot atlas. */
    struct yetty_yfont_ms_font *fallback_font; /* borrowed (scene owns) */
    WGPUBuffer fallback_meta_buffer;
    size_t fallback_meta_capacity;
    WGPUTexture fallback_atlas_texture;
    WGPUTextureView fallback_atlas_view;
    uint32_t fallback_atlas_width;
    uint32_t fallback_atlas_height;
    uint32_t fallback_atlas_format;
    uint32_t fallback_atlas_bytes_per_pixel;

    WGPUBindGroup bind_group;
    int bind_group_valid;

    uint32_t *pack_scratch;
    size_t pack_scratch_cells;

    /* Per-face MSDF geometry, refreshed from the font on upload. */
    float uni_pixel_range;
    float uni_scale;
    float uni_baseline_y;
    float uni_glyph_left;
    struct yetty_ycore_pixel_size cell_size;
};

/* Provided by the generated impl glue (foot include). */
struct yetty_yclass_ptr_result yetty_yscene_vtermgrid_class_get(void);
YETTY_YRESULT_DECLARE(yetty_yscene_vtermgrid_ptr, struct yetty_yscene_vtermgrid *);
struct yetty_yscene_vtermgrid_ptr_result yetty_yscene_vtermgrid_from(
    struct yetty_yclass_object *obj);

/* GPU teardown (defined in the GPU section below) — released on dispose. */
static void vtermgrid_gpu_teardown(struct yetty_yscene_vtermgrid *grid);

/*===========================================================================
 * Small helpers.
 *=========================================================================*/

static uint32_t vtermgrid_pack_color(VTermColor color)
{
    return (uint32_t)color.red | ((uint32_t)color.green << 8) | ((uint32_t)color.blue << 16) |
           (0xFFu << 24);
}

static VTermColor vtermgrid_unpack_web_rgb(uint32_t rgb)
{
    VTermColor color;
    color.red = (uint8_t)(rgb & 0xFFu);
    color.green = (uint8_t)((rgb >> 8) & 0xFFu);
    color.blue = (uint8_t)((rgb >> 16) & 0xFFu);
    return color;
}

/*===========================================================================
 * Screen callbacks — the client only tracks damage + cursor.
 *=========================================================================*/

static uint32_t vtermgrid_pack_color(VTermColor color);

/* --- STATE callbacks (#699.5 cutover): canonical mutations wired into the
 * cluster-preserving store; the fork's screen layer is bypassed entirely. --- */

static struct yetty_yscene_vtermgrid_store *vtermgrid_active_store(
    struct yetty_yscene_vtermgrid *grid)
{
    return grid->on_alt_screen ? &grid->alt_store : &grid->store;
}

YETTY_EXTERNAL_CALLBACK
static int vtermgrid_cb_putglyph(VTermGlyphInfo *info, VTermPos pos, void *user)
{
    struct yetty_yscene_vtermgrid *grid = user;
    uint32_t codepoints[1 + YETTY_YSCENE_VTERMGRID_STORE_MAX_MARKS];
    uint32_t count = 0;
    if (info->chars) {
        while (count < 1 + YETTY_YSCENE_VTERMGRID_STORE_MAX_MARKS && info->chars[count]) {
            codepoints[count] = info->chars[count];
            ++count;
        }
    }
    struct yetty_yscene_vtermgrid_store *active = vtermgrid_active_store(grid);
    active->pen_protected = info->protected_cell ? 1 : 0;
    struct yetty_ycore_void_result put_res = yetty_yscene_vtermgrid_store_put(
        active, pos.row >= 0 ? (uint32_t)pos.row : 0u, pos.col >= 0 ? (uint32_t)pos.col : 0u,
        codepoints, count, info->width >= 2);
    if (YETTY_IS_ERR(put_res)) {
        yetty_ycore_error_destroy(put_res.error); /* out-of-range write — ignore */
    }
    grid->generation++;
    return 1;
}

YETTY_EXTERNAL_CALLBACK
static int vtermgrid_cb_state_moverect(VTermRect dest, VTermRect src, void *user)
{
    /* Rectangle copy on the store (the fork's partial-scroll decomposition
     * step). Row-major memmove-safe ordering by direction. */
    struct yetty_yscene_vtermgrid *grid = user;
    struct yetty_yscene_vtermgrid_store *store = vtermgrid_active_store(grid);
    int rows = dest.end_row - dest.start_row;
    int cols = dest.end_col - dest.start_col;
    if (rows <= 0 || cols <= 0) {
        return 1;
    }
    int row_step = dest.start_row <= src.start_row ? 1 : -1;
    for (int step = 0; step < rows; ++step) {
        int row_offset = row_step > 0 ? step : rows - 1 - step;
        int dest_row = dest.start_row + row_offset;
        int src_row = src.start_row + row_offset;
        if (dest_row < 0 || (uint32_t)dest_row >= store->rows || src_row < 0 ||
            (uint32_t)src_row >= store->rows) {
            continue;
        }
        /* Column direction matters too (review #12): a rightward
         * overlapping move copied left-to-right overwrites source cells
         * before they are read. */
        int col_step = dest.start_col <= src.start_col ? 1 : -1;
        for (int step_col = 0; step_col < cols; ++step_col) {
            int col_offset = col_step > 0 ? step_col : cols - 1 - step_col;
            int from_col = src.start_col + col_offset;
            int to_col = dest.start_col + col_offset;
            if (from_col < 0 || (uint32_t)from_col >= store->cols || to_col < 0 ||
                (uint32_t)to_col >= store->cols) {
                continue;
            }
            store->cells[(size_t)dest_row * store->cols + to_col] =
                store->cells[(size_t)src_row * store->cols + from_col];
        }
    }
    grid->generation++;
    return 1;
}

YETTY_EXTERNAL_CALLBACK
static int vtermgrid_cb_state_erase(VTermRect rect, int selective, void *user)
{
    struct yetty_yscene_vtermgrid *grid = user;
    yetty_yscene_vtermgrid_store_erase_selective(
        vtermgrid_active_store(grid), rect.start_row >= 0 ? (uint32_t)rect.start_row : 0u,
        rect.end_row >= 0 ? (uint32_t)rect.end_row : 0u,
        rect.start_col >= 0 ? (uint32_t)rect.start_col : 0u,
        rect.end_col >= 0 ? (uint32_t)rect.end_col : 0u, selective);
    grid->generation++;
    return 1;
}

YETTY_EXTERNAL_CALLBACK
static int vtermgrid_cb_scrollrect(VTermRect rect, int downward, int rightward, void *user)
{
    struct yetty_yscene_vtermgrid *grid = user;
    struct yetty_yscene_vtermgrid_store *store = vtermgrid_active_store(grid);
    if (rightward == 0 && rect.start_col == 0 && rect.end_col == (int)store->cols &&
        rect.start_row == 0 && rect.end_row == (int)store->rows) {
        yetty_yscene_vtermgrid_store_scroll(store, downward);
        grid->generation++;
        return 1;
    }
    if (downward == 0 && rect.end_row == rect.start_row + 1 && rect.start_row >= 0 &&
        rect.end_col == (int)store->cols) {
        yetty_yscene_vtermgrid_store_hshift(store, (uint32_t)rect.start_row,
                                            rect.start_col >= 0 ? (uint32_t)rect.start_col : 0u,
                                            -rightward);
        grid->generation++;
        return 1;
    }
    /* Partial rect: the fork decomposes into move + erase steps. */
    vterm_scroll_rect(rect, downward, rightward, vtermgrid_cb_state_moverect,
                      vtermgrid_cb_state_erase, grid);
    return 1;
}

YETTY_EXTERNAL_CALLBACK
static int vtermgrid_cb_initpen(void *user)
{
    struct yetty_yscene_vtermgrid *grid = user;
    struct yetty_yscene_vtermgrid_store *store = vtermgrid_active_store(grid);
    store->pen_fg = store->default_fg;
    store->pen_bg = store->default_bg;
    store->pen_attrs = 0;
    store->pen_protected = 0;
    return 1;
}

YETTY_EXTERNAL_CALLBACK
static int vtermgrid_cb_setpenattr(VTermAttr attr, VTermValue *val, void *user)
{
    struct yetty_yscene_vtermgrid *grid = user;
    struct yetty_yscene_vtermgrid_store *store = vtermgrid_active_store(grid);
    switch (attr) {
    case VTERM_ATTR_BOLD:
        store->pen_attrs = (uint16_t)((store->pen_attrs & ~YETTY_YSCENE_VTERMGRID_ATTR_BOLD) |
                                      (val->boolean ? YETTY_YSCENE_VTERMGRID_ATTR_BOLD : 0));
        break;
    case VTERM_ATTR_UNDERLINE:
        store->pen_attrs &= (uint16_t)~(YETTY_YSCENE_VTERMGRID_ATTR_UNDERLINE |
                                        YETTY_YSCENE_VTERMGRID_ATTR_UNDERLINE2 |
                                        YETTY_YSCENE_VTERMGRID_ATTR_UNDERLINE_CURLY);
        if (val->number == VTERM_UNDERLINE_SINGLE) {
            store->pen_attrs |= YETTY_YSCENE_VTERMGRID_ATTR_UNDERLINE;
        } else if (val->number == VTERM_UNDERLINE_DOUBLE) {
            store->pen_attrs |= YETTY_YSCENE_VTERMGRID_ATTR_UNDERLINE2;
        } else if (val->number >= VTERM_UNDERLINE_CURLY) {
            store->pen_attrs |= YETTY_YSCENE_VTERMGRID_ATTR_UNDERLINE2 |
                                YETTY_YSCENE_VTERMGRID_ATTR_UNDERLINE_CURLY;
        }
        break;
    case VTERM_ATTR_FAINT:
        store->pen_attrs = (uint16_t)((store->pen_attrs & ~YETTY_YSCENE_VTERMGRID_ATTR_FAINT) |
                                      (val->boolean ? YETTY_YSCENE_VTERMGRID_ATTR_FAINT : 0));
        break;
    case VTERM_ATTR_ITALIC:
        store->pen_attrs = (uint16_t)((store->pen_attrs & ~YETTY_YSCENE_VTERMGRID_ATTR_ITALIC) |
                                      (val->boolean ? YETTY_YSCENE_VTERMGRID_ATTR_ITALIC : 0));
        break;
    case VTERM_ATTR_BLINK:
        store->pen_attrs = (uint16_t)((store->pen_attrs & ~YETTY_YSCENE_VTERMGRID_ATTR_BLINK) |
                                      (val->boolean ? YETTY_YSCENE_VTERMGRID_ATTR_BLINK : 0));
        break;
    case VTERM_ATTR_REVERSE:
        store->pen_attrs = (uint16_t)((store->pen_attrs & ~YETTY_YSCENE_VTERMGRID_ATTR_REVERSE) |
                                      (val->boolean ? YETTY_YSCENE_VTERMGRID_ATTR_REVERSE : 0));
        break;
    case VTERM_ATTR_STRIKE:
        store->pen_attrs = (uint16_t)((store->pen_attrs & ~YETTY_YSCENE_VTERMGRID_ATTR_STRIKE) |
                                      (val->boolean ? YETTY_YSCENE_VTERMGRID_ATTR_STRIKE : 0));
        break;
    case VTERM_ATTR_CONCEAL:
        store->pen_attrs = (uint16_t)((store->pen_attrs & ~YETTY_YSCENE_VTERMGRID_ATTR_CONCEAL) |
                                      (val->boolean ? YETTY_YSCENE_VTERMGRID_ATTR_CONCEAL : 0));
        break;
    case VTERM_ATTR_FOREGROUND:
        store->pen_fg = vtermgrid_pack_color(val->color);
        break;
    case VTERM_ATTR_BACKGROUND:
        store->pen_bg = vtermgrid_pack_color(val->color);
        break;
    default:
        break;
    }
    return 1;
}

YETTY_EXTERNAL_CALLBACK
static int vtermgrid_cb_state_resize(int rows, int cols, VTermStateFields *fields, void *user)
{
    struct yetty_yscene_vtermgrid *grid = user;
    (void)fields;
    uint32_t new_rows = rows > 0 ? (uint32_t)rows : 1u;
    uint32_t new_cols = cols > 0 ? (uint32_t)cols : 1u;
    struct yetty_ycore_void_result resize_res =
        yetty_yscene_vtermgrid_store_resize(&grid->store, new_rows, new_cols);
    if (YETTY_IS_ERR(resize_res)) {
        yetty_ycore_error_destroy(resize_res.error);
    }
    struct yetty_ycore_void_result alt_resize_res =
        yetty_yscene_vtermgrid_store_resize(&grid->alt_store, new_rows, new_cols);
    if (YETTY_IS_ERR(alt_resize_res)) {
        yetty_ycore_error_destroy(alt_resize_res.error);
    }
    grid->rows = new_rows;
    grid->cols = new_cols;
    grid->generation++;
    return 1;
}

YETTY_EXTERNAL_CALLBACK
static int vtermgrid_cb_movecursor(VTermPos pos, VTermPos oldpos, int visible, void *user)
{
    (void)oldpos;
    struct yetty_yscene_vtermgrid *grid = user;
    grid->cursor_row = pos.row >= 0 ? (uint32_t)pos.row : 0;
    grid->cursor_col = pos.col >= 0 ? (uint32_t)pos.col : 0;
    grid->cursor_visible = visible;
    grid->generation++;
    return 1;
}

YETTY_EXTERNAL_CALLBACK
static int vtermgrid_cb_settermprop(VTermProp prop, VTermValue *val, void *user)
{
    struct yetty_yscene_vtermgrid *grid = user;
    switch (prop) {
    case VTERM_PROP_CURSORVISIBLE:
        grid->cursor_visible = val->boolean;
        break;
    case VTERM_PROP_CURSORBLINK:
        grid->cursor_blink = val->boolean;
        break;
    case VTERM_PROP_CURSORSHAPE:
        grid->cursor_shape = val->number;
        break;
    case VTERM_PROP_REVERSE:
        grid->reverse_video = val->boolean;
        break;
    case VTERM_PROP_ALTSCREEN:
        /* Enter: switch writes/reads to the alt store, blanked like a fresh
         * screen. Leave: the PRIMARY store was never touched — restoring it
         * is the switch itself (review #11). */
        if (val->boolean && !grid->on_alt_screen) {
            yetty_yscene_vtermgrid_store_erase(&grid->alt_store, 0, grid->alt_store.rows, 0,
                                               grid->alt_store.cols);
            /* The pen is TERMINAL state, not screen state: the live pen
             * follows the switch (review #12 — entering alt under a
             * non-default SGR painted stale colors). */
            grid->alt_store.pen_fg = grid->store.pen_fg;
            grid->alt_store.pen_bg = grid->store.pen_bg;
            grid->alt_store.pen_attrs = grid->store.pen_attrs;
            grid->alt_store.pen_protected = grid->store.pen_protected;
            grid->on_alt_screen = 1;
        } else if (!val->boolean && grid->on_alt_screen) {
            grid->store.pen_fg = grid->alt_store.pen_fg;
            grid->store.pen_bg = grid->alt_store.pen_bg;
            grid->store.pen_attrs = grid->alt_store.pen_attrs;
            grid->store.pen_protected = grid->alt_store.pen_protected;
            grid->on_alt_screen = 0;
        }
        break;
    default:
        break;
    }
    grid->generation++;
    return 1;
}

YETTY_EXTERNAL_CALLBACK
static int vtermgrid_cb_resize(int rows, int cols, void *user)
{
    struct yetty_yscene_vtermgrid *grid = user;
    grid->rows = rows > 0 ? (uint32_t)rows : 1;
    grid->cols = cols > 0 ? (uint32_t)cols : 1;
    grid->generation++;
    return 1;
}

/* libvterm reply bytes (answers to DA/DSR/... queries in the fed stream):
 * ACCUMULATED into the bounded reply buffer for the scene's scalar-word
 * drain (the bridge forwards them through attachment input — the single
 * controlling attachment answers, never N projections). Overflow past the
 * buffer is counted into reply_discarded_bytes. */
YETTY_EXTERNAL_CALLBACK
static void vtermgrid_cb_output(const char *bytes, size_t len, void *user)
{
    struct yetty_yscene_vtermgrid *grid = user;
    enum { REPLY_BUFFER_MAX = 1u << 20 };
    size_t needed = grid->reply_buffer_len + len;
    if (needed > grid->reply_buffer_cap && grid->reply_buffer_cap < REPLY_BUFFER_MAX) {
        size_t new_cap = grid->reply_buffer_cap ? grid->reply_buffer_cap * 2 : 1024;
        while (new_cap < needed && new_cap < REPLY_BUFFER_MAX) {
            new_cap *= 2;
        }
        uint8_t *grown = realloc(grid->reply_buffer, new_cap);
        if (grown) {
            grid->reply_buffer = grown;
            grid->reply_buffer_cap = new_cap;
        }
    }
    size_t room = grid->reply_buffer_cap > grid->reply_buffer_len
                      ? grid->reply_buffer_cap - grid->reply_buffer_len
                      : 0;
    size_t take = len < room ? len : room;
    if (take > 0) {
        memcpy(grid->reply_buffer + grid->reply_buffer_len, bytes, take);
        grid->reply_buffer_len += take;
    }
    if (take < len) {
        grid->reply_discarded_bytes += len - take; /* only past the 1 MB bound */
    }
}

YETTY_EXTERNAL_CALLBACK
static int vtermgrid_cb_bell(void *user)
{
    struct yetty_yscene_vtermgrid *grid = user;
    grid->bell_count++;
    if (grid->bell_hook) {
        grid->bell_hook(grid->bell_hook_userdata);
    }
    return 1;
}

/* The state callback table lives at program scope as a static const local, so
 * no file-scope data symbol is emitted. */
static const VTermStateCallbacks *vtermgrid_state_callbacks(void)
{
    static const VTermStateCallbacks callbacks = {
        .putglyph = vtermgrid_cb_putglyph,
        .movecursor = vtermgrid_cb_movecursor,
        .scrollrect = vtermgrid_cb_scrollrect,
        .moverect = vtermgrid_cb_state_moverect,
        .erase = vtermgrid_cb_state_erase,
        .initpen = vtermgrid_cb_initpen,
        .setpenattr = vtermgrid_cb_setpenattr,
        .settermprop = vtermgrid_cb_settermprop,
        .bell = vtermgrid_cb_bell,
        .resize = vtermgrid_cb_state_resize,
    };
    return &callbacks;
}

/*===========================================================================
 * Lifecycle.
 *=========================================================================*/

static void vtermgrid_teardown(struct yetty_yscene_vtermgrid *grid)
{
    if (grid->vterm) {
        vterm_free(grid->vterm);
        grid->vterm = NULL;
    }
    yetty_yscene_vtermgrid_store_free(&grid->store);
    yetty_yscene_vtermgrid_store_free(&grid->alt_store);
    grid->state = NULL;
}

static struct yetty_ycore_void_result vtermgrid_open_vterm(struct yetty_yscene_vtermgrid *grid,
                                                           uint32_t rows, uint32_t cols)
{
    grid->vterm = vterm_new((int)rows, (int)cols);
    if (!grid->vterm) {
        return YETTY_ERR(yetty_ycore_void, "vtermgrid: vterm_new");
    }
    vterm_set_utf8(grid->vterm, 1);
    vterm_output_set_callback(grid->vterm, vtermgrid_cb_output, grid);
    /* #699.5 cutover: STATE callbacks into the cluster-preserving store —
     * the fork's screen layer (which drops combining marks) is bypassed. */
    grid->state = vterm_obtain_state(grid->vterm);
    if (!grid->state) {
        vtermgrid_teardown(grid);
        return YETTY_ERR(yetty_ycore_void, "vtermgrid: obtain_state");
    }
    struct yetty_ycore_void_result store_res = yetty_yscene_vtermgrid_store_init(
        &grid->store, rows, cols, grid->default_fg, grid->default_bg);
    if (YETTY_IS_ERR(store_res)) {
        vtermgrid_teardown(grid);
        return YETTY_ERR(yetty_ycore_void, "vtermgrid: store init", store_res);
    }
    struct yetty_ycore_void_result alt_store_res = yetty_yscene_vtermgrid_store_init(
        &grid->alt_store, rows, cols, grid->default_fg, grid->default_bg);
    if (YETTY_IS_ERR(alt_store_res)) {
        vtermgrid_teardown(grid);
        return YETTY_ERR(yetty_ycore_void, "vtermgrid: alt store init", alt_store_res);
    }
    vterm_state_set_callbacks(grid->state, vtermgrid_state_callbacks(), grid);
    VTermColor fg = vtermgrid_unpack_web_rgb(grid->default_fg);
    VTermColor bg = vtermgrid_unpack_web_rgb(grid->default_bg);
    vterm_state_set_default_colors(grid->state, &fg, &bg);
    /* Theme endpoint (review #19): DSR ?996n must report the REAL scheme of
     * this grid, not the zero-initialized "no preference" — derive dark vs
     * light from the configured default background's luma so tmux's theme
     * handshake (?997;1n / ?997;2n) carries a truthful value. */
    {
        uint32_t bg_red = grid->default_bg & 0xFFu;
        uint32_t bg_green = (grid->default_bg >> 8) & 0xFFu;
        uint32_t bg_blue = (grid->default_bg >> 16) & 0xFFu;
        uint32_t luma = (bg_red * 299u + bg_green * 587u + bg_blue * 114u) / 1000u;
        vterm_set_color_scheme(grid->vterm, luma < 128u ? 1 : 2);
    }
    vterm_state_reset(grid->state, 1 /* hard */);

    grid->rows = rows;
    grid->cols = cols;
    grid->cursor_row = 0;
    grid->cursor_col = 0;
    grid->cursor_visible = 1;
    grid->cursor_shape = VTERM_PROP_CURSORSHAPE_BLOCK;
    grid->cursor_blink = 1;
    grid->reverse_video = 0;
    grid->pending_utf8_len = 0;
    grid->generation++;
    return YETTY_OK_VOID();
}

/* Creation-time defaults + open the libvterm. (`constructor`/`destroy` are
 * module-scoped lifecycle slots owned by the scene class, so this class uses
 * the plain-object make/dispose idiom — like class@ymux:engine — while its
 * operational methods below are proper virtual@ RPC slots.) */
static struct yetty_ycore_void_result vtermgrid_init(struct yetty_yscene_vtermgrid *grid,
                                                     uint32_t rows, uint32_t cols)
{
    grid->default_fg = YETTY_YSCENE_VTERMGRID_DEFAULT_FG;
    grid->default_bg = YETTY_YSCENE_VTERMGRID_DEFAULT_BG;
    grid->generation = 1;
    return vtermgrid_open_vterm(grid, rows, cols);
}

YETTY_ANNOTATE("expose")
struct yetty_yclass_object_ptr_result yetty_yscene_vtermgrid_make(uint32_t rows, uint32_t cols)
{
    if (rows == 0 || cols == 0) {
        return YETTY_ERR(yetty_yclass_object_ptr, "vtermgrid_make: invalid size");
    }
    struct yetty_yclass_ptr_result class_res = yetty_yscene_vtermgrid_class_get();
    YETTY_RETURN_IF_ERR(yetty_yclass_object_ptr, class_res, "vtermgrid_make: class");
    struct yetty_yclass_object_ptr_result object_res = yetty_yclass_object_alloc(class_res.value);
    YETTY_RETURN_IF_ERR(yetty_yclass_object_ptr, object_res, "vtermgrid_make: object_alloc");
    struct yetty_yscene_vtermgrid_ptr_result grid_res =
        yetty_yscene_vtermgrid_from(object_res.value);
    if (YETTY_IS_ERR(grid_res)) {
        struct yetty_ycore_void_result free_res = yetty_yclass_object_free(object_res.value);
        if (YETTY_IS_ERR(free_res)) {
            yetty_ycore_error_destroy(free_res.error);
        }
        return YETTY_ERR(yetty_yclass_object_ptr, "vtermgrid_make: from_obj", grid_res);
    }
    struct yetty_ycore_void_result init_res = vtermgrid_init(grid_res.value, rows, cols);
    if (YETTY_IS_ERR(init_res)) {
        struct yetty_ycore_void_result free_res = yetty_yclass_object_free(object_res.value);
        if (YETTY_IS_ERR(free_res)) {
            yetty_ycore_error_destroy(free_res.error);
        }
        return YETTY_ERR(yetty_yclass_object_ptr, "vtermgrid_make: init", init_res);
    }
    return YETTY_OK(yetty_yclass_object_ptr, object_res.value);
}

YETTY_ANNOTATE("expose")
struct yetty_ycore_void_result yetty_yscene_vtermgrid_dispose(struct yetty_yclass_object *obj)
{
    if (!obj) {
        return YETTY_OK_VOID();
    }
    struct yetty_yscene_vtermgrid_ptr_result grid_res = yetty_yscene_vtermgrid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, grid_res, "vtermgrid_dispose: from_obj");
    vtermgrid_gpu_teardown(grid_res.value);
    vtermgrid_teardown(grid_res.value);
    return yetty_yclass_object_free(obj);
}

/*===========================================================================
 * Feed / reset / resize.
 *=========================================================================*/

/* Return the expected total byte length of a UTF-8 sequence given its lead
 * byte, or 0 for a continuation/invalid byte (treated as single-byte). */
static uint8_t vtermgrid_utf8_seq_len(uint8_t lead)
{
    if (lead < 0x80u) {
        return 1;
    }
    if ((lead & 0xE0u) == 0xC0u) {
        return 2;
    }
    if ((lead & 0xF0u) == 0xE0u) {
        return 3;
    }
    if ((lead & 0xF8u) == 0xF0u) {
        return 4;
    }
    return 1;
}

/* Feed ordinary terminal bytes to libvterm, holding back a trailing partial
 * UTF-8 sequence so a chunk split mid-codepoint never corrupts decoding. Local
 * (expose) — the scene's virtual@ terminal_grid_write is the RPC surface and
 * forwards here. */
YETTY_ANNOTATE("expose")
struct yetty_ycore_void_result yetty_yscene_vtermgrid_write(struct yetty_yclass_object *obj,
                                                            const uint8_t *bytes, size_t len)
{
    struct yetty_yscene_vtermgrid_ptr_result grid_res = yetty_yscene_vtermgrid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, grid_res, "vtermgrid_write: from_obj");
    struct yetty_yscene_vtermgrid *grid = grid_res.value;
    if (!grid->vterm || len == 0 || !bytes) {
        return YETTY_OK_VOID();
    }

    /* Reassemble a held-back partial sequence with the head of this chunk. */
    if (grid->pending_utf8_len > 0) {
        uint8_t need = vtermgrid_utf8_seq_len(grid->pending_utf8[0]);
        size_t take = 0;
        while (grid->pending_utf8_len + take < need && take < len) {
            grid->pending_utf8[grid->pending_utf8_len + take] = bytes[take];
            take++;
        }
        grid->pending_utf8_len = (uint8_t)(grid->pending_utf8_len + take);
        if (grid->pending_utf8_len == need) {
            vterm_input_write(grid->vterm, (const char *)grid->pending_utf8, need);
            grid->pending_utf8_len = 0;
            bytes += take;
            len -= take;
        } else {
            /* Still incomplete — consumed the whole chunk into the hold-back. */
            return YETTY_OK_VOID();
        }
    }

    /* Scan the tail for a partial multibyte sequence and hold it back. */
    size_t feed_len = len;
    if (len > 0) {
        size_t scan = len;
        size_t back = 0;
        while (scan > 0 && back < 3) {
            uint8_t byte = bytes[scan - 1];
            if ((byte & 0xC0u) == 0x80u) {
                /* continuation byte */
                scan--;
                back++;
                continue;
            }
            /* lead or ASCII byte */
            uint8_t need = vtermgrid_utf8_seq_len(byte);
            size_t have = len - (scan - 1);
            if (need > 1 && have < need) {
                feed_len = scan - 1;
            }
            break;
        }
        if (feed_len < len) {
            size_t tail = len - feed_len;
            if (tail <= sizeof(grid->pending_utf8)) {
                memcpy(grid->pending_utf8, bytes + feed_len, tail);
                grid->pending_utf8_len = (uint8_t)tail;
            } else {
                feed_len = len; /* pathological; feed as-is */
            }
        }
    }

    size_t offset = 0;
    while (offset < feed_len) {
        size_t wrote =
            vterm_input_write(grid->vterm, (const char *)(bytes + offset), feed_len - offset);
        if (wrote == 0) {
            break;
        }
        offset += wrote;
    }
    return YETTY_OK_VOID();
}

/* Discard all client terminal state and rebuild a fresh grid at the given
 * geometry — the reconnect / new-stream-epoch path. No parser checkpoint or
 * private state is carried across. */
YETTY_ANNOTATE("expose")
struct yetty_ycore_void_result yetty_yscene_vtermgrid_reset(struct yetty_yclass_object *obj,
                                                            uint32_t rows, uint32_t cols)
{
    struct yetty_yscene_vtermgrid_ptr_result grid_res = yetty_yscene_vtermgrid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, grid_res, "vtermgrid_reset: from_obj");
    struct yetty_yscene_vtermgrid *grid = grid_res.value;
    if (rows == 0 || cols == 0) {
        return YETTY_ERR(yetty_ycore_void, "vtermgrid_reset: invalid size");
    }
    vtermgrid_teardown(grid);
    return vtermgrid_open_vterm(grid, rows, cols);
}

/* Resize the grid in place; the screen layer reallocs its own buffers and
 * lineinfo (no manual fix needed, unlike the state-layer engine). */
YETTY_ANNOTATE("expose")
struct yetty_ycore_void_result yetty_yscene_vtermgrid_resize(struct yetty_yclass_object *obj,
                                                             uint32_t rows, uint32_t cols)
{
    struct yetty_yscene_vtermgrid_ptr_result grid_res = yetty_yscene_vtermgrid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, grid_res, "vtermgrid_resize: from_obj");
    struct yetty_yscene_vtermgrid *grid = grid_res.value;
    if (rows == 0 || cols == 0) {
        return YETTY_ERR(yetty_ycore_void, "vtermgrid_resize: invalid size");
    }
    if (!grid->vterm) {
        return YETTY_ERR(yetty_ycore_void, "vtermgrid_resize: no vterm");
    }
    vterm_set_size(grid->vterm, (int)rows, (int)cols);
    grid->rows = rows;
    grid->cols = cols;
    grid->generation++;
    return YETTY_OK_VOID();
}

/*===========================================================================
 * Accessors — cells, cursor, dims, generation.
 *=========================================================================*/

YETTY_ANNOTATE("expose")
struct yetty_ycore_void_result yetty_yscene_vtermgrid_dims(struct yetty_yclass_object *obj,
                                                           uint32_t *rows, uint32_t *cols)
{
    struct yetty_yscene_vtermgrid_ptr_result grid_res = yetty_yscene_vtermgrid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, grid_res, "vtermgrid_dims: from_obj");
    if (rows) {
        *rows = grid_res.value->rows;
    }
    if (cols) {
        *cols = grid_res.value->cols;
    }
    return YETTY_OK_VOID();
}

YETTY_ANNOTATE("expose")
struct yetty_ycore_uint32_result yetty_yscene_vtermgrid_generation(struct yetty_yclass_object *obj)
{
    struct yetty_yscene_vtermgrid_ptr_result grid_res = yetty_yscene_vtermgrid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_uint32, grid_res, "vtermgrid_generation: from_obj");
    return YETTY_OK(yetty_ycore_uint32, grid_res.value->generation);
}

YETTY_ANNOTATE("expose")
struct yetty_ycore_void_result yetty_yscene_vtermgrid_cursor(struct yetty_yclass_object *obj,
                                                             uint32_t *row, uint32_t *col,
                                                             int *visible)
{
    struct yetty_yscene_vtermgrid_ptr_result grid_res = yetty_yscene_vtermgrid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, grid_res, "vtermgrid_cursor: from_obj");
    struct yetty_yscene_vtermgrid *grid = grid_res.value;
    if (row) {
        *row = grid->cursor_row;
    }
    if (col) {
        *col = grid->cursor_col;
    }
    if (visible) {
        *visible = grid->cursor_visible;
    }
    return YETTY_OK_VOID();
}

/* Resolve libvterm's screen cell at (row,col) into the exposed packed form,
 * mapping the wide-continuation sentinel to width 0 and applying screen-wide
 * reverse. Out-of-range positions yield a blank default cell. */
static void vtermgrid_read_cell(struct yetty_yscene_vtermgrid *grid, uint32_t row, uint32_t col,
                                struct yetty_yscene_vtermgrid_cell *out)
{
    memset(out, 0, sizeof(*out));
    out->fg = grid->default_fg;
    out->bg = grid->default_bg;
    out->width = 1;
    if (row >= grid->rows || col >= grid->cols) {
        return;
    }
    /* #699.5: read from the cluster-preserving store. store_read resolves
     * reverse (cell attr XOR DECSCNM) into swapped colors — the same render
     * contract the fork's screen layer established; do NOT swap again. */
    vtermgrid_active_store(grid)->global_reverse = grid->reverse_video;
    struct yetty_yscene_vtermgrid_store_cell cell;
    yetty_yscene_vtermgrid_store_read(vtermgrid_active_store(grid), row, col, &cell);
    out->glyph = cell.codepoint; /* 0 = empty cell */
    out->width = cell.width;     /* 1 normal, 2 wide head, 0 wide continuation */
    out->fg = cell.fg;
    out->bg = cell.bg;
    out->attrs = cell.attrs;
}

/* Read one cell of the current screen. Out-of-range positions yield a blank
 * cell. */
YETTY_ANNOTATE("expose")
struct yetty_ycore_void_result yetty_yscene_vtermgrid_cell(struct yetty_yclass_object *obj,
                                                           uint32_t row, uint32_t col,
                                                           struct yetty_yscene_vtermgrid_cell *out)
{
    struct yetty_yscene_vtermgrid_ptr_result grid_res = yetty_yscene_vtermgrid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, grid_res, "vtermgrid_cell: from_obj");
    if (!out) {
        return YETTY_ERR(yetty_ycore_void, "vtermgrid_cell: null out");
    }
    vtermgrid_read_cell(grid_res.value, row, col, out);
    return YETTY_OK_VOID();
}

/*===========================================================================
 * GPU: a dedicated packed MSDF cell-grid pass.
 *
 * One full-screen quad reads a packed 4-u32-per-cell storage buffer plus an
 * MSDF glyph atlas + 10-float-per-glyph metrics buffer, and paints the grid in
 * the fragment stage. Reimplemented fresh (the yvterm grid technique, not its
 * code); single font face, no effects/zoom.
 *=========================================================================*/

/* Packed cell layout (matches the embedded shader):
 *   word0 = atlas glyph slot (0 blank, 0xFFFFFFFF notdef/tofu)
 *   word1 = fg.r | fg.g<<8 | fg.b<<16 | bg.r<<24
 *   word2 = bg.g | bg.b<<8 | attrs<<16
 *   word3 = width(8) | face(8)
 *   word4..8 = combining-mark atlas slots (0 = none): ALL five retained
 *              cluster marks composite over the base glyph (review #11)
 *   word9..11 = reserved                                                       */
enum { YETTY_YSCENE_VTERMGRID_WORDS_PER_CELL = 12 };

static const char *vtermgrid_shader_wgsl(void)
{
    return "struct Uniforms {\n"
           "  grid_size: vec2<f32>,\n"
           "  cell_size: vec2<f32>,\n"
           "  pixel_range: f32,\n"
           "  scale: f32,\n"
           "  baseline_y: f32,\n"
           "  glyph_left: f32,\n"
           "  cursor_col: u32,\n"
           "  cursor_row: u32,\n"
           "  cursor_visible: u32,\n"
           "  cursor_shape: u32,\n"
           "  sel_start_row: u32,\n"
           "  sel_start_col: u32,\n"
           "  sel_end_row: u32,\n"
           "  sel_end_col: u32,\n"
           "  sel_active: u32,\n"
           "  pad0: u32,\n"
           "  pad1: u32,\n"
           "  pad2: u32,\n"
           "};\n"
           "@group(0) @binding(0) var<storage, read> cells: array<u32>;\n"
           "@group(0) @binding(1) var<storage, read> glyph_meta: array<u32>;\n"
           "@group(0) @binding(2) var atlas_tex: texture_2d<f32>;\n"
           "@group(0) @binding(3) var atlas_smp: sampler;\n"
           "@group(0) @binding(4) var<uniform> uni: Uniforms;\n"
           "@group(0) @binding(5) var<storage, read> glyph_meta_fb: array<u32>;\n"
           "@group(0) @binding(6) var atlas_fb_tex: texture_2d<f32>;\n"
           "struct VSOut {\n"
           "  @builtin(position) pos: vec4<f32>,\n"
           "  @location(0) @interpolate(linear) grid_pixel: vec2<f32>,\n"
           "};\n"
           "@vertex\n"
           "fn vs_main(@builtin(vertex_index) vid: u32) -> VSOut {\n"
           "  var corners = array<vec2<f32>,6>(\n"
           "    vec2<f32>(-1.0,-1.0), vec2<f32>(1.0,-1.0), vec2<f32>(1.0,1.0),\n"
           "    vec2<f32>(-1.0,-1.0), vec2<f32>(1.0,1.0), vec2<f32>(-1.0,1.0));\n"
           "  let ndc = corners[vid];\n"
           "  var out: VSOut;\n"
           "  out.pos = vec4<f32>(ndc, 0.0, 1.0);\n"
           "  let gw = uni.grid_size.x * uni.cell_size.x;\n"
           "  let gh = uni.grid_size.y * uni.cell_size.y;\n"
           "  out.grid_pixel = vec2<f32>((ndc.x*0.5+0.5)*gw, (0.5-ndc.y*0.5)*gh);\n"
           "  return out;\n"
           "}\n"
           "fn median3(r: f32, g: f32, b: f32) -> f32 { return max(min(r,g), min(max(r,g), b)); }\n"
           "// Fallback face: cell-slot raster atlas (4-word records: uv origin,\n"
           "// slot width in cells). Coverage is the R channel, no SDF decode.\n"
           "fn sample_fallback(glyph: u32, local_px: vec2<f32>) -> f32 {\n"
           "  let base = glyph * 4u;\n"
           "  let uvx = bitcast<f32>(glyph_meta_fb[base+0u]);\n"
           "  let uvy = bitcast<f32>(glyph_meta_fb[base+1u]);\n"
           "  if (uvx < 0.0) { return 0.0; }\n"
           "  let width_cells = max(bitcast<f32>(glyph_meta_fb[base+2u]), 1.0);\n"
           "  let slot = vec2<f32>(uni.cell_size.x * width_cells, uni.cell_size.y);\n"
           "  if (local_px.x < 0.0 || local_px.y < 0.0 || local_px.x >= slot.x || local_px.y >= "
           "slot.y) { return 0.0; }\n"
           "  let atlas_size = vec2<f32>(textureDimensions(atlas_fb_tex));\n"
           "  let uv = vec2<f32>(uvx, uvy) + local_px / atlas_size;\n"
           "  return textureSampleLevel(atlas_fb_tex, atlas_smp, uv, 0.0).r;\n"
           "}\n"
           "fn sample_glyph(glyph: u32, local_px_in: vec2<f32>, bold: bool, italic: bool) -> f32 "
           "{\n"
           "  var local_px = local_px_in;\n"
           "  // Faux italic: shear the sample coordinate so glyph content leans right\n"
           "  // above the baseline (no italic face — a synthetic slant of ~11 deg).\n"
           "  if (italic) { local_px.x = local_px.x - (uni.baseline_y - local_px.y) * 0.20; }\n"
           "  let base = glyph * 10u;\n"
           "  let uv_min = vec2<f32>(bitcast<f32>(glyph_meta[base+0u]), "
           "bitcast<f32>(glyph_meta[base+1u]));\n"
           "  let uv_max = vec2<f32>(bitcast<f32>(glyph_meta[base+2u]), "
           "bitcast<f32>(glyph_meta[base+3u]));\n"
           "  let gsize = vec2<f32>(bitcast<f32>(glyph_meta[base+4u]), "
           "bitcast<f32>(glyph_meta[base+5u]));\n"
           "  let bear = vec2<f32>(bitcast<f32>(glyph_meta[base+6u]), "
           "bitcast<f32>(glyph_meta[base+7u]));\n"
           "  if (gsize.x <= 0.0 || gsize.y <= 0.0) { return 0.0; }\n"
           "  let ssz = gsize * uni.scale;\n"
           "  let sbr = bear * uni.scale;\n"
           "  let gtop = uni.baseline_y - sbr.y;\n"
           "  let gleft = uni.glyph_left + sbr.x;\n"
           "  if (local_px.x < gleft || local_px.x >= gleft+ssz.x || local_px.y < gtop || "
           "local_px.y >= gtop+ssz.y) { return 0.0; }\n"
           "  let gl = (local_px - vec2<f32>(gleft, gtop)) / ssz;\n"
           "  let uv = mix(uv_min, uv_max, gl);\n"
           "  let texel = textureSampleLevel(atlas_tex, atlas_smp, uv, 0.0);\n"
           "  let sd = median3(texel.r, texel.g, texel.b);\n"
           "  let spr = max(uni.pixel_range * uni.scale, 1.0);\n"
           "  // Faux bold: bias the MSDF threshold outward so the coverage grows\n"
           "  // (no bold face — a synthetic weight increase).\n"
           "  let bias = select(0.0, 0.14, bold);\n"
           "  return clamp((sd - 0.5 + bias) * spr + 0.5, 0.0, 1.0);\n"
           "}\n"
           "@fragment\n"
           "fn fs_main(in: VSOut) -> @location(0) vec4<f32> {\n"
           "  let gw = uni.grid_size.x * uni.cell_size.x;\n"
           "  let gh = uni.grid_size.y * uni.cell_size.y;\n"
           "  let px = in.grid_pixel;\n"
           "  if (px.x < 0.0 || px.y < 0.0 || px.x >= gw || px.y >= gh) { return "
           "vec4<f32>(0.0,0.0,0.0,1.0); }\n"
           "  let colf = floor(px.x / uni.cell_size.x);\n"
           "  let rowf = floor(px.y / uni.cell_size.y);\n"
           "  let col = u32(colf);\n"
           "  let row = u32(rowf);\n"
           "  let gcols = u32(uni.grid_size.x);\n"
           "  let ci = row * gcols + col;\n"
           "  var local = vec2<f32>(px.x - colf*uni.cell_size.x, px.y - rowf*uni.cell_size.y);\n"
           "  var glyph = cells[ci*12u + 0u];\n"
           "  var face = (cells[ci*12u + 3u] >> 8u) & 0xFFu;\n"
           "  let w1 = cells[ci*12u + 1u];\n"
           "  let w2 = cells[ci*12u + 2u];\n"
           "  let attrs = (w2 >> 16u) & 0xFFFFu;\n"
           "  let bold = (attrs & 0x1u) != 0u;\n"
           "  let italic = (attrs & 0x8u) != 0u;\n"
           "  let fg = vec3<f32>(f32(w1 & 0xFFu)/255.0, f32((w1>>8u)&0xFFu)/255.0, "
           "f32((w1>>16u)&0xFFu)/255.0);\n"
           "  let bg = vec3<f32>(f32((w1>>24u)&0xFFu)/255.0, f32(w2 & 0xFFu)/255.0, "
           "f32((w2>>8u)&0xFFu)/255.0);\n"
           "  if ((cells[ci*12u + 3u] & 0xFFu) == 0u && col > 0u) {\n"
           "    let head = row * gcols + (col - 1u);\n"
           "    if ((cells[head*12u + 3u] & 0xFFu) == 2u) {\n"
           "      glyph = cells[head*12u + 0u];\n"
           "      face = (cells[head*12u + 3u] >> 8u) & 0xFFu;\n"
           "      local.x = local.x + uni.cell_size.x;\n"
           "    }\n"
           "  }\n"
           "  var alpha = 0.0;\n"
           "  if (glyph == 0xFFFFFFFFu) {\n"
           "    let inx = uni.cell_size.x * 0.16; let iny = uni.cell_size.y * 0.12;\n"
           "    let th = max(1.0, uni.cell_size.x * 0.07);\n"
           "    let x0 = inx; let x1 = uni.cell_size.x - inx; let y0 = iny; let y1 = "
           "uni.cell_size.y - iny;\n"
           "    let on_box = local.x >= x0 && local.x <= x1 && local.y >= y0 && local.y <= y1;\n"
           "    let in_hole = local.x >= x0+th && local.x <= x1-th && local.y >= y0+th && local.y "
           "<= y1-th;\n"
           "    if (on_box && !in_hole) { alpha = 1.0; }\n"
           "  } else if (glyph != 0u) {\n"
           "    if (face == 1u) { alpha = sample_fallback(glyph, local); }\n"
           "    else { alpha = sample_glyph(glyph, local, bold, italic); }\n"
           "  }\n"
           "  // Combining marks (Stage C): retained cluster marks composite over\n"
           "  // the base glyph by max coverage, sharing its fg.\n"
           "  for (var mark = 0u; face == 0u && mark < 5u; mark = mark + 1u) {\n"
           "    let mslot = cells[ci*12u + 4u + mark];\n"
           "    if (mslot != 0u && mslot != 0xFFFFFFFFu) {\n"
           "      alpha = max(alpha, sample_glyph(mslot, local, bold, italic));\n"
           "    }\n"
           "  }\n"
           "  // Conceal (SGR 8): the cell's glyph is suppressed (bg-only).\n"
           "  if ((attrs & 0x80u) != 0u) { alpha = 0.0; }\n"
           "  let line_h = max(1.0, uni.cell_size.y * 0.07);\n"
           "  let ul_y = uni.baseline_y + max(1.0, uni.cell_size.y * 0.10);\n"
           "  // Underline styles (review #19): 0x2 single, 0x4 double,\n"
           "  // 0x4|0x200 curly — DISTINCT forms, not one collapsed bar.\n"
           "  if ((attrs & 0x2u) != 0u && local.y >= ul_y && local.y < ul_y + line_h) { alpha = "
           "1.0; }\n"
           "  if ((attrs & 0x4u) != 0u && (attrs & 0x200u) == 0u) {\n"
           "    // Double: the second stroke sits ABOVE the baseline stroke —\n"
           "    // below would clip at the cell's bottom edge.\n"
           "    let gap = line_h + max(1.0, uni.cell_size.y * 0.05);\n"
           "    if ((local.y >= ul_y && local.y < ul_y + line_h) ||\n"
           "        (local.y >= ul_y - gap && local.y < ul_y - gap + line_h)) { alpha = 1.0; }\n"
           "  }\n"
           "  if ((attrs & 0x200u) != 0u) {\n"
           "    // Curly: the wave rides ABOVE the baseline position so its\n"
           "    // troughs stay inside the cell.\n"
           "    let wave = sin(local.x / uni.cell_size.x * 12.56637) * line_h * 0.9;\n"
           "    let wy = ul_y - line_h + wave;\n"
           "    if (local.y >= wy && local.y < wy + line_h) { alpha = 1.0; }\n"
           "  }\n"
           "  let st_y = uni.cell_size.y * 0.5;\n"
           "  if ((attrs & 0x40u) != 0u && local.y >= st_y && local.y < st_y + line_h) { alpha = "
           "1.0; }\n"
           "  let is_cursor = uni.cursor_visible != 0u && col == uni.cursor_col && row == "
           "uni.cursor_row;\n"
           "  // Faint (SGR 2, review #19): the foreground renders dimmed.\n"
           "  var fgc = fg;\n"
           "  if ((attrs & 0x100u) != 0u) { fgc = fg * 0.55; }\n"
           "  var composed = mix(bg, fgc, alpha);\n"
           "  // Selection: a LINEAR span (terminal semantics) renders inverted.\n"
           "  if (uni.sel_active != 0u) {\n"
           "    let after_start = row > uni.sel_start_row || (row == uni.sel_start_row && col >= "
           "uni.sel_start_col);\n"
           "    let before_end = row < uni.sel_end_row || (row == uni.sel_end_row && col <= "
           "uni.sel_end_col);\n"
           "    if (after_start && before_end) { composed = mix(fgc, bg, alpha); }\n"
           "  }\n"
           "  if (is_cursor) {\n"
           "    if (uni.cursor_shape == 2u) {\n"
           "      // Underline cursor: an fg bar across the bottom of the cell.\n"
           "      let cur_h = max(1.0, uni.cell_size.y * 0.15);\n"
           "      if (local.y >= uni.cell_size.y - cur_h) { composed = fgc; }\n"
           "    } else if (uni.cursor_shape == 3u) {\n"
           "      // Bar cursor: an fg bar down the left edge of the cell.\n"
           "      let cur_w = max(1.0, uni.cell_size.x * 0.15);\n"
           "      if (local.x < cur_w) { composed = fgc; }\n"
           "    } else {\n"
           "      // Block cursor (default): invert the whole cell.\n"
           "      composed = mix(fgc, bg, alpha);\n"
           "    }\n"
           "  }\n"
           "  return vec4<f32>(composed, 1.0);\n"
           "}\n";
}

struct vtermgrid_uniforms {
    float grid_size[2];
    float cell_size[2];
    float pixel_range;
    float scale;
    float baseline_y;
    float glyph_left;
    uint32_t cursor_col;
    uint32_t cursor_row;
    uint32_t cursor_visible;
    uint32_t cursor_shape; /* VTERM_PROP_CURSORSHAPE_* (1 block, 2 underline, 3 bar) */
    uint32_t sel_start_row;
    uint32_t sel_start_col;
    uint32_t sel_end_row;
    uint32_t sel_end_col;
    uint32_t sel_active;
    uint32_t pad0;
    uint32_t pad1;
    uint32_t pad2;
};

static WGPUStringView vtermgrid_sv(const char *text)
{
    return (WGPUStringView){.data = text, .length = text ? strlen(text) : 0};
}

static WGPUTextureFormat vtermgrid_atlas_format_to_wgpu(uint32_t yrender_format)
{
    switch (yrender_format) {
    case YETTY_YRENDER_TEXTURE_FORMAT_R8_UNORM:
        return WGPUTextureFormat_R8Unorm;
    case YETTY_YRENDER_TEXTURE_FORMAT_RGBA8_UNORM:
    default:
        return WGPUTextureFormat_RGBA8Unorm;
    }
}

static uint32_t vtermgrid_atlas_bpp(uint32_t yrender_format)
{
    return yrender_format == YETTY_YRENDER_TEXTURE_FORMAT_R8_UNORM ? 1u : 4u;
}

static void vtermgrid_gpu_teardown(struct yetty_yscene_vtermgrid *grid)
{
    if (grid->blink_timer_running && grid->event_loop) {
        struct yetty_yevent_event_loop *loop = grid->event_loop;
        struct yetty_ycore_void_result deregister_res =
            loop->ops->deregister_timer_listener(loop, grid->blink_timer, &grid->blink_listener);
        if (YETTY_IS_ERR(deregister_res)) {
            yetty_ycore_error_destroy(deregister_res.error);
        }
        struct yetty_ycore_void_result stop_res = loop->ops->stop_timer(loop, grid->blink_timer);
        if (YETTY_IS_ERR(stop_res)) {
            yetty_ycore_error_destroy(stop_res.error);
        }
        struct yetty_ycore_void_result destroy_res =
            loop->ops->destroy_timer(loop, grid->blink_timer);
        if (YETTY_IS_ERR(destroy_res)) {
            yetty_ycore_error_destroy(destroy_res.error);
        }
        grid->blink_timer_running = 0;
    }
    if (grid->bind_group) {
        wgpuBindGroupRelease(grid->bind_group);
        grid->bind_group = NULL;
    }
    grid->bind_group_valid = 0;
    if (grid->atlas_view) {
        wgpuTextureViewRelease(grid->atlas_view);
        grid->atlas_view = NULL;
    }
    if (grid->atlas_texture) {
        wgpuTextureDestroy(grid->atlas_texture);
        wgpuTextureRelease(grid->atlas_texture);
        grid->atlas_texture = NULL;
    }
    if (grid->fallback_atlas_view) {
        wgpuTextureViewRelease(grid->fallback_atlas_view);
        grid->fallback_atlas_view = NULL;
    }
    if (grid->fallback_atlas_texture) {
        wgpuTextureDestroy(grid->fallback_atlas_texture);
        wgpuTextureRelease(grid->fallback_atlas_texture);
        grid->fallback_atlas_texture = NULL;
    }
    if (grid->fallback_meta_buffer) {
        wgpuBufferDestroy(grid->fallback_meta_buffer);
        wgpuBufferRelease(grid->fallback_meta_buffer);
        grid->fallback_meta_buffer = NULL;
    }
    if (grid->meta_buffer) {
        wgpuBufferDestroy(grid->meta_buffer);
        wgpuBufferRelease(grid->meta_buffer);
        grid->meta_buffer = NULL;
    }
    grid->meta_capacity = 0;
    if (grid->cell_buffer) {
        wgpuBufferDestroy(grid->cell_buffer);
        wgpuBufferRelease(grid->cell_buffer);
        grid->cell_buffer = NULL;
    }
    grid->cell_buffer_cells = 0;
    if (grid->uniform_buffer) {
        wgpuBufferDestroy(grid->uniform_buffer);
        wgpuBufferRelease(grid->uniform_buffer);
        grid->uniform_buffer = NULL;
    }
    if (grid->pipeline) {
        wgpuRenderPipelineRelease(grid->pipeline);
        grid->pipeline = NULL;
    }
    if (grid->bind_group_layout) {
        wgpuBindGroupLayoutRelease(grid->bind_group_layout);
        grid->bind_group_layout = NULL;
    }
    if (grid->sampler) {
        wgpuSamplerRelease(grid->sampler);
        grid->sampler = NULL;
    }
    if (grid->shader_module) {
        wgpuShaderModuleRelease(grid->shader_module);
        grid->shader_module = NULL;
    }
    free(grid->pack_scratch);
    free(grid->reply_buffer);
    grid->pack_scratch = NULL;
    grid->pack_scratch_cells = 0;
}

static struct yetty_ycore_void_result vtermgrid_gpu_build_pipeline(
    struct yetty_yscene_vtermgrid *grid)
{
    if (grid->pipeline) {
        return YETTY_OK_VOID();
    }
    WGPUShaderSourceWGSL wgsl = {0};
    wgsl.chain.sType = WGPUSType_ShaderSourceWGSL;
    wgsl.code = vtermgrid_sv(vtermgrid_shader_wgsl());
    WGPUShaderModuleDescriptor shader_desc = {0};
    shader_desc.nextInChain = &wgsl.chain;
    shader_desc.label = vtermgrid_sv("yscene vtermgrid shader");
    grid->shader_module = wgpuDeviceCreateShaderModule(grid->device, &shader_desc);
    if (!grid->shader_module) {
        return YETTY_ERR(yetty_ycore_void, "vtermgrid: shader module");
    }

    WGPUBindGroupLayoutEntry entries[7] = {0};
    entries[0].binding = 0;
    entries[0].visibility = WGPUShaderStage_Fragment;
    entries[0].buffer.type = WGPUBufferBindingType_ReadOnlyStorage;
    entries[1].binding = 1;
    entries[1].visibility = WGPUShaderStage_Fragment;
    entries[1].buffer.type = WGPUBufferBindingType_ReadOnlyStorage;
    entries[2].binding = 2;
    entries[2].visibility = WGPUShaderStage_Fragment;
    entries[2].texture.sampleType = WGPUTextureSampleType_Float;
    entries[2].texture.viewDimension = WGPUTextureViewDimension_2D;
    entries[3].binding = 3;
    entries[3].visibility = WGPUShaderStage_Fragment;
    entries[3].sampler.type = WGPUSamplerBindingType_Filtering;
    entries[4].binding = 4;
    entries[4].visibility = WGPUShaderStage_Vertex | WGPUShaderStage_Fragment;
    entries[4].buffer.type = WGPUBufferBindingType_Uniform;
    entries[4].buffer.minBindingSize = sizeof(struct vtermgrid_uniforms);
    entries[5].binding = 5;
    entries[5].visibility = WGPUShaderStage_Fragment;
    entries[5].buffer.type = WGPUBufferBindingType_ReadOnlyStorage;
    entries[6].binding = 6;
    entries[6].visibility = WGPUShaderStage_Fragment;
    entries[6].texture.sampleType = WGPUTextureSampleType_Float;
    entries[6].texture.viewDimension = WGPUTextureViewDimension_2D;
    WGPUBindGroupLayoutDescriptor bgl_desc = {0};
    bgl_desc.entryCount = 7;
    bgl_desc.entries = entries;
    grid->bind_group_layout = wgpuDeviceCreateBindGroupLayout(grid->device, &bgl_desc);
    if (!grid->bind_group_layout) {
        return YETTY_ERR(yetty_ycore_void, "vtermgrid: bind group layout");
    }

    WGPUPipelineLayoutDescriptor pl_desc = {0};
    pl_desc.bindGroupLayoutCount = 1;
    pl_desc.bindGroupLayouts = &grid->bind_group_layout;
    WGPUPipelineLayout layout = wgpuDeviceCreatePipelineLayout(grid->device, &pl_desc);
    if (!layout) {
        return YETTY_ERR(yetty_ycore_void, "vtermgrid: pipeline layout");
    }

    WGPUColorTargetState color_target = {0};
    color_target.format = grid->target_format;
    color_target.writeMask = WGPUColorWriteMask_All;
    WGPUFragmentState fragment = {0};
    fragment.module = grid->shader_module;
    fragment.entryPoint = vtermgrid_sv("fs_main");
    fragment.targetCount = 1;
    fragment.targets = &color_target;
    WGPURenderPipelineDescriptor rp_desc = {0};
    rp_desc.label = vtermgrid_sv("yscene vtermgrid pipeline");
    rp_desc.layout = layout;
    rp_desc.vertex.module = grid->shader_module;
    rp_desc.vertex.entryPoint = vtermgrid_sv("vs_main");
    rp_desc.fragment = &fragment;
    rp_desc.primitive.topology = WGPUPrimitiveTopology_TriangleList;
    rp_desc.primitive.frontFace = WGPUFrontFace_CCW;
    rp_desc.primitive.cullMode = WGPUCullMode_None;
    rp_desc.multisample.count = 1;
    rp_desc.multisample.mask = ~0u;
    grid->pipeline = wgpuDeviceCreateRenderPipeline(grid->device, &rp_desc);
    wgpuPipelineLayoutRelease(layout);
    if (!grid->pipeline) {
        return YETTY_ERR(yetty_ycore_void, "vtermgrid: render pipeline");
    }

    WGPUSamplerDescriptor sampler_desc = {0};
    sampler_desc.minFilter = WGPUFilterMode_Linear;
    sampler_desc.magFilter = WGPUFilterMode_Linear;
    sampler_desc.addressModeU = WGPUAddressMode_ClampToEdge;
    sampler_desc.addressModeV = WGPUAddressMode_ClampToEdge;
    sampler_desc.maxAnisotropy = 1;
    grid->sampler = wgpuDeviceCreateSampler(grid->device, &sampler_desc);
    if (!grid->sampler) {
        return YETTY_ERR(yetty_ycore_void, "vtermgrid: sampler");
    }

    WGPUBufferDescriptor uni_desc = {0};
    uni_desc.label = vtermgrid_sv("yscene vtermgrid uniforms");
    uni_desc.usage = WGPUBufferUsage_Uniform | WGPUBufferUsage_CopyDst;
    uni_desc.size = sizeof(struct vtermgrid_uniforms);
    grid->uniform_buffer = wgpuDeviceCreateBuffer(grid->device, &uni_desc);
    if (!grid->uniform_buffer) {
        return YETTY_ERR(yetty_ycore_void, "vtermgrid: uniform buffer");
    }
    return YETTY_OK_VOID();
}

/* Upload the font atlas + glyph metrics, refreshing on generation change, and
 * cache the MSDF geometry uniforms + cell size. */
static struct yetty_ycore_void_result vtermgrid_gpu_upload_font(struct yetty_yscene_vtermgrid *grid)
{
    if (!grid->font) {
        return YETTY_ERR(yetty_ycore_void, "vtermgrid: no font");
    }
    struct pixel_size_result cell_res = grid->font->ops->get_cell_size(grid->font);
    if (YETTY_IS_OK(cell_res)) {
        grid->cell_size = cell_res.value;
    }
    struct yetty_yrender_gpu_resource_set_result rs_res =
        grid->font->ops->get_gpu_resource_set(grid->font);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, rs_res, "vtermgrid: font resource set");
    const struct yetty_yrender_gpu_resource_set *rs = rs_res.value;

    grid->uni_pixel_range = rs->uniforms[0].f32;
    grid->uni_scale = rs->uniforms[1].f32;
    grid->uni_baseline_y = rs->uniforms[2].f32;
    grid->uni_glyph_left = rs->uniforms[3].f32;

    const struct yetty_yrender_texture *atlas = &rs->textures[0];
    if (atlas->data && atlas->width > 0 && atlas->height > 0) {
        uint32_t format =
            atlas->format ? atlas->format : (uint32_t)YETTY_YRENDER_TEXTURE_FORMAT_RGBA8_UNORM;
        if (!grid->atlas_texture || atlas->width != grid->atlas_width ||
            atlas->height != grid->atlas_height || format != grid->atlas_format) {
            if (grid->atlas_view) {
                wgpuTextureViewRelease(grid->atlas_view);
                grid->atlas_view = NULL;
            }
            if (grid->atlas_texture) {
                wgpuTextureDestroy(grid->atlas_texture);
                wgpuTextureRelease(grid->atlas_texture);
                grid->atlas_texture = NULL;
            }
            WGPUTextureDescriptor tex_desc = {0};
            tex_desc.label = vtermgrid_sv("yscene vtermgrid atlas");
            tex_desc.usage = WGPUTextureUsage_TextureBinding | WGPUTextureUsage_CopyDst;
            tex_desc.dimension = WGPUTextureDimension_2D;
            tex_desc.size.width = atlas->width;
            tex_desc.size.height = atlas->height;
            tex_desc.size.depthOrArrayLayers = 1;
            tex_desc.format = vtermgrid_atlas_format_to_wgpu(format);
            tex_desc.mipLevelCount = 1;
            tex_desc.sampleCount = 1;
            grid->atlas_texture = wgpuDeviceCreateTexture(grid->device, &tex_desc);
            if (!grid->atlas_texture) {
                return YETTY_ERR(yetty_ycore_void, "vtermgrid: atlas texture");
            }
            grid->atlas_view = wgpuTextureCreateView(grid->atlas_texture, NULL);
            if (!grid->atlas_view) {
                return YETTY_ERR(yetty_ycore_void, "vtermgrid: atlas view");
            }
            grid->atlas_width = atlas->width;
            grid->atlas_height = atlas->height;
            grid->atlas_format = format;
            grid->atlas_bytes_per_pixel = vtermgrid_atlas_bpp(format);
            grid->bind_group_valid = 0;
        }
        WGPUTexelCopyTextureInfo dest = {0};
        dest.texture = grid->atlas_texture;
        dest.mipLevel = 0;
        WGPUTexelCopyBufferLayout src_layout = {0};
        src_layout.bytesPerRow = atlas->width * grid->atlas_bytes_per_pixel;
        src_layout.rowsPerImage = atlas->height;
        WGPUExtent3D extent = {atlas->width, atlas->height, 1};
        size_t bytes = (size_t)atlas->width * atlas->height * grid->atlas_bytes_per_pixel;
        wgpuQueueWriteTexture(grid->queue, &dest, atlas->data, bytes, &src_layout, &extent);
    }

    const struct yetty_yrender_buffer *meta = &rs->buffers[0];
    if (meta->data && meta->size > 0) {
        if (!grid->meta_buffer || meta->size > grid->meta_capacity) {
            if (grid->meta_buffer) {
                wgpuBufferDestroy(grid->meta_buffer);
                wgpuBufferRelease(grid->meta_buffer);
                grid->meta_buffer = NULL;
            }
            WGPUBufferDescriptor desc = {0};
            desc.label = vtermgrid_sv("yscene vtermgrid meta");
            desc.usage = WGPUBufferUsage_Storage | WGPUBufferUsage_CopyDst;
            desc.size = meta->size;
            grid->meta_buffer = wgpuDeviceCreateBuffer(grid->device, &desc);
            if (!grid->meta_buffer) {
                return YETTY_ERR(yetty_ycore_void, "vtermgrid: meta buffer");
            }
            grid->meta_capacity = meta->size;
            grid->bind_group_valid = 0;
        }
        wgpuQueueWriteBuffer(grid->queue, grid->meta_buffer, 0, meta->data, meta->size);
    }

    /* Mirror for the optional fallback face (cell-slot raster atlas). */
    if (grid->fallback_font) {
        struct yetty_yrender_gpu_resource_set_result fallback_rs_res =
            grid->fallback_font->ops->get_gpu_resource_set(grid->fallback_font);
        YETTY_RETURN_IF_ERR(yetty_ycore_void, fallback_rs_res,
                            "vtermgrid: fallback font resource set");
        const struct yetty_yrender_gpu_resource_set *fallback_rs = fallback_rs_res.value;
        const struct yetty_yrender_texture *fb_atlas = &fallback_rs->textures[0];
        if (fb_atlas->data && fb_atlas->width > 0 && fb_atlas->height > 0) {
            uint32_t fb_format = fb_atlas->format ? fb_atlas->format
                                                  : (uint32_t)YETTY_YRENDER_TEXTURE_FORMAT_R8_UNORM;
            if (!grid->fallback_atlas_texture || fb_atlas->width != grid->fallback_atlas_width ||
                fb_atlas->height != grid->fallback_atlas_height ||
                fb_format != grid->fallback_atlas_format) {
                if (grid->fallback_atlas_view) {
                    wgpuTextureViewRelease(grid->fallback_atlas_view);
                    grid->fallback_atlas_view = NULL;
                }
                if (grid->fallback_atlas_texture) {
                    wgpuTextureDestroy(grid->fallback_atlas_texture);
                    wgpuTextureRelease(grid->fallback_atlas_texture);
                    grid->fallback_atlas_texture = NULL;
                }
                WGPUTextureDescriptor fb_desc = {0};
                fb_desc.label = vtermgrid_sv("yscene vtermgrid fallback atlas");
                fb_desc.usage = WGPUTextureUsage_TextureBinding | WGPUTextureUsage_CopyDst;
                fb_desc.dimension = WGPUTextureDimension_2D;
                fb_desc.size.width = fb_atlas->width;
                fb_desc.size.height = fb_atlas->height;
                fb_desc.size.depthOrArrayLayers = 1;
                fb_desc.format = vtermgrid_atlas_format_to_wgpu(fb_format);
                fb_desc.mipLevelCount = 1;
                fb_desc.sampleCount = 1;
                grid->fallback_atlas_texture = wgpuDeviceCreateTexture(grid->device, &fb_desc);
                if (!grid->fallback_atlas_texture) {
                    return YETTY_ERR(yetty_ycore_void, "vtermgrid: fallback atlas texture");
                }
                grid->fallback_atlas_view =
                    wgpuTextureCreateView(grid->fallback_atlas_texture, NULL);
                if (!grid->fallback_atlas_view) {
                    return YETTY_ERR(yetty_ycore_void, "vtermgrid: fallback atlas view");
                }
                grid->fallback_atlas_width = fb_atlas->width;
                grid->fallback_atlas_height = fb_atlas->height;
                grid->fallback_atlas_format = fb_format;
                grid->fallback_atlas_bytes_per_pixel = vtermgrid_atlas_bpp(fb_format);
                grid->bind_group_valid = 0;
            }
            WGPUTexelCopyTextureInfo fb_dest = {0};
            fb_dest.texture = grid->fallback_atlas_texture;
            fb_dest.mipLevel = 0;
            WGPUTexelCopyBufferLayout fb_layout = {0};
            fb_layout.bytesPerRow = fb_atlas->width * grid->fallback_atlas_bytes_per_pixel;
            fb_layout.rowsPerImage = fb_atlas->height;
            WGPUExtent3D fb_extent = {fb_atlas->width, fb_atlas->height, 1};
            size_t fb_bytes =
                (size_t)fb_atlas->width * fb_atlas->height * grid->fallback_atlas_bytes_per_pixel;
            wgpuQueueWriteTexture(grid->queue, &fb_dest, fb_atlas->data, fb_bytes, &fb_layout,
                                  &fb_extent);
        }
        const struct yetty_yrender_buffer *fb_meta = &fallback_rs->buffers[0];
        if (fb_meta->data && fb_meta->size > 0) {
            if (!grid->fallback_meta_buffer || fb_meta->size > grid->fallback_meta_capacity) {
                if (grid->fallback_meta_buffer) {
                    wgpuBufferDestroy(grid->fallback_meta_buffer);
                    wgpuBufferRelease(grid->fallback_meta_buffer);
                    grid->fallback_meta_buffer = NULL;
                }
                WGPUBufferDescriptor fb_buf_desc = {0};
                fb_buf_desc.label = vtermgrid_sv("yscene vtermgrid fallback meta");
                fb_buf_desc.usage = WGPUBufferUsage_Storage | WGPUBufferUsage_CopyDst;
                fb_buf_desc.size = fb_meta->size;
                grid->fallback_meta_buffer = wgpuDeviceCreateBuffer(grid->device, &fb_buf_desc);
                if (!grid->fallback_meta_buffer) {
                    return YETTY_ERR(yetty_ycore_void, "vtermgrid: fallback meta buffer");
                }
                grid->fallback_meta_capacity = fb_meta->size;
                grid->bind_group_valid = 0;
            }
            wgpuQueueWriteBuffer(grid->queue, grid->fallback_meta_buffer, 0, fb_meta->data,
                                 fb_meta->size);
        }
    }
    return YETTY_OK_VOID();
}

static struct yetty_ycore_void_result vtermgrid_gpu_ensure_cell_buffer(
    struct yetty_yscene_vtermgrid *grid, size_t cells_needed)
{
    if (grid->cell_buffer && grid->cell_buffer_cells >= cells_needed) {
        return YETTY_OK_VOID();
    }
    if (grid->cell_buffer) {
        wgpuBufferDestroy(grid->cell_buffer);
        wgpuBufferRelease(grid->cell_buffer);
        grid->cell_buffer = NULL;
    }
    uint64_t size =
        (uint64_t)cells_needed * YETTY_YSCENE_VTERMGRID_WORDS_PER_CELL * sizeof(uint32_t);
    WGPUBufferDescriptor desc = {0};
    desc.label = vtermgrid_sv("yscene vtermgrid cells");
    desc.usage = WGPUBufferUsage_Storage | WGPUBufferUsage_CopyDst;
    desc.size = size;
    grid->cell_buffer = wgpuDeviceCreateBuffer(grid->device, &desc);
    if (!grid->cell_buffer) {
        return YETTY_ERR(yetty_ycore_void, "vtermgrid: cell buffer");
    }
    grid->cell_buffer_cells = cells_needed;
    grid->bind_group_valid = 0;
    return YETTY_OK_VOID();
}

/* Pack the whole visible grid into `pack_scratch` and upload it. */
/* Blink tick: flip the phase and schedule a re-pack. No-ops (timer left
 * running at its slow cadence) while the screen has no blink cells. */
static struct yetty_ycore_int_result vtermgrid_blink_on_tick(
    struct yetty_yevent_event_listener *listener, const struct yetty_yui_event *event)
{
    (void)event;
    struct yetty_yscene_vtermgrid *grid =
        container_of(listener, struct yetty_yscene_vtermgrid, blink_listener);
    int cursor_blinks = grid->cursor_blink && grid->cursor_visible;
    if (!grid->has_blink_cells && !cursor_blinks) {
        return YETTY_OK(yetty_ycore_int, 0);
    }
    grid->blink_phase = !grid->blink_phase;
    grid->generation++;
    if (grid->render_kick) {
        grid->render_kick(grid->render_kick_userdata);
    } else if (grid->event_loop) {
        grid->event_loop->ops->request_render(grid->event_loop);
    }
    return YETTY_OK(yetty_ycore_int, 0);
}

/* Bell hook + counter (hand-written seams): the embedder wires presentation
 * (audible/visual bell) or polls the counter. */
void yetty_yscene_vtermgrid_set_bell_hook(struct yetty_yclass_object *obj,
                                          void (*hook)(void *userdata), void *userdata)
{
    struct yetty_yscene_vtermgrid_ptr_result grid_res = yetty_yscene_vtermgrid_from(obj);
    if (YETTY_IS_ERR(grid_res)) {
        yetty_ycore_error_destroy(grid_res.error);
        return;
    }
    grid_res.value->bell_hook = hook;
    grid_res.value->bell_hook_userdata = userdata;
}

struct yetty_ycore_uint64_result yetty_yscene_vtermgrid_bell_count(struct yetty_yclass_object *obj)
{
    struct yetty_yscene_vtermgrid_ptr_result grid_res = yetty_yscene_vtermgrid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_uint64, grid_res, "vtermgrid_bell_count: from_obj");
    return YETTY_OK(yetty_ycore_uint64, grid_res.value->bell_count);
}

/* Reply bytes the projection swallowed (observability for the by-design drop —
 * the authoritative engine answers at the pane). */
struct yetty_ycore_uint64_result yetty_yscene_vtermgrid_replies_discarded(
    struct yetty_yclass_object *obj)
{
    struct yetty_yscene_vtermgrid_ptr_result grid_res = yetty_yscene_vtermgrid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_uint64, grid_res, "vtermgrid_replies_discarded: from_obj");
    return YETTY_OK(yetty_ycore_uint64, grid_res.value->reply_discarded_bytes);
}

/* Install the owning scene's render kick (figure-dirty + render request) for
 * animation ticks. Plain hand-written setter. */
void yetty_yscene_vtermgrid_set_render_kick(struct yetty_yclass_object *obj,
                                            void (*kick)(void *userdata), void *userdata)
{
    struct yetty_yscene_vtermgrid_ptr_result grid_res = yetty_yscene_vtermgrid_from(obj);
    if (YETTY_IS_ERR(grid_res)) {
        yetty_ycore_error_destroy(grid_res.error);
        return;
    }
    grid_res.value->render_kick = kick;
    grid_res.value->render_kick_userdata = userdata;
}

/* Lazily bring the blink timer up (first pack that sees a blink cell). A
 * failure leaves blink frozen visible — cosmetic, so absorbed with a debug
 * note rather than failing the pack. */
static void vtermgrid_blink_ensure_timer(struct yetty_yscene_vtermgrid *grid)
{
    if (grid->blink_timer_running || !grid->event_loop) {
        return;
    }
    struct yetty_yevent_event_loop *loop = grid->event_loop;
    struct yetty_yevent_timer_id_result timer_res = loop->ops->create_timer(loop);
    if (YETTY_IS_ERR(timer_res)) {
        yetty_ycore_error_destroy(timer_res.error);
        return;
    }
    grid->blink_timer = timer_res.value;
    grid->blink_listener.handler = vtermgrid_blink_on_tick;
    struct yetty_ycore_void_result config_res =
        loop->ops->config_timer(loop, grid->blink_timer, 530 /* ms, tmux-ish cadence */);
    struct yetty_ycore_void_result register_res =
        YETTY_IS_OK(config_res)
            ? loop->ops->register_timer_listener(loop, grid->blink_timer, &grid->blink_listener)
            : config_res;
    struct yetty_ycore_void_result start_res =
        YETTY_IS_OK(register_res) ? loop->ops->start_timer(loop, grid->blink_timer) : register_res;
    if (YETTY_IS_ERR(start_res)) {
        ydebug("vtermgrid: blink timer setup failed: %s",
               start_res.error.msg ? start_res.error.msg : "unknown");
        yetty_ycore_error_destroy(start_res.error);
        struct yetty_ycore_void_result destroy_res =
            loop->ops->destroy_timer(loop, grid->blink_timer);
        if (YETTY_IS_ERR(destroy_res)) {
            yetty_ycore_error_destroy(destroy_res.error);
        }
        return;
    }
    grid->blink_timer_running = 1;
}

static struct yetty_ycore_void_result vtermgrid_gpu_pack_and_upload(
    struct yetty_yscene_vtermgrid *grid)
{
    size_t cells = (size_t)grid->rows * grid->cols;
    if (cells == 0) {
        return YETTY_OK_VOID();
    }
    size_t words = cells * YETTY_YSCENE_VTERMGRID_WORDS_PER_CELL;
    if (grid->pack_scratch_cells < cells) {
        uint32_t *grown = realloc(grid->pack_scratch, words * sizeof(uint32_t));
        if (!grown) {
            return YETTY_ERR(yetty_ycore_void, "vtermgrid: pack scratch alloc");
        }
        grid->pack_scratch = grown;
        grid->pack_scratch_cells = cells;
    }

    int saw_blink_cell = 0;
    for (uint32_t row = 0; row < grid->rows; ++row) {
        for (uint32_t col = 0; col < grid->cols; ++col) {
            struct yetty_yscene_vtermgrid_cell cell;
            vtermgrid_read_cell(grid, row, col, &cell);

            int cell_blinks = (cell.attrs & YETTY_YSCENE_VTERMGRID_ATTR_BLINK) != 0;
            if (cell_blinks) {
                saw_blink_cell = 1;
            }
            uint32_t slot = 0;
            uint32_t cell_face = 0;
            /* Hidden blink phase: keep the cell's bg but pack a blank glyph. */
            if (cell.width != 0 && cell.glyph != 0 &&
                (cell.attrs & YETTY_YSCENE_VTERMGRID_ATTR_CONCEAL) == 0 &&
                !(cell_blinks && grid->blink_phase)) {
                struct uint32_result idx = grid->font->ops->get_glyph_index(grid->font, cell.glyph);
                if (YETTY_IS_OK(idx)) {
                    slot = idx.value;
                } else {
                    yetty_ycore_error_destroy(idx.error);
                    slot = 0xFFFFFFFFu; /* notdef / tofu */
                    /* FALLBACK face (#89): the raster chain covers what the
                     * MSDF base misses (CJK etc.); its cluster lookup bakes
                     * the combining marks into ONE slot. */
                    if (grid->fallback_font) {
                        struct yetty_yfont_ms_font *fallback = grid->fallback_font;
                        struct uint32_result fb_idx;
                        const struct yetty_yscene_vtermgrid_store_cell *fb_stored = NULL;
                        if (row < vtermgrid_active_store(grid)->rows &&
                            col < vtermgrid_active_store(grid)->cols) {
                            fb_stored =
                                &vtermgrid_active_store(grid)
                                     ->cells[(size_t)row * vtermgrid_active_store(grid)->cols +
                                             col];
                        }
                        if (fb_stored && fb_stored->mark_count > 0 &&
                            fallback->ops->get_glyph_index_cluster) {
                            fb_idx = fallback->ops->get_glyph_index_cluster(
                                fallback, cell.glyph, fb_stored->marks, fb_stored->mark_count,
                                YETTY_YFONT_MS_STYLE_REGULAR);
                        } else {
                            fb_idx = fallback->ops->get_glyph_index(fallback, cell.glyph);
                        }
                        if (YETTY_IS_OK(fb_idx)) {
                            slot = fb_idx.value;
                            cell_face = 1;
                        } else {
                            yetty_ycore_error_destroy(fb_idx.error);
                        }
                    }
                }
            }

            uint32_t fr = cell.fg & 0xFFu, fg = (cell.fg >> 8) & 0xFFu,
                     fb = (cell.fg >> 16) & 0xFFu;
            uint32_t br = cell.bg & 0xFFu, bgc = (cell.bg >> 8) & 0xFFu,
                     bb = (cell.bg >> 16) & 0xFFu;
            size_t base = ((size_t)row * grid->cols + col) * YETTY_YSCENE_VTERMGRID_WORDS_PER_CELL;
            grid->pack_scratch[base + 0] = slot;
            grid->pack_scratch[base + 1] = fr | (fg << 8) | (fb << 16) | (br << 24);
            grid->pack_scratch[base + 2] = bgc | (bb << 8) | ((uint32_t)cell.attrs << 16);
            grid->pack_scratch[base + 3] = (uint32_t)cell.width | (cell_face << 8);
            /* Stage C (#699.5): the RETAINED combining marks, resolved to
             * atlas slots, composite over the base glyph in the shader. Read
             * straight from the store (module-internal) — the exposed cell
             * API stays base-only until its codegen extension. */
            for (uint32_t clear_word = 4; clear_word < YETTY_YSCENE_VTERMGRID_WORDS_PER_CELL;
                 ++clear_word) {
                grid->pack_scratch[base + clear_word] = 0;
            }
            if (cell_face == 0 && row < vtermgrid_active_store(grid)->rows &&
                col < vtermgrid_active_store(grid)->cols) {
                const struct yetty_yscene_vtermgrid_store_cell *stored =
                    &vtermgrid_active_store(grid)
                         ->cells[(size_t)row * vtermgrid_active_store(grid)->cols + col];
                uint32_t packed_marks = 0;
                for (uint8_t mark = 0; mark < stored->mark_count && packed_marks < 5; ++mark) {
                    struct uint32_result mark_idx =
                        grid->font->ops->get_glyph_index(grid->font, stored->marks[mark]);
                    if (YETTY_IS_OK(mark_idx)) {
                        grid->pack_scratch[base + 4 + packed_marks] = mark_idx.value;
                        ++packed_marks;
                    } else {
                        yetty_ycore_error_destroy(mark_idx.error);
                    }
                }
            }
        }
    }

    grid->has_blink_cells = saw_blink_cell;
    if (saw_blink_cell || (grid->cursor_blink && grid->cursor_visible)) {
        vtermgrid_blink_ensure_timer(grid);
    }

    wgpuQueueWriteBuffer(grid->queue, grid->cell_buffer, 0, grid->pack_scratch,
                         words * sizeof(uint32_t));
    return YETTY_OK_VOID();
}

static struct yetty_ycore_void_result vtermgrid_gpu_ensure_bind_group(
    struct yetty_yscene_vtermgrid *grid)
{
    if (grid->bind_group_valid && grid->bind_group) {
        return YETTY_OK_VOID();
    }
    if (grid->bind_group) {
        wgpuBindGroupRelease(grid->bind_group);
        grid->bind_group = NULL;
    }
    if (!grid->cell_buffer || !grid->meta_buffer || !grid->atlas_view || !grid->sampler ||
        !grid->uniform_buffer) {
        return YETTY_ERR(yetty_ycore_void, "vtermgrid: bind group missing resource");
    }
    WGPUBindGroupEntry entries[7] = {0};
    entries[0].binding = 0;
    entries[0].buffer = grid->cell_buffer;
    entries[0].size = WGPU_WHOLE_SIZE;
    entries[1].binding = 1;
    entries[1].buffer = grid->meta_buffer;
    entries[1].size = WGPU_WHOLE_SIZE;
    entries[2].binding = 2;
    entries[2].textureView = grid->atlas_view;
    entries[3].binding = 3;
    entries[3].sampler = grid->sampler;
    entries[4].binding = 4;
    entries[4].buffer = grid->uniform_buffer;
    entries[4].size = sizeof(struct vtermgrid_uniforms);
    /* Fallback face bindings — the primary resources stand in when no
     * fallback font is attached (never sampled: face is always 0 then). */
    entries[5].binding = 5;
    entries[5].buffer = grid->fallback_meta_buffer ? grid->fallback_meta_buffer : grid->meta_buffer;
    entries[5].size = WGPU_WHOLE_SIZE;
    entries[6].binding = 6;
    entries[6].textureView =
        grid->fallback_atlas_view ? grid->fallback_atlas_view : grid->atlas_view;
    WGPUBindGroupDescriptor bg_desc = {0};
    bg_desc.layout = grid->bind_group_layout;
    bg_desc.entryCount = 7;
    bg_desc.entries = entries;
    grid->bind_group = wgpuDeviceCreateBindGroup(grid->device, &bg_desc);
    if (!grid->bind_group) {
        return YETTY_ERR(yetty_ycore_void, "vtermgrid: bind group create");
    }
    grid->bind_group_valid = 1;
    return YETTY_OK_VOID();
}

/* Bind the GPU context (from the framework runtime) + the MSDF font this grid
 * renders with, and build the pipeline. Local (expose): WebGPU handles come
 * from `runtime->gpu`, so no raw WebGPU type ever crosses the generated API. */
YETTY_ANNOTATE("expose")
struct yetty_ycore_void_result yetty_yscene_vtermgrid_gpu_setup(struct yetty_yclass_object *obj,
                                                                struct yetty_yframework *runtime,
                                                                struct yetty_yfont_ms_font *font)
{
    struct yetty_yscene_vtermgrid_ptr_result grid_res = yetty_yscene_vtermgrid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, grid_res, "vtermgrid_gpu_setup: from_obj");
    struct yetty_yscene_vtermgrid *grid = grid_res.value;
    if (!runtime || !runtime->gpu.device || !runtime->gpu.queue) {
        return YETTY_ERR(yetty_ycore_void, "vtermgrid_gpu_setup: no gpu runtime");
    }
    grid->device = runtime->gpu.device;
    grid->event_loop = runtime->event_loop;
    grid->queue = runtime->gpu.queue;
    grid->target_format = runtime->gpu.surface_format;
    grid->font = font;
    return vtermgrid_gpu_build_pipeline(grid);
}

/* Attach the optional FALLBACK face (#89): a raster ms-font whose FreeType
 * fallback chain covers codepoints the MSDF base face lacks (CJK etc.).
 * Borrowed — the scene owns both fonts. Local (expose). */
YETTY_ANNOTATE("expose")
struct yetty_ycore_void_result yetty_yscene_vtermgrid_gpu_set_fallback_font(
    struct yetty_yclass_object *obj, struct yetty_yfont_ms_font *fallback_font)
{
    struct yetty_yscene_vtermgrid_ptr_result grid_res = yetty_yscene_vtermgrid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, grid_res, "vtermgrid_gpu_set_fallback_font: from_obj");
    struct yetty_yscene_vtermgrid *grid = grid_res.value;
    grid->fallback_font = fallback_font;
    grid->bind_group_valid = 0;
    return YETTY_OK_VOID();
}

/* Test observability (review #14): the alternate-screen flag, so full-state
 * fragmentation comparisons include mode state. Local (expose). */
/* Packed mode/prop flags for state-equality tests (review #14): bit0 =
 * cursor blink, bit1 = reverse video (DECSCNM); bits 8..15 = cursor shape
 * (VTERM_PROP_CURSORSHAPE_*). Rendering state only — parser/pen internals
 * are pinned behaviorally by fragmentation + continuation vectors. */
YETTY_ANNOTATE("expose")
struct yetty_ycore_uint32_result yetty_yscene_vtermgrid_mode_flags(struct yetty_yclass_object *obj)
{
    struct yetty_yscene_vtermgrid_ptr_result grid_res = yetty_yscene_vtermgrid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_uint32, grid_res, "vtermgrid_mode_flags: from_obj");
    struct yetty_yscene_vtermgrid *grid = grid_res.value;
    uint32_t flags = 0;
    if (grid->cursor_blink) {
        flags |= 1u;
    }
    if (grid->reverse_video) {
        flags |= 2u;
    }
    flags |= ((uint32_t)grid->cursor_shape & 0xFFu) << 8;
    return YETTY_OK(yetty_ycore_uint32, flags);
}

/* Pending (untaken) terminal-reply byte count — peek, does not drain. */
YETTY_ANNOTATE("expose")
struct yetty_ycore_uint32_result yetty_yscene_vtermgrid_reply_pending(
    struct yetty_yclass_object *obj)
{
    struct yetty_yscene_vtermgrid_ptr_result grid_res = yetty_yscene_vtermgrid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_uint32, grid_res, "vtermgrid_reply_pending: from_obj");
    return YETTY_OK(yetty_ycore_uint32, (uint32_t)grid_res.value->reply_buffer_len);
}

/* Scalar-word access into the pending reply bytes (review #15): 8 bytes at
 * word_index*8, packed LE into a u64 — RPC-marshallable, unlike a buffer
 * return. Consume drops the drained prefix. */
YETTY_ANNOTATE("expose")
struct yetty_ycore_uint64_result yetty_yscene_vtermgrid_reply_word(struct yetty_yclass_object *obj,
                                                                   uint32_t word_index)
{
    struct yetty_yscene_vtermgrid_ptr_result grid_res = yetty_yscene_vtermgrid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_uint64, grid_res, "vtermgrid_reply_word: from_obj");
    struct yetty_yscene_vtermgrid *grid = grid_res.value;
    uint64_t packed = 0;
    for (uint32_t byte_index = 0; byte_index < 8; ++byte_index) {
        size_t offset = (size_t)word_index * 8 + byte_index;
        if (offset >= grid->reply_buffer_len) {
            break;
        }
        packed |= (uint64_t)grid->reply_buffer[offset] << (byte_index * 8);
    }
    return YETTY_OK(yetty_ycore_uint64, packed);
}

YETTY_ANNOTATE("expose")
struct yetty_ycore_void_result yetty_yscene_vtermgrid_reply_consume(struct yetty_yclass_object *obj,
                                                                    uint32_t byte_count)
{
    struct yetty_yscene_vtermgrid_ptr_result grid_res = yetty_yscene_vtermgrid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, grid_res, "vtermgrid_reply_consume: from_obj");
    struct yetty_yscene_vtermgrid *grid = grid_res.value;
    size_t drop = byte_count < grid->reply_buffer_len ? byte_count : grid->reply_buffer_len;
    memmove(grid->reply_buffer, grid->reply_buffer + drop, grid->reply_buffer_len - drop);
    grid->reply_buffer_len -= drop;
    return YETTY_OK_VOID();
}

/* Take (and clear) the accumulated terminal reply bytes — the scalar-word
 * drain (reply_word/reply_consume) is the production route; this whole-copy
 * form serves local embedders and tests. */
YETTY_ANNOTATE("expose")
struct yetty_ycore_uint32_result yetty_yscene_vtermgrid_take_replies(
    struct yetty_yclass_object *obj, uint8_t *out, uint32_t out_capacity)
{
    struct yetty_yscene_vtermgrid_ptr_result grid_res = yetty_yscene_vtermgrid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_uint32, grid_res, "vtermgrid_take_replies: from_obj");
    struct yetty_yscene_vtermgrid *grid = grid_res.value;
    uint32_t take =
        grid->reply_buffer_len < out_capacity ? (uint32_t)grid->reply_buffer_len : out_capacity;
    if (take > 0 && out) {
        memcpy(out, grid->reply_buffer, take);
    }
    memmove(grid->reply_buffer, grid->reply_buffer + take, grid->reply_buffer_len - take);
    grid->reply_buffer_len -= take;
    return YETTY_OK(yetty_ycore_uint32, take);
}

YETTY_ANNOTATE("expose")
struct yetty_ycore_int_result yetty_yscene_vtermgrid_on_alt_screen(struct yetty_yclass_object *obj)
{
    struct yetty_yscene_vtermgrid_ptr_result grid_res = yetty_yscene_vtermgrid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_int, grid_res, "vtermgrid_on_alt_screen: from_obj");
    return YETTY_OK(yetty_ycore_int, grid_res.value->on_alt_screen);
}

/* Selection span (review #11): a linear [start..end] cell range rendered
 * INVERTED (fg/bg swap, like tmux/xterm selections). active == 0 clears.
 * Local (expose): copy-mode chrome drives this from the bridge. */
YETTY_ANNOTATE("expose")
struct yetty_ycore_void_result yetty_yscene_vtermgrid_set_selection(struct yetty_yclass_object *obj,
                                                                    uint32_t start_row,
                                                                    uint32_t start_col,
                                                                    uint32_t end_row,
                                                                    uint32_t end_col, int active)
{
    struct yetty_yscene_vtermgrid_ptr_result grid_res = yetty_yscene_vtermgrid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, grid_res, "vtermgrid_set_selection: from_obj");
    struct yetty_yscene_vtermgrid *grid = grid_res.value;
    grid->sel_start_row = start_row;
    grid->sel_start_col = start_col;
    grid->sel_end_row = end_row;
    grid->sel_end_col = end_col;
    grid->sel_active = active ? 1 : 0;
    grid->generation++;
    if (grid->render_kick) {
        grid->render_kick(grid->render_kick_userdata);
    }
    return YETTY_OK_VOID();
}

/* Draw the current cell grid into `target`, positioned/clipped to `rect`
 * (logical pixels, pane-local). No-op when GPU state or font is absent
 * (headless). Composites with LoadOp_Load over whatever is already in the
 * target. Local (expose): the scene calls this from its render pass. */
YETTY_ANNOTATE("expose")
struct yetty_ycore_void_result yetty_yscene_vtermgrid_render(struct yetty_yclass_object *obj,
                                                             struct yetty_ydraw_target *target,
                                                             struct yetty_ycore_rectangle rect)
{
    struct yetty_yscene_vtermgrid_ptr_result grid_res = yetty_yscene_vtermgrid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, grid_res, "vtermgrid_render: from_obj");
    struct yetty_yscene_vtermgrid *grid = grid_res.value;
    if (!grid->device || !grid->font || !target || grid->rows == 0 || grid->cols == 0) {
        return YETTY_OK_VOID(); /* headless / not yet attached */
    }

    struct yetty_ycore_void_result pipe = vtermgrid_gpu_build_pipeline(grid);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, pipe, "vtermgrid_gpu_render: pipeline");
    struct yetty_ycore_void_result buf_res =
        vtermgrid_gpu_ensure_cell_buffer(grid, (size_t)grid->rows * grid->cols);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, buf_res, "vtermgrid_gpu_render: cell buffer");
    /* Pack BEFORE uploading the font atlas: pack calls get_glyph_index, which
     * allocates any not-yet-seen glyph into the font's atlas image. If the atlas
     * were uploaded first (as it was), that glyph's slot would reference an
     * un-uploaded region on its FIRST frame and sample as tofu until the next
     * render. Packing first, then uploading the (now-grown) atlas, makes a new
     * glyph correct on the very frame it appears. */
    struct yetty_ycore_void_result pack_res = vtermgrid_gpu_pack_and_upload(grid);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, pack_res, "vtermgrid_gpu_render: pack");
    struct yetty_ycore_void_result font_res = vtermgrid_gpu_upload_font(grid);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, font_res, "vtermgrid_gpu_render: font");

    float cell_w = grid->cell_size.width > 0 ? (float)grid->cell_size.width : 1.0f;
    float cell_h = grid->cell_size.height > 0 ? (float)grid->cell_size.height : 1.0f;
    struct vtermgrid_uniforms uniforms = {0};
    uniforms.grid_size[0] = (float)grid->cols;
    uniforms.grid_size[1] = (float)grid->rows;
    uniforms.cell_size[0] = cell_w;
    uniforms.cell_size[1] = cell_h;
    uniforms.pixel_range = grid->uni_pixel_range;
    uniforms.scale = grid->uni_scale;
    uniforms.baseline_y = grid->uni_baseline_y;
    uniforms.glyph_left = grid->uni_glyph_left;
    uniforms.cursor_col = grid->cursor_col;
    uniforms.cursor_row = grid->cursor_row;
    /* A blinking cursor hides on the shared blink phase (review #10: the
     * blink timer previously animated only blink CELLS). */
    int cursor_shown = grid->cursor_visible && (!grid->cursor_blink || !grid->blink_phase);
    uniforms.cursor_visible = cursor_shown ? 1u : 0u;
    uniforms.cursor_shape = (uint32_t)grid->cursor_shape;
    uniforms.sel_start_row = grid->sel_start_row;
    uniforms.sel_start_col = grid->sel_start_col;
    uniforms.sel_end_row = grid->sel_end_row;
    uniforms.sel_end_col = grid->sel_end_col;
    uniforms.sel_active = grid->sel_active ? 1u : 0u;
    wgpuQueueWriteBuffer(grid->queue, grid->uniform_buffer, 0, &uniforms, sizeof(uniforms));

    struct yetty_ycore_void_result bind_res = vtermgrid_gpu_ensure_bind_group(grid);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, bind_res, "vtermgrid_gpu_render: bind group");

    WGPUTextureView view = target->ops->get_view(target);
    if (!view) {
        return YETTY_ERR(yetty_ycore_void, "vtermgrid_gpu_render: target view NULL");
    }
    float vx = target->viewport.x + rect.min.x;
    float vy = target->viewport.y + rect.min.y;
    float width = rect.max.x - rect.min.x;
    float height = rect.max.y - rect.min.y;
    if (width <= 0.0f || height <= 0.0f) {
        return YETTY_OK_VOID();
    }

    WGPUCommandEncoderDescriptor enc_desc = {0};
    WGPUCommandEncoder enc = wgpuDeviceCreateCommandEncoder(grid->device, &enc_desc);
    if (!enc) {
        return YETTY_ERR(yetty_ycore_void, "vtermgrid_gpu_render: encoder");
    }
    WGPURenderPassColorAttachment ca = {0};
    ca.view = view;
    ca.loadOp = WGPULoadOp_Load;
    ca.storeOp = WGPUStoreOp_Store;
    ca.depthSlice = WGPU_DEPTH_SLICE_UNDEFINED;
    WGPURenderPassDescriptor pass_desc = {0};
    pass_desc.colorAttachmentCount = 1;
    pass_desc.colorAttachments = &ca;
    WGPURenderPassEncoder pass = wgpuCommandEncoderBeginRenderPass(enc, &pass_desc);
    if (!pass) {
        wgpuCommandEncoderRelease(enc);
        return YETTY_ERR(yetty_ycore_void, "vtermgrid_gpu_render: begin pass");
    }
    wgpuRenderPassEncoderSetViewport(pass, vx, vy, width, height, 0.0f, 1.0f);
    float tx0 = target->viewport.x, ty0 = target->viewport.y;
    float tx1 = tx0 + target->viewport.w, ty1 = ty0 + target->viewport.h;
    float sx0 = vx > tx0 ? vx : tx0;
    float sy0 = vy > ty0 ? vy : ty0;
    float sx1 = (vx + width) < tx1 ? (vx + width) : tx1;
    float sy1 = (vy + height) < ty1 ? (vy + height) : ty1;
    if (sx1 > sx0 && sy1 > sy0) {
        wgpuRenderPassEncoderSetScissorRect(pass, (uint32_t)sx0, (uint32_t)sy0,
                                            (uint32_t)(sx1 - sx0), (uint32_t)(sy1 - sy0));
        wgpuRenderPassEncoderSetPipeline(pass, grid->pipeline);
        wgpuRenderPassEncoderSetBindGroup(pass, 0, grid->bind_group, 0, NULL);
        wgpuRenderPassEncoderDraw(pass, 6, 1, 0, 0);
    }
    wgpuRenderPassEncoderEnd(pass);
    wgpuRenderPassEncoderRelease(pass);
    WGPUCommandBufferDescriptor cmd_desc = {0};
    WGPUCommandBuffer cmd = wgpuCommandEncoderFinish(enc, &cmd_desc);
    wgpuQueueSubmit(grid->queue, 1, &cmd);
    wgpuCommandBufferRelease(cmd);
    wgpuCommandEncoderRelease(enc);
    return YETTY_OK_VOID();
}

#include "yetty/gen/impl/yscene/vtermgrid.c"
