#!/usr/bin/env python3
"""
Generate the shader-glyph name->codepoint table.

Scans `src/yetty/yfont/glyph-shaders/0xNN-name.wgsl` and emits a C header
with a `static const struct ... TABLE[]` sorted alphabetically by name.

Codepoint = PUA_BASE (0xE000) + local_id (the NN from the filename).
This matches yterm/text-layer.c::resolve_glyph and shader-glyph-layer.h.

Usage: gen-shader-glyph-table.py <glyphs_dir> <output_header>
"""

import re
import sys
from pathlib import Path

PUA_BASE = 0xE000
FILE_RE = re.compile(r"^0x([0-9a-fA-F]+)-(.+)\.wgsl$")


def scan(glyphs_dir: Path):
    out = []
    for path in sorted(glyphs_dir.glob("*.wgsl")):
        m = FILE_RE.match(path.name)
        if not m:
            continue
        local_id = int(m.group(1), 16)
        name = m.group(2)
        if local_id > 0xFF:
            print(
                f"warning: {path.name}: local_id 0x{local_id:x} > 0xFF — "
                f"outside U+E000..U+E0FF range, skipping",
                file=sys.stderr,
            )
            continue
        out.append((name, PUA_BASE + local_id))
    out.sort(key=lambda e: e[0])
    return out


def render(entries) -> str:
    lines = [
        "/* Auto-generated by gen-shader-glyph-table.py — DO NOT EDIT */",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "#include <yetty/yfont/shader-glyph.h>",
        "",
        f"#define YETTY_YFONT_SHADER_GLYPH_TABLE_COUNT ((size_t){len(entries)})",
        "",
        "static const struct yetty_yfont_shader_glyph_entry "
        "yetty_yfont_shader_glyph_table_data[] = {",
    ]
    for name, cp in entries:
        lines.append(f'    {{"{name}", 0x{cp:04X}u}},')
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main():
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <glyphs_dir> <output_header>", file=sys.stderr)
        sys.exit(1)

    glyphs_dir = Path(sys.argv[1])
    out_path = Path(sys.argv[2])

    if not glyphs_dir.is_dir():
        print(f"error: {glyphs_dir} is not a directory", file=sys.stderr)
        sys.exit(1)

    entries = scan(glyphs_dir)
    content = render(entries)

    if out_path.exists() and out_path.read_text() == content:
        print(f"shader-glyph table unchanged ({len(entries)} entries)")
        return

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content)
    print(f"shader-glyph table: wrote {out_path} ({len(entries)} entries)")


if __name__ == "__main__":
    main()
