// MSDF font shader — instance-namespaced.
//
// Multiple msdf-font instances coexist as separate children of one layer
// (e.g. ydraw mixing 13 PDF-embedded fonts). The pipeline binder gives
// each instance a unique namespace and substitutes __NS__ here with that
// namespace at shader-merge time. After substitution each instance
// contributes its own helpers (e.g. `msdf_<hash>_glyph_sample`) and
// references its own per-instance uniforms / buffer offset / atlas region.
//
// The layer's dispatcher (generated by the binder once it knows the child
// set) calls the right per-instance helper based on the prim's font_id.
//
// Per-instance values supplied by the binder:
//   uniforms.__NS___base_size       — font_size used to bake metrics
//   uniforms.__NS___cell_size       — atlas cell side in pixels
//   uniforms.__NS___atlas_cols      — cells per atlas row at upload time
//   uniforms.__NS___pixel_range     — MSDF range, in pixels
//   uniforms.__NS___texture_region  — vec4(u_min, v_min, u_max, v_max) of
//                                     this font's slice in the packed atlas
//   __NS___buffer_offset            — start of glyph metadata in storage
//
// Glyph metadata layout (6 u32 / glyph):
//   [0] size_x    bitmap width  in px at base_size
//   [1] size_y    bitmap height in px at base_size
//   [2] bearing_x   horizontal bearing (pre-applied by ydraw on the CPU)
//   [3] bearing_y   vertical   bearing (pre-applied by ydraw on the CPU)
//   [4] advance     horizontal advance in px at base_size
//   [5] cell_idx    atlas-cell index (-1 for empty glyphs like space)

fn __NS___median3(r: f32, g: f32, b: f32) -> f32 {
    return max(min(r, g), min(max(r, g), b));
}

fn __NS___base_size() -> f32 {
    return uniforms.__NS___base_size;
}

fn __NS___glyph_size(glyph_index: u32) -> vec2<f32> {
    let base = __NS___buffer_offset + glyph_index * 6u;
    return vec2<f32>(
        bitcast<f32>(storage_buffer[base + 0u]),
        bitcast<f32>(storage_buffer[base + 1u])
    );
}

// Alpha coverage for a glyph at normalised glyph-local coords (0..1).
// pixel_scale = rendered_pixels / base_size — drives MSDF antialiasing.
fn __NS___glyph_sample(glyph_index: u32,
                       glyph_uv: vec2<f32>,
                       pixel_scale: f32) -> f32 {
    let meta_base = __NS___buffer_offset + glyph_index * 6u;
    let glyph_size = vec2<f32>(
        bitcast<f32>(storage_buffer[meta_base + 0u]),
        bitcast<f32>(storage_buffer[meta_base + 1u])
    );
    if (glyph_size.x <= 0.0 || glyph_size.y <= 0.0) {
        return 0.0;
    }
    let cell_idx_f = bitcast<f32>(storage_buffer[meta_base + 5u]);
    if (cell_idx_f < 0.0) {
        return 0.0;
    }

    let cell_idx = u32(cell_idx_f);
    let cell_size_px = f32(uniforms.__NS___cell_size);
    let atlas_cols = uniforms.__NS___atlas_cols;
    let col = cell_idx % atlas_cols;
    let row = cell_idx / atlas_cols;

    // Sub-region of the packed atlas this font occupies (normalised UV).
    let region = uniforms.__NS___texture_region;
    let region_origin_uv = region.xy;
    let atlas_size = vec2<f32>(textureDimensions(atlas_rgba8_texture, 0));

    // Cell origin within the font's own region, then normalised.
    let cell_origin_px = vec2<f32>(f32(col), f32(row)) * cell_size_px;
    // Bitmap is centred in its cell — map glyph_uv to the inner region.
    let padding = (vec2<f32>(cell_size_px) - glyph_size) * 0.5;
    let inner_min_px = cell_origin_px + padding;
    let inner_max_px = cell_origin_px + padding + glyph_size;

    let uv_min = region_origin_uv + inner_min_px / atlas_size;
    let uv_max = region_origin_uv + inner_max_px / atlas_size;
    let uv = clamp(glyph_uv, vec2<f32>(0.0), vec2<f32>(1.0));
    let sample_uv = mix(uv_min, uv_max, uv);

    let msdf = textureSampleLevel(atlas_rgba8_texture, atlas_rgba8_sampler,
                                  sample_uv, 0.0);
    let sd = __NS___median3(msdf.r, msdf.g, msdf.b);
    let screen_px_range = uniforms.__NS___pixel_range * pixel_scale;
    return clamp((sd - 0.5) * screen_px_range + 0.5, 0.0, 1.0);
}
