// Auto-generated from sdf-drawables.yaml - DO NOT EDIT
// Generated by: src/yetty/ysdf/gen-sdf-code.py

// yclass shape classes of the v2 ydraw client interface (module ysdf2).
// Record layout per shape: [type|HAS_ID][id?][z][fill][stroke]
// [stroke_width][geometry words in schema order].

#include <yetty/yclass/class.h>
#include <yetty/ycore/result.h>
#include <yetty/ycore/types.h>
#include <yetty/ydraw-list/drawable-list.h>

#include <string.h>

/* Parent-module property accessors (shape paint prefix). */
#include "yetty/gen/impl/ydrawlist2/shape.h"

struct YETTY_ANNOTATE("class@ysdf2:circle") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_circle {
    YETTY_ANNOTATE("property") float center_x;
    YETTY_ANNOTATE("property") float center_y;
    YETTY_ANNOTATE("property") float radius;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_circle_ptr, struct yetty_ysdf2_circle *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_CIRCLE_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_circle_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_circle_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 circle pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 circle pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 circle pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 circle pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 circle pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_circle_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 circle pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 circle pack: slice");
    const struct yetty_ysdf2_circle *geometry =
        (const struct yetty_ysdf2_circle *)self_r.value;

    uint32_t data[9];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFFFFu;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->center_x, sizeof(float));
    memcpy(&data[off++], &geometry->center_y, sizeof(float));
    memcpy(&data[off++], &geometry->radius, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 circle pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:box") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_box {
    YETTY_ANNOTATE("property") float center_x;
    YETTY_ANNOTATE("property") float center_y;
    YETTY_ANNOTATE("property") float half_width;
    YETTY_ANNOTATE("property") float half_height;
    YETTY_ANNOTATE("property") float corner_radius;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_box_ptr, struct yetty_ysdf2_box *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_BOX_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_box_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_box_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 box pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 box pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 box pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 box pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 box pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_box_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 box pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 box pack: slice");
    const struct yetty_ysdf2_box *geometry =
        (const struct yetty_ysdf2_box *)self_r.value;

    uint32_t data[11];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFFFEu;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->center_x, sizeof(float));
    memcpy(&data[off++], &geometry->center_y, sizeof(float));
    memcpy(&data[off++], &geometry->half_width, sizeof(float));
    memcpy(&data[off++], &geometry->half_height, sizeof(float));
    memcpy(&data[off++], &geometry->corner_radius, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 box pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:segment") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_segment {
    YETTY_ANNOTATE("property") float start_x;
    YETTY_ANNOTATE("property") float start_y;
    YETTY_ANNOTATE("property") float end_x;
    YETTY_ANNOTATE("property") float end_y;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_segment_ptr, struct yetty_ysdf2_segment *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_SEGMENT_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_segment_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_segment_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 segment pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 segment pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 segment pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 segment pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 segment pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_segment_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 segment pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 segment pack: slice");
    const struct yetty_ysdf2_segment *geometry =
        (const struct yetty_ysdf2_segment *)self_r.value;

    uint32_t data[10];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFFFDu;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->start_x, sizeof(float));
    memcpy(&data[off++], &geometry->start_y, sizeof(float));
    memcpy(&data[off++], &geometry->end_x, sizeof(float));
    memcpy(&data[off++], &geometry->end_y, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 segment pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:triangle") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_triangle {
    YETTY_ANNOTATE("property") float vertex_a_x;
    YETTY_ANNOTATE("property") float vertex_a_y;
    YETTY_ANNOTATE("property") float vertex_b_x;
    YETTY_ANNOTATE("property") float vertex_b_y;
    YETTY_ANNOTATE("property") float vertex_c_x;
    YETTY_ANNOTATE("property") float vertex_c_y;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_triangle_ptr, struct yetty_ysdf2_triangle *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_TRIANGLE_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_triangle_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_triangle_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 triangle pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 triangle pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 triangle pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 triangle pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 triangle pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_triangle_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 triangle pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 triangle pack: slice");
    const struct yetty_ysdf2_triangle *geometry =
        (const struct yetty_ysdf2_triangle *)self_r.value;

    uint32_t data[12];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFFFCu;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->vertex_a_x, sizeof(float));
    memcpy(&data[off++], &geometry->vertex_a_y, sizeof(float));
    memcpy(&data[off++], &geometry->vertex_b_x, sizeof(float));
    memcpy(&data[off++], &geometry->vertex_b_y, sizeof(float));
    memcpy(&data[off++], &geometry->vertex_c_x, sizeof(float));
    memcpy(&data[off++], &geometry->vertex_c_y, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 triangle pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:ellipse") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_ellipse {
    YETTY_ANNOTATE("property") float center_x;
    YETTY_ANNOTATE("property") float center_y;
    YETTY_ANNOTATE("property") float radius_x;
    YETTY_ANNOTATE("property") float radius_y;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_ellipse_ptr, struct yetty_ysdf2_ellipse *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_ELLIPSE_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_ellipse_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_ellipse_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 ellipse pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 ellipse pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 ellipse pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 ellipse pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 ellipse pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_ellipse_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 ellipse pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 ellipse pack: slice");
    const struct yetty_ysdf2_ellipse *geometry =
        (const struct yetty_ysdf2_ellipse *)self_r.value;

    uint32_t data[10];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFFF9u;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->center_x, sizeof(float));
    memcpy(&data[off++], &geometry->center_y, sizeof(float));
    memcpy(&data[off++], &geometry->radius_x, sizeof(float));
    memcpy(&data[off++], &geometry->radius_y, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 ellipse pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:arc") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_arc {
    YETTY_ANNOTATE("property") float center_x;
    YETTY_ANNOTATE("property") float center_y;
    YETTY_ANNOTATE("property") float aperture_x;
    YETTY_ANNOTATE("property") float aperture_y;
    YETTY_ANNOTATE("property") float radius;
    YETTY_ANNOTATE("property") float thickness;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_arc_ptr, struct yetty_ysdf2_arc *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_ARC_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_arc_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_arc_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 arc pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 arc pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 arc pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 arc pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 arc pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_arc_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 arc pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 arc pack: slice");
    const struct yetty_ysdf2_arc *geometry =
        (const struct yetty_ysdf2_arc *)self_r.value;

    uint32_t data[12];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFFF8u;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->center_x, sizeof(float));
    memcpy(&data[off++], &geometry->center_y, sizeof(float));
    memcpy(&data[off++], &geometry->aperture_x, sizeof(float));
    memcpy(&data[off++], &geometry->aperture_y, sizeof(float));
    memcpy(&data[off++], &geometry->radius, sizeof(float));
    memcpy(&data[off++], &geometry->thickness, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 arc pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:rounded_box") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_rounded_box {
    YETTY_ANNOTATE("property") float center_x;
    YETTY_ANNOTATE("property") float center_y;
    YETTY_ANNOTATE("property") float half_width;
    YETTY_ANNOTATE("property") float half_height;
    YETTY_ANNOTATE("property") float radius_top_right;
    YETTY_ANNOTATE("property") float radius_bottom_right;
    YETTY_ANNOTATE("property") float radius_top_left;
    YETTY_ANNOTATE("property") float radius_bottom_left;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_rounded_box_ptr, struct yetty_ysdf2_rounded_box *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_ROUNDED_BOX_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_rounded_box_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_rounded_box_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 rounded_box pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 rounded_box pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 rounded_box pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 rounded_box pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 rounded_box pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_rounded_box_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 rounded_box pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 rounded_box pack: slice");
    const struct yetty_ysdf2_rounded_box *geometry =
        (const struct yetty_ysdf2_rounded_box *)self_r.value;

    uint32_t data[14];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFFF7u;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->center_x, sizeof(float));
    memcpy(&data[off++], &geometry->center_y, sizeof(float));
    memcpy(&data[off++], &geometry->half_width, sizeof(float));
    memcpy(&data[off++], &geometry->half_height, sizeof(float));
    memcpy(&data[off++], &geometry->radius_top_right, sizeof(float));
    memcpy(&data[off++], &geometry->radius_bottom_right, sizeof(float));
    memcpy(&data[off++], &geometry->radius_top_left, sizeof(float));
    memcpy(&data[off++], &geometry->radius_bottom_left, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 rounded_box pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:rhombus") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_rhombus {
    YETTY_ANNOTATE("property") float center_x;
    YETTY_ANNOTATE("property") float center_y;
    YETTY_ANNOTATE("property") float half_width;
    YETTY_ANNOTATE("property") float half_height;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_rhombus_ptr, struct yetty_ysdf2_rhombus *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_RHOMBUS_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_rhombus_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_rhombus_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 rhombus pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 rhombus pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 rhombus pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 rhombus pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 rhombus pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_rhombus_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 rhombus pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 rhombus pack: slice");
    const struct yetty_ysdf2_rhombus *geometry =
        (const struct yetty_ysdf2_rhombus *)self_r.value;

    uint32_t data[10];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFFF6u;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->center_x, sizeof(float));
    memcpy(&data[off++], &geometry->center_y, sizeof(float));
    memcpy(&data[off++], &geometry->half_width, sizeof(float));
    memcpy(&data[off++], &geometry->half_height, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 rhombus pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:pentagon") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_pentagon {
    YETTY_ANNOTATE("property") float center_x;
    YETTY_ANNOTATE("property") float center_y;
    YETTY_ANNOTATE("property") float radius;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_pentagon_ptr, struct yetty_ysdf2_pentagon *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_PENTAGON_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_pentagon_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_pentagon_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 pentagon pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 pentagon pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 pentagon pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 pentagon pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 pentagon pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_pentagon_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 pentagon pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 pentagon pack: slice");
    const struct yetty_ysdf2_pentagon *geometry =
        (const struct yetty_ysdf2_pentagon *)self_r.value;

    uint32_t data[9];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFFF5u;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->center_x, sizeof(float));
    memcpy(&data[off++], &geometry->center_y, sizeof(float));
    memcpy(&data[off++], &geometry->radius, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 pentagon pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:hexagon") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_hexagon {
    YETTY_ANNOTATE("property") float center_x;
    YETTY_ANNOTATE("property") float center_y;
    YETTY_ANNOTATE("property") float radius;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_hexagon_ptr, struct yetty_ysdf2_hexagon *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_HEXAGON_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_hexagon_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_hexagon_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 hexagon pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 hexagon pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 hexagon pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 hexagon pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 hexagon pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_hexagon_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 hexagon pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 hexagon pack: slice");
    const struct yetty_ysdf2_hexagon *geometry =
        (const struct yetty_ysdf2_hexagon *)self_r.value;

    uint32_t data[9];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFFF4u;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->center_x, sizeof(float));
    memcpy(&data[off++], &geometry->center_y, sizeof(float));
    memcpy(&data[off++], &geometry->radius, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 hexagon pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:star") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_star {
    YETTY_ANNOTATE("property") float center_x;
    YETTY_ANNOTATE("property") float center_y;
    YETTY_ANNOTATE("property") float radius;
    YETTY_ANNOTATE("property") float num_points;
    YETTY_ANNOTATE("property") float inner_ratio;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_star_ptr, struct yetty_ysdf2_star *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_STAR_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_star_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_star_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 star pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 star pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 star pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 star pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 star pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_star_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 star pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 star pack: slice");
    const struct yetty_ysdf2_star *geometry =
        (const struct yetty_ysdf2_star *)self_r.value;

    uint32_t data[11];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFFF3u;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->center_x, sizeof(float));
    memcpy(&data[off++], &geometry->center_y, sizeof(float));
    memcpy(&data[off++], &geometry->radius, sizeof(float));
    memcpy(&data[off++], &geometry->num_points, sizeof(float));
    memcpy(&data[off++], &geometry->inner_ratio, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 star pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:pie") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_pie {
    YETTY_ANNOTATE("property") float center_x;
    YETTY_ANNOTATE("property") float center_y;
    YETTY_ANNOTATE("property") float aperture_x;
    YETTY_ANNOTATE("property") float aperture_y;
    YETTY_ANNOTATE("property") float radius;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_pie_ptr, struct yetty_ysdf2_pie *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_PIE_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_pie_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_pie_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 pie pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 pie pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 pie pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 pie pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 pie pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_pie_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 pie pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 pie pack: slice");
    const struct yetty_ysdf2_pie *geometry =
        (const struct yetty_ysdf2_pie *)self_r.value;

    uint32_t data[11];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFFF2u;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->center_x, sizeof(float));
    memcpy(&data[off++], &geometry->center_y, sizeof(float));
    memcpy(&data[off++], &geometry->aperture_x, sizeof(float));
    memcpy(&data[off++], &geometry->aperture_y, sizeof(float));
    memcpy(&data[off++], &geometry->radius, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 pie pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:ring") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_ring {
    YETTY_ANNOTATE("property") float center_x;
    YETTY_ANNOTATE("property") float center_y;
    YETTY_ANNOTATE("property") float normal_x;
    YETTY_ANNOTATE("property") float normal_y;
    YETTY_ANNOTATE("property") float radius;
    YETTY_ANNOTATE("property") float thickness;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_ring_ptr, struct yetty_ysdf2_ring *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_RING_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_ring_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_ring_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 ring pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 ring pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 ring pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 ring pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 ring pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_ring_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 ring pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 ring pack: slice");
    const struct yetty_ysdf2_ring *geometry =
        (const struct yetty_ysdf2_ring *)self_r.value;

    uint32_t data[12];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFFF1u;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->center_x, sizeof(float));
    memcpy(&data[off++], &geometry->center_y, sizeof(float));
    memcpy(&data[off++], &geometry->normal_x, sizeof(float));
    memcpy(&data[off++], &geometry->normal_y, sizeof(float));
    memcpy(&data[off++], &geometry->radius, sizeof(float));
    memcpy(&data[off++], &geometry->thickness, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 ring pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:heart") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_heart {
    YETTY_ANNOTATE("property") float center_x;
    YETTY_ANNOTATE("property") float center_y;
    YETTY_ANNOTATE("property") float scale;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_heart_ptr, struct yetty_ysdf2_heart *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_HEART_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_heart_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_heart_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 heart pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 heart pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 heart pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 heart pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 heart pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_heart_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 heart pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 heart pack: slice");
    const struct yetty_ysdf2_heart *geometry =
        (const struct yetty_ysdf2_heart *)self_r.value;

    uint32_t data[9];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFFF0u;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->center_x, sizeof(float));
    memcpy(&data[off++], &geometry->center_y, sizeof(float));
    memcpy(&data[off++], &geometry->scale, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 heart pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:cross") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_cross {
    YETTY_ANNOTATE("property") float center_x;
    YETTY_ANNOTATE("property") float center_y;
    YETTY_ANNOTATE("property") float half_width;
    YETTY_ANNOTATE("property") float half_height;
    YETTY_ANNOTATE("property") float corner_radius;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_cross_ptr, struct yetty_ysdf2_cross *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_CROSS_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_cross_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_cross_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 cross pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 cross pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 cross pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 cross pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 cross pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_cross_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 cross pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 cross pack: slice");
    const struct yetty_ysdf2_cross *geometry =
        (const struct yetty_ysdf2_cross *)self_r.value;

    uint32_t data[11];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFFEFu;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->center_x, sizeof(float));
    memcpy(&data[off++], &geometry->center_y, sizeof(float));
    memcpy(&data[off++], &geometry->half_width, sizeof(float));
    memcpy(&data[off++], &geometry->half_height, sizeof(float));
    memcpy(&data[off++], &geometry->corner_radius, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 cross pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:rounded_x") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_rounded_x {
    YETTY_ANNOTATE("property") float center_x;
    YETTY_ANNOTATE("property") float center_y;
    YETTY_ANNOTATE("property") float width;
    YETTY_ANNOTATE("property") float radius;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_rounded_x_ptr, struct yetty_ysdf2_rounded_x *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_ROUNDED_X_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_rounded_x_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_rounded_x_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 rounded_x pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 rounded_x pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 rounded_x pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 rounded_x pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 rounded_x pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_rounded_x_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 rounded_x pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 rounded_x pack: slice");
    const struct yetty_ysdf2_rounded_x *geometry =
        (const struct yetty_ysdf2_rounded_x *)self_r.value;

    uint32_t data[10];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFFEEu;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->center_x, sizeof(float));
    memcpy(&data[off++], &geometry->center_y, sizeof(float));
    memcpy(&data[off++], &geometry->width, sizeof(float));
    memcpy(&data[off++], &geometry->radius, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 rounded_x pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:capsule") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_capsule {
    YETTY_ANNOTATE("property") float start_x;
    YETTY_ANNOTATE("property") float start_y;
    YETTY_ANNOTATE("property") float end_x;
    YETTY_ANNOTATE("property") float end_y;
    YETTY_ANNOTATE("property") float radius;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_capsule_ptr, struct yetty_ysdf2_capsule *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_CAPSULE_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_capsule_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_capsule_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 capsule pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 capsule pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 capsule pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 capsule pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 capsule pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_capsule_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 capsule pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 capsule pack: slice");
    const struct yetty_ysdf2_capsule *geometry =
        (const struct yetty_ysdf2_capsule *)self_r.value;

    uint32_t data[11];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFFEDu;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->start_x, sizeof(float));
    memcpy(&data[off++], &geometry->start_y, sizeof(float));
    memcpy(&data[off++], &geometry->end_x, sizeof(float));
    memcpy(&data[off++], &geometry->end_y, sizeof(float));
    memcpy(&data[off++], &geometry->radius, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 capsule pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:moon") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_moon {
    YETTY_ANNOTATE("property") float center_x;
    YETTY_ANNOTATE("property") float center_y;
    YETTY_ANNOTATE("property") float offset;
    YETTY_ANNOTATE("property") float radius_outer;
    YETTY_ANNOTATE("property") float radius_inner;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_moon_ptr, struct yetty_ysdf2_moon *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_MOON_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_moon_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_moon_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 moon pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 moon pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 moon pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 moon pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 moon pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_moon_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 moon pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 moon pack: slice");
    const struct yetty_ysdf2_moon *geometry =
        (const struct yetty_ysdf2_moon *)self_r.value;

    uint32_t data[11];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFFECu;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->center_x, sizeof(float));
    memcpy(&data[off++], &geometry->center_y, sizeof(float));
    memcpy(&data[off++], &geometry->offset, sizeof(float));
    memcpy(&data[off++], &geometry->radius_outer, sizeof(float));
    memcpy(&data[off++], &geometry->radius_inner, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 moon pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:egg") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_egg {
    YETTY_ANNOTATE("property") float center_x;
    YETTY_ANNOTATE("property") float center_y;
    YETTY_ANNOTATE("property") float radius_outer;
    YETTY_ANNOTATE("property") float radius_inner;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_egg_ptr, struct yetty_ysdf2_egg *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_EGG_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_egg_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_egg_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 egg pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 egg pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 egg pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 egg pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 egg pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_egg_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 egg pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 egg pack: slice");
    const struct yetty_ysdf2_egg *geometry =
        (const struct yetty_ysdf2_egg *)self_r.value;

    uint32_t data[10];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFFEBu;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->center_x, sizeof(float));
    memcpy(&data[off++], &geometry->center_y, sizeof(float));
    memcpy(&data[off++], &geometry->radius_outer, sizeof(float));
    memcpy(&data[off++], &geometry->radius_inner, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 egg pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:octogon") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_octogon {
    YETTY_ANNOTATE("property") float center_x;
    YETTY_ANNOTATE("property") float center_y;
    YETTY_ANNOTATE("property") float radius;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_octogon_ptr, struct yetty_ysdf2_octogon *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_OCTOGON_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_octogon_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_octogon_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 octogon pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 octogon pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 octogon pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 octogon pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 octogon pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_octogon_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 octogon pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 octogon pack: slice");
    const struct yetty_ysdf2_octogon *geometry =
        (const struct yetty_ysdf2_octogon *)self_r.value;

    uint32_t data[9];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFFE3u;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->center_x, sizeof(float));
    memcpy(&data[off++], &geometry->center_y, sizeof(float));
    memcpy(&data[off++], &geometry->radius, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 octogon pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:hexagram") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_hexagram {
    YETTY_ANNOTATE("property") float center_x;
    YETTY_ANNOTATE("property") float center_y;
    YETTY_ANNOTATE("property") float radius;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_hexagram_ptr, struct yetty_ysdf2_hexagram *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_HEXAGRAM_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_hexagram_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_hexagram_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 hexagram pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 hexagram pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 hexagram pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 hexagram pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 hexagram pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_hexagram_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 hexagram pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 hexagram pack: slice");
    const struct yetty_ysdf2_hexagram *geometry =
        (const struct yetty_ysdf2_hexagram *)self_r.value;

    uint32_t data[9];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFFE2u;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->center_x, sizeof(float));
    memcpy(&data[off++], &geometry->center_y, sizeof(float));
    memcpy(&data[off++], &geometry->radius, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 hexagram pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:pentagram") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_pentagram {
    YETTY_ANNOTATE("property") float center_x;
    YETTY_ANNOTATE("property") float center_y;
    YETTY_ANNOTATE("property") float radius;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_pentagram_ptr, struct yetty_ysdf2_pentagram *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_PENTAGRAM_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_pentagram_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_pentagram_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 pentagram pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 pentagram pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 pentagram pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 pentagram pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 pentagram pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_pentagram_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 pentagram pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 pentagram pack: slice");
    const struct yetty_ysdf2_pentagram *geometry =
        (const struct yetty_ysdf2_pentagram *)self_r.value;

    uint32_t data[9];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFFE1u;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->center_x, sizeof(float));
    memcpy(&data[off++], &geometry->center_y, sizeof(float));
    memcpy(&data[off++], &geometry->radius, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 pentagram pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:linear_gradient_box") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_linear_gradient_box {
    YETTY_ANNOTATE("property") float center_x;
    YETTY_ANNOTATE("property") float center_y;
    YETTY_ANNOTATE("property") float half_width;
    YETTY_ANNOTATE("property") float half_height;
    YETTY_ANNOTATE("property") float corner_radius;
    YETTY_ANNOTATE("property") float grad_x0;
    YETTY_ANNOTATE("property") float grad_y0;
    YETTY_ANNOTATE("property") float grad_x1;
    YETTY_ANNOTATE("property") float grad_y1;
    YETTY_ANNOTATE("property") uint32_t color0;
    YETTY_ANNOTATE("property") uint32_t color1;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_linear_gradient_box_ptr, struct yetty_ysdf2_linear_gradient_box *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_LINEAR_GRADIENT_BOX_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_linear_gradient_box_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_linear_gradient_box_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 linear_gradient_box pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 linear_gradient_box pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 linear_gradient_box pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 linear_gradient_box pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 linear_gradient_box pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_linear_gradient_box_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 linear_gradient_box pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 linear_gradient_box pack: slice");
    const struct yetty_ysdf2_linear_gradient_box *geometry =
        (const struct yetty_ysdf2_linear_gradient_box *)self_r.value;

    uint32_t data[17];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFF7Du;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->center_x, sizeof(float));
    memcpy(&data[off++], &geometry->center_y, sizeof(float));
    memcpy(&data[off++], &geometry->half_width, sizeof(float));
    memcpy(&data[off++], &geometry->half_height, sizeof(float));
    memcpy(&data[off++], &geometry->corner_radius, sizeof(float));
    memcpy(&data[off++], &geometry->grad_x0, sizeof(float));
    memcpy(&data[off++], &geometry->grad_y0, sizeof(float));
    memcpy(&data[off++], &geometry->grad_x1, sizeof(float));
    memcpy(&data[off++], &geometry->grad_y1, sizeof(float));
    data[off++] = (uint32_t)geometry->color0;
    data[off++] = (uint32_t)geometry->color1;

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 linear_gradient_box pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:radial_gradient_box") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_radial_gradient_box {
    YETTY_ANNOTATE("property") float center_x;
    YETTY_ANNOTATE("property") float center_y;
    YETTY_ANNOTATE("property") float half_width;
    YETTY_ANNOTATE("property") float half_height;
    YETTY_ANNOTATE("property") float corner_radius;
    YETTY_ANNOTATE("property") float grad_cx;
    YETTY_ANNOTATE("property") float grad_cy;
    YETTY_ANNOTATE("property") float grad_radius;
    YETTY_ANNOTATE("property") uint32_t color_inner;
    YETTY_ANNOTATE("property") uint32_t color_outer;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_radial_gradient_box_ptr, struct yetty_ysdf2_radial_gradient_box *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_RADIAL_GRADIENT_BOX_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_radial_gradient_box_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_radial_gradient_box_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 radial_gradient_box pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 radial_gradient_box pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 radial_gradient_box pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 radial_gradient_box pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 radial_gradient_box pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_radial_gradient_box_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 radial_gradient_box pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 radial_gradient_box pack: slice");
    const struct yetty_ysdf2_radial_gradient_box *geometry =
        (const struct yetty_ysdf2_radial_gradient_box *)self_r.value;

    uint32_t data[16];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFF7Cu;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->center_x, sizeof(float));
    memcpy(&data[off++], &geometry->center_y, sizeof(float));
    memcpy(&data[off++], &geometry->half_width, sizeof(float));
    memcpy(&data[off++], &geometry->half_height, sizeof(float));
    memcpy(&data[off++], &geometry->corner_radius, sizeof(float));
    memcpy(&data[off++], &geometry->grad_cx, sizeof(float));
    memcpy(&data[off++], &geometry->grad_cy, sizeof(float));
    memcpy(&data[off++], &geometry->grad_radius, sizeof(float));
    data[off++] = (uint32_t)geometry->color_inner;
    data[off++] = (uint32_t)geometry->color_outer;

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 radial_gradient_box pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:sphere_3d") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_sphere_3d {
    YETTY_ANNOTATE("property") float position_x;
    YETTY_ANNOTATE("property") float position_y;
    YETTY_ANNOTATE("property") float position_z;
    YETTY_ANNOTATE("property") float radius;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_sphere_3d_ptr, struct yetty_ysdf2_sphere_3d *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_SPHERE_3D_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_sphere_3d_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_sphere_3d_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 sphere_3d pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 sphere_3d pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 sphere_3d pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 sphere_3d pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 sphere_3d pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_sphere_3d_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 sphere_3d pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 sphere_3d pack: slice");
    const struct yetty_ysdf2_sphere_3d *geometry =
        (const struct yetty_ysdf2_sphere_3d *)self_r.value;

    uint32_t data[10];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFF9Bu;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->position_x, sizeof(float));
    memcpy(&data[off++], &geometry->position_y, sizeof(float));
    memcpy(&data[off++], &geometry->position_z, sizeof(float));
    memcpy(&data[off++], &geometry->radius, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 sphere_3d pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:box_3d") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_box_3d {
    YETTY_ANNOTATE("property") float position_x;
    YETTY_ANNOTATE("property") float position_y;
    YETTY_ANNOTATE("property") float position_z;
    YETTY_ANNOTATE("property") float half_size_x;
    YETTY_ANNOTATE("property") float half_size_y;
    YETTY_ANNOTATE("property") float half_size_z;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_box_3d_ptr, struct yetty_ysdf2_box_3d *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_BOX_3D_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_box_3d_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_box_3d_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 box_3d pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 box_3d pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 box_3d pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 box_3d pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 box_3d pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_box_3d_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 box_3d pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 box_3d pack: slice");
    const struct yetty_ysdf2_box_3d *geometry =
        (const struct yetty_ysdf2_box_3d *)self_r.value;

    uint32_t data[12];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFF9Au;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->position_x, sizeof(float));
    memcpy(&data[off++], &geometry->position_y, sizeof(float));
    memcpy(&data[off++], &geometry->position_z, sizeof(float));
    memcpy(&data[off++], &geometry->half_size_x, sizeof(float));
    memcpy(&data[off++], &geometry->half_size_y, sizeof(float));
    memcpy(&data[off++], &geometry->half_size_z, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 box_3d pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:torus_3d") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_torus_3d {
    YETTY_ANNOTATE("property") float position_x;
    YETTY_ANNOTATE("property") float position_y;
    YETTY_ANNOTATE("property") float position_z;
    YETTY_ANNOTATE("property") float major_radius;
    YETTY_ANNOTATE("property") float minor_radius;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_torus_3d_ptr, struct yetty_ysdf2_torus_3d *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_TORUS_3D_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_torus_3d_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_torus_3d_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 torus_3d pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 torus_3d pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 torus_3d pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 torus_3d pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 torus_3d pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_torus_3d_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 torus_3d pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 torus_3d pack: slice");
    const struct yetty_ysdf2_torus_3d *geometry =
        (const struct yetty_ysdf2_torus_3d *)self_r.value;

    uint32_t data[11];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFF98u;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->position_x, sizeof(float));
    memcpy(&data[off++], &geometry->position_y, sizeof(float));
    memcpy(&data[off++], &geometry->position_z, sizeof(float));
    memcpy(&data[off++], &geometry->major_radius, sizeof(float));
    memcpy(&data[off++], &geometry->minor_radius, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 torus_3d pack: add_prim");
    return YETTY_OK_VOID();
}

struct YETTY_ANNOTATE("class@ysdf2:cylinder_3d") YETTY_ANNOTATE("parent@ydrawlist2:shape")
    yetty_ysdf2_cylinder_3d {
    YETTY_ANNOTATE("property") float position_x;
    YETTY_ANNOTATE("property") float position_y;
    YETTY_ANNOTATE("property") float position_z;
    YETTY_ANNOTATE("property") float radius;
    YETTY_ANNOTATE("property") float half_height;
};

YETTY_YRESULT_DECLARE(yetty_ysdf2_cylinder_3d_ptr, struct yetty_ysdf2_cylinder_3d *);
/* Keep the impl glue's guarded re-emission out of this TU (C23 tag-compat). */
#define YETTY_YCLASSGEN_TYPE_YETTY_YSDF2_CYLINDER_3D_PTR_RESULT

struct yetty_yclass_ptr_result yetty_ysdf2_cylinder_3d_class_get(void);

YETTY_ANNOTATE("override@ydrawlist2:drawable:pack")
static struct yetty_ycore_void_result ysdf2_cylinder_3d_pack(
    struct yetty_yclass_object *obj, struct yetty_ydraw_drawable_list *list)
{
    struct uint32_result id_r = yetty_ydrawlist2_shape_id_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, id_r, "ysdf2 cylinder_3d pack: id");
    struct uint32_result z_r = yetty_ydrawlist2_shape_z_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, z_r, "ysdf2 cylinder_3d pack: z");
    struct uint32_result fill_r = yetty_ydrawlist2_shape_fill_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, fill_r, "ysdf2 cylinder_3d pack: fill");
    struct uint32_result stroke_r = yetty_ydrawlist2_shape_stroke_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_r, "ysdf2 cylinder_3d pack: stroke");
    struct float_result stroke_width_r =
        yetty_ydrawlist2_shape_stroke_width_get(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, stroke_width_r, "ysdf2 cylinder_3d pack: stroke_width");
    struct yetty_yclass_ptr_result class_r = yetty_ysdf2_cylinder_3d_class_get();
    YETTY_RETURN_IF_ERR(yetty_ycore_void, class_r, "ysdf2 cylinder_3d pack: class");
    struct yetty_yclass_void_ptr_result self_r =
        yetty_yclass_object_data(obj, class_r.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, self_r, "ysdf2 cylinder_3d pack: slice");
    const struct yetty_ysdf2_cylinder_3d *geometry =
        (const struct yetty_ysdf2_cylinder_3d *)self_r.value;

    uint32_t data[11];
    uint32_t off = 0;
    uint32_t tmp = (uint32_t)0x7FFFFF96u;
    if (id_r.value != 0u) {
        tmp |= 0x80000000u;
    }
    data[off++] = tmp;
    if (id_r.value != 0u) {
        data[off++] = id_r.value;
    }
    data[off++] = z_r.value;
    data[off++] = fill_r.value;
    data[off++] = stroke_r.value;
    memcpy(&data[off++], &stroke_width_r.value, sizeof(float));
    memcpy(&data[off++], &geometry->position_x, sizeof(float));
    memcpy(&data[off++], &geometry->position_y, sizeof(float));
    memcpy(&data[off++], &geometry->position_z, sizeof(float));
    memcpy(&data[off++], &geometry->radius, sizeof(float));
    memcpy(&data[off++], &geometry->half_height, sizeof(float));

    struct yetty_ydraw_id_result add_r =
        yetty_ydraw_drawable_list_add_prim(list, data, off * sizeof(uint32_t));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, add_r, "ysdf2 cylinder_3d pack: add_prim");
    return YETTY_OK_VOID();
}

#include "yetty/gen/impl/ysdf2/shapes.c"
