/* Generated by src/yetty/yrdawn/generate.py — DO NOT EDIT. */
#ifndef YETTY_YRDAWN_METHODS_GEN_H
#define YETTY_YRDAWN_METHODS_GEN_H

#include <stdint.h>

/* Brings in WGPU* by-value struct types (WGPUColor, WGPUExtent3D, …)
 * referenced by auto-generated args structs. The wire layout reuses
 * the C layout because both client and server are C and use the
 * same webgpu.h. */
#include <webgpu/webgpu.h>

#include <yetty/ycore/result.h>

#ifdef __cplusplus
extern "C" {
#endif

enum yetty_yrdawn_method_id {
    YETTY_YRDAWN_METHOD_INVALID = 0,
    YETTY_YRDAWN_METHOD_wgpuCreateInstance = 1,
    YETTY_YRDAWN_METHOD_wgpuInstanceRelease = 2,
    YETTY_YRDAWN_METHOD_wgpuDeviceTick = 3,
    YETTY_YRDAWN_METHOD_wgpuDeviceGetQueue = 4,
    YETTY_YRDAWN_METHOD_wgpuQueueRelease = 5,
    YETTY_YRDAWN_METHOD_wgpuDeviceRelease = 6,
    YETTY_YRDAWN_METHOD_wgpuAdapterRelease = 7,
    YETTY_YRDAWN_METHOD_wgpuDeviceCreateCommandEncoder = 8,
    YETTY_YRDAWN_METHOD_wgpuCommandEncoderRelease = 9,
    YETTY_YRDAWN_METHOD_wgpuCommandEncoderFinish = 10,
    YETTY_YRDAWN_METHOD_wgpuCommandBufferRelease = 11,
    YETTY_YRDAWN_METHOD_wgpuInstanceRequestAdapter = 12,
    YETTY_YRDAWN_METHOD_wgpuAdapterRequestDevice = 13,
    YETTY_YRDAWN_METHOD_yetty_yrdawn_present_frame = 100,
    YETTY_YRDAWN_METHOD_wgpuAdapterAddRef = 200,
    YETTY_YRDAWN_METHOD_wgpuAdapterCreateDevice = 201,
    YETTY_YRDAWN_METHOD_wgpuAdapterGetFeatures = 202,
    YETTY_YRDAWN_METHOD_wgpuAdapterGetFormatCapabilities = 203,
    YETTY_YRDAWN_METHOD_wgpuAdapterGetInfo = 204,
    YETTY_YRDAWN_METHOD_wgpuAdapterGetInstance = 205,
    YETTY_YRDAWN_METHOD_wgpuAdapterGetLimits = 206,
    YETTY_YRDAWN_METHOD_wgpuAdapterHasFeature = 207,
    YETTY_YRDAWN_METHOD_wgpuAdapterInfoFreeMembers = 208,
    YETTY_YRDAWN_METHOD_wgpuAdapterPropertiesMemoryHeapsFreeMembers = 209,
    YETTY_YRDAWN_METHOD_wgpuAdapterPropertiesSubgroupMatrixConfigsFreeMembers = 210,
    YETTY_YRDAWN_METHOD_wgpuBindGroupAddRef = 211,
    YETTY_YRDAWN_METHOD_wgpuBindGroupLayoutAddRef = 212,
    YETTY_YRDAWN_METHOD_wgpuBindGroupLayoutRelease = 213,
    YETTY_YRDAWN_METHOD_wgpuBindGroupLayoutSetLabel = 214,
    YETTY_YRDAWN_METHOD_wgpuBindGroupRelease = 215,
    YETTY_YRDAWN_METHOD_wgpuBindGroupSetLabel = 216,
    YETTY_YRDAWN_METHOD_wgpuBufferAddRef = 217,
    YETTY_YRDAWN_METHOD_wgpuBufferCreateTexelView = 218,
    YETTY_YRDAWN_METHOD_wgpuBufferDestroy = 219,
    YETTY_YRDAWN_METHOD_wgpuBufferGetMapState = 220,
    YETTY_YRDAWN_METHOD_wgpuBufferGetSize = 221,
    YETTY_YRDAWN_METHOD_wgpuBufferGetUsage = 222,
    YETTY_YRDAWN_METHOD_wgpuBufferMapAsync = 223,
    YETTY_YRDAWN_METHOD_wgpuBufferReadMappedRange = 224,
    YETTY_YRDAWN_METHOD_wgpuBufferRelease = 225,
    YETTY_YRDAWN_METHOD_wgpuBufferSetLabel = 226,
    YETTY_YRDAWN_METHOD_wgpuBufferUnmap = 227,
    YETTY_YRDAWN_METHOD_wgpuBufferWriteMappedRange = 228,
    YETTY_YRDAWN_METHOD_wgpuCommandBufferAddRef = 229,
    YETTY_YRDAWN_METHOD_wgpuCommandBufferSetLabel = 230,
    YETTY_YRDAWN_METHOD_wgpuCommandEncoderAddRef = 231,
    YETTY_YRDAWN_METHOD_wgpuCommandEncoderBeginComputePass = 232,
    YETTY_YRDAWN_METHOD_wgpuCommandEncoderBeginRenderPass = 233,
    YETTY_YRDAWN_METHOD_wgpuCommandEncoderClearBuffer = 234,
    YETTY_YRDAWN_METHOD_wgpuCommandEncoderCopyBufferToBuffer = 235,
    YETTY_YRDAWN_METHOD_wgpuCommandEncoderCopyBufferToTexture = 236,
    YETTY_YRDAWN_METHOD_wgpuCommandEncoderCopyTextureToBuffer = 237,
    YETTY_YRDAWN_METHOD_wgpuCommandEncoderCopyTextureToTexture = 238,
    YETTY_YRDAWN_METHOD_wgpuCommandEncoderInjectValidationError = 239,
    YETTY_YRDAWN_METHOD_wgpuCommandEncoderInsertDebugMarker = 240,
    YETTY_YRDAWN_METHOD_wgpuCommandEncoderPopDebugGroup = 241,
    YETTY_YRDAWN_METHOD_wgpuCommandEncoderPushDebugGroup = 242,
    YETTY_YRDAWN_METHOD_wgpuCommandEncoderResolveQuerySet = 243,
    YETTY_YRDAWN_METHOD_wgpuCommandEncoderSetLabel = 244,
    YETTY_YRDAWN_METHOD_wgpuCommandEncoderWriteBuffer = 245,
    YETTY_YRDAWN_METHOD_wgpuCommandEncoderWriteTimestamp = 246,
    YETTY_YRDAWN_METHOD_wgpuComputePassEncoderAddRef = 247,
    YETTY_YRDAWN_METHOD_wgpuComputePassEncoderDispatchWorkgroups = 248,
    YETTY_YRDAWN_METHOD_wgpuComputePassEncoderDispatchWorkgroupsIndirect = 249,
    YETTY_YRDAWN_METHOD_wgpuComputePassEncoderEnd = 250,
    YETTY_YRDAWN_METHOD_wgpuComputePassEncoderInsertDebugMarker = 251,
    YETTY_YRDAWN_METHOD_wgpuComputePassEncoderPopDebugGroup = 252,
    YETTY_YRDAWN_METHOD_wgpuComputePassEncoderPushDebugGroup = 253,
    YETTY_YRDAWN_METHOD_wgpuComputePassEncoderRelease = 254,
    YETTY_YRDAWN_METHOD_wgpuComputePassEncoderSetBindGroup = 255,
    YETTY_YRDAWN_METHOD_wgpuComputePassEncoderSetImmediates = 256,
    YETTY_YRDAWN_METHOD_wgpuComputePassEncoderSetLabel = 257,
    YETTY_YRDAWN_METHOD_wgpuComputePassEncoderSetPipeline = 258,
    YETTY_YRDAWN_METHOD_wgpuComputePassEncoderSetResourceTable = 259,
    YETTY_YRDAWN_METHOD_wgpuComputePassEncoderWriteTimestamp = 260,
    YETTY_YRDAWN_METHOD_wgpuComputePipelineAddRef = 261,
    YETTY_YRDAWN_METHOD_wgpuComputePipelineGetBindGroupLayout = 262,
    YETTY_YRDAWN_METHOD_wgpuComputePipelineRelease = 263,
    YETTY_YRDAWN_METHOD_wgpuComputePipelineSetLabel = 264,
    YETTY_YRDAWN_METHOD_wgpuDawnDrmFormatCapabilitiesFreeMembers = 265,
    YETTY_YRDAWN_METHOD_wgpuDeviceAddRef = 266,
    YETTY_YRDAWN_METHOD_wgpuDeviceCreateBindGroup = 267,
    YETTY_YRDAWN_METHOD_wgpuDeviceCreateBindGroupLayout = 268,
    YETTY_YRDAWN_METHOD_wgpuDeviceCreateBuffer = 269,
    YETTY_YRDAWN_METHOD_wgpuDeviceCreateComputePipeline = 270,
    YETTY_YRDAWN_METHOD_wgpuDeviceCreateComputePipelineAsync = 271,
    YETTY_YRDAWN_METHOD_wgpuDeviceCreateErrorBuffer = 272,
    YETTY_YRDAWN_METHOD_wgpuDeviceCreateErrorExternalTexture = 273,
    YETTY_YRDAWN_METHOD_wgpuDeviceCreateErrorShaderModule = 274,
    YETTY_YRDAWN_METHOD_wgpuDeviceCreateErrorTexture = 275,
    YETTY_YRDAWN_METHOD_wgpuDeviceCreateExternalTexture = 276,
    YETTY_YRDAWN_METHOD_wgpuDeviceCreatePipelineLayout = 277,
    YETTY_YRDAWN_METHOD_wgpuDeviceCreateQuerySet = 278,
    YETTY_YRDAWN_METHOD_wgpuDeviceCreateRenderBundleEncoder = 279,
    YETTY_YRDAWN_METHOD_wgpuDeviceCreateRenderPipeline = 280,
    YETTY_YRDAWN_METHOD_wgpuDeviceCreateRenderPipelineAsync = 281,
    YETTY_YRDAWN_METHOD_wgpuDeviceCreateResourceTable = 282,
    YETTY_YRDAWN_METHOD_wgpuDeviceCreateSampler = 283,
    YETTY_YRDAWN_METHOD_wgpuDeviceCreateShaderModule = 284,
    YETTY_YRDAWN_METHOD_wgpuDeviceCreateTexture = 285,
    YETTY_YRDAWN_METHOD_wgpuDeviceDestroy = 286,
    YETTY_YRDAWN_METHOD_wgpuDeviceForceLoss = 287,
    YETTY_YRDAWN_METHOD_wgpuDeviceGetAHardwareBufferProperties = 288,
    YETTY_YRDAWN_METHOD_wgpuDeviceGetAdapter = 289,
    YETTY_YRDAWN_METHOD_wgpuDeviceGetAdapterInfo = 290,
    YETTY_YRDAWN_METHOD_wgpuDeviceGetFeatures = 291,
    YETTY_YRDAWN_METHOD_wgpuDeviceGetLimits = 292,
    YETTY_YRDAWN_METHOD_wgpuDeviceGetLostFuture = 293,
    YETTY_YRDAWN_METHOD_wgpuDeviceHasFeature = 294,
    YETTY_YRDAWN_METHOD_wgpuDeviceImportSharedBufferMemory = 295,
    YETTY_YRDAWN_METHOD_wgpuDeviceImportSharedFence = 296,
    YETTY_YRDAWN_METHOD_wgpuDeviceImportSharedTextureMemory = 297,
    YETTY_YRDAWN_METHOD_wgpuDeviceInjectError = 298,
    YETTY_YRDAWN_METHOD_wgpuDevicePopErrorScope = 299,
    YETTY_YRDAWN_METHOD_wgpuDevicePushErrorScope = 300,
    YETTY_YRDAWN_METHOD_wgpuDeviceSetLabel = 301,
    YETTY_YRDAWN_METHOD_wgpuDeviceSetLoggingCallback = 302,
    YETTY_YRDAWN_METHOD_wgpuDeviceValidateTextureDescriptor = 303,
    YETTY_YRDAWN_METHOD_wgpuExternalTextureAddRef = 304,
    YETTY_YRDAWN_METHOD_wgpuExternalTextureDestroy = 305,
    YETTY_YRDAWN_METHOD_wgpuExternalTextureExpire = 306,
    YETTY_YRDAWN_METHOD_wgpuExternalTextureRefresh = 307,
    YETTY_YRDAWN_METHOD_wgpuExternalTextureRelease = 308,
    YETTY_YRDAWN_METHOD_wgpuExternalTextureSetLabel = 309,
    YETTY_YRDAWN_METHOD_wgpuGetInstanceFeatures = 310,
    YETTY_YRDAWN_METHOD_wgpuGetInstanceLimits = 311,
    YETTY_YRDAWN_METHOD_wgpuGetProcAddress = 312,
    YETTY_YRDAWN_METHOD_wgpuHasInstanceFeature = 313,
    YETTY_YRDAWN_METHOD_wgpuInstanceAddRef = 314,
    YETTY_YRDAWN_METHOD_wgpuInstanceCreateSurface = 315,
    YETTY_YRDAWN_METHOD_wgpuInstanceGetWGSLLanguageFeatures = 316,
    YETTY_YRDAWN_METHOD_wgpuInstanceHasWGSLLanguageFeature = 317,
    YETTY_YRDAWN_METHOD_wgpuInstanceProcessEvents = 318,
    YETTY_YRDAWN_METHOD_wgpuInstanceWaitAny = 319,
    YETTY_YRDAWN_METHOD_wgpuPipelineLayoutAddRef = 320,
    YETTY_YRDAWN_METHOD_wgpuPipelineLayoutRelease = 321,
    YETTY_YRDAWN_METHOD_wgpuPipelineLayoutSetLabel = 322,
    YETTY_YRDAWN_METHOD_wgpuQuerySetAddRef = 323,
    YETTY_YRDAWN_METHOD_wgpuQuerySetDestroy = 324,
    YETTY_YRDAWN_METHOD_wgpuQuerySetGetCount = 325,
    YETTY_YRDAWN_METHOD_wgpuQuerySetGetType = 326,
    YETTY_YRDAWN_METHOD_wgpuQuerySetRelease = 327,
    YETTY_YRDAWN_METHOD_wgpuQuerySetSetLabel = 328,
    YETTY_YRDAWN_METHOD_wgpuQueueAddRef = 329,
    YETTY_YRDAWN_METHOD_wgpuQueueCopyExternalTextureForBrowser = 330,
    YETTY_YRDAWN_METHOD_wgpuQueueCopyTextureForBrowser = 331,
    YETTY_YRDAWN_METHOD_wgpuQueueOnSubmittedWorkDone = 332,
    YETTY_YRDAWN_METHOD_wgpuQueueSetLabel = 333,
    YETTY_YRDAWN_METHOD_wgpuQueueSubmit = 334,
    YETTY_YRDAWN_METHOD_wgpuQueueWriteBuffer = 335,
    YETTY_YRDAWN_METHOD_wgpuQueueWriteTexture = 336,
    YETTY_YRDAWN_METHOD_wgpuRenderBundleAddRef = 337,
    YETTY_YRDAWN_METHOD_wgpuRenderBundleEncoderAddRef = 338,
    YETTY_YRDAWN_METHOD_wgpuRenderBundleEncoderDraw = 339,
    YETTY_YRDAWN_METHOD_wgpuRenderBundleEncoderDrawIndexed = 340,
    YETTY_YRDAWN_METHOD_wgpuRenderBundleEncoderDrawIndexedIndirect = 341,
    YETTY_YRDAWN_METHOD_wgpuRenderBundleEncoderDrawIndirect = 342,
    YETTY_YRDAWN_METHOD_wgpuRenderBundleEncoderFinish = 343,
    YETTY_YRDAWN_METHOD_wgpuRenderBundleEncoderInsertDebugMarker = 344,
    YETTY_YRDAWN_METHOD_wgpuRenderBundleEncoderPopDebugGroup = 345,
    YETTY_YRDAWN_METHOD_wgpuRenderBundleEncoderPushDebugGroup = 346,
    YETTY_YRDAWN_METHOD_wgpuRenderBundleEncoderRelease = 347,
    YETTY_YRDAWN_METHOD_wgpuRenderBundleEncoderSetBindGroup = 348,
    YETTY_YRDAWN_METHOD_wgpuRenderBundleEncoderSetImmediates = 349,
    YETTY_YRDAWN_METHOD_wgpuRenderBundleEncoderSetIndexBuffer = 350,
    YETTY_YRDAWN_METHOD_wgpuRenderBundleEncoderSetLabel = 351,
    YETTY_YRDAWN_METHOD_wgpuRenderBundleEncoderSetPipeline = 352,
    YETTY_YRDAWN_METHOD_wgpuRenderBundleEncoderSetResourceTable = 353,
    YETTY_YRDAWN_METHOD_wgpuRenderBundleEncoderSetVertexBuffer = 354,
    YETTY_YRDAWN_METHOD_wgpuRenderBundleRelease = 355,
    YETTY_YRDAWN_METHOD_wgpuRenderBundleSetLabel = 356,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderAddRef = 357,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderBeginOcclusionQuery = 358,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderDraw = 359,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderDrawIndexed = 360,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderDrawIndexedIndirect = 361,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderDrawIndirect = 362,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderEnd = 363,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderEndOcclusionQuery = 364,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderExecuteBundles = 365,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderInsertDebugMarker = 366,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderMultiDrawIndexedIndirect = 367,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderMultiDrawIndirect = 368,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderPixelLocalStorageBarrier = 369,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderPopDebugGroup = 370,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderPushDebugGroup = 371,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderRelease = 372,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderSetBindGroup = 373,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderSetBlendConstant = 374,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderSetImmediates = 375,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderSetIndexBuffer = 376,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderSetLabel = 377,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderSetPipeline = 378,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderSetResourceTable = 379,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderSetScissorRect = 380,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderSetStencilReference = 381,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderSetVertexBuffer = 382,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderSetViewport = 383,
    YETTY_YRDAWN_METHOD_wgpuRenderPassEncoderWriteTimestamp = 384,
    YETTY_YRDAWN_METHOD_wgpuRenderPipelineAddRef = 385,
    YETTY_YRDAWN_METHOD_wgpuRenderPipelineGetBindGroupLayout = 386,
    YETTY_YRDAWN_METHOD_wgpuRenderPipelineRelease = 387,
    YETTY_YRDAWN_METHOD_wgpuRenderPipelineSetLabel = 388,
    YETTY_YRDAWN_METHOD_wgpuResourceTableAddRef = 389,
    YETTY_YRDAWN_METHOD_wgpuResourceTableDestroy = 390,
    YETTY_YRDAWN_METHOD_wgpuResourceTableGetSize = 391,
    YETTY_YRDAWN_METHOD_wgpuResourceTableInsertBinding = 392,
    YETTY_YRDAWN_METHOD_wgpuResourceTableRelease = 393,
    YETTY_YRDAWN_METHOD_wgpuResourceTableRemoveBinding = 394,
    YETTY_YRDAWN_METHOD_wgpuResourceTableUpdate = 395,
    YETTY_YRDAWN_METHOD_wgpuSamplerAddRef = 396,
    YETTY_YRDAWN_METHOD_wgpuSamplerRelease = 397,
    YETTY_YRDAWN_METHOD_wgpuSamplerSetLabel = 398,
    YETTY_YRDAWN_METHOD_wgpuShaderModuleAddRef = 399,
    YETTY_YRDAWN_METHOD_wgpuShaderModuleGetCompilationInfo = 400,
    YETTY_YRDAWN_METHOD_wgpuShaderModuleRelease = 401,
    YETTY_YRDAWN_METHOD_wgpuShaderModuleSetLabel = 402,
    YETTY_YRDAWN_METHOD_wgpuSharedBufferMemoryAddRef = 403,
    YETTY_YRDAWN_METHOD_wgpuSharedBufferMemoryBeginAccess = 404,
    YETTY_YRDAWN_METHOD_wgpuSharedBufferMemoryCreateBuffer = 405,
    YETTY_YRDAWN_METHOD_wgpuSharedBufferMemoryEndAccess = 406,
    YETTY_YRDAWN_METHOD_wgpuSharedBufferMemoryEndAccessStateFreeMembers = 407,
    YETTY_YRDAWN_METHOD_wgpuSharedBufferMemoryGetProperties = 408,
    YETTY_YRDAWN_METHOD_wgpuSharedBufferMemoryIsDeviceLost = 409,
    YETTY_YRDAWN_METHOD_wgpuSharedBufferMemoryRelease = 410,
    YETTY_YRDAWN_METHOD_wgpuSharedBufferMemorySetLabel = 411,
    YETTY_YRDAWN_METHOD_wgpuSharedFenceAddRef = 412,
    YETTY_YRDAWN_METHOD_wgpuSharedFenceExportInfo = 413,
    YETTY_YRDAWN_METHOD_wgpuSharedFenceRelease = 414,
    YETTY_YRDAWN_METHOD_wgpuSharedFenceSetLabel = 415,
    YETTY_YRDAWN_METHOD_wgpuSharedTextureMemoryAddRef = 416,
    YETTY_YRDAWN_METHOD_wgpuSharedTextureMemoryBeginAccess = 417,
    YETTY_YRDAWN_METHOD_wgpuSharedTextureMemoryCreateTexture = 418,
    YETTY_YRDAWN_METHOD_wgpuSharedTextureMemoryEndAccess = 419,
    YETTY_YRDAWN_METHOD_wgpuSharedTextureMemoryEndAccessStateFreeMembers = 420,
    YETTY_YRDAWN_METHOD_wgpuSharedTextureMemoryGetProperties = 421,
    YETTY_YRDAWN_METHOD_wgpuSharedTextureMemoryIsDeviceLost = 422,
    YETTY_YRDAWN_METHOD_wgpuSharedTextureMemoryRelease = 423,
    YETTY_YRDAWN_METHOD_wgpuSharedTextureMemorySetLabel = 424,
    YETTY_YRDAWN_METHOD_wgpuSupportedFeaturesFreeMembers = 425,
    YETTY_YRDAWN_METHOD_wgpuSupportedInstanceFeaturesFreeMembers = 426,
    YETTY_YRDAWN_METHOD_wgpuSupportedWGSLLanguageFeaturesFreeMembers = 427,
    YETTY_YRDAWN_METHOD_wgpuSurfaceAddRef = 428,
    YETTY_YRDAWN_METHOD_wgpuSurfaceCapabilitiesFreeMembers = 429,
    YETTY_YRDAWN_METHOD_wgpuSurfaceConfigure = 430,
    YETTY_YRDAWN_METHOD_wgpuSurfaceGetCapabilities = 431,
    YETTY_YRDAWN_METHOD_wgpuSurfaceGetCurrentTexture = 432,
    YETTY_YRDAWN_METHOD_wgpuSurfacePresent = 433,
    YETTY_YRDAWN_METHOD_wgpuSurfaceRelease = 434,
    YETTY_YRDAWN_METHOD_wgpuSurfaceSetLabel = 435,
    YETTY_YRDAWN_METHOD_wgpuSurfaceUnconfigure = 436,
    YETTY_YRDAWN_METHOD_wgpuTexelBufferViewAddRef = 437,
    YETTY_YRDAWN_METHOD_wgpuTexelBufferViewRelease = 438,
    YETTY_YRDAWN_METHOD_wgpuTexelBufferViewSetLabel = 439,
    YETTY_YRDAWN_METHOD_wgpuTextureAddRef = 440,
    YETTY_YRDAWN_METHOD_wgpuTextureCreateErrorView = 441,
    YETTY_YRDAWN_METHOD_wgpuTextureCreateView = 442,
    YETTY_YRDAWN_METHOD_wgpuTextureDestroy = 443,
    YETTY_YRDAWN_METHOD_wgpuTextureGetDepthOrArrayLayers = 444,
    YETTY_YRDAWN_METHOD_wgpuTextureGetDimension = 445,
    YETTY_YRDAWN_METHOD_wgpuTextureGetFormat = 446,
    YETTY_YRDAWN_METHOD_wgpuTextureGetHeight = 447,
    YETTY_YRDAWN_METHOD_wgpuTextureGetMipLevelCount = 448,
    YETTY_YRDAWN_METHOD_wgpuTextureGetSampleCount = 449,
    YETTY_YRDAWN_METHOD_wgpuTextureGetTextureBindingViewDimension = 450,
    YETTY_YRDAWN_METHOD_wgpuTextureGetUsage = 451,
    YETTY_YRDAWN_METHOD_wgpuTextureGetWidth = 452,
    YETTY_YRDAWN_METHOD_wgpuTexturePin = 453,
    YETTY_YRDAWN_METHOD_wgpuTextureRelease = 454,
    YETTY_YRDAWN_METHOD_wgpuTextureSetLabel = 455,
    YETTY_YRDAWN_METHOD_wgpuTextureSetOwnershipForMemoryDump = 456,
    YETTY_YRDAWN_METHOD_wgpuTextureUnpin = 457,
    YETTY_YRDAWN_METHOD_wgpuTextureViewAddRef = 458,
    YETTY_YRDAWN_METHOD_wgpuTextureViewRelease = 459,
    YETTY_YRDAWN_METHOD_wgpuTextureViewSetLabel = 460,
};

struct yrdawn_args_wgpuCreateInstance {
    uint64_t result_handle;
};

struct yrdawn_args_wgpuInstanceRelease {
    uint64_t instance;
};

struct yrdawn_args_wgpuDeviceTick {
    uint64_t device;
};

struct yrdawn_args_wgpuDeviceGetQueue {
    uint64_t device;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuQueueRelease {
    uint64_t queue;
};

struct yrdawn_args_wgpuDeviceRelease {
    uint64_t device;
};

struct yrdawn_args_wgpuAdapterRelease {
    uint64_t adapter;
};

struct yrdawn_args_wgpuDeviceCreateCommandEncoder {
    uint64_t device;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuCommandEncoderRelease {
    uint64_t encoder;
};

struct yrdawn_args_wgpuCommandEncoderFinish {
    uint64_t encoder;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuCommandBufferRelease {
    uint64_t buffer;
};

struct yrdawn_args_wgpuInstanceRequestAdapter {
    uint64_t instance;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuAdapterRequestDevice {
    uint64_t adapter;
    uint64_t result_handle;
};

struct yrdawn_args_yetty_yrdawn_present_frame {
    uint32_t width;
    uint32_t height;
    uint32_t format;
    uint32_t payload_ref;
};

struct yrdawn_args_wgpuAdapterAddRef {
    uint64_t adapter;
};

struct yrdawn_args_wgpuAdapterCreateDevice {
    uint64_t adapter;
    WGPUDeviceDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuAdapterGetFeatures {
    uint64_t adapter;
    WGPUSupportedFeatures features;
};

struct yrdawn_args_wgpuAdapterGetFormatCapabilities {
    uint64_t adapter;
    uint32_t format;
    WGPUDawnFormatCapabilities capabilities;
};

struct yrdawn_args_wgpuAdapterGetInfo {
    uint64_t adapter;
    WGPUAdapterInfo info;
};

struct yrdawn_args_wgpuAdapterGetInstance {
    uint64_t adapter;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuAdapterGetLimits {
    uint64_t adapter;
    WGPULimits limits;
};

struct yrdawn_args_wgpuAdapterHasFeature {
    uint64_t adapter;
    uint32_t feature;
};

struct yrdawn_args_wgpuAdapterInfoFreeMembers {
    uint64_t adapterInfo;
};

struct yrdawn_args_wgpuAdapterPropertiesMemoryHeapsFreeMembers {
    uint64_t adapterPropertiesMemoryHeaps;
};

struct yrdawn_args_wgpuAdapterPropertiesSubgroupMatrixConfigsFreeMembers {
    uint64_t adapterPropertiesSubgroupMatrixConfigs;
};

struct yrdawn_args_wgpuBindGroupAddRef {
    uint64_t bindGroup;
};

struct yrdawn_args_wgpuBindGroupLayoutAddRef {
    uint64_t bindGroupLayout;
};

struct yrdawn_args_wgpuBindGroupLayoutRelease {
    uint64_t bindGroupLayout;
};

struct yrdawn_args_wgpuBindGroupLayoutSetLabel {
    uint64_t bindGroupLayout;
    WGPUStringView label;
};

struct yrdawn_args_wgpuBindGroupRelease {
    uint64_t bindGroup;
};

struct yrdawn_args_wgpuBindGroupSetLabel {
    uint64_t bindGroup;
    WGPUStringView label;
};

struct yrdawn_args_wgpuBufferAddRef {
    uint64_t buffer;
};

struct yrdawn_args_wgpuBufferCreateTexelView {
    uint64_t buffer;
    WGPUTexelBufferViewDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuBufferDestroy {
    uint64_t buffer;
};

struct yrdawn_args_wgpuBufferGetMapState {
    uint64_t buffer;
};

struct yrdawn_args_wgpuBufferGetSize {
    uint64_t buffer;
};

struct yrdawn_args_wgpuBufferGetUsage {
    uint64_t buffer;
};

struct yrdawn_args_wgpuBufferMapAsync {
    uint64_t buffer;
    uint32_t mode;
    size_t offset;
    size_t size;
    WGPUBufferMapCallbackInfo callbackInfo;
};

struct yrdawn_args_wgpuBufferReadMappedRange {
    uint64_t buffer;
    size_t offset;
    size_t size;
    uint8_t data;
};

struct yrdawn_args_wgpuBufferRelease {
    uint64_t buffer;
};

struct yrdawn_args_wgpuBufferSetLabel {
    uint64_t buffer;
    WGPUStringView label;
};

struct yrdawn_args_wgpuBufferUnmap {
    uint64_t buffer;
};

struct yrdawn_args_wgpuBufferWriteMappedRange {
    uint64_t buffer;
    size_t offset;
    size_t size;
    uint8_t data;
};

struct yrdawn_args_wgpuCommandBufferAddRef {
    uint64_t commandBuffer;
};

struct yrdawn_args_wgpuCommandBufferSetLabel {
    uint64_t commandBuffer;
    WGPUStringView label;
};

struct yrdawn_args_wgpuCommandEncoderAddRef {
    uint64_t commandEncoder;
};

struct yrdawn_args_wgpuCommandEncoderBeginComputePass {
    uint64_t commandEncoder;
    WGPUComputePassDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuCommandEncoderBeginRenderPass {
    uint64_t commandEncoder;
    WGPURenderPassDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuCommandEncoderClearBuffer {
    uint64_t commandEncoder;
    uint64_t buffer;
    uint64_t offset;
    uint64_t size;
};

struct yrdawn_args_wgpuCommandEncoderCopyBufferToBuffer {
    uint64_t commandEncoder;
    uint64_t source;
    uint64_t sourceOffset;
    uint64_t destination;
    uint64_t destinationOffset;
    uint64_t size;
};

struct yrdawn_args_wgpuCommandEncoderCopyBufferToTexture {
    uint64_t commandEncoder;
    WGPUTexelCopyBufferInfo source;
    WGPUTexelCopyTextureInfo destination;
    uint32_t copySize_present;
    WGPUExtent3D copySize;
};

struct yrdawn_args_wgpuCommandEncoderCopyTextureToBuffer {
    uint64_t commandEncoder;
    WGPUTexelCopyTextureInfo source;
    WGPUTexelCopyBufferInfo destination;
    uint32_t copySize_present;
    WGPUExtent3D copySize;
};

struct yrdawn_args_wgpuCommandEncoderCopyTextureToTexture {
    uint64_t commandEncoder;
    WGPUTexelCopyTextureInfo source;
    WGPUTexelCopyTextureInfo destination;
    uint32_t copySize_present;
    WGPUExtent3D copySize;
};

struct yrdawn_args_wgpuCommandEncoderInjectValidationError {
    uint64_t commandEncoder;
    WGPUStringView message;
};

struct yrdawn_args_wgpuCommandEncoderInsertDebugMarker {
    uint64_t commandEncoder;
    WGPUStringView markerLabel;
};

struct yrdawn_args_wgpuCommandEncoderPopDebugGroup {
    uint64_t commandEncoder;
};

struct yrdawn_args_wgpuCommandEncoderPushDebugGroup {
    uint64_t commandEncoder;
    WGPUStringView groupLabel;
};

struct yrdawn_args_wgpuCommandEncoderResolveQuerySet {
    uint64_t commandEncoder;
    uint64_t querySet;
    uint32_t firstQuery;
    uint32_t queryCount;
    uint64_t destination;
    uint64_t destinationOffset;
};

struct yrdawn_args_wgpuCommandEncoderSetLabel {
    uint64_t commandEncoder;
    WGPUStringView label;
};

struct yrdawn_args_wgpuCommandEncoderWriteBuffer {
    uint64_t commandEncoder;
    uint64_t buffer;
    uint64_t bufferOffset;
    size_t size;
    uint8_t data;
};

struct yrdawn_args_wgpuCommandEncoderWriteTimestamp {
    uint64_t commandEncoder;
    uint64_t querySet;
    uint32_t queryIndex;
};

struct yrdawn_args_wgpuComputePassEncoderAddRef {
    uint64_t computePassEncoder;
};

struct yrdawn_args_wgpuComputePassEncoderDispatchWorkgroups {
    uint64_t computePassEncoder;
    uint32_t workgroupCountX;
    uint32_t workgroupCountY;
    uint32_t workgroupCountZ;
};

struct yrdawn_args_wgpuComputePassEncoderDispatchWorkgroupsIndirect {
    uint64_t computePassEncoder;
    uint64_t indirectBuffer;
    uint64_t indirectOffset;
};

struct yrdawn_args_wgpuComputePassEncoderEnd {
    uint64_t computePassEncoder;
};

struct yrdawn_args_wgpuComputePassEncoderInsertDebugMarker {
    uint64_t computePassEncoder;
    WGPUStringView markerLabel;
};

struct yrdawn_args_wgpuComputePassEncoderPopDebugGroup {
    uint64_t computePassEncoder;
};

struct yrdawn_args_wgpuComputePassEncoderPushDebugGroup {
    uint64_t computePassEncoder;
    WGPUStringView groupLabel;
};

struct yrdawn_args_wgpuComputePassEncoderRelease {
    uint64_t computePassEncoder;
};

struct yrdawn_args_wgpuComputePassEncoderSetBindGroup {
    uint64_t computePassEncoder;
    uint32_t groupIndex;
    uint64_t group;
    size_t dynamicOffsetCount;
    uint32_t dynamicOffsets;
};

struct yrdawn_args_wgpuComputePassEncoderSetImmediates {
    uint64_t computePassEncoder;
    uint32_t offset;
    size_t size;
    uint8_t data;
};

struct yrdawn_args_wgpuComputePassEncoderSetLabel {
    uint64_t computePassEncoder;
    WGPUStringView label;
};

struct yrdawn_args_wgpuComputePassEncoderSetPipeline {
    uint64_t computePassEncoder;
    uint64_t pipeline;
};

struct yrdawn_args_wgpuComputePassEncoderSetResourceTable {
    uint64_t computePassEncoder;
    uint64_t table;
};

struct yrdawn_args_wgpuComputePassEncoderWriteTimestamp {
    uint64_t computePassEncoder;
    uint64_t querySet;
    uint32_t queryIndex;
};

struct yrdawn_args_wgpuComputePipelineAddRef {
    uint64_t computePipeline;
};

struct yrdawn_args_wgpuComputePipelineGetBindGroupLayout {
    uint64_t computePipeline;
    uint32_t groupIndex;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuComputePipelineRelease {
    uint64_t computePipeline;
};

struct yrdawn_args_wgpuComputePipelineSetLabel {
    uint64_t computePipeline;
    WGPUStringView label;
};

struct yrdawn_args_wgpuDawnDrmFormatCapabilitiesFreeMembers {
    uint64_t dawnDrmFormatCapabilities;
};

struct yrdawn_args_wgpuDeviceAddRef {
    uint64_t device;
};

struct yrdawn_args_wgpuDeviceCreateBindGroup {
    uint64_t device;
    WGPUBindGroupDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuDeviceCreateBindGroupLayout {
    uint64_t device;
    WGPUBindGroupLayoutDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuDeviceCreateBuffer {
    uint64_t device;
    WGPUBufferDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuDeviceCreateComputePipeline {
    uint64_t device;
    WGPUComputePipelineDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuDeviceCreateComputePipelineAsync {
    uint64_t device;
    WGPUComputePipelineDescriptor descriptor;
    WGPUCreateComputePipelineAsyncCallbackInfo callbackInfo;
};

struct yrdawn_args_wgpuDeviceCreateErrorBuffer {
    uint64_t device;
    WGPUBufferDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuDeviceCreateErrorExternalTexture {
    uint64_t device;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuDeviceCreateErrorShaderModule {
    uint64_t device;
    WGPUShaderModuleDescriptor descriptor;
    WGPUStringView errorMessage;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuDeviceCreateErrorTexture {
    uint64_t device;
    WGPUTextureDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuDeviceCreateExternalTexture {
    uint64_t device;
    WGPUExternalTextureDescriptor externalTextureDescriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuDeviceCreatePipelineLayout {
    uint64_t device;
    WGPUPipelineLayoutDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuDeviceCreateQuerySet {
    uint64_t device;
    WGPUQuerySetDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuDeviceCreateRenderBundleEncoder {
    uint64_t device;
    WGPURenderBundleEncoderDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuDeviceCreateRenderPipeline {
    uint64_t device;
    WGPURenderPipelineDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuDeviceCreateRenderPipelineAsync {
    uint64_t device;
    WGPURenderPipelineDescriptor descriptor;
    WGPUCreateRenderPipelineAsyncCallbackInfo callbackInfo;
};

struct yrdawn_args_wgpuDeviceCreateResourceTable {
    uint64_t device;
    WGPUResourceTableDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuDeviceCreateSampler {
    uint64_t device;
    WGPUSamplerDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuDeviceCreateShaderModule {
    uint64_t device;
    WGPUShaderModuleDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuDeviceCreateTexture {
    uint64_t device;
    WGPUTextureDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuDeviceDestroy {
    uint64_t device;
};

struct yrdawn_args_wgpuDeviceForceLoss {
    uint64_t device;
    uint32_t type;
    WGPUStringView message;
};

struct yrdawn_args_wgpuDeviceGetAHardwareBufferProperties {
    uint64_t device;
    uint64_t handle;
    WGPUAHardwareBufferProperties properties;
};

struct yrdawn_args_wgpuDeviceGetAdapter {
    uint64_t device;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuDeviceGetAdapterInfo {
    uint64_t device;
    WGPUAdapterInfo adapterInfo;
};

struct yrdawn_args_wgpuDeviceGetFeatures {
    uint64_t device;
    WGPUSupportedFeatures features;
};

struct yrdawn_args_wgpuDeviceGetLimits {
    uint64_t device;
    WGPULimits limits;
};

struct yrdawn_args_wgpuDeviceGetLostFuture {
    uint64_t device;
};

struct yrdawn_args_wgpuDeviceHasFeature {
    uint64_t device;
    uint32_t feature;
};

struct yrdawn_args_wgpuDeviceImportSharedBufferMemory {
    uint64_t device;
    WGPUSharedBufferMemoryDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuDeviceImportSharedFence {
    uint64_t device;
    WGPUSharedFenceDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuDeviceImportSharedTextureMemory {
    uint64_t device;
    WGPUSharedTextureMemoryDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuDeviceInjectError {
    uint64_t device;
    uint32_t type;
    WGPUStringView message;
};

struct yrdawn_args_wgpuDevicePopErrorScope {
    uint64_t device;
    WGPUPopErrorScopeCallbackInfo callbackInfo;
};

struct yrdawn_args_wgpuDevicePushErrorScope {
    uint64_t device;
    uint32_t filter;
};

struct yrdawn_args_wgpuDeviceSetLabel {
    uint64_t device;
    WGPUStringView label;
};

struct yrdawn_args_wgpuDeviceSetLoggingCallback {
    uint64_t device;
    WGPULoggingCallbackInfo callbackInfo;
};

struct yrdawn_args_wgpuDeviceValidateTextureDescriptor {
    uint64_t device;
    WGPUTextureDescriptor descriptor;
};

struct yrdawn_args_wgpuExternalTextureAddRef {
    uint64_t externalTexture;
};

struct yrdawn_args_wgpuExternalTextureDestroy {
    uint64_t externalTexture;
};

struct yrdawn_args_wgpuExternalTextureExpire {
    uint64_t externalTexture;
};

struct yrdawn_args_wgpuExternalTextureRefresh {
    uint64_t externalTexture;
};

struct yrdawn_args_wgpuExternalTextureRelease {
    uint64_t externalTexture;
};

struct yrdawn_args_wgpuExternalTextureSetLabel {
    uint64_t externalTexture;
    WGPUStringView label;
};

struct yrdawn_args_wgpuGetInstanceFeatures {
    WGPUSupportedInstanceFeatures features;
};

struct yrdawn_args_wgpuGetInstanceLimits {
    WGPUInstanceLimits limits;
};

struct yrdawn_args_wgpuGetProcAddress {
    WGPUStringView procName;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuHasInstanceFeature {
    uint32_t feature;
};

struct yrdawn_args_wgpuInstanceAddRef {
    uint64_t instance;
};

struct yrdawn_args_wgpuInstanceCreateSurface {
    uint64_t instance;
    WGPUSurfaceDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuInstanceGetWGSLLanguageFeatures {
    uint64_t instance;
    WGPUSupportedWGSLLanguageFeatures features;
};

struct yrdawn_args_wgpuInstanceHasWGSLLanguageFeature {
    uint64_t instance;
    uint32_t feature;
};

struct yrdawn_args_wgpuInstanceProcessEvents {
    uint64_t instance;
};

struct yrdawn_args_wgpuInstanceWaitAny {
    uint64_t instance;
    size_t futureCount;
    uint32_t futures_present;
    WGPUFutureWaitInfo futures;
    uint64_t timeoutNS;
};

struct yrdawn_args_wgpuPipelineLayoutAddRef {
    uint64_t pipelineLayout;
};

struct yrdawn_args_wgpuPipelineLayoutRelease {
    uint64_t pipelineLayout;
};

struct yrdawn_args_wgpuPipelineLayoutSetLabel {
    uint64_t pipelineLayout;
    WGPUStringView label;
};

struct yrdawn_args_wgpuQuerySetAddRef {
    uint64_t querySet;
};

struct yrdawn_args_wgpuQuerySetDestroy {
    uint64_t querySet;
};

struct yrdawn_args_wgpuQuerySetGetCount {
    uint64_t querySet;
};

struct yrdawn_args_wgpuQuerySetGetType {
    uint64_t querySet;
};

struct yrdawn_args_wgpuQuerySetRelease {
    uint64_t querySet;
};

struct yrdawn_args_wgpuQuerySetSetLabel {
    uint64_t querySet;
    WGPUStringView label;
};

struct yrdawn_args_wgpuQueueAddRef {
    uint64_t queue;
};

struct yrdawn_args_wgpuQueueCopyExternalTextureForBrowser {
    uint64_t queue;
    WGPUImageCopyExternalTexture source;
    WGPUTexelCopyTextureInfo destination;
    uint32_t copySize_present;
    WGPUExtent3D copySize;
    WGPUCopyTextureForBrowserOptions options;
};

struct yrdawn_args_wgpuQueueCopyTextureForBrowser {
    uint64_t queue;
    WGPUTexelCopyTextureInfo source;
    WGPUTexelCopyTextureInfo destination;
    uint32_t copySize_present;
    WGPUExtent3D copySize;
    WGPUCopyTextureForBrowserOptions options;
};

struct yrdawn_args_wgpuQueueOnSubmittedWorkDone {
    uint64_t queue;
    WGPUQueueWorkDoneCallbackInfo callbackInfo;
};

struct yrdawn_args_wgpuQueueSetLabel {
    uint64_t queue;
    WGPUStringView label;
};

struct yrdawn_args_wgpuQueueSubmit {
    uint64_t queue;
    size_t commandCount;
    WGPUCommandBuffer commands;
};

struct yrdawn_args_wgpuQueueWriteBuffer {
    uint64_t queue;
    uint64_t buffer;
    uint64_t bufferOffset;
    size_t size;
    uint8_t data;
};

struct yrdawn_args_wgpuQueueWriteTexture {
    uint64_t queue;
    WGPUTexelCopyTextureInfo destination;
    size_t dataSize;
    uint8_t data;
    uint32_t dataLayout_present;
    WGPUTexelCopyBufferLayout dataLayout;
    uint32_t writeSize_present;
    WGPUExtent3D writeSize;
};

struct yrdawn_args_wgpuRenderBundleAddRef {
    uint64_t renderBundle;
};

struct yrdawn_args_wgpuRenderBundleEncoderAddRef {
    uint64_t renderBundleEncoder;
};

struct yrdawn_args_wgpuRenderBundleEncoderDraw {
    uint64_t renderBundleEncoder;
    uint32_t vertexCount;
    uint32_t instanceCount;
    uint32_t firstVertex;
    uint32_t firstInstance;
};

struct yrdawn_args_wgpuRenderBundleEncoderDrawIndexed {
    uint64_t renderBundleEncoder;
    uint32_t indexCount;
    uint32_t instanceCount;
    uint32_t firstIndex;
    int32_t baseVertex;
    uint32_t firstInstance;
};

struct yrdawn_args_wgpuRenderBundleEncoderDrawIndexedIndirect {
    uint64_t renderBundleEncoder;
    uint64_t indirectBuffer;
    uint64_t indirectOffset;
};

struct yrdawn_args_wgpuRenderBundleEncoderDrawIndirect {
    uint64_t renderBundleEncoder;
    uint64_t indirectBuffer;
    uint64_t indirectOffset;
};

struct yrdawn_args_wgpuRenderBundleEncoderFinish {
    uint64_t renderBundleEncoder;
    WGPURenderBundleDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuRenderBundleEncoderInsertDebugMarker {
    uint64_t renderBundleEncoder;
    WGPUStringView markerLabel;
};

struct yrdawn_args_wgpuRenderBundleEncoderPopDebugGroup {
    uint64_t renderBundleEncoder;
};

struct yrdawn_args_wgpuRenderBundleEncoderPushDebugGroup {
    uint64_t renderBundleEncoder;
    WGPUStringView groupLabel;
};

struct yrdawn_args_wgpuRenderBundleEncoderRelease {
    uint64_t renderBundleEncoder;
};

struct yrdawn_args_wgpuRenderBundleEncoderSetBindGroup {
    uint64_t renderBundleEncoder;
    uint32_t groupIndex;
    uint64_t group;
    size_t dynamicOffsetCount;
    uint32_t dynamicOffsets;
};

struct yrdawn_args_wgpuRenderBundleEncoderSetImmediates {
    uint64_t renderBundleEncoder;
    uint32_t offset;
    size_t size;
    uint8_t data;
};

struct yrdawn_args_wgpuRenderBundleEncoderSetIndexBuffer {
    uint64_t renderBundleEncoder;
    uint64_t buffer;
    uint32_t format;
    uint64_t offset;
    uint64_t size;
};

struct yrdawn_args_wgpuRenderBundleEncoderSetLabel {
    uint64_t renderBundleEncoder;
    WGPUStringView label;
};

struct yrdawn_args_wgpuRenderBundleEncoderSetPipeline {
    uint64_t renderBundleEncoder;
    uint64_t pipeline;
};

struct yrdawn_args_wgpuRenderBundleEncoderSetResourceTable {
    uint64_t renderBundleEncoder;
    uint64_t table;
};

struct yrdawn_args_wgpuRenderBundleEncoderSetVertexBuffer {
    uint64_t renderBundleEncoder;
    uint32_t slot;
    uint64_t buffer;
    uint64_t offset;
    uint64_t size;
};

struct yrdawn_args_wgpuRenderBundleRelease {
    uint64_t renderBundle;
};

struct yrdawn_args_wgpuRenderBundleSetLabel {
    uint64_t renderBundle;
    WGPUStringView label;
};

struct yrdawn_args_wgpuRenderPassEncoderAddRef {
    uint64_t renderPassEncoder;
};

struct yrdawn_args_wgpuRenderPassEncoderBeginOcclusionQuery {
    uint64_t renderPassEncoder;
    uint32_t queryIndex;
};

struct yrdawn_args_wgpuRenderPassEncoderDraw {
    uint64_t renderPassEncoder;
    uint32_t vertexCount;
    uint32_t instanceCount;
    uint32_t firstVertex;
    uint32_t firstInstance;
};

struct yrdawn_args_wgpuRenderPassEncoderDrawIndexed {
    uint64_t renderPassEncoder;
    uint32_t indexCount;
    uint32_t instanceCount;
    uint32_t firstIndex;
    int32_t baseVertex;
    uint32_t firstInstance;
};

struct yrdawn_args_wgpuRenderPassEncoderDrawIndexedIndirect {
    uint64_t renderPassEncoder;
    uint64_t indirectBuffer;
    uint64_t indirectOffset;
};

struct yrdawn_args_wgpuRenderPassEncoderDrawIndirect {
    uint64_t renderPassEncoder;
    uint64_t indirectBuffer;
    uint64_t indirectOffset;
};

struct yrdawn_args_wgpuRenderPassEncoderEnd {
    uint64_t renderPassEncoder;
};

struct yrdawn_args_wgpuRenderPassEncoderEndOcclusionQuery {
    uint64_t renderPassEncoder;
};

struct yrdawn_args_wgpuRenderPassEncoderExecuteBundles {
    uint64_t renderPassEncoder;
    size_t bundleCount;
    WGPURenderBundle bundles;
};

struct yrdawn_args_wgpuRenderPassEncoderInsertDebugMarker {
    uint64_t renderPassEncoder;
    WGPUStringView markerLabel;
};

struct yrdawn_args_wgpuRenderPassEncoderMultiDrawIndexedIndirect {
    uint64_t renderPassEncoder;
    uint64_t indirectBuffer;
    uint64_t indirectOffset;
    uint32_t maxDrawCount;
    uint64_t drawCountBuffer;
    uint64_t drawCountBufferOffset;
};

struct yrdawn_args_wgpuRenderPassEncoderMultiDrawIndirect {
    uint64_t renderPassEncoder;
    uint64_t indirectBuffer;
    uint64_t indirectOffset;
    uint32_t maxDrawCount;
    uint64_t drawCountBuffer;
    uint64_t drawCountBufferOffset;
};

struct yrdawn_args_wgpuRenderPassEncoderPixelLocalStorageBarrier {
    uint64_t renderPassEncoder;
};

struct yrdawn_args_wgpuRenderPassEncoderPopDebugGroup {
    uint64_t renderPassEncoder;
};

struct yrdawn_args_wgpuRenderPassEncoderPushDebugGroup {
    uint64_t renderPassEncoder;
    WGPUStringView groupLabel;
};

struct yrdawn_args_wgpuRenderPassEncoderRelease {
    uint64_t renderPassEncoder;
};

struct yrdawn_args_wgpuRenderPassEncoderSetBindGroup {
    uint64_t renderPassEncoder;
    uint32_t groupIndex;
    uint64_t group;
    size_t dynamicOffsetCount;
    uint32_t dynamicOffsets;
};

struct yrdawn_args_wgpuRenderPassEncoderSetBlendConstant {
    uint64_t renderPassEncoder;
    uint32_t color_present;
    WGPUColor color;
};

struct yrdawn_args_wgpuRenderPassEncoderSetImmediates {
    uint64_t renderPassEncoder;
    uint32_t offset;
    size_t size;
    uint8_t data;
};

struct yrdawn_args_wgpuRenderPassEncoderSetIndexBuffer {
    uint64_t renderPassEncoder;
    uint64_t buffer;
    uint32_t format;
    uint64_t offset;
    uint64_t size;
};

struct yrdawn_args_wgpuRenderPassEncoderSetLabel {
    uint64_t renderPassEncoder;
    WGPUStringView label;
};

struct yrdawn_args_wgpuRenderPassEncoderSetPipeline {
    uint64_t renderPassEncoder;
    uint64_t pipeline;
};

struct yrdawn_args_wgpuRenderPassEncoderSetResourceTable {
    uint64_t renderPassEncoder;
    uint64_t table;
};

struct yrdawn_args_wgpuRenderPassEncoderSetScissorRect {
    uint64_t renderPassEncoder;
    uint32_t x;
    uint32_t y;
    uint32_t width;
    uint32_t height;
};

struct yrdawn_args_wgpuRenderPassEncoderSetStencilReference {
    uint64_t renderPassEncoder;
    uint32_t reference;
};

struct yrdawn_args_wgpuRenderPassEncoderSetVertexBuffer {
    uint64_t renderPassEncoder;
    uint32_t slot;
    uint64_t buffer;
    uint64_t offset;
    uint64_t size;
};

struct yrdawn_args_wgpuRenderPassEncoderSetViewport {
    uint64_t renderPassEncoder;
    float x;
    float y;
    float width;
    float height;
    float minDepth;
    float maxDepth;
};

struct yrdawn_args_wgpuRenderPassEncoderWriteTimestamp {
    uint64_t renderPassEncoder;
    uint64_t querySet;
    uint32_t queryIndex;
};

struct yrdawn_args_wgpuRenderPipelineAddRef {
    uint64_t renderPipeline;
};

struct yrdawn_args_wgpuRenderPipelineGetBindGroupLayout {
    uint64_t renderPipeline;
    uint32_t groupIndex;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuRenderPipelineRelease {
    uint64_t renderPipeline;
};

struct yrdawn_args_wgpuRenderPipelineSetLabel {
    uint64_t renderPipeline;
    WGPUStringView label;
};

struct yrdawn_args_wgpuResourceTableAddRef {
    uint64_t resourceTable;
};

struct yrdawn_args_wgpuResourceTableDestroy {
    uint64_t resourceTable;
};

struct yrdawn_args_wgpuResourceTableGetSize {
    uint64_t resourceTable;
};

struct yrdawn_args_wgpuResourceTableInsertBinding {
    uint64_t resourceTable;
    WGPUBindingResource resource;
};

struct yrdawn_args_wgpuResourceTableRelease {
    uint64_t resourceTable;
};

struct yrdawn_args_wgpuResourceTableRemoveBinding {
    uint64_t resourceTable;
    uint32_t slot;
};

struct yrdawn_args_wgpuResourceTableUpdate {
    uint64_t resourceTable;
    uint32_t slot;
    WGPUBindingResource resource;
};

struct yrdawn_args_wgpuSamplerAddRef {
    uint64_t sampler;
};

struct yrdawn_args_wgpuSamplerRelease {
    uint64_t sampler;
};

struct yrdawn_args_wgpuSamplerSetLabel {
    uint64_t sampler;
    WGPUStringView label;
};

struct yrdawn_args_wgpuShaderModuleAddRef {
    uint64_t shaderModule;
};

struct yrdawn_args_wgpuShaderModuleGetCompilationInfo {
    uint64_t shaderModule;
    WGPUCompilationInfoCallbackInfo callbackInfo;
};

struct yrdawn_args_wgpuShaderModuleRelease {
    uint64_t shaderModule;
};

struct yrdawn_args_wgpuShaderModuleSetLabel {
    uint64_t shaderModule;
    WGPUStringView label;
};

struct yrdawn_args_wgpuSharedBufferMemoryAddRef {
    uint64_t sharedBufferMemory;
};

struct yrdawn_args_wgpuSharedBufferMemoryBeginAccess {
    uint64_t sharedBufferMemory;
    uint64_t buffer;
    WGPUSharedBufferMemoryBeginAccessDescriptor descriptor;
};

struct yrdawn_args_wgpuSharedBufferMemoryCreateBuffer {
    uint64_t sharedBufferMemory;
    WGPUBufferDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuSharedBufferMemoryEndAccess {
    uint64_t sharedBufferMemory;
    uint64_t buffer;
    WGPUSharedBufferMemoryEndAccessState descriptor;
};

struct yrdawn_args_wgpuSharedBufferMemoryEndAccessStateFreeMembers {
    uint64_t sharedBufferMemoryEndAccessState;
};

struct yrdawn_args_wgpuSharedBufferMemoryGetProperties {
    uint64_t sharedBufferMemory;
    WGPUSharedBufferMemoryProperties properties;
};

struct yrdawn_args_wgpuSharedBufferMemoryIsDeviceLost {
    uint64_t sharedBufferMemory;
};

struct yrdawn_args_wgpuSharedBufferMemoryRelease {
    uint64_t sharedBufferMemory;
};

struct yrdawn_args_wgpuSharedBufferMemorySetLabel {
    uint64_t sharedBufferMemory;
    WGPUStringView label;
};

struct yrdawn_args_wgpuSharedFenceAddRef {
    uint64_t sharedFence;
};

struct yrdawn_args_wgpuSharedFenceExportInfo {
    uint64_t sharedFence;
    WGPUSharedFenceExportInfo info;
};

struct yrdawn_args_wgpuSharedFenceRelease {
    uint64_t sharedFence;
};

struct yrdawn_args_wgpuSharedFenceSetLabel {
    uint64_t sharedFence;
    WGPUStringView label;
};

struct yrdawn_args_wgpuSharedTextureMemoryAddRef {
    uint64_t sharedTextureMemory;
};

struct yrdawn_args_wgpuSharedTextureMemoryBeginAccess {
    uint64_t sharedTextureMemory;
    uint64_t texture;
    WGPUSharedTextureMemoryBeginAccessDescriptor descriptor;
};

struct yrdawn_args_wgpuSharedTextureMemoryCreateTexture {
    uint64_t sharedTextureMemory;
    WGPUTextureDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuSharedTextureMemoryEndAccess {
    uint64_t sharedTextureMemory;
    uint64_t texture;
    WGPUSharedTextureMemoryEndAccessState descriptor;
};

struct yrdawn_args_wgpuSharedTextureMemoryEndAccessStateFreeMembers {
    uint64_t sharedTextureMemoryEndAccessState;
};

struct yrdawn_args_wgpuSharedTextureMemoryGetProperties {
    uint64_t sharedTextureMemory;
    WGPUSharedTextureMemoryProperties properties;
};

struct yrdawn_args_wgpuSharedTextureMemoryIsDeviceLost {
    uint64_t sharedTextureMemory;
};

struct yrdawn_args_wgpuSharedTextureMemoryRelease {
    uint64_t sharedTextureMemory;
};

struct yrdawn_args_wgpuSharedTextureMemorySetLabel {
    uint64_t sharedTextureMemory;
    WGPUStringView label;
};

struct yrdawn_args_wgpuSupportedFeaturesFreeMembers {
    uint64_t supportedFeatures;
};

struct yrdawn_args_wgpuSupportedInstanceFeaturesFreeMembers {
    uint64_t supportedInstanceFeatures;
};

struct yrdawn_args_wgpuSupportedWGSLLanguageFeaturesFreeMembers {
    uint64_t supportedWGSLLanguageFeatures;
};

struct yrdawn_args_wgpuSurfaceAddRef {
    uint64_t surface;
};

struct yrdawn_args_wgpuSurfaceCapabilitiesFreeMembers {
    uint64_t surfaceCapabilities;
};

struct yrdawn_args_wgpuSurfaceConfigure {
    uint64_t surface;
    WGPUSurfaceConfiguration config;
};

struct yrdawn_args_wgpuSurfaceGetCapabilities {
    uint64_t surface;
    uint64_t adapter;
    WGPUSurfaceCapabilities capabilities;
};

struct yrdawn_args_wgpuSurfaceGetCurrentTexture {
    uint64_t surface;
    WGPUSurfaceTexture surfaceTexture;
};

struct yrdawn_args_wgpuSurfacePresent {
    uint64_t surface;
};

struct yrdawn_args_wgpuSurfaceRelease {
    uint64_t surface;
};

struct yrdawn_args_wgpuSurfaceSetLabel {
    uint64_t surface;
    WGPUStringView label;
};

struct yrdawn_args_wgpuSurfaceUnconfigure {
    uint64_t surface;
};

struct yrdawn_args_wgpuTexelBufferViewAddRef {
    uint64_t texelBufferView;
};

struct yrdawn_args_wgpuTexelBufferViewRelease {
    uint64_t texelBufferView;
};

struct yrdawn_args_wgpuTexelBufferViewSetLabel {
    uint64_t texelBufferView;
    WGPUStringView label;
};

struct yrdawn_args_wgpuTextureAddRef {
    uint64_t texture;
};

struct yrdawn_args_wgpuTextureCreateErrorView {
    uint64_t texture;
    WGPUTextureViewDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuTextureCreateView {
    uint64_t texture;
    WGPUTextureViewDescriptor descriptor;
    uint64_t result_handle;
};

struct yrdawn_args_wgpuTextureDestroy {
    uint64_t texture;
};

struct yrdawn_args_wgpuTextureGetDepthOrArrayLayers {
    uint64_t texture;
};

struct yrdawn_args_wgpuTextureGetDimension {
    uint64_t texture;
};

struct yrdawn_args_wgpuTextureGetFormat {
    uint64_t texture;
};

struct yrdawn_args_wgpuTextureGetHeight {
    uint64_t texture;
};

struct yrdawn_args_wgpuTextureGetMipLevelCount {
    uint64_t texture;
};

struct yrdawn_args_wgpuTextureGetSampleCount {
    uint64_t texture;
};

struct yrdawn_args_wgpuTextureGetTextureBindingViewDimension {
    uint64_t texture;
};

struct yrdawn_args_wgpuTextureGetUsage {
    uint64_t texture;
};

struct yrdawn_args_wgpuTextureGetWidth {
    uint64_t texture;
};

struct yrdawn_args_wgpuTexturePin {
    uint64_t texture;
    uint32_t usage;
};

struct yrdawn_args_wgpuTextureRelease {
    uint64_t texture;
};

struct yrdawn_args_wgpuTextureSetLabel {
    uint64_t texture;
    WGPUStringView label;
};

struct yrdawn_args_wgpuTextureSetOwnershipForMemoryDump {
    uint64_t texture;
    uint64_t ownerGuid;
};

struct yrdawn_args_wgpuTextureUnpin {
    uint64_t texture;
};

struct yrdawn_args_wgpuTextureViewAddRef {
    uint64_t textureView;
};

struct yrdawn_args_wgpuTextureViewRelease {
    uint64_t textureView;
};

struct yrdawn_args_wgpuTextureViewSetLabel {
    uint64_t textureView;
    WGPUStringView label;
};

struct yetty_yrdawn_client;
typedef void (*yetty_yrdawn_reply_cb)(void *user, uint32_t status, uint32_t method_id,
                                      const uint8_t *body, size_t body_len);

uint64_t yrdawn_client_wgpuCreateInstance(struct yetty_yrdawn_client *c);
struct yetty_ycore_void_result yrdawn_client_wgpuInstanceRelease(struct yetty_yrdawn_client *c,
                                                                 uint64_t instance);
struct yetty_ycore_void_result yrdawn_client_wgpuDeviceTick(struct yetty_yrdawn_client *c,
                                                            uint64_t device);
uint64_t yrdawn_client_wgpuDeviceGetQueue(struct yetty_yrdawn_client *c, uint64_t device);
struct yetty_ycore_void_result yrdawn_client_wgpuQueueRelease(struct yetty_yrdawn_client *c,
                                                              uint64_t queue);
struct yetty_ycore_void_result yrdawn_client_wgpuDeviceRelease(struct yetty_yrdawn_client *c,
                                                               uint64_t device);
struct yetty_ycore_void_result yrdawn_client_wgpuAdapterRelease(struct yetty_yrdawn_client *c,
                                                                uint64_t adapter);
uint64_t yrdawn_client_wgpuDeviceCreateCommandEncoder(struct yetty_yrdawn_client *c,
                                                      uint64_t device);
struct yetty_ycore_void_result yrdawn_client_wgpuCommandEncoderRelease(
    struct yetty_yrdawn_client *c, uint64_t encoder);
uint64_t yrdawn_client_wgpuCommandEncoderFinish(struct yetty_yrdawn_client *c, uint64_t encoder);
struct yetty_ycore_void_result yrdawn_client_wgpuCommandBufferRelease(struct yetty_yrdawn_client *c,
                                                                      uint64_t buffer);
uint64_t yrdawn_client_wgpuInstanceRequestAdapter(struct yetty_yrdawn_client *c, uint64_t instance,
                                                  yetty_yrdawn_reply_cb cb, void *user);
uint64_t yrdawn_client_wgpuAdapterRequestDevice(struct yetty_yrdawn_client *c, uint64_t adapter,
                                                yetty_yrdawn_reply_cb cb, void *user);
struct yetty_ycore_void_result yrdawn_client_wgpuAdapterAddRef(struct yetty_yrdawn_client *c,
                                                               uint64_t adapter);
uint64_t yrdawn_client_wgpuAdapterCreateDevice(struct yetty_yrdawn_client *c, uint64_t adapter,
                                               WGPUDeviceDescriptor const *descriptor);
struct yetty_ycore_void_result yrdawn_client_wgpuAdapterGetFeatures(
    struct yetty_yrdawn_client *c, uint64_t adapter, WGPUSupportedFeatures *features);
WGPUStatus yrdawn_client_wgpuAdapterGetFormatCapabilities(struct yetty_yrdawn_client *c,
                                                          uint64_t adapter, uint32_t format,
                                                          WGPUDawnFormatCapabilities *capabilities);
WGPUStatus yrdawn_client_wgpuAdapterGetInfo(struct yetty_yrdawn_client *c, uint64_t adapter,
                                            WGPUAdapterInfo *info);
uint64_t yrdawn_client_wgpuAdapterGetInstance(struct yetty_yrdawn_client *c, uint64_t adapter);
WGPUStatus yrdawn_client_wgpuAdapterGetLimits(struct yetty_yrdawn_client *c, uint64_t adapter,
                                              WGPULimits *limits);
WGPUBool yrdawn_client_wgpuAdapterHasFeature(struct yetty_yrdawn_client *c, uint64_t adapter,
                                             uint32_t feature);
void yrdawn_client_wgpuAdapterInfoFreeMembers(struct yetty_yrdawn_client *c,
                                              WGPUAdapterInfo adapterInfo);
void yrdawn_client_wgpuAdapterPropertiesMemoryHeapsFreeMembers(
    struct yetty_yrdawn_client *c, WGPUAdapterPropertiesMemoryHeaps adapterPropertiesMemoryHeaps);
void yrdawn_client_wgpuAdapterPropertiesSubgroupMatrixConfigsFreeMembers(
    struct yetty_yrdawn_client *c,
    WGPUAdapterPropertiesSubgroupMatrixConfigs adapterPropertiesSubgroupMatrixConfigs);
struct yetty_ycore_void_result yrdawn_client_wgpuBindGroupAddRef(struct yetty_yrdawn_client *c,
                                                                 uint64_t bindGroup);
struct yetty_ycore_void_result yrdawn_client_wgpuBindGroupLayoutAddRef(
    struct yetty_yrdawn_client *c, uint64_t bindGroupLayout);
struct yetty_ycore_void_result yrdawn_client_wgpuBindGroupLayoutRelease(
    struct yetty_yrdawn_client *c, uint64_t bindGroupLayout);
struct yetty_ycore_void_result yrdawn_client_wgpuBindGroupLayoutSetLabel(
    struct yetty_yrdawn_client *c, uint64_t bindGroupLayout, WGPUStringView label);
struct yetty_ycore_void_result yrdawn_client_wgpuBindGroupRelease(struct yetty_yrdawn_client *c,
                                                                  uint64_t bindGroup);
struct yetty_ycore_void_result yrdawn_client_wgpuBindGroupSetLabel(struct yetty_yrdawn_client *c,
                                                                   uint64_t bindGroup,
                                                                   WGPUStringView label);
struct yetty_ycore_void_result yrdawn_client_wgpuBufferAddRef(struct yetty_yrdawn_client *c,
                                                              uint64_t buffer);
uint64_t yrdawn_client_wgpuBufferCreateTexelView(struct yetty_yrdawn_client *c, uint64_t buffer,
                                                 WGPUTexelBufferViewDescriptor const *descriptor);
struct yetty_ycore_void_result yrdawn_client_wgpuBufferDestroy(struct yetty_yrdawn_client *c,
                                                               uint64_t buffer);
WGPUBufferMapState yrdawn_client_wgpuBufferGetMapState(struct yetty_yrdawn_client *c,
                                                       uint64_t buffer);
uint64_t yrdawn_client_wgpuBufferGetSize(struct yetty_yrdawn_client *c, uint64_t buffer);
WGPUBufferUsage yrdawn_client_wgpuBufferGetUsage(struct yetty_yrdawn_client *c, uint64_t buffer);
WGPUFuture yrdawn_client_wgpuBufferMapAsync(struct yetty_yrdawn_client *c, uint64_t buffer,
                                            uint32_t mode, size_t offset, size_t size,
                                            yetty_yrdawn_reply_cb cb, void *user);
WGPUStatus yrdawn_client_wgpuBufferReadMappedRange(struct yetty_yrdawn_client *c, uint64_t buffer,
                                                   size_t offset, void *data, size_t size);
struct yetty_ycore_void_result yrdawn_client_wgpuBufferRelease(struct yetty_yrdawn_client *c,
                                                               uint64_t buffer);
struct yetty_ycore_void_result yrdawn_client_wgpuBufferSetLabel(struct yetty_yrdawn_client *c,
                                                                uint64_t buffer,
                                                                WGPUStringView label);
struct yetty_ycore_void_result yrdawn_client_wgpuBufferUnmap(struct yetty_yrdawn_client *c,
                                                             uint64_t buffer);
WGPUStatus yrdawn_client_wgpuBufferWriteMappedRange(struct yetty_yrdawn_client *c, uint64_t buffer,
                                                    size_t offset, void const *data, size_t size);
struct yetty_ycore_void_result yrdawn_client_wgpuCommandBufferAddRef(struct yetty_yrdawn_client *c,
                                                                     uint64_t commandBuffer);
struct yetty_ycore_void_result yrdawn_client_wgpuCommandBufferSetLabel(
    struct yetty_yrdawn_client *c, uint64_t commandBuffer, WGPUStringView label);
struct yetty_ycore_void_result yrdawn_client_wgpuCommandEncoderAddRef(struct yetty_yrdawn_client *c,
                                                                      uint64_t commandEncoder);
uint64_t yrdawn_client_wgpuCommandEncoderBeginComputePass(
    struct yetty_yrdawn_client *c, uint64_t commandEncoder,
    WGPUComputePassDescriptor const *descriptor);
uint64_t yrdawn_client_wgpuCommandEncoderBeginRenderPass(
    struct yetty_yrdawn_client *c, uint64_t commandEncoder,
    WGPURenderPassDescriptor const *descriptor);
struct yetty_ycore_void_result yrdawn_client_wgpuCommandEncoderClearBuffer(
    struct yetty_yrdawn_client *c, uint64_t commandEncoder, uint64_t buffer, uint64_t offset,
    uint64_t size);
struct yetty_ycore_void_result yrdawn_client_wgpuCommandEncoderCopyBufferToBuffer(
    struct yetty_yrdawn_client *c, uint64_t commandEncoder, uint64_t source, uint64_t sourceOffset,
    uint64_t destination, uint64_t destinationOffset, uint64_t size);
struct yetty_ycore_void_result yrdawn_client_wgpuCommandEncoderCopyBufferToTexture(
    struct yetty_yrdawn_client *c, uint64_t commandEncoder, WGPUTexelCopyBufferInfo const *source,
    WGPUTexelCopyTextureInfo const *destination, WGPUExtent3D const *copySize);
struct yetty_ycore_void_result yrdawn_client_wgpuCommandEncoderCopyTextureToBuffer(
    struct yetty_yrdawn_client *c, uint64_t commandEncoder, WGPUTexelCopyTextureInfo const *source,
    WGPUTexelCopyBufferInfo const *destination, WGPUExtent3D const *copySize);
struct yetty_ycore_void_result yrdawn_client_wgpuCommandEncoderCopyTextureToTexture(
    struct yetty_yrdawn_client *c, uint64_t commandEncoder, WGPUTexelCopyTextureInfo const *source,
    WGPUTexelCopyTextureInfo const *destination, WGPUExtent3D const *copySize);
struct yetty_ycore_void_result yrdawn_client_wgpuCommandEncoderInjectValidationError(
    struct yetty_yrdawn_client *c, uint64_t commandEncoder, WGPUStringView message);
struct yetty_ycore_void_result yrdawn_client_wgpuCommandEncoderInsertDebugMarker(
    struct yetty_yrdawn_client *c, uint64_t commandEncoder, WGPUStringView markerLabel);
struct yetty_ycore_void_result yrdawn_client_wgpuCommandEncoderPopDebugGroup(
    struct yetty_yrdawn_client *c, uint64_t commandEncoder);
struct yetty_ycore_void_result yrdawn_client_wgpuCommandEncoderPushDebugGroup(
    struct yetty_yrdawn_client *c, uint64_t commandEncoder, WGPUStringView groupLabel);
struct yetty_ycore_void_result yrdawn_client_wgpuCommandEncoderResolveQuerySet(
    struct yetty_yrdawn_client *c, uint64_t commandEncoder, uint64_t querySet, uint32_t firstQuery,
    uint32_t queryCount, uint64_t destination, uint64_t destinationOffset);
struct yetty_ycore_void_result yrdawn_client_wgpuCommandEncoderSetLabel(
    struct yetty_yrdawn_client *c, uint64_t commandEncoder, WGPUStringView label);
struct yetty_ycore_void_result yrdawn_client_wgpuCommandEncoderWriteBuffer(
    struct yetty_yrdawn_client *c, uint64_t commandEncoder, uint64_t buffer, uint64_t bufferOffset,
    void const *data, size_t size);
struct yetty_ycore_void_result yrdawn_client_wgpuCommandEncoderWriteTimestamp(
    struct yetty_yrdawn_client *c, uint64_t commandEncoder, uint64_t querySet, uint32_t queryIndex);
struct yetty_ycore_void_result yrdawn_client_wgpuComputePassEncoderAddRef(
    struct yetty_yrdawn_client *c, uint64_t computePassEncoder);
struct yetty_ycore_void_result yrdawn_client_wgpuComputePassEncoderDispatchWorkgroups(
    struct yetty_yrdawn_client *c, uint64_t computePassEncoder, uint32_t workgroupCountX,
    uint32_t workgroupCountY, uint32_t workgroupCountZ);
struct yetty_ycore_void_result yrdawn_client_wgpuComputePassEncoderDispatchWorkgroupsIndirect(
    struct yetty_yrdawn_client *c, uint64_t computePassEncoder, uint64_t indirectBuffer,
    uint64_t indirectOffset);
struct yetty_ycore_void_result yrdawn_client_wgpuComputePassEncoderEnd(
    struct yetty_yrdawn_client *c, uint64_t computePassEncoder);
struct yetty_ycore_void_result yrdawn_client_wgpuComputePassEncoderInsertDebugMarker(
    struct yetty_yrdawn_client *c, uint64_t computePassEncoder, WGPUStringView markerLabel);
struct yetty_ycore_void_result yrdawn_client_wgpuComputePassEncoderPopDebugGroup(
    struct yetty_yrdawn_client *c, uint64_t computePassEncoder);
struct yetty_ycore_void_result yrdawn_client_wgpuComputePassEncoderPushDebugGroup(
    struct yetty_yrdawn_client *c, uint64_t computePassEncoder, WGPUStringView groupLabel);
struct yetty_ycore_void_result yrdawn_client_wgpuComputePassEncoderRelease(
    struct yetty_yrdawn_client *c, uint64_t computePassEncoder);
struct yetty_ycore_void_result yrdawn_client_wgpuComputePassEncoderSetBindGroup(
    struct yetty_yrdawn_client *c, uint64_t computePassEncoder, uint32_t groupIndex, uint64_t group,
    size_t dynamicOffsetCount, uint32_t const *dynamicOffsets);
struct yetty_ycore_void_result yrdawn_client_wgpuComputePassEncoderSetImmediates(
    struct yetty_yrdawn_client *c, uint64_t computePassEncoder, uint32_t offset, void const *data,
    size_t size);
struct yetty_ycore_void_result yrdawn_client_wgpuComputePassEncoderSetLabel(
    struct yetty_yrdawn_client *c, uint64_t computePassEncoder, WGPUStringView label);
struct yetty_ycore_void_result yrdawn_client_wgpuComputePassEncoderSetPipeline(
    struct yetty_yrdawn_client *c, uint64_t computePassEncoder, uint64_t pipeline);
struct yetty_ycore_void_result yrdawn_client_wgpuComputePassEncoderSetResourceTable(
    struct yetty_yrdawn_client *c, uint64_t computePassEncoder, uint64_t table);
struct yetty_ycore_void_result yrdawn_client_wgpuComputePassEncoderWriteTimestamp(
    struct yetty_yrdawn_client *c, uint64_t computePassEncoder, uint64_t querySet,
    uint32_t queryIndex);
struct yetty_ycore_void_result yrdawn_client_wgpuComputePipelineAddRef(
    struct yetty_yrdawn_client *c, uint64_t computePipeline);
uint64_t yrdawn_client_wgpuComputePipelineGetBindGroupLayout(struct yetty_yrdawn_client *c,
                                                             uint64_t computePipeline,
                                                             uint32_t groupIndex);
struct yetty_ycore_void_result yrdawn_client_wgpuComputePipelineRelease(
    struct yetty_yrdawn_client *c, uint64_t computePipeline);
struct yetty_ycore_void_result yrdawn_client_wgpuComputePipelineSetLabel(
    struct yetty_yrdawn_client *c, uint64_t computePipeline, WGPUStringView label);
void yrdawn_client_wgpuDawnDrmFormatCapabilitiesFreeMembers(
    struct yetty_yrdawn_client *c, WGPUDawnDrmFormatCapabilities dawnDrmFormatCapabilities);
struct yetty_ycore_void_result yrdawn_client_wgpuDeviceAddRef(struct yetty_yrdawn_client *c,
                                                              uint64_t device);
uint64_t yrdawn_client_wgpuDeviceCreateBindGroup(struct yetty_yrdawn_client *c, uint64_t device,
                                                 WGPUBindGroupDescriptor const *descriptor);
uint64_t yrdawn_client_wgpuDeviceCreateBindGroupLayout(
    struct yetty_yrdawn_client *c, uint64_t device,
    WGPUBindGroupLayoutDescriptor const *descriptor);
uint64_t yrdawn_client_wgpuDeviceCreateBuffer(struct yetty_yrdawn_client *c, uint64_t device,
                                              WGPUBufferDescriptor const *descriptor);
uint64_t yrdawn_client_wgpuDeviceCreateComputePipeline(
    struct yetty_yrdawn_client *c, uint64_t device,
    WGPUComputePipelineDescriptor const *descriptor);
WGPUFuture yrdawn_client_wgpuDeviceCreateComputePipelineAsync(
    struct yetty_yrdawn_client *c, uint64_t device, WGPUComputePipelineDescriptor const *descriptor,
    yetty_yrdawn_reply_cb cb, void *user);
uint64_t yrdawn_client_wgpuDeviceCreateErrorBuffer(struct yetty_yrdawn_client *c, uint64_t device,
                                                   WGPUBufferDescriptor const *descriptor);
uint64_t yrdawn_client_wgpuDeviceCreateErrorExternalTexture(struct yetty_yrdawn_client *c,
                                                            uint64_t device);
uint64_t yrdawn_client_wgpuDeviceCreateErrorShaderModule(
    struct yetty_yrdawn_client *c, uint64_t device, WGPUShaderModuleDescriptor const *descriptor,
    WGPUStringView errorMessage);
uint64_t yrdawn_client_wgpuDeviceCreateErrorTexture(struct yetty_yrdawn_client *c, uint64_t device,
                                                    WGPUTextureDescriptor const *descriptor);
uint64_t yrdawn_client_wgpuDeviceCreateExternalTexture(
    struct yetty_yrdawn_client *c, uint64_t device,
    WGPUExternalTextureDescriptor const *externalTextureDescriptor);
uint64_t yrdawn_client_wgpuDeviceCreatePipelineLayout(
    struct yetty_yrdawn_client *c, uint64_t device, WGPUPipelineLayoutDescriptor const *descriptor);
uint64_t yrdawn_client_wgpuDeviceCreateQuerySet(struct yetty_yrdawn_client *c, uint64_t device,
                                                WGPUQuerySetDescriptor const *descriptor);
uint64_t yrdawn_client_wgpuDeviceCreateRenderBundleEncoder(
    struct yetty_yrdawn_client *c, uint64_t device,
    WGPURenderBundleEncoderDescriptor const *descriptor);
uint64_t yrdawn_client_wgpuDeviceCreateRenderPipeline(
    struct yetty_yrdawn_client *c, uint64_t device, WGPURenderPipelineDescriptor const *descriptor);
WGPUFuture yrdawn_client_wgpuDeviceCreateRenderPipelineAsync(
    struct yetty_yrdawn_client *c, uint64_t device, WGPURenderPipelineDescriptor const *descriptor,
    yetty_yrdawn_reply_cb cb, void *user);
uint64_t yrdawn_client_wgpuDeviceCreateResourceTable(struct yetty_yrdawn_client *c, uint64_t device,
                                                     WGPUResourceTableDescriptor const *descriptor);
uint64_t yrdawn_client_wgpuDeviceCreateSampler(struct yetty_yrdawn_client *c, uint64_t device,
                                               WGPUSamplerDescriptor const *descriptor);
uint64_t yrdawn_client_wgpuDeviceCreateShaderModule(struct yetty_yrdawn_client *c, uint64_t device,
                                                    WGPUShaderModuleDescriptor const *descriptor);
uint64_t yrdawn_client_wgpuDeviceCreateTexture(struct yetty_yrdawn_client *c, uint64_t device,
                                               WGPUTextureDescriptor const *descriptor);
struct yetty_ycore_void_result yrdawn_client_wgpuDeviceDestroy(struct yetty_yrdawn_client *c,
                                                               uint64_t device);
struct yetty_ycore_void_result yrdawn_client_wgpuDeviceForceLoss(struct yetty_yrdawn_client *c,
                                                                 uint64_t device, uint32_t type,
                                                                 WGPUStringView message);
WGPUStatus yrdawn_client_wgpuDeviceGetAHardwareBufferProperties(
    struct yetty_yrdawn_client *c, uint64_t device, uint64_t handle,
    WGPUAHardwareBufferProperties *properties);
uint64_t yrdawn_client_wgpuDeviceGetAdapter(struct yetty_yrdawn_client *c, uint64_t device);
WGPUStatus yrdawn_client_wgpuDeviceGetAdapterInfo(struct yetty_yrdawn_client *c, uint64_t device,
                                                  WGPUAdapterInfo *adapterInfo);
struct yetty_ycore_void_result yrdawn_client_wgpuDeviceGetFeatures(struct yetty_yrdawn_client *c,
                                                                   uint64_t device,
                                                                   WGPUSupportedFeatures *features);
WGPUStatus yrdawn_client_wgpuDeviceGetLimits(struct yetty_yrdawn_client *c, uint64_t device,
                                             WGPULimits *limits);
WGPUFuture yrdawn_client_wgpuDeviceGetLostFuture(struct yetty_yrdawn_client *c, uint64_t device);
WGPUBool yrdawn_client_wgpuDeviceHasFeature(struct yetty_yrdawn_client *c, uint64_t device,
                                            uint32_t feature);
uint64_t yrdawn_client_wgpuDeviceImportSharedBufferMemory(
    struct yetty_yrdawn_client *c, uint64_t device,
    WGPUSharedBufferMemoryDescriptor const *descriptor);
uint64_t yrdawn_client_wgpuDeviceImportSharedFence(struct yetty_yrdawn_client *c, uint64_t device,
                                                   WGPUSharedFenceDescriptor const *descriptor);
uint64_t yrdawn_client_wgpuDeviceImportSharedTextureMemory(
    struct yetty_yrdawn_client *c, uint64_t device,
    WGPUSharedTextureMemoryDescriptor const *descriptor);
struct yetty_ycore_void_result yrdawn_client_wgpuDeviceInjectError(struct yetty_yrdawn_client *c,
                                                                   uint64_t device, uint32_t type,
                                                                   WGPUStringView message);
WGPUFuture yrdawn_client_wgpuDevicePopErrorScope(struct yetty_yrdawn_client *c, uint64_t device,
                                                 yetty_yrdawn_reply_cb cb, void *user);
struct yetty_ycore_void_result yrdawn_client_wgpuDevicePushErrorScope(struct yetty_yrdawn_client *c,
                                                                      uint64_t device,
                                                                      uint32_t filter);
struct yetty_ycore_void_result yrdawn_client_wgpuDeviceSetLabel(struct yetty_yrdawn_client *c,
                                                                uint64_t device,
                                                                WGPUStringView label);
struct yetty_ycore_void_result yrdawn_client_wgpuDeviceSetLoggingCallback(
    struct yetty_yrdawn_client *c, uint64_t device, yetty_yrdawn_reply_cb cb, void *user);
struct yetty_ycore_void_result yrdawn_client_wgpuDeviceValidateTextureDescriptor(
    struct yetty_yrdawn_client *c, uint64_t device, WGPUTextureDescriptor const *descriptor);
struct yetty_ycore_void_result yrdawn_client_wgpuExternalTextureAddRef(
    struct yetty_yrdawn_client *c, uint64_t externalTexture);
struct yetty_ycore_void_result yrdawn_client_wgpuExternalTextureDestroy(
    struct yetty_yrdawn_client *c, uint64_t externalTexture);
struct yetty_ycore_void_result yrdawn_client_wgpuExternalTextureExpire(
    struct yetty_yrdawn_client *c, uint64_t externalTexture);
struct yetty_ycore_void_result yrdawn_client_wgpuExternalTextureRefresh(
    struct yetty_yrdawn_client *c, uint64_t externalTexture);
struct yetty_ycore_void_result yrdawn_client_wgpuExternalTextureRelease(
    struct yetty_yrdawn_client *c, uint64_t externalTexture);
struct yetty_ycore_void_result yrdawn_client_wgpuExternalTextureSetLabel(
    struct yetty_yrdawn_client *c, uint64_t externalTexture, WGPUStringView label);
struct yetty_ycore_void_result yrdawn_client_wgpuGetInstanceFeatures(
    struct yetty_yrdawn_client *c, WGPUSupportedInstanceFeatures *features);
WGPUStatus yrdawn_client_wgpuGetInstanceLimits(struct yetty_yrdawn_client *c,
                                               WGPUInstanceLimits *limits);
uint64_t yrdawn_client_wgpuGetProcAddress(struct yetty_yrdawn_client *c, WGPUStringView procName);
WGPUBool yrdawn_client_wgpuHasInstanceFeature(struct yetty_yrdawn_client *c, uint32_t feature);
struct yetty_ycore_void_result yrdawn_client_wgpuInstanceAddRef(struct yetty_yrdawn_client *c,
                                                                uint64_t instance);
uint64_t yrdawn_client_wgpuInstanceCreateSurface(struct yetty_yrdawn_client *c, uint64_t instance,
                                                 WGPUSurfaceDescriptor const *descriptor);
struct yetty_ycore_void_result yrdawn_client_wgpuInstanceGetWGSLLanguageFeatures(
    struct yetty_yrdawn_client *c, uint64_t instance, WGPUSupportedWGSLLanguageFeatures *features);
WGPUBool yrdawn_client_wgpuInstanceHasWGSLLanguageFeature(struct yetty_yrdawn_client *c,
                                                          uint64_t instance, uint32_t feature);
struct yetty_ycore_void_result yrdawn_client_wgpuInstanceProcessEvents(
    struct yetty_yrdawn_client *c, uint64_t instance);
WGPUWaitStatus yrdawn_client_wgpuInstanceWaitAny(struct yetty_yrdawn_client *c, uint64_t instance,
                                                 size_t futureCount,
                                                 WGPUFutureWaitInfo const *futures,
                                                 uint64_t timeoutNS);
struct yetty_ycore_void_result yrdawn_client_wgpuPipelineLayoutAddRef(struct yetty_yrdawn_client *c,
                                                                      uint64_t pipelineLayout);
struct yetty_ycore_void_result yrdawn_client_wgpuPipelineLayoutRelease(
    struct yetty_yrdawn_client *c, uint64_t pipelineLayout);
struct yetty_ycore_void_result yrdawn_client_wgpuPipelineLayoutSetLabel(
    struct yetty_yrdawn_client *c, uint64_t pipelineLayout, WGPUStringView label);
struct yetty_ycore_void_result yrdawn_client_wgpuQuerySetAddRef(struct yetty_yrdawn_client *c,
                                                                uint64_t querySet);
struct yetty_ycore_void_result yrdawn_client_wgpuQuerySetDestroy(struct yetty_yrdawn_client *c,
                                                                 uint64_t querySet);
uint32_t yrdawn_client_wgpuQuerySetGetCount(struct yetty_yrdawn_client *c, uint64_t querySet);
WGPUQueryType yrdawn_client_wgpuQuerySetGetType(struct yetty_yrdawn_client *c, uint64_t querySet);
struct yetty_ycore_void_result yrdawn_client_wgpuQuerySetRelease(struct yetty_yrdawn_client *c,
                                                                 uint64_t querySet);
struct yetty_ycore_void_result yrdawn_client_wgpuQuerySetSetLabel(struct yetty_yrdawn_client *c,
                                                                  uint64_t querySet,
                                                                  WGPUStringView label);
struct yetty_ycore_void_result yrdawn_client_wgpuQueueAddRef(struct yetty_yrdawn_client *c,
                                                             uint64_t queue);
struct yetty_ycore_void_result yrdawn_client_wgpuQueueCopyExternalTextureForBrowser(
    struct yetty_yrdawn_client *c, uint64_t queue, WGPUImageCopyExternalTexture const *source,
    WGPUTexelCopyTextureInfo const *destination, WGPUExtent3D const *copySize,
    WGPUCopyTextureForBrowserOptions const *options);
struct yetty_ycore_void_result yrdawn_client_wgpuQueueCopyTextureForBrowser(
    struct yetty_yrdawn_client *c, uint64_t queue, WGPUTexelCopyTextureInfo const *source,
    WGPUTexelCopyTextureInfo const *destination, WGPUExtent3D const *copySize,
    WGPUCopyTextureForBrowserOptions const *options);
WGPUFuture yrdawn_client_wgpuQueueOnSubmittedWorkDone(struct yetty_yrdawn_client *c, uint64_t queue,
                                                      yetty_yrdawn_reply_cb cb, void *user);
struct yetty_ycore_void_result yrdawn_client_wgpuQueueSetLabel(struct yetty_yrdawn_client *c,
                                                               uint64_t queue,
                                                               WGPUStringView label);
struct yetty_ycore_void_result yrdawn_client_wgpuQueueSubmit(struct yetty_yrdawn_client *c,
                                                             uint64_t queue, size_t commandCount,
                                                             WGPUCommandBuffer const *commands);
struct yetty_ycore_void_result yrdawn_client_wgpuQueueWriteBuffer(struct yetty_yrdawn_client *c,
                                                                  uint64_t queue, uint64_t buffer,
                                                                  uint64_t bufferOffset,
                                                                  void const *data, size_t size);
struct yetty_ycore_void_result yrdawn_client_wgpuQueueWriteTexture(
    struct yetty_yrdawn_client *c, uint64_t queue, WGPUTexelCopyTextureInfo const *destination,
    void const *data, size_t dataSize, WGPUTexelCopyBufferLayout const *dataLayout,
    WGPUExtent3D const *writeSize);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderBundleAddRef(struct yetty_yrdawn_client *c,
                                                                    uint64_t renderBundle);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderBundleEncoderAddRef(
    struct yetty_yrdawn_client *c, uint64_t renderBundleEncoder);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderBundleEncoderDraw(
    struct yetty_yrdawn_client *c, uint64_t renderBundleEncoder, uint32_t vertexCount,
    uint32_t instanceCount, uint32_t firstVertex, uint32_t firstInstance);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderBundleEncoderDrawIndexed(
    struct yetty_yrdawn_client *c, uint64_t renderBundleEncoder, uint32_t indexCount,
    uint32_t instanceCount, uint32_t firstIndex, int32_t baseVertex, uint32_t firstInstance);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderBundleEncoderDrawIndexedIndirect(
    struct yetty_yrdawn_client *c, uint64_t renderBundleEncoder, uint64_t indirectBuffer,
    uint64_t indirectOffset);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderBundleEncoderDrawIndirect(
    struct yetty_yrdawn_client *c, uint64_t renderBundleEncoder, uint64_t indirectBuffer,
    uint64_t indirectOffset);
uint64_t yrdawn_client_wgpuRenderBundleEncoderFinish(struct yetty_yrdawn_client *c,
                                                     uint64_t renderBundleEncoder,
                                                     WGPURenderBundleDescriptor const *descriptor);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderBundleEncoderInsertDebugMarker(
    struct yetty_yrdawn_client *c, uint64_t renderBundleEncoder, WGPUStringView markerLabel);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderBundleEncoderPopDebugGroup(
    struct yetty_yrdawn_client *c, uint64_t renderBundleEncoder);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderBundleEncoderPushDebugGroup(
    struct yetty_yrdawn_client *c, uint64_t renderBundleEncoder, WGPUStringView groupLabel);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderBundleEncoderRelease(
    struct yetty_yrdawn_client *c, uint64_t renderBundleEncoder);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderBundleEncoderSetBindGroup(
    struct yetty_yrdawn_client *c, uint64_t renderBundleEncoder, uint32_t groupIndex,
    uint64_t group, size_t dynamicOffsetCount, uint32_t const *dynamicOffsets);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderBundleEncoderSetImmediates(
    struct yetty_yrdawn_client *c, uint64_t renderBundleEncoder, uint32_t offset, void const *data,
    size_t size);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderBundleEncoderSetIndexBuffer(
    struct yetty_yrdawn_client *c, uint64_t renderBundleEncoder, uint64_t buffer, uint32_t format,
    uint64_t offset, uint64_t size);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderBundleEncoderSetLabel(
    struct yetty_yrdawn_client *c, uint64_t renderBundleEncoder, WGPUStringView label);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderBundleEncoderSetPipeline(
    struct yetty_yrdawn_client *c, uint64_t renderBundleEncoder, uint64_t pipeline);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderBundleEncoderSetResourceTable(
    struct yetty_yrdawn_client *c, uint64_t renderBundleEncoder, uint64_t table);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderBundleEncoderSetVertexBuffer(
    struct yetty_yrdawn_client *c, uint64_t renderBundleEncoder, uint32_t slot, uint64_t buffer,
    uint64_t offset, uint64_t size);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderBundleRelease(struct yetty_yrdawn_client *c,
                                                                     uint64_t renderBundle);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderBundleSetLabel(struct yetty_yrdawn_client *c,
                                                                      uint64_t renderBundle,
                                                                      WGPUStringView label);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderAddRef(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderBeginOcclusionQuery(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder, uint32_t queryIndex);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderDraw(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder, uint32_t vertexCount,
    uint32_t instanceCount, uint32_t firstVertex, uint32_t firstInstance);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderDrawIndexed(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder, uint32_t indexCount,
    uint32_t instanceCount, uint32_t firstIndex, int32_t baseVertex, uint32_t firstInstance);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderDrawIndexedIndirect(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder, uint64_t indirectBuffer,
    uint64_t indirectOffset);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderDrawIndirect(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder, uint64_t indirectBuffer,
    uint64_t indirectOffset);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderEnd(struct yetty_yrdawn_client *c,
                                                                      uint64_t renderPassEncoder);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderEndOcclusionQuery(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderExecuteBundles(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder, size_t bundleCount,
    WGPURenderBundle const *bundles);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderInsertDebugMarker(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder, WGPUStringView markerLabel);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderMultiDrawIndexedIndirect(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder, uint64_t indirectBuffer,
    uint64_t indirectOffset, uint32_t maxDrawCount, uint64_t drawCountBuffer,
    uint64_t drawCountBufferOffset);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderMultiDrawIndirect(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder, uint64_t indirectBuffer,
    uint64_t indirectOffset, uint32_t maxDrawCount, uint64_t drawCountBuffer,
    uint64_t drawCountBufferOffset);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderPixelLocalStorageBarrier(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderPopDebugGroup(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderPushDebugGroup(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder, WGPUStringView groupLabel);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderRelease(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderSetBindGroup(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder, uint32_t groupIndex, uint64_t group,
    size_t dynamicOffsetCount, uint32_t const *dynamicOffsets);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderSetBlendConstant(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder, WGPUColor const *color);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderSetImmediates(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder, uint32_t offset, void const *data,
    size_t size);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderSetIndexBuffer(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder, uint64_t buffer, uint32_t format,
    uint64_t offset, uint64_t size);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderSetLabel(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder, WGPUStringView label);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderSetPipeline(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder, uint64_t pipeline);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderSetResourceTable(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder, uint64_t table);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderSetScissorRect(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder, uint32_t x, uint32_t y,
    uint32_t width, uint32_t height);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderSetStencilReference(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder, uint32_t reference);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderSetVertexBuffer(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder, uint32_t slot, uint64_t buffer,
    uint64_t offset, uint64_t size);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderSetViewport(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder, float x, float y, float width,
    float height, float minDepth, float maxDepth);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPassEncoderWriteTimestamp(
    struct yetty_yrdawn_client *c, uint64_t renderPassEncoder, uint64_t querySet,
    uint32_t queryIndex);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPipelineAddRef(struct yetty_yrdawn_client *c,
                                                                      uint64_t renderPipeline);
uint64_t yrdawn_client_wgpuRenderPipelineGetBindGroupLayout(struct yetty_yrdawn_client *c,
                                                            uint64_t renderPipeline,
                                                            uint32_t groupIndex);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPipelineRelease(
    struct yetty_yrdawn_client *c, uint64_t renderPipeline);
struct yetty_ycore_void_result yrdawn_client_wgpuRenderPipelineSetLabel(
    struct yetty_yrdawn_client *c, uint64_t renderPipeline, WGPUStringView label);
struct yetty_ycore_void_result yrdawn_client_wgpuResourceTableAddRef(struct yetty_yrdawn_client *c,
                                                                     uint64_t resourceTable);
struct yetty_ycore_void_result yrdawn_client_wgpuResourceTableDestroy(struct yetty_yrdawn_client *c,
                                                                      uint64_t resourceTable);
uint32_t yrdawn_client_wgpuResourceTableGetSize(struct yetty_yrdawn_client *c,
                                                uint64_t resourceTable);
uint32_t yrdawn_client_wgpuResourceTableInsertBinding(struct yetty_yrdawn_client *c,
                                                      uint64_t resourceTable,
                                                      WGPUBindingResource const *resource);
struct yetty_ycore_void_result yrdawn_client_wgpuResourceTableRelease(struct yetty_yrdawn_client *c,
                                                                      uint64_t resourceTable);
WGPUStatus yrdawn_client_wgpuResourceTableRemoveBinding(struct yetty_yrdawn_client *c,
                                                        uint64_t resourceTable, uint32_t slot);
WGPUStatus yrdawn_client_wgpuResourceTableUpdate(struct yetty_yrdawn_client *c,
                                                 uint64_t resourceTable, uint32_t slot,
                                                 WGPUBindingResource const *resource);
struct yetty_ycore_void_result yrdawn_client_wgpuSamplerAddRef(struct yetty_yrdawn_client *c,
                                                               uint64_t sampler);
struct yetty_ycore_void_result yrdawn_client_wgpuSamplerRelease(struct yetty_yrdawn_client *c,
                                                                uint64_t sampler);
struct yetty_ycore_void_result yrdawn_client_wgpuSamplerSetLabel(struct yetty_yrdawn_client *c,
                                                                 uint64_t sampler,
                                                                 WGPUStringView label);
struct yetty_ycore_void_result yrdawn_client_wgpuShaderModuleAddRef(struct yetty_yrdawn_client *c,
                                                                    uint64_t shaderModule);
WGPUFuture yrdawn_client_wgpuShaderModuleGetCompilationInfo(struct yetty_yrdawn_client *c,
                                                            uint64_t shaderModule,
                                                            yetty_yrdawn_reply_cb cb, void *user);
struct yetty_ycore_void_result yrdawn_client_wgpuShaderModuleRelease(struct yetty_yrdawn_client *c,
                                                                     uint64_t shaderModule);
struct yetty_ycore_void_result yrdawn_client_wgpuShaderModuleSetLabel(struct yetty_yrdawn_client *c,
                                                                      uint64_t shaderModule,
                                                                      WGPUStringView label);
struct yetty_ycore_void_result yrdawn_client_wgpuSharedBufferMemoryAddRef(
    struct yetty_yrdawn_client *c, uint64_t sharedBufferMemory);
WGPUStatus yrdawn_client_wgpuSharedBufferMemoryBeginAccess(
    struct yetty_yrdawn_client *c, uint64_t sharedBufferMemory, uint64_t buffer,
    WGPUSharedBufferMemoryBeginAccessDescriptor const *descriptor);
uint64_t yrdawn_client_wgpuSharedBufferMemoryCreateBuffer(struct yetty_yrdawn_client *c,
                                                          uint64_t sharedBufferMemory,
                                                          WGPUBufferDescriptor const *descriptor);
WGPUStatus yrdawn_client_wgpuSharedBufferMemoryEndAccess(
    struct yetty_yrdawn_client *c, uint64_t sharedBufferMemory, uint64_t buffer,
    WGPUSharedBufferMemoryEndAccessState *descriptor);
void yrdawn_client_wgpuSharedBufferMemoryEndAccessStateFreeMembers(
    struct yetty_yrdawn_client *c,
    WGPUSharedBufferMemoryEndAccessState sharedBufferMemoryEndAccessState);
WGPUStatus yrdawn_client_wgpuSharedBufferMemoryGetProperties(
    struct yetty_yrdawn_client *c, uint64_t sharedBufferMemory,
    WGPUSharedBufferMemoryProperties *properties);
WGPUBool yrdawn_client_wgpuSharedBufferMemoryIsDeviceLost(struct yetty_yrdawn_client *c,
                                                          uint64_t sharedBufferMemory);
struct yetty_ycore_void_result yrdawn_client_wgpuSharedBufferMemoryRelease(
    struct yetty_yrdawn_client *c, uint64_t sharedBufferMemory);
struct yetty_ycore_void_result yrdawn_client_wgpuSharedBufferMemorySetLabel(
    struct yetty_yrdawn_client *c, uint64_t sharedBufferMemory, WGPUStringView label);
struct yetty_ycore_void_result yrdawn_client_wgpuSharedFenceAddRef(struct yetty_yrdawn_client *c,
                                                                   uint64_t sharedFence);
struct yetty_ycore_void_result yrdawn_client_wgpuSharedFenceExportInfo(
    struct yetty_yrdawn_client *c, uint64_t sharedFence, WGPUSharedFenceExportInfo *info);
struct yetty_ycore_void_result yrdawn_client_wgpuSharedFenceRelease(struct yetty_yrdawn_client *c,
                                                                    uint64_t sharedFence);
struct yetty_ycore_void_result yrdawn_client_wgpuSharedFenceSetLabel(struct yetty_yrdawn_client *c,
                                                                     uint64_t sharedFence,
                                                                     WGPUStringView label);
struct yetty_ycore_void_result yrdawn_client_wgpuSharedTextureMemoryAddRef(
    struct yetty_yrdawn_client *c, uint64_t sharedTextureMemory);
WGPUStatus yrdawn_client_wgpuSharedTextureMemoryBeginAccess(
    struct yetty_yrdawn_client *c, uint64_t sharedTextureMemory, uint64_t texture,
    WGPUSharedTextureMemoryBeginAccessDescriptor const *descriptor);
uint64_t yrdawn_client_wgpuSharedTextureMemoryCreateTexture(
    struct yetty_yrdawn_client *c, uint64_t sharedTextureMemory,
    WGPUTextureDescriptor const *descriptor);
WGPUStatus yrdawn_client_wgpuSharedTextureMemoryEndAccess(
    struct yetty_yrdawn_client *c, uint64_t sharedTextureMemory, uint64_t texture,
    WGPUSharedTextureMemoryEndAccessState *descriptor);
void yrdawn_client_wgpuSharedTextureMemoryEndAccessStateFreeMembers(
    struct yetty_yrdawn_client *c,
    WGPUSharedTextureMemoryEndAccessState sharedTextureMemoryEndAccessState);
WGPUStatus yrdawn_client_wgpuSharedTextureMemoryGetProperties(
    struct yetty_yrdawn_client *c, uint64_t sharedTextureMemory,
    WGPUSharedTextureMemoryProperties *properties);
WGPUBool yrdawn_client_wgpuSharedTextureMemoryIsDeviceLost(struct yetty_yrdawn_client *c,
                                                           uint64_t sharedTextureMemory);
struct yetty_ycore_void_result yrdawn_client_wgpuSharedTextureMemoryRelease(
    struct yetty_yrdawn_client *c, uint64_t sharedTextureMemory);
struct yetty_ycore_void_result yrdawn_client_wgpuSharedTextureMemorySetLabel(
    struct yetty_yrdawn_client *c, uint64_t sharedTextureMemory, WGPUStringView label);
void yrdawn_client_wgpuSupportedFeaturesFreeMembers(struct yetty_yrdawn_client *c,
                                                    WGPUSupportedFeatures supportedFeatures);
void yrdawn_client_wgpuSupportedInstanceFeaturesFreeMembers(
    struct yetty_yrdawn_client *c, WGPUSupportedInstanceFeatures supportedInstanceFeatures);
void yrdawn_client_wgpuSupportedWGSLLanguageFeaturesFreeMembers(
    struct yetty_yrdawn_client *c, WGPUSupportedWGSLLanguageFeatures supportedWGSLLanguageFeatures);
struct yetty_ycore_void_result yrdawn_client_wgpuSurfaceAddRef(struct yetty_yrdawn_client *c,
                                                               uint64_t surface);
void yrdawn_client_wgpuSurfaceCapabilitiesFreeMembers(struct yetty_yrdawn_client *c,
                                                      WGPUSurfaceCapabilities surfaceCapabilities);
struct yetty_ycore_void_result yrdawn_client_wgpuSurfaceConfigure(
    struct yetty_yrdawn_client *c, uint64_t surface, WGPUSurfaceConfiguration const *config);
WGPUStatus yrdawn_client_wgpuSurfaceGetCapabilities(struct yetty_yrdawn_client *c, uint64_t surface,
                                                    uint64_t adapter,
                                                    WGPUSurfaceCapabilities *capabilities);
struct yetty_ycore_void_result yrdawn_client_wgpuSurfaceGetCurrentTexture(
    struct yetty_yrdawn_client *c, uint64_t surface, WGPUSurfaceTexture *surfaceTexture);
WGPUStatus yrdawn_client_wgpuSurfacePresent(struct yetty_yrdawn_client *c, uint64_t surface);
struct yetty_ycore_void_result yrdawn_client_wgpuSurfaceRelease(struct yetty_yrdawn_client *c,
                                                                uint64_t surface);
struct yetty_ycore_void_result yrdawn_client_wgpuSurfaceSetLabel(struct yetty_yrdawn_client *c,
                                                                 uint64_t surface,
                                                                 WGPUStringView label);
struct yetty_ycore_void_result yrdawn_client_wgpuSurfaceUnconfigure(struct yetty_yrdawn_client *c,
                                                                    uint64_t surface);
struct yetty_ycore_void_result yrdawn_client_wgpuTexelBufferViewAddRef(
    struct yetty_yrdawn_client *c, uint64_t texelBufferView);
struct yetty_ycore_void_result yrdawn_client_wgpuTexelBufferViewRelease(
    struct yetty_yrdawn_client *c, uint64_t texelBufferView);
struct yetty_ycore_void_result yrdawn_client_wgpuTexelBufferViewSetLabel(
    struct yetty_yrdawn_client *c, uint64_t texelBufferView, WGPUStringView label);
struct yetty_ycore_void_result yrdawn_client_wgpuTextureAddRef(struct yetty_yrdawn_client *c,
                                                               uint64_t texture);
uint64_t yrdawn_client_wgpuTextureCreateErrorView(struct yetty_yrdawn_client *c, uint64_t texture,
                                                  WGPUTextureViewDescriptor const *descriptor);
uint64_t yrdawn_client_wgpuTextureCreateView(struct yetty_yrdawn_client *c, uint64_t texture,
                                             WGPUTextureViewDescriptor const *descriptor);
struct yetty_ycore_void_result yrdawn_client_wgpuTextureDestroy(struct yetty_yrdawn_client *c,
                                                                uint64_t texture);
uint32_t yrdawn_client_wgpuTextureGetDepthOrArrayLayers(struct yetty_yrdawn_client *c,
                                                        uint64_t texture);
WGPUTextureDimension yrdawn_client_wgpuTextureGetDimension(struct yetty_yrdawn_client *c,
                                                           uint64_t texture);
WGPUTextureFormat yrdawn_client_wgpuTextureGetFormat(struct yetty_yrdawn_client *c,
                                                     uint64_t texture);
uint32_t yrdawn_client_wgpuTextureGetHeight(struct yetty_yrdawn_client *c, uint64_t texture);
uint32_t yrdawn_client_wgpuTextureGetMipLevelCount(struct yetty_yrdawn_client *c, uint64_t texture);
uint32_t yrdawn_client_wgpuTextureGetSampleCount(struct yetty_yrdawn_client *c, uint64_t texture);
WGPUTextureViewDimension yrdawn_client_wgpuTextureGetTextureBindingViewDimension(
    struct yetty_yrdawn_client *c, uint64_t texture);
WGPUTextureUsage yrdawn_client_wgpuTextureGetUsage(struct yetty_yrdawn_client *c, uint64_t texture);
uint32_t yrdawn_client_wgpuTextureGetWidth(struct yetty_yrdawn_client *c, uint64_t texture);
struct yetty_ycore_void_result yrdawn_client_wgpuTexturePin(struct yetty_yrdawn_client *c,
                                                            uint64_t texture, uint32_t usage);
struct yetty_ycore_void_result yrdawn_client_wgpuTextureRelease(struct yetty_yrdawn_client *c,
                                                                uint64_t texture);
struct yetty_ycore_void_result yrdawn_client_wgpuTextureSetLabel(struct yetty_yrdawn_client *c,
                                                                 uint64_t texture,
                                                                 WGPUStringView label);
struct yetty_ycore_void_result yrdawn_client_wgpuTextureSetOwnershipForMemoryDump(
    struct yetty_yrdawn_client *c, uint64_t texture, uint64_t ownerGuid);
struct yetty_ycore_void_result yrdawn_client_wgpuTextureUnpin(struct yetty_yrdawn_client *c,
                                                              uint64_t texture);
struct yetty_ycore_void_result yrdawn_client_wgpuTextureViewAddRef(struct yetty_yrdawn_client *c,
                                                                   uint64_t textureView);
struct yetty_ycore_void_result yrdawn_client_wgpuTextureViewRelease(struct yetty_yrdawn_client *c,
                                                                    uint64_t textureView);
struct yetty_ycore_void_result yrdawn_client_wgpuTextureViewSetLabel(struct yetty_yrdawn_client *c,
                                                                     uint64_t textureView,
                                                                     WGPUStringView label);

#ifdef __cplusplus
}
#endif

#endif /* YETTY_YRDAWN_METHODS_GEN_H */
