/*
 * yrdawn/wire.h — wire format for the WebGPU-over-OSC bridge.
 *
 * The remote side (a wasm process linking yetty_yrdawn_client) implements
 * <webgpu/webgpu.h>; every wgpu* call serializes into an OSC envelope and
 * rides the PTY back to the local yetty, where the yrdawn-layer replays it
 * against Dawn and renders the resulting Dawn texture into its own
 * terminal layer. Replies, async completions, and uncalled callbacks flow
 * back the other way as OSC frames written into the PTY input.
 *
 * Envelope (matches ywire/wire-statemachine + ymgui/wire.h):
 *
 *     \e]<code>;<flag>;<base64[(LZ4F)payload]>\e\\
 *
 * <flag> = '0' (raw b64) for tiny control frames (HELLO, REPLY headers,
 * EVENT), '1' (lz4f+b64) for CMD and BULK. Layer-side decode is fixed by
 * the OSC framer — see <yetty/ywire/wire-statemachine.h>.
 *
 * All integers little-endian. All structs naturally aligned at 4 B.
 * Handles are opaque u64 chosen by the client at call time; the server
 * keeps a handle table mapping each u64 to its real WGPU* Dawn object.
 * Handle == 0 is reserved (= "null handle").
 *
 * The per-WebGPU-call command body that lives inside a CMD frame is
 * generated by src/yetty/yrdawn/generate.py and is NOT defined here —
 * this header pins only the outer frame shape and the meta channel
 * (HELLO/REPLY/EVENT/BULK/ERROR/BYE).
 */
#ifndef YETTY_YRDAWN_WIRE_H
#define YETTY_YRDAWN_WIRE_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define YETTY_YRDAWN_HANDLE_NULL 0ull

/*=============================================================================
 * OSC code allocation
 *
 * Same policy as ymgui: 6xxxxx = client→server (remote → local yetty),
 * 7xxxxx = server→client. yrdawn owns the 62xxxx / 72xxxx block. Within
 * each direction the OSC code is the dispatch key — no body inspection
 * required to route.
 *===========================================================================*/

/* Remote (wasm) → local yetty. */
#define YETTY_YRDAWN_OSC_CS_HELLO 620000 /* yetty_yrdawn_wire_hello,     flag=0 */
#define YETTY_YRDAWN_OSC_CS_CMD 620001   /* yetty_yrdawn_wire_cmd_hdr,   flag=1 */
#define YETTY_YRDAWN_OSC_CS_BULK 620002  /* yetty_yrdawn_wire_bulk_hdr,  flag=1 */
#define YETTY_YRDAWN_OSC_CS_BYE 620003   /* yetty_yrdawn_wire_bye,       flag=0 */

/* Local yetty → remote (wasm). */
#define YETTY_YRDAWN_OSC_SC_HELLO_ACK 720000 /* yetty_yrdawn_wire_hello_ack, flag=0 */
#define YETTY_YRDAWN_OSC_SC_REPLY 720001     /* yetty_yrdawn_wire_reply_hdr, flag=0/1 */
#define YETTY_YRDAWN_OSC_SC_EVENT 720002     /* yetty_yrdawn_wire_event_hdr, flag=0 */
#define YETTY_YRDAWN_OSC_SC_BULK 720003      /* yetty_yrdawn_wire_bulk_hdr,  flag=1 */
#define YETTY_YRDAWN_OSC_SC_ERROR 720004     /* yetty_yrdawn_wire_error,     flag=0 */
#define YETTY_YRDAWN_OSC_SC_KEY 720100       /* yetty_yrdawn_wire_input_key,    flag=0 */
#define YETTY_YRDAWN_OSC_SC_RESIZE 720101    /* yetty_yrdawn_wire_input_resize, flag=0 */

/*=============================================================================
 * Magic + version
 *
 * Every payload starts with {magic, version, total_size, flags}. Magic
 * acts as a sanity tag (and a debugging anchor in hex dumps); version is
 * bumped whenever the meta-channel layout changes.
 *===========================================================================*/

#define YETTY_YRDAWN_WIRE_VERSION 1u

#define YETTY_YRDAWN_MAGIC_HELLO 0x4D4C4859u        /* "YHLM" */
#define YETTY_YRDAWN_MAGIC_HELLO_ACK 0x4D414859u    /* "YHAM" */
#define YETTY_YRDAWN_MAGIC_CMD 0x4D444D43u          /* "CMDM" */
#define YETTY_YRDAWN_MAGIC_REPLY 0x4D504552u        /* "REPM" */
#define YETTY_YRDAWN_MAGIC_EVENT 0x4D545645u        /* "EVTM" */
#define YETTY_YRDAWN_MAGIC_BULK 0x4D4B4C42u         /* "BLKM" */
#define YETTY_YRDAWN_MAGIC_ERROR 0x4D525245u        /* "ERRM" */
#define YETTY_YRDAWN_MAGIC_BYE 0x4D455942u          /* "BYEM" */
#define YETTY_YRDAWN_MAGIC_INPUT_KEY 0x4D59454Bu    /* "KEYM" */
#define YETTY_YRDAWN_MAGIC_INPUT_RESIZE 0x4D525352u /* "RSRM" */

/*=============================================================================
 * Protocol bootstrap — HELLO / HELLO_ACK
 *
 * The first frame the client sends; the server replies with HELLO_ACK.
 * Trivial connection sentinel — magic + version match is all that
 * gates the session.
 *===========================================================================*/

enum yetty_yrdawn_hello_status {
    YETTY_YRDAWN_HELLO_OK = 0,
    YETTY_YRDAWN_HELLO_REJECTED = 1,
};

struct yetty_yrdawn_wire_hello {
    uint32_t magic; /* YETTY_YRDAWN_MAGIC_HELLO */
    uint32_t version;
    uint32_t total_size; /* sizeof(this struct) */
    uint32_t _pad0;
};

struct yetty_yrdawn_wire_hello_ack {
    uint32_t magic; /* YETTY_YRDAWN_MAGIC_HELLO_ACK */
    uint32_t version;
    uint32_t total_size; /* sizeof(this struct) */
    uint32_t status;     /* enum yetty_yrdawn_hello_status */
};

struct yetty_yrdawn_wire_bye {
    uint32_t magic; /* YETTY_YRDAWN_MAGIC_BYE */
    uint32_t version;
    uint32_t total_size; /* sizeof(this struct) */
    uint32_t _pad0;
};

/*=============================================================================
 * Command channel — CMD
 *
 * Each WebGPU entrypoint maps to a method_id (assigned by tools/yrdawn-gen
 * from dawn.json position; the same hash that's baked into HELLO covers
 * the assignment). req_id is non-zero iff the entrypoint has a callback
 * (mapAsync, onSubmittedWorkDone, popErrorScope, requestAdapter,
 * requestDevice, getCompilationInfo). Sync calls send req_id = 0.
 *
 * The body that follows is method_id-specific: codegen emits the
 * encoder/decoder for each entrypoint. Most methods carry only POD
 * args + handle remappings inline; bulk payloads (writeBuffer/
 * writeTexture/createShaderModule source) sit in BULK frames and the
 * CMD body carries only a u32 payload_ref.
 *===========================================================================*/

struct yetty_yrdawn_wire_cmd_hdr {
    uint32_t magic; /* YETTY_YRDAWN_MAGIC_CMD */
    uint32_t version;
    uint32_t total_size; /* whole CMD payload incl. method body */
    uint32_t method_id;  /* codegen-assigned; see build-tools/yrdawn-gen output */
    uint32_t req_id;     /* 0 for sync; otherwise correlation id (non-zero) */
    uint32_t flags;      /* reserved, send 0 */
    /* Method-specific body follows. */
};

/*=============================================================================
 * Reply channel — REPLY
 *
 * Matches a CMD by req_id. kind discriminates between (a) a sync return
 * value for entrypoints that have one but no callback (e.g.
 * wgpuDeviceCreateBuffer returns immediately with a handle the *client*
 * already chose — REPLY in that case just confirms success), and (b)
 * the actual async callback firing (mapAsync done, etc.).
 *
 * For mapAsync read-mapped: when status == OK, payload_ref points at a
 * server→client BULK stream carrying the mapped bytes; the client's
 * pending entry stages them and the user's getMappedRange returns into
 * that staging arena.
 *===========================================================================*/

enum yetty_yrdawn_reply_kind {
    YETTY_YRDAWN_REPLY_SYNC = 0,  /* sync return for a CMD with no callback */
    YETTY_YRDAWN_REPLY_ASYNC = 1, /* async callback firing */
};

enum yetty_yrdawn_reply_status {
    YETTY_YRDAWN_REPLY_OK = 0,
    YETTY_YRDAWN_REPLY_VALIDATION_ERROR = 1, /* Dawn rejected the call */
    YETTY_YRDAWN_REPLY_OUT_OF_MEMORY = 2,
    YETTY_YRDAWN_REPLY_DEVICE_LOST = 3,
    YETTY_YRDAWN_REPLY_UNKNOWN_METHOD = 4,
    YETTY_YRDAWN_REPLY_INTERNAL = 5,
};

struct yetty_yrdawn_wire_reply_hdr {
    uint32_t magic; /* YETTY_YRDAWN_MAGIC_REPLY */
    uint32_t version;
    uint32_t total_size;  /* whole REPLY payload incl. method-specific body */
    uint32_t req_id;      /* matches the originating CMD's req_id (non-zero) */
    uint32_t method_id;   /* echoed for client-side dispatch */
    uint32_t kind;        /* enum yetty_yrdawn_reply_kind */
    uint32_t status;      /* enum yetty_yrdawn_reply_status */
    uint32_t payload_ref; /* 0 if no bulk payload, else BULK ref id */
    /* Method-specific reply body follows (e.g. CompilationInfoCallbackInfo
     * fields for getCompilationInfo). */
};

/*=============================================================================
 * Event channel — EVENT
 *
 * Unsolicited callbacks not tied to a req_id: device-lost, uncaptured-
 * error, queue-internal events. device_handle pins the EVENT to the
 * client-side device object so multiple devices on one connection route
 * correctly.
 *===========================================================================*/

enum yetty_yrdawn_event_kind {
    YETTY_YRDAWN_EVENT_DEVICE_LOST = 0,
    YETTY_YRDAWN_EVENT_UNCAPTURED_ERROR = 1,
    YETTY_YRDAWN_EVENT_LOGGING = 2,
};

struct yetty_yrdawn_wire_event_hdr {
    uint32_t magic; /* YETTY_YRDAWN_MAGIC_EVENT */
    uint32_t version;
    uint32_t total_size;
    uint32_t kind;          /* enum yetty_yrdawn_event_kind */
    uint64_t device_handle; /* the affected device's u64 handle */
    /* kind-specific body follows (reason code + UTF-8 message). */
};

/*=============================================================================
 * Bulk channel — BULK
 *
 * Big payloads (texture / buffer uploads, shader source, mapAsync
 * readback) ride a separate OSC code so the framer doesn't stall the
 * command stream behind a multi-megabyte payload. A CMD or REPLY frame
 * carries a payload_ref; the matching bytes arrive in one or more BULK
 * frames bearing the same ref. The receiver buffers chunks into a
 * per-ref staging arena and dispatches the dependent CMD/REPLY once
 * last_chunk = 1 lands.
 *
 * Chunk size is up to the sender; aligning at the existing 64KB lz4F
 * block in wire-statemachine.c avoids fighting the envelope but is not
 * required.
 *===========================================================================*/

#define YETTY_YRDAWN_BULK_FLAG_LAST (1u << 0) /* this is the final chunk for ref */

struct yetty_yrdawn_wire_bulk_hdr {
    uint32_t magic; /* YETTY_YRDAWN_MAGIC_BULK */
    uint32_t version;
    uint32_t total_size; /* sizeof header + chunk_size */
    uint32_t ref;        /* payload_ref this chunk belongs to (non-zero) */
    uint32_t seq;        /* 0-based chunk index within ref */
    uint32_t flags;      /* YETTY_YRDAWN_BULK_FLAG_* */
    uint32_t chunk_size; /* bytes of payload that follow this header */
    uint32_t _pad0;
    /* chunk_size bytes follow. */
};

/*=============================================================================
 * Protocol-level error — ERROR
 *
 * Server emits this only for protocol-level faults (malformed frame,
 * unknown method_id without HELLO, BULK ref leak). WebGPU validation
 * errors travel as REPLY with status != OK or as EVENT_UNCAPTURED_ERROR
 * — they are not protocol errors. After ERROR the server typically
 * tears down the session; the client may attempt re-HELLO.
 *===========================================================================*/

enum yetty_yrdawn_error_code {
    YETTY_YRDAWN_ERR_MALFORMED = 1,
    YETTY_YRDAWN_ERR_NO_HELLO = 2,
    YETTY_YRDAWN_ERR_UNKNOWN_METHOD = 3,
    YETTY_YRDAWN_ERR_UNKNOWN_HANDLE = 4,
    YETTY_YRDAWN_ERR_BULK_REF_LEAK = 5,
    YETTY_YRDAWN_ERR_INTERNAL = 6,
};

struct yetty_yrdawn_wire_error {
    uint32_t magic; /* YETTY_YRDAWN_MAGIC_ERROR */
    uint32_t version;
    uint32_t total_size;
    uint32_t code; /* enum yetty_yrdawn_error_code */
    /* UTF-8 reason string follows, length = total_size - sizeof header. */
};

/*=============================================================================
 * Input — keyboard
 *
 * Mirrors ymgui's input model. CHAR carries a Unicode codepoint (text
 * input, modifier-sensitive); DOWN/UP carry a GLFW-compatible keycode
 * for non-text keys. mods is the GLFW mod bitmask
 * (SHIFT=1, CTRL=2, ALT=4, SUPER=8).
 *
 * The wasm app's pump() routes this to its input_cb. Mouse/resize will
 * be added under the same 7201xx block as the layer learns to hit-test
 * its sub-region of the terminal pane.
 *===========================================================================*/

enum yetty_yrdawn_input_key_kind {
    YETTY_YRDAWN_INPUT_KEY_DOWN = 0,
    YETTY_YRDAWN_INPUT_KEY_UP = 1,
    YETTY_YRDAWN_INPUT_KEY_CHAR = 2,
};

struct yetty_yrdawn_wire_input_key {
    uint32_t magic; /* YETTY_YRDAWN_MAGIC_INPUT_KEY */
    uint32_t version;
    uint32_t total_size;
    uint32_t kind;      /* enum yetty_yrdawn_input_key_kind */
    int32_t key;        /* GLFW keycode for DOWN/UP, -1 for CHAR */
    int32_t mods;       /* GLFW mod bitmask */
    uint32_t codepoint; /* CHAR only; 0 otherwise */
    uint32_t _pad0;
};

/* Pane (sub-region the layer occupies) pixel size changed. The client
 * uses (width, height) to reconfigure its swapchain-equivalent. */
struct yetty_yrdawn_wire_input_resize {
    uint32_t magic; /* YETTY_YRDAWN_MAGIC_INPUT_RESIZE */
    uint32_t version;
    uint32_t total_size;
    uint32_t _pad0;
    float width;  /* pixels */
    float height; /* pixels */
};

#ifdef __cplusplus
}
#endif

#endif /* YETTY_YRDAWN_WIRE_H */
