/*
 * yrdawn/wire.h — wire format for the WebGPU-over-OSC bridge.
 *
 * yrdawn rides the figure-tree OSC channel exactly like ymgui: every
 * client→server message is a record inside YETTY_DCS_YCOMPOSITOR_BIN
 * (see <yetty/yterminal/osc-codes.h>) of shape `{u32 length, u32 id,
 * body}`. `id == 0` means container-admin (CREATE_CHILD / DELETE_CHILD
 * / SET_CHILD_RECT — see <yetty/yfigure/wire.h>); `id != 0` addresses
 * a specific yrdawn figure (== one remote canvas) and the body starts
 * with a u32 SUB_OP discriminator chosen from `enum
 * yetty_yrdawn_figure_sub_op` below.
 *
 * Server→client messages keep dedicated OSC codes in the 72xxxx range
 * because there is no figure-tree on the server-to-client direction —
 * the client multiplexes incoming envelopes by the `figure_id` carried
 * inside every SC struct.
 *
 * Sessions: every wasm process is one yrdawn client and owns N canvases.
 * The shared WGPU handle table (instance/adapter/device/buffers/...) lives
 * on the server-side session. session_id is client-chosen at startup and
 * embedded in every SUB_HELLO; multiple yrdawn processes on the same PTY
 * each pick their own session_id so the server keeps their handle tables
 * apart.
 *
 * Envelope (yface):
 *     \e]<code>;<flag>;<base64[(LZ4F)payload]>\e\\
 *
 * <flag> = '0' raw, '1' lz4f+b64. All integers little-endian; structs
 * naturally aligned at 4 B. Handles are opaque u64 chosen client-side;
 * handle == 0 reserved (== "null handle").
 *
 * The per-WebGPU-call body inside SUB_CMD is generated by
 * src/yetty/yrdawn/generate.py and NOT defined here — this header pins
 * only the outer record shape, sub-op discriminator, and the meta
 * channel (HELLO/REPLY/EVENT/BULK/ERROR/BYE).
 */
#ifndef YETTY_YRDAWN_WIRE_H
#define YETTY_YRDAWN_WIRE_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define YETTY_YRDAWN_HANDLE_NULL 0ull

/*=============================================================================
 * Server→client OSC codes
 *
 * 72xxxx block. CS direction has no per-message codes any more — every
 * client→server message rides YETTY_DCS_YCOMPOSITOR_BIN as a sub-record.
 *===========================================================================*/

#define YETTY_YRDAWN_OSC_SC_HELLO_ACK 720000 /* yetty_yrdawn_wire_hello_ack, flag=0 */
#define YETTY_YRDAWN_OSC_SC_REPLY 720001     /* yetty_yrdawn_wire_reply_hdr, flag=0/1 */
#define YETTY_YRDAWN_OSC_SC_EVENT 720002     /* yetty_yrdawn_wire_event_hdr, flag=0 */
#define YETTY_YRDAWN_OSC_SC_BULK 720003      /* yetty_yrdawn_wire_bulk_hdr,  flag=1 */
#define YETTY_YRDAWN_OSC_SC_ERROR 720004     /* yetty_yrdawn_wire_error,     flag=0 */
#define YETTY_YRDAWN_OSC_SC_KEY 720100       /* yetty_yrdawn_wire_input_key,    flag=0 */
#define YETTY_YRDAWN_OSC_SC_RESIZE 720101    /* yetty_yrdawn_wire_input_resize, flag=0 */

/*=============================================================================
 * Sub-op discriminator
 *
 * Every body of an id!=0 figure-tree record begins with a u32 picked
 * from this enum, followed by the matching wire struct (the existing
 * hello / cmd_hdr / bulk_hdr / bye structs; their `magic` field
 * doubles as a sanity check).
 *===========================================================================*/

enum yetty_yrdawn_figure_sub_op {
    YETTY_YRDAWN_FIGURE_SUB_HELLO = 1, /* + yetty_yrdawn_wire_hello       */
    YETTY_YRDAWN_FIGURE_SUB_CMD = 2,   /* + yetty_yrdawn_wire_cmd_hdr +body */
    YETTY_YRDAWN_FIGURE_SUB_BULK = 3,  /* + yetty_yrdawn_wire_bulk_hdr+body */
    YETTY_YRDAWN_FIGURE_SUB_BYE = 4,   /* + yetty_yrdawn_wire_bye         */
};

/*=============================================================================
 * Magic + version
 *
 * Every payload starts with {magic, version, ...}. Magic is a sanity tag.
 * Version is bumped whenever the meta-channel layout changes.
 *===========================================================================*/

#define YETTY_YRDAWN_WIRE_VERSION 2u

#define YETTY_YRDAWN_MAGIC_HELLO 0x4D4C4859u        /* "YHLM" */
#define YETTY_YRDAWN_MAGIC_HELLO_ACK 0x4D414859u    /* "YHAM" */
#define YETTY_YRDAWN_MAGIC_CMD 0x4D444D43u          /* "CMDM" */
#define YETTY_YRDAWN_MAGIC_REPLY 0x4D504552u        /* "REPM" */
#define YETTY_YRDAWN_MAGIC_EVENT 0x4D545645u        /* "EVTM" */
#define YETTY_YRDAWN_MAGIC_BULK 0x4D4B4C42u         /* "BLKM" */
#define YETTY_YRDAWN_MAGIC_ERROR 0x4D525245u        /* "ERRM" */
#define YETTY_YRDAWN_MAGIC_BYE 0x4D455942u          /* "BYEM" */
#define YETTY_YRDAWN_MAGIC_INPUT_KEY 0x4D59454Bu    /* "KEYM" */
#define YETTY_YRDAWN_MAGIC_INPUT_RESIZE 0x4D525352u /* "RSRM" */

/*=============================================================================
 * Protocol bootstrap — HELLO / HELLO_ACK
 *
 * HELLO travels as the body of the CREATE_CHILD admin record's
 * `init_payload` (kind=YRDAWN). The figure factory reads it, looks up
 * the session by `session_id` (lazy-creating it), and replies with a
 * HELLO_ACK SC envelope carrying the same session_id + the assigned
 * figure_id. Once HELLO_ACK is dispatched, ordinary SUB_CMD records
 * for this figure are accepted.
 *
 * Multiple canvases owned by one client share one session_id —
 * subsequent CREATE_CHILD records carrying the same session_id are
 * bound to the existing session rather than minting a new one.
 *===========================================================================*/

enum yetty_yrdawn_hello_status {
    YETTY_YRDAWN_HELLO_OK = 0,
    YETTY_YRDAWN_HELLO_REJECTED = 1,
};

struct yetty_yrdawn_wire_hello {
    uint32_t magic; /* YETTY_YRDAWN_MAGIC_HELLO */
    uint32_t version;
    uint32_t total_size; /* sizeof(this struct) */
    uint32_t session_id; /* client-chosen, non-zero, stable per process */
    uint32_t figure_id;  /* MUST match the CREATE_CHILD admin's child_id */
    uint32_t _pad0;
};

struct yetty_yrdawn_wire_hello_ack {
    uint32_t magic; /* YETTY_YRDAWN_MAGIC_HELLO_ACK */
    uint32_t version;
    uint32_t total_size; /* sizeof(this struct) */
    uint32_t status;     /* enum yetty_yrdawn_hello_status */
    uint32_t session_id; /* echoed from HELLO so the client can match */
    uint32_t figure_id;  /* assigned canvas id */
};

struct yetty_yrdawn_wire_bye {
    uint32_t magic; /* YETTY_YRDAWN_MAGIC_BYE */
    uint32_t version;
    uint32_t total_size; /* sizeof(this struct) */
    uint32_t _pad0;
};

/*=============================================================================
 * Command channel — CMD
 *
 * Each WebGPU entrypoint maps to a method_id (assigned by
 * tools/yrdawn-gen from dawn.json position). req_id is non-zero iff the
 * entrypoint has a callback. Sync calls send req_id = 0.
 *
 * The body that follows is method_id-specific: codegen emits the
 * encoder/decoder for each entrypoint. Most methods carry only POD
 * args + handle remappings inline; bulk payloads (writeBuffer /
 * writeTexture / createShaderModule source) sit in BULK frames and the
 * CMD body carries only a u32 payload_ref.
 *===========================================================================*/

struct yetty_yrdawn_wire_cmd_hdr {
    uint32_t magic; /* YETTY_YRDAWN_MAGIC_CMD */
    uint32_t version;
    uint32_t total_size; /* whole CMD payload incl. method body */
    uint32_t method_id;  /* codegen-assigned; see build-tools/yrdawn-gen output */
    uint32_t req_id;     /* 0 for sync; otherwise correlation id (non-zero) */
    uint32_t flags;      /* reserved, send 0 */
    /* Method-specific body follows. */
};

/*=============================================================================
 * Reply channel — REPLY
 *
 * Matches a CMD by req_id. kind discriminates between (a) a sync return
 * value for entrypoints that have one but no callback, and (b) the
 * actual async callback firing.
 *
 * `figure_id` lets the client demux: the same client process may have
 * multiple canvases and each per-canvas reply table is keyed by it.
 *===========================================================================*/

enum yetty_yrdawn_reply_kind {
    YETTY_YRDAWN_REPLY_SYNC = 0,  /* sync return for a CMD with no callback */
    YETTY_YRDAWN_REPLY_ASYNC = 1, /* async callback firing */
};

enum yetty_yrdawn_reply_status {
    YETTY_YRDAWN_REPLY_OK = 0,
    YETTY_YRDAWN_REPLY_VALIDATION_ERROR = 1, /* Dawn rejected the call */
    YETTY_YRDAWN_REPLY_OUT_OF_MEMORY = 2,
    YETTY_YRDAWN_REPLY_DEVICE_LOST = 3,
    YETTY_YRDAWN_REPLY_UNKNOWN_METHOD = 4,
    YETTY_YRDAWN_REPLY_INTERNAL = 5,
};

/* Human-readable name for a reply status, for diagnostics/logging. Returns a
 * static string ("ok", "validation-error", …); never NULL. Unknown values map
 * to "unknown". Inline so both the client (yetty_yrdawn) and server
 * (yetty_yrdawn_server) libraries get it without a cross-library dependency. */
static inline const char *yetty_yrdawn_reply_status_str(uint32_t status)
{
    switch (status) {
    case YETTY_YRDAWN_REPLY_OK:
        return "ok";
    case YETTY_YRDAWN_REPLY_VALIDATION_ERROR:
        return "validation-error";
    case YETTY_YRDAWN_REPLY_OUT_OF_MEMORY:
        return "out-of-memory";
    case YETTY_YRDAWN_REPLY_DEVICE_LOST:
        return "device-lost";
    case YETTY_YRDAWN_REPLY_UNKNOWN_METHOD:
        return "unknown-method";
    case YETTY_YRDAWN_REPLY_INTERNAL:
        return "internal-error";
    default:
        return "unknown";
    }
}

/* On an error reply (status != OK) the server appends a NUL-terminated, UTF-8
 * description after the reply header so the client can log a clear message
 * instead of a bare numeric status. The OK path keeps the method-specific
 * reply body unchanged. */

struct yetty_yrdawn_wire_reply_hdr {
    uint32_t magic; /* YETTY_YRDAWN_MAGIC_REPLY */
    uint32_t version;
    uint32_t total_size;  /* whole REPLY payload incl. method-specific body */
    uint32_t req_id;      /* matches the originating CMD's req_id (non-zero) */
    uint32_t method_id;   /* echoed for client-side dispatch */
    uint32_t kind;        /* enum yetty_yrdawn_reply_kind */
    uint32_t status;      /* enum yetty_yrdawn_reply_status */
    uint32_t payload_ref; /* 0 if no bulk payload, else BULK ref id */
    uint32_t figure_id;   /* canvas the originating CMD targeted */
    uint32_t _pad0;
    /* Method-specific reply body follows. */
};

/*=============================================================================
 * Event channel — EVENT
 *
 * Unsolicited callbacks not tied to a req_id: device-lost,
 * uncaptured-error, queue-internal events. device_handle pins the EVENT
 * to a specific WGPUDevice; figure_id pins it to the canvas whose
 * activity triggered it (so the client can route to the right
 * per-canvas handler even when the device is shared).
 *===========================================================================*/

enum yetty_yrdawn_event_kind {
    YETTY_YRDAWN_EVENT_DEVICE_LOST = 0,
    YETTY_YRDAWN_EVENT_UNCAPTURED_ERROR = 1,
    YETTY_YRDAWN_EVENT_LOGGING = 2,
};

struct yetty_yrdawn_wire_event_hdr {
    uint32_t magic; /* YETTY_YRDAWN_MAGIC_EVENT */
    uint32_t version;
    uint32_t total_size;
    uint32_t kind;          /* enum yetty_yrdawn_event_kind */
    uint64_t device_handle; /* the affected device's u64 handle */
    uint32_t figure_id;     /* originating canvas */
    uint32_t _pad0;
    /* kind-specific body follows (reason code + UTF-8 message). */
};

/*=============================================================================
 * Bulk channel — BULK
 *
 * Big payloads ride a separate OSC code on the SC direction so the
 * framer doesn't stall behind a multi-MB blob. On the CS direction
 * BULK is just another SUB_BULK record inside the figure-tree
 * envelope.
 *
 * A CMD or REPLY carries a payload_ref; the matching bytes arrive in
 * one or more BULK frames bearing the same ref. The receiver buffers
 * chunks into a per-ref staging arena (lives on the session, not the
 * figure) and dispatches the dependent CMD/REPLY once
 * YETTY_YRDAWN_BULK_FLAG_LAST lands.
 *
 * Chunk size is up to the sender; aligning at the existing 64KB lz4f
 * block avoids fighting the envelope.
 *===========================================================================*/

#define YETTY_YRDAWN_BULK_FLAG_LAST (1u << 0) /* this is the final chunk for ref */

struct yetty_yrdawn_wire_bulk_hdr {
    uint32_t magic; /* YETTY_YRDAWN_MAGIC_BULK */
    uint32_t version;
    uint32_t total_size; /* sizeof header + chunk_size */
    uint32_t ref;        /* payload_ref this chunk belongs to (non-zero) */
    uint32_t seq;        /* 0-based chunk index within ref */
    uint32_t flags;      /* YETTY_YRDAWN_BULK_FLAG_* */
    uint32_t chunk_size; /* bytes of payload that follow this header */
    uint32_t figure_id;  /* canvas that ref belongs to (== session scope) */
    /* chunk_size bytes follow. */
};

/*=============================================================================
 * Protocol-level error — ERROR
 *===========================================================================*/

enum yetty_yrdawn_error_code {
    YETTY_YRDAWN_ERR_MALFORMED = 1,
    YETTY_YRDAWN_ERR_NO_HELLO = 2,
    YETTY_YRDAWN_ERR_UNKNOWN_METHOD = 3,
    YETTY_YRDAWN_ERR_UNKNOWN_HANDLE = 4,
    YETTY_YRDAWN_ERR_BULK_REF_LEAK = 5,
    YETTY_YRDAWN_ERR_INTERNAL = 6,
};

struct yetty_yrdawn_wire_error {
    uint32_t magic; /* YETTY_YRDAWN_MAGIC_ERROR */
    uint32_t version;
    uint32_t total_size;
    uint32_t code;      /* enum yetty_yrdawn_error_code */
    uint32_t figure_id; /* 0 if session-wide / pre-binding error */
    uint32_t _pad0;
    /* UTF-8 reason string follows, length = total_size - sizeof header. */
};

/*=============================================================================
 * Input — keyboard
 *===========================================================================*/

enum yetty_yrdawn_input_key_kind {
    YETTY_YRDAWN_INPUT_KEY_DOWN = 0,
    YETTY_YRDAWN_INPUT_KEY_UP = 1,
    YETTY_YRDAWN_INPUT_KEY_CHAR = 2,
};

struct yetty_yrdawn_wire_input_key {
    uint32_t magic; /* YETTY_YRDAWN_MAGIC_INPUT_KEY */
    uint32_t version;
    uint32_t total_size;
    uint32_t kind;      /* enum yetty_yrdawn_input_key_kind */
    int32_t key;        /* GLFW keycode for DOWN/UP, -1 for CHAR */
    int32_t mods;       /* GLFW mod bitmask */
    uint32_t codepoint; /* CHAR only; 0 otherwise */
    uint32_t figure_id; /* canvas that received the keystroke (focused) */
};

/* Pane (the canvas figure's rect) pixel size changed. */
struct yetty_yrdawn_wire_input_resize {
    uint32_t magic; /* YETTY_YRDAWN_MAGIC_INPUT_RESIZE */
    uint32_t version;
    uint32_t total_size;
    uint32_t figure_id; /* the resized canvas */
    float width;        /* pixels */
    float height;       /* pixels */
};

#ifdef __cplusplus
}
#endif

#endif /* YETTY_YRDAWN_WIRE_H */
