// Auto-generated from yfsvm-opcodes.yaml - DO NOT EDIT
// Generated by: src/yetty/yfsvm/gen-yfsvm-code.py

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// Constants
#define YFSVM_MAGIC 0x5946534Du
#define YFSVM_VERSION 1u
#define YFSVM_MAX_REGISTERS 16u
#define YFSVM_MAX_FUNCTIONS 16u
#define YFSVM_MAX_CONSTANTS 4096u
#define YFSVM_MAX_INSTRUCTIONS 256u
#define YFSVM_MAX_EXECUTION_STEPS 1024u

// Opcodes
typedef enum yetty_yfsvm_YfsvmOpcode {
    YETTY_YFSVM_OP_NOP = 0x00,
    YETTY_YFSVM_OP_RET = 0x01,
    YETTY_YFSVM_OP_LOAD_C = 0x02,
    YETTY_YFSVM_OP_LOAD_X = 0x03,
    YETTY_YFSVM_OP_LOAD_T = 0x04,
    YETTY_YFSVM_OP_LOAD_S = 0x05,
    YETTY_YFSVM_OP_MOV = 0x06,
    YETTY_YFSVM_OP_LOAD_Y = 0x07,
    YETTY_YFSVM_OP_ADD = 0x10,
    YETTY_YFSVM_OP_SUB = 0x11,
    YETTY_YFSVM_OP_MUL = 0x12,
    YETTY_YFSVM_OP_DIV = 0x13,
    YETTY_YFSVM_OP_NEG = 0x14,
    YETTY_YFSVM_OP_MOD = 0x15,
    YETTY_YFSVM_OP_SIN = 0x20,
    YETTY_YFSVM_OP_COS = 0x21,
    YETTY_YFSVM_OP_TAN = 0x22,
    YETTY_YFSVM_OP_ASIN = 0x23,
    YETTY_YFSVM_OP_ACOS = 0x24,
    YETTY_YFSVM_OP_ATAN = 0x25,
    YETTY_YFSVM_OP_ATAN2 = 0x26,
    YETTY_YFSVM_OP_SINH = 0x27,
    YETTY_YFSVM_OP_COSH = 0x28,
    YETTY_YFSVM_OP_TANH = 0x29,
    YETTY_YFSVM_OP_ASINH = 0x2A,
    YETTY_YFSVM_OP_ACOSH = 0x2B,
    YETTY_YFSVM_OP_ATANH = 0x2C,
    YETTY_YFSVM_OP_SINC = 0x2D,
    YETTY_YFSVM_OP_EXP = 0x30,
    YETTY_YFSVM_OP_EXP2 = 0x31,
    YETTY_YFSVM_OP_LOG = 0x32,
    YETTY_YFSVM_OP_LOG2 = 0x33,
    YETTY_YFSVM_OP_POW = 0x34,
    YETTY_YFSVM_OP_SQRT = 0x35,
    YETTY_YFSVM_OP_RSQRT = 0x36,
    YETTY_YFSVM_OP_ERF = 0x37,
    YETTY_YFSVM_OP_ERFC = 0x38,
    YETTY_YFSVM_OP_ABS = 0x40,
    YETTY_YFSVM_OP_MIN = 0x41,
    YETTY_YFSVM_OP_MAX = 0x42,
    YETTY_YFSVM_OP_FLOOR = 0x43,
    YETTY_YFSVM_OP_CEIL = 0x44,
    YETTY_YFSVM_OP_ROUND = 0x45,
    YETTY_YFSVM_OP_FRACT = 0x46,
    YETTY_YFSVM_OP_SIGN = 0x47,
    YETTY_YFSVM_OP_CLAMP01 = 0x48,
    YETTY_YFSVM_OP_STEP = 0x49,
    YETTY_YFSVM_OP_MIX = 0x4A,
    YETTY_YFSVM_OP_SMOOTHSTEP = 0x4B,
    YETTY_YFSVM_OP_TRUNC = 0x4C,
    YETTY_YFSVM_OP_RADIANS = 0x4D,
    YETTY_YFSVM_OP_DEGREES = 0x4E,
    YETTY_YFSVM_OP_SELECT = 0x4F,
    YETTY_YFSVM_OP_LT = 0x50,
    YETTY_YFSVM_OP_GT = 0x51,
    YETTY_YFSVM_OP_LE = 0x52,
    YETTY_YFSVM_OP_GE = 0x53,
    YETTY_YFSVM_OP_EQ = 0x54,
    YETTY_YFSVM_OP_NE = 0x55,
    YETTY_YFSVM_OP_RAND = 0x60,
    YETTY_YFSVM_OP_NOISE = 0x61,
} YfsvmOpcode;

// Instruction format (32-bit):
//   [31:24] opcode (8 bits)
//   [23:20] dst    (4 bits)
//   [19:16] src1   (4 bits)
//   [15:12] src2   (4 bits)
//   [11:0]  imm12  (12 bits)

// Encode instruction
static inline uint32_t yfsvm_encode(YfsvmOpcode op, uint8_t dst, uint8_t src1, uint8_t src2,
                                    uint16_t imm12)
{
    return ((uint32_t)op << 24) | ((dst & 0xF) << 20) | ((src1 & 0xF) << 16) |
           ((src2 & 0xF) << 12) | (imm12 & 0xFFF);
}

// Decode instruction
static inline YfsvmOpcode yfsvm_decode_opcode(uint32_t instr)
{
    return (YfsvmOpcode)((instr >> 24) & 0xFF);
}
static inline uint8_t yfsvm_decode_dst(uint32_t instr)
{
    return (instr >> 20) & 0xF;
}
static inline uint8_t yfsvm_decode_src1(uint32_t instr)
{
    return (instr >> 16) & 0xF;
}
static inline uint8_t yfsvm_decode_src2(uint32_t instr)
{
    return (instr >> 12) & 0xF;
}
static inline uint16_t yfsvm_decode_imm12(uint32_t instr)
{
    return instr & 0xFFF;
}

// Get opcode name for debugging
static inline const char *yfsvm_opcode_name(YfsvmOpcode op)
{
    switch (op) {
    case YETTY_YFSVM_OP_NOP:
        return "NOP";
    case YETTY_YFSVM_OP_RET:
        return "RET";
    case YETTY_YFSVM_OP_LOAD_C:
        return "LOAD_C";
    case YETTY_YFSVM_OP_LOAD_X:
        return "LOAD_X";
    case YETTY_YFSVM_OP_LOAD_T:
        return "LOAD_T";
    case YETTY_YFSVM_OP_LOAD_S:
        return "LOAD_S";
    case YETTY_YFSVM_OP_MOV:
        return "MOV";
    case YETTY_YFSVM_OP_LOAD_Y:
        return "LOAD_Y";
    case YETTY_YFSVM_OP_ADD:
        return "ADD";
    case YETTY_YFSVM_OP_SUB:
        return "SUB";
    case YETTY_YFSVM_OP_MUL:
        return "MUL";
    case YETTY_YFSVM_OP_DIV:
        return "DIV";
    case YETTY_YFSVM_OP_NEG:
        return "NEG";
    case YETTY_YFSVM_OP_MOD:
        return "MOD";
    case YETTY_YFSVM_OP_SIN:
        return "SIN";
    case YETTY_YFSVM_OP_COS:
        return "COS";
    case YETTY_YFSVM_OP_TAN:
        return "TAN";
    case YETTY_YFSVM_OP_ASIN:
        return "ASIN";
    case YETTY_YFSVM_OP_ACOS:
        return "ACOS";
    case YETTY_YFSVM_OP_ATAN:
        return "ATAN";
    case YETTY_YFSVM_OP_ATAN2:
        return "ATAN2";
    case YETTY_YFSVM_OP_SINH:
        return "SINH";
    case YETTY_YFSVM_OP_COSH:
        return "COSH";
    case YETTY_YFSVM_OP_TANH:
        return "TANH";
    case YETTY_YFSVM_OP_ASINH:
        return "ASINH";
    case YETTY_YFSVM_OP_ACOSH:
        return "ACOSH";
    case YETTY_YFSVM_OP_ATANH:
        return "ATANH";
    case YETTY_YFSVM_OP_SINC:
        return "SINC";
    case YETTY_YFSVM_OP_EXP:
        return "EXP";
    case YETTY_YFSVM_OP_EXP2:
        return "EXP2";
    case YETTY_YFSVM_OP_LOG:
        return "LOG";
    case YETTY_YFSVM_OP_LOG2:
        return "LOG2";
    case YETTY_YFSVM_OP_POW:
        return "POW";
    case YETTY_YFSVM_OP_SQRT:
        return "SQRT";
    case YETTY_YFSVM_OP_RSQRT:
        return "RSQRT";
    case YETTY_YFSVM_OP_ERF:
        return "ERF";
    case YETTY_YFSVM_OP_ERFC:
        return "ERFC";
    case YETTY_YFSVM_OP_ABS:
        return "ABS";
    case YETTY_YFSVM_OP_MIN:
        return "MIN";
    case YETTY_YFSVM_OP_MAX:
        return "MAX";
    case YETTY_YFSVM_OP_FLOOR:
        return "FLOOR";
    case YETTY_YFSVM_OP_CEIL:
        return "CEIL";
    case YETTY_YFSVM_OP_ROUND:
        return "ROUND";
    case YETTY_YFSVM_OP_FRACT:
        return "FRACT";
    case YETTY_YFSVM_OP_SIGN:
        return "SIGN";
    case YETTY_YFSVM_OP_CLAMP01:
        return "CLAMP01";
    case YETTY_YFSVM_OP_STEP:
        return "STEP";
    case YETTY_YFSVM_OP_MIX:
        return "MIX";
    case YETTY_YFSVM_OP_SMOOTHSTEP:
        return "SMOOTHSTEP";
    case YETTY_YFSVM_OP_TRUNC:
        return "TRUNC";
    case YETTY_YFSVM_OP_RADIANS:
        return "RADIANS";
    case YETTY_YFSVM_OP_DEGREES:
        return "DEGREES";
    case YETTY_YFSVM_OP_SELECT:
        return "SELECT";
    case YETTY_YFSVM_OP_LT:
        return "LT";
    case YETTY_YFSVM_OP_GT:
        return "GT";
    case YETTY_YFSVM_OP_LE:
        return "LE";
    case YETTY_YFSVM_OP_GE:
        return "GE";
    case YETTY_YFSVM_OP_EQ:
        return "EQ";
    case YETTY_YFSVM_OP_NE:
        return "NE";
    case YETTY_YFSVM_OP_RAND:
        return "RAND";
    case YETTY_YFSVM_OP_NOISE:
        return "NOISE";
    default:
        return "UNKNOWN";
    }
}

#ifdef __cplusplus
}
#endif