// Auto-generated from yvideo.yaml - DO NOT EDIT
// Uniform accessors - read from uniforms struct generated by binder
// Buffer accessors - read from storage buffer

// Uniform accessors

fn yvideo_get_bounds_x() -> f32 {
    return uniforms.yvideo_bounds_x;
}

fn yvideo_get_bounds_y() -> f32 {
    return uniforms.yvideo_bounds_y;
}

fn yvideo_get_bounds_w() -> f32 {
    return uniforms.yvideo_bounds_w;
}

fn yvideo_get_bounds_h() -> f32 {
    return uniforms.yvideo_bounds_h;
}

fn yvideo_get_video_w() -> u32 {
    return uniforms.yvideo_video_w;
}

fn yvideo_get_video_h() -> u32 {
    return uniforms.yvideo_video_h;
}

fn yvideo_get_fps() -> f32 {
    return uniforms.yvideo_fps;
}

fn yvideo_get_color_matrix() -> u32 {
    return uniforms.yvideo_color_matrix;
}

fn yvideo_get_flags() -> u32 {
    return uniforms.yvideo_flags;
}

// Buffer data is in storage_buffer (binding 1+)
// Access via: storage_buffer[offset]

