/* Generated by src/yetty/ywasm/generate.py — DO NOT EDIT. */
#ifndef YETTY_YWASM_METHODS_GEN_H
#define YETTY_YWASM_METHODS_GEN_H

#include <stdint.h>

/* Brings in WGPU* by-value struct types (WGPUColor, WGPUExtent3D, …)
 * referenced by auto-generated args structs. The wire layout reuses
 * the C layout because both client and server are C and use the
 * same webgpu.h. */
#include <webgpu/webgpu.h>

#include <yetty/ycore/result.h>

#ifdef __cplusplus
extern "C" {
#endif

enum yetty_ywasm_method_id {
    YETTY_YWASM_METHOD_INVALID = 0,
    YETTY_YWASM_METHOD_wgpuCreateInstance = 1,
    YETTY_YWASM_METHOD_wgpuInstanceRelease = 2,
    YETTY_YWASM_METHOD_wgpuDeviceTick = 3,
    YETTY_YWASM_METHOD_wgpuDeviceGetQueue = 4,
    YETTY_YWASM_METHOD_wgpuQueueRelease = 5,
    YETTY_YWASM_METHOD_wgpuDeviceRelease = 6,
    YETTY_YWASM_METHOD_wgpuAdapterRelease = 7,
    YETTY_YWASM_METHOD_wgpuDeviceCreateCommandEncoder = 8,
    YETTY_YWASM_METHOD_wgpuCommandEncoderRelease = 9,
    YETTY_YWASM_METHOD_wgpuCommandEncoderFinish = 10,
    YETTY_YWASM_METHOD_wgpuCommandBufferRelease = 11,
    YETTY_YWASM_METHOD_wgpuInstanceRequestAdapter = 12,
    YETTY_YWASM_METHOD_wgpuAdapterRequestDevice = 13,
    YETTY_YWASM_METHOD_yetty_ywasm_present_frame = 100,
    YETTY_YWASM_METHOD_wgpuAdapterAddRef = 200,
    YETTY_YWASM_METHOD_wgpuAdapterCreateDevice = 201,
    YETTY_YWASM_METHOD_wgpuAdapterGetFeatures = 202,
    YETTY_YWASM_METHOD_wgpuAdapterGetFormatCapabilities = 203,
    YETTY_YWASM_METHOD_wgpuAdapterGetInfo = 204,
    YETTY_YWASM_METHOD_wgpuAdapterGetInstance = 205,
    YETTY_YWASM_METHOD_wgpuAdapterGetLimits = 206,
    YETTY_YWASM_METHOD_wgpuAdapterHasFeature = 207,
    YETTY_YWASM_METHOD_wgpuAdapterInfoFreeMembers = 208,
    YETTY_YWASM_METHOD_wgpuAdapterPropertiesMemoryHeapsFreeMembers = 209,
    YETTY_YWASM_METHOD_wgpuAdapterPropertiesSubgroupMatrixConfigsFreeMembers = 210,
    YETTY_YWASM_METHOD_wgpuBindGroupAddRef = 211,
    YETTY_YWASM_METHOD_wgpuBindGroupLayoutAddRef = 212,
    YETTY_YWASM_METHOD_wgpuBindGroupLayoutRelease = 213,
    YETTY_YWASM_METHOD_wgpuBindGroupLayoutSetLabel = 214,
    YETTY_YWASM_METHOD_wgpuBindGroupRelease = 215,
    YETTY_YWASM_METHOD_wgpuBindGroupSetLabel = 216,
    YETTY_YWASM_METHOD_wgpuBufferAddRef = 217,
    YETTY_YWASM_METHOD_wgpuBufferCreateTexelView = 218,
    YETTY_YWASM_METHOD_wgpuBufferDestroy = 219,
    YETTY_YWASM_METHOD_wgpuBufferGetConstMappedRange = 220,
    YETTY_YWASM_METHOD_wgpuBufferGetMapState = 221,
    YETTY_YWASM_METHOD_wgpuBufferGetMappedRange = 222,
    YETTY_YWASM_METHOD_wgpuBufferGetSize = 223,
    YETTY_YWASM_METHOD_wgpuBufferGetUsage = 224,
    YETTY_YWASM_METHOD_wgpuBufferMapAsync = 225,
    YETTY_YWASM_METHOD_wgpuBufferReadMappedRange = 226,
    YETTY_YWASM_METHOD_wgpuBufferRelease = 227,
    YETTY_YWASM_METHOD_wgpuBufferSetLabel = 228,
    YETTY_YWASM_METHOD_wgpuBufferUnmap = 229,
    YETTY_YWASM_METHOD_wgpuBufferWriteMappedRange = 230,
    YETTY_YWASM_METHOD_wgpuCommandBufferAddRef = 231,
    YETTY_YWASM_METHOD_wgpuCommandBufferSetLabel = 232,
    YETTY_YWASM_METHOD_wgpuCommandEncoderAddRef = 233,
    YETTY_YWASM_METHOD_wgpuCommandEncoderBeginComputePass = 234,
    YETTY_YWASM_METHOD_wgpuCommandEncoderBeginRenderPass = 235,
    YETTY_YWASM_METHOD_wgpuCommandEncoderClearBuffer = 236,
    YETTY_YWASM_METHOD_wgpuCommandEncoderCopyBufferToBuffer = 237,
    YETTY_YWASM_METHOD_wgpuCommandEncoderCopyBufferToTexture = 238,
    YETTY_YWASM_METHOD_wgpuCommandEncoderCopyTextureToBuffer = 239,
    YETTY_YWASM_METHOD_wgpuCommandEncoderCopyTextureToTexture = 240,
    YETTY_YWASM_METHOD_wgpuCommandEncoderInjectValidationError = 241,
    YETTY_YWASM_METHOD_wgpuCommandEncoderInsertDebugMarker = 242,
    YETTY_YWASM_METHOD_wgpuCommandEncoderPopDebugGroup = 243,
    YETTY_YWASM_METHOD_wgpuCommandEncoderPushDebugGroup = 244,
    YETTY_YWASM_METHOD_wgpuCommandEncoderResolveQuerySet = 245,
    YETTY_YWASM_METHOD_wgpuCommandEncoderSetLabel = 246,
    YETTY_YWASM_METHOD_wgpuCommandEncoderWriteBuffer = 247,
    YETTY_YWASM_METHOD_wgpuCommandEncoderWriteTimestamp = 248,
    YETTY_YWASM_METHOD_wgpuComputePassEncoderAddRef = 249,
    YETTY_YWASM_METHOD_wgpuComputePassEncoderDispatchWorkgroups = 250,
    YETTY_YWASM_METHOD_wgpuComputePassEncoderDispatchWorkgroupsIndirect = 251,
    YETTY_YWASM_METHOD_wgpuComputePassEncoderEnd = 252,
    YETTY_YWASM_METHOD_wgpuComputePassEncoderInsertDebugMarker = 253,
    YETTY_YWASM_METHOD_wgpuComputePassEncoderPopDebugGroup = 254,
    YETTY_YWASM_METHOD_wgpuComputePassEncoderPushDebugGroup = 255,
    YETTY_YWASM_METHOD_wgpuComputePassEncoderRelease = 256,
    YETTY_YWASM_METHOD_wgpuComputePassEncoderSetBindGroup = 257,
    YETTY_YWASM_METHOD_wgpuComputePassEncoderSetImmediates = 258,
    YETTY_YWASM_METHOD_wgpuComputePassEncoderSetLabel = 259,
    YETTY_YWASM_METHOD_wgpuComputePassEncoderSetPipeline = 260,
    YETTY_YWASM_METHOD_wgpuComputePassEncoderSetResourceTable = 261,
    YETTY_YWASM_METHOD_wgpuComputePassEncoderWriteTimestamp = 262,
    YETTY_YWASM_METHOD_wgpuComputePipelineAddRef = 263,
    YETTY_YWASM_METHOD_wgpuComputePipelineGetBindGroupLayout = 264,
    YETTY_YWASM_METHOD_wgpuComputePipelineRelease = 265,
    YETTY_YWASM_METHOD_wgpuComputePipelineSetLabel = 266,
    YETTY_YWASM_METHOD_wgpuDawnDrmFormatCapabilitiesFreeMembers = 267,
    YETTY_YWASM_METHOD_wgpuDeviceAddRef = 268,
    YETTY_YWASM_METHOD_wgpuDeviceCreateBindGroup = 269,
    YETTY_YWASM_METHOD_wgpuDeviceCreateBindGroupLayout = 270,
    YETTY_YWASM_METHOD_wgpuDeviceCreateBuffer = 271,
    YETTY_YWASM_METHOD_wgpuDeviceCreateComputePipeline = 272,
    YETTY_YWASM_METHOD_wgpuDeviceCreateComputePipelineAsync = 273,
    YETTY_YWASM_METHOD_wgpuDeviceCreateErrorBuffer = 274,
    YETTY_YWASM_METHOD_wgpuDeviceCreateErrorExternalTexture = 275,
    YETTY_YWASM_METHOD_wgpuDeviceCreateErrorShaderModule = 276,
    YETTY_YWASM_METHOD_wgpuDeviceCreateErrorTexture = 277,
    YETTY_YWASM_METHOD_wgpuDeviceCreateExternalTexture = 278,
    YETTY_YWASM_METHOD_wgpuDeviceCreatePipelineLayout = 279,
    YETTY_YWASM_METHOD_wgpuDeviceCreateQuerySet = 280,
    YETTY_YWASM_METHOD_wgpuDeviceCreateRenderBundleEncoder = 281,
    YETTY_YWASM_METHOD_wgpuDeviceCreateRenderPipeline = 282,
    YETTY_YWASM_METHOD_wgpuDeviceCreateRenderPipelineAsync = 283,
    YETTY_YWASM_METHOD_wgpuDeviceCreateResourceTable = 284,
    YETTY_YWASM_METHOD_wgpuDeviceCreateSampler = 285,
    YETTY_YWASM_METHOD_wgpuDeviceCreateShaderModule = 286,
    YETTY_YWASM_METHOD_wgpuDeviceCreateTexture = 287,
    YETTY_YWASM_METHOD_wgpuDeviceDestroy = 288,
    YETTY_YWASM_METHOD_wgpuDeviceForceLoss = 289,
    YETTY_YWASM_METHOD_wgpuDeviceGetAHardwareBufferProperties = 290,
    YETTY_YWASM_METHOD_wgpuDeviceGetAdapter = 291,
    YETTY_YWASM_METHOD_wgpuDeviceGetAdapterInfo = 292,
    YETTY_YWASM_METHOD_wgpuDeviceGetFeatures = 293,
    YETTY_YWASM_METHOD_wgpuDeviceGetLimits = 294,
    YETTY_YWASM_METHOD_wgpuDeviceGetLostFuture = 295,
    YETTY_YWASM_METHOD_wgpuDeviceHasFeature = 296,
    YETTY_YWASM_METHOD_wgpuDeviceImportSharedBufferMemory = 297,
    YETTY_YWASM_METHOD_wgpuDeviceImportSharedFence = 298,
    YETTY_YWASM_METHOD_wgpuDeviceImportSharedTextureMemory = 299,
    YETTY_YWASM_METHOD_wgpuDeviceInjectError = 300,
    YETTY_YWASM_METHOD_wgpuDevicePopErrorScope = 301,
    YETTY_YWASM_METHOD_wgpuDevicePushErrorScope = 302,
    YETTY_YWASM_METHOD_wgpuDeviceSetLabel = 303,
    YETTY_YWASM_METHOD_wgpuDeviceSetLoggingCallback = 304,
    YETTY_YWASM_METHOD_wgpuDeviceValidateTextureDescriptor = 305,
    YETTY_YWASM_METHOD_wgpuExternalTextureAddRef = 306,
    YETTY_YWASM_METHOD_wgpuExternalTextureDestroy = 307,
    YETTY_YWASM_METHOD_wgpuExternalTextureExpire = 308,
    YETTY_YWASM_METHOD_wgpuExternalTextureRefresh = 309,
    YETTY_YWASM_METHOD_wgpuExternalTextureRelease = 310,
    YETTY_YWASM_METHOD_wgpuExternalTextureSetLabel = 311,
    YETTY_YWASM_METHOD_wgpuGetInstanceFeatures = 312,
    YETTY_YWASM_METHOD_wgpuGetInstanceLimits = 313,
    YETTY_YWASM_METHOD_wgpuGetProcAddress = 314,
    YETTY_YWASM_METHOD_wgpuHasInstanceFeature = 315,
    YETTY_YWASM_METHOD_wgpuInstanceAddRef = 316,
    YETTY_YWASM_METHOD_wgpuInstanceCreateSurface = 317,
    YETTY_YWASM_METHOD_wgpuInstanceGetWGSLLanguageFeatures = 318,
    YETTY_YWASM_METHOD_wgpuInstanceHasWGSLLanguageFeature = 319,
    YETTY_YWASM_METHOD_wgpuInstanceProcessEvents = 320,
    YETTY_YWASM_METHOD_wgpuInstanceWaitAny = 321,
    YETTY_YWASM_METHOD_wgpuPipelineLayoutAddRef = 322,
    YETTY_YWASM_METHOD_wgpuPipelineLayoutRelease = 323,
    YETTY_YWASM_METHOD_wgpuPipelineLayoutSetLabel = 324,
    YETTY_YWASM_METHOD_wgpuQuerySetAddRef = 325,
    YETTY_YWASM_METHOD_wgpuQuerySetDestroy = 326,
    YETTY_YWASM_METHOD_wgpuQuerySetGetCount = 327,
    YETTY_YWASM_METHOD_wgpuQuerySetGetType = 328,
    YETTY_YWASM_METHOD_wgpuQuerySetRelease = 329,
    YETTY_YWASM_METHOD_wgpuQuerySetSetLabel = 330,
    YETTY_YWASM_METHOD_wgpuQueueAddRef = 331,
    YETTY_YWASM_METHOD_wgpuQueueCopyExternalTextureForBrowser = 332,
    YETTY_YWASM_METHOD_wgpuQueueCopyTextureForBrowser = 333,
    YETTY_YWASM_METHOD_wgpuQueueOnSubmittedWorkDone = 334,
    YETTY_YWASM_METHOD_wgpuQueueSetLabel = 335,
    YETTY_YWASM_METHOD_wgpuQueueSubmit = 336,
    YETTY_YWASM_METHOD_wgpuQueueWriteBuffer = 337,
    YETTY_YWASM_METHOD_wgpuQueueWriteTexture = 338,
    YETTY_YWASM_METHOD_wgpuRenderBundleAddRef = 339,
    YETTY_YWASM_METHOD_wgpuRenderBundleEncoderAddRef = 340,
    YETTY_YWASM_METHOD_wgpuRenderBundleEncoderDraw = 341,
    YETTY_YWASM_METHOD_wgpuRenderBundleEncoderDrawIndexed = 342,
    YETTY_YWASM_METHOD_wgpuRenderBundleEncoderDrawIndexedIndirect = 343,
    YETTY_YWASM_METHOD_wgpuRenderBundleEncoderDrawIndirect = 344,
    YETTY_YWASM_METHOD_wgpuRenderBundleEncoderFinish = 345,
    YETTY_YWASM_METHOD_wgpuRenderBundleEncoderInsertDebugMarker = 346,
    YETTY_YWASM_METHOD_wgpuRenderBundleEncoderPopDebugGroup = 347,
    YETTY_YWASM_METHOD_wgpuRenderBundleEncoderPushDebugGroup = 348,
    YETTY_YWASM_METHOD_wgpuRenderBundleEncoderRelease = 349,
    YETTY_YWASM_METHOD_wgpuRenderBundleEncoderSetBindGroup = 350,
    YETTY_YWASM_METHOD_wgpuRenderBundleEncoderSetImmediates = 351,
    YETTY_YWASM_METHOD_wgpuRenderBundleEncoderSetIndexBuffer = 352,
    YETTY_YWASM_METHOD_wgpuRenderBundleEncoderSetLabel = 353,
    YETTY_YWASM_METHOD_wgpuRenderBundleEncoderSetPipeline = 354,
    YETTY_YWASM_METHOD_wgpuRenderBundleEncoderSetResourceTable = 355,
    YETTY_YWASM_METHOD_wgpuRenderBundleEncoderSetVertexBuffer = 356,
    YETTY_YWASM_METHOD_wgpuRenderBundleRelease = 357,
    YETTY_YWASM_METHOD_wgpuRenderBundleSetLabel = 358,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderAddRef = 359,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderBeginOcclusionQuery = 360,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderDraw = 361,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderDrawIndexed = 362,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderDrawIndexedIndirect = 363,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderDrawIndirect = 364,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderEnd = 365,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderEndOcclusionQuery = 366,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderExecuteBundles = 367,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderInsertDebugMarker = 368,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderMultiDrawIndexedIndirect = 369,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderMultiDrawIndirect = 370,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderPixelLocalStorageBarrier = 371,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderPopDebugGroup = 372,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderPushDebugGroup = 373,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderRelease = 374,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderSetBindGroup = 375,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderSetBlendConstant = 376,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderSetImmediates = 377,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderSetIndexBuffer = 378,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderSetLabel = 379,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderSetPipeline = 380,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderSetResourceTable = 381,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderSetScissorRect = 382,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderSetStencilReference = 383,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderSetVertexBuffer = 384,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderSetViewport = 385,
    YETTY_YWASM_METHOD_wgpuRenderPassEncoderWriteTimestamp = 386,
    YETTY_YWASM_METHOD_wgpuRenderPipelineAddRef = 387,
    YETTY_YWASM_METHOD_wgpuRenderPipelineGetBindGroupLayout = 388,
    YETTY_YWASM_METHOD_wgpuRenderPipelineRelease = 389,
    YETTY_YWASM_METHOD_wgpuRenderPipelineSetLabel = 390,
    YETTY_YWASM_METHOD_wgpuResourceTableAddRef = 391,
    YETTY_YWASM_METHOD_wgpuResourceTableDestroy = 392,
    YETTY_YWASM_METHOD_wgpuResourceTableGetSize = 393,
    YETTY_YWASM_METHOD_wgpuResourceTableInsertBinding = 394,
    YETTY_YWASM_METHOD_wgpuResourceTableRelease = 395,
    YETTY_YWASM_METHOD_wgpuResourceTableRemoveBinding = 396,
    YETTY_YWASM_METHOD_wgpuResourceTableUpdate = 397,
    YETTY_YWASM_METHOD_wgpuSamplerAddRef = 398,
    YETTY_YWASM_METHOD_wgpuSamplerRelease = 399,
    YETTY_YWASM_METHOD_wgpuSamplerSetLabel = 400,
    YETTY_YWASM_METHOD_wgpuShaderModuleAddRef = 401,
    YETTY_YWASM_METHOD_wgpuShaderModuleGetCompilationInfo = 402,
    YETTY_YWASM_METHOD_wgpuShaderModuleRelease = 403,
    YETTY_YWASM_METHOD_wgpuShaderModuleSetLabel = 404,
    YETTY_YWASM_METHOD_wgpuSharedBufferMemoryAddRef = 405,
    YETTY_YWASM_METHOD_wgpuSharedBufferMemoryBeginAccess = 406,
    YETTY_YWASM_METHOD_wgpuSharedBufferMemoryCreateBuffer = 407,
    YETTY_YWASM_METHOD_wgpuSharedBufferMemoryEndAccess = 408,
    YETTY_YWASM_METHOD_wgpuSharedBufferMemoryEndAccessStateFreeMembers = 409,
    YETTY_YWASM_METHOD_wgpuSharedBufferMemoryGetProperties = 410,
    YETTY_YWASM_METHOD_wgpuSharedBufferMemoryIsDeviceLost = 411,
    YETTY_YWASM_METHOD_wgpuSharedBufferMemoryRelease = 412,
    YETTY_YWASM_METHOD_wgpuSharedBufferMemorySetLabel = 413,
    YETTY_YWASM_METHOD_wgpuSharedFenceAddRef = 414,
    YETTY_YWASM_METHOD_wgpuSharedFenceExportInfo = 415,
    YETTY_YWASM_METHOD_wgpuSharedFenceRelease = 416,
    YETTY_YWASM_METHOD_wgpuSharedFenceSetLabel = 417,
    YETTY_YWASM_METHOD_wgpuSharedTextureMemoryAddRef = 418,
    YETTY_YWASM_METHOD_wgpuSharedTextureMemoryBeginAccess = 419,
    YETTY_YWASM_METHOD_wgpuSharedTextureMemoryCreateTexture = 420,
    YETTY_YWASM_METHOD_wgpuSharedTextureMemoryEndAccess = 421,
    YETTY_YWASM_METHOD_wgpuSharedTextureMemoryEndAccessStateFreeMembers = 422,
    YETTY_YWASM_METHOD_wgpuSharedTextureMemoryGetProperties = 423,
    YETTY_YWASM_METHOD_wgpuSharedTextureMemoryIsDeviceLost = 424,
    YETTY_YWASM_METHOD_wgpuSharedTextureMemoryRelease = 425,
    YETTY_YWASM_METHOD_wgpuSharedTextureMemorySetLabel = 426,
    YETTY_YWASM_METHOD_wgpuSupportedFeaturesFreeMembers = 427,
    YETTY_YWASM_METHOD_wgpuSupportedInstanceFeaturesFreeMembers = 428,
    YETTY_YWASM_METHOD_wgpuSupportedWGSLLanguageFeaturesFreeMembers = 429,
    YETTY_YWASM_METHOD_wgpuSurfaceAddRef = 430,
    YETTY_YWASM_METHOD_wgpuSurfaceCapabilitiesFreeMembers = 431,
    YETTY_YWASM_METHOD_wgpuSurfaceConfigure = 432,
    YETTY_YWASM_METHOD_wgpuSurfaceGetCapabilities = 433,
    YETTY_YWASM_METHOD_wgpuSurfaceGetCurrentTexture = 434,
    YETTY_YWASM_METHOD_wgpuSurfacePresent = 435,
    YETTY_YWASM_METHOD_wgpuSurfaceRelease = 436,
    YETTY_YWASM_METHOD_wgpuSurfaceSetLabel = 437,
    YETTY_YWASM_METHOD_wgpuSurfaceUnconfigure = 438,
    YETTY_YWASM_METHOD_wgpuTexelBufferViewAddRef = 439,
    YETTY_YWASM_METHOD_wgpuTexelBufferViewRelease = 440,
    YETTY_YWASM_METHOD_wgpuTexelBufferViewSetLabel = 441,
    YETTY_YWASM_METHOD_wgpuTextureAddRef = 442,
    YETTY_YWASM_METHOD_wgpuTextureCreateErrorView = 443,
    YETTY_YWASM_METHOD_wgpuTextureCreateView = 444,
    YETTY_YWASM_METHOD_wgpuTextureDestroy = 445,
    YETTY_YWASM_METHOD_wgpuTextureGetDepthOrArrayLayers = 446,
    YETTY_YWASM_METHOD_wgpuTextureGetDimension = 447,
    YETTY_YWASM_METHOD_wgpuTextureGetFormat = 448,
    YETTY_YWASM_METHOD_wgpuTextureGetHeight = 449,
    YETTY_YWASM_METHOD_wgpuTextureGetMipLevelCount = 450,
    YETTY_YWASM_METHOD_wgpuTextureGetSampleCount = 451,
    YETTY_YWASM_METHOD_wgpuTextureGetTextureBindingViewDimension = 452,
    YETTY_YWASM_METHOD_wgpuTextureGetUsage = 453,
    YETTY_YWASM_METHOD_wgpuTextureGetWidth = 454,
    YETTY_YWASM_METHOD_wgpuTexturePin = 455,
    YETTY_YWASM_METHOD_wgpuTextureRelease = 456,
    YETTY_YWASM_METHOD_wgpuTextureSetLabel = 457,
    YETTY_YWASM_METHOD_wgpuTextureSetOwnershipForMemoryDump = 458,
    YETTY_YWASM_METHOD_wgpuTextureUnpin = 459,
    YETTY_YWASM_METHOD_wgpuTextureViewAddRef = 460,
    YETTY_YWASM_METHOD_wgpuTextureViewRelease = 461,
    YETTY_YWASM_METHOD_wgpuTextureViewSetLabel = 462,
};

struct ywasm_args_wgpuCreateInstance {
    uint64_t result_handle;
};

struct ywasm_args_wgpuInstanceRelease {
    uint64_t instance;
};

struct ywasm_args_wgpuDeviceTick {
    uint64_t device;
};

struct ywasm_args_wgpuDeviceGetQueue {
    uint64_t device;
    uint64_t result_handle;
};

struct ywasm_args_wgpuQueueRelease {
    uint64_t queue;
};

struct ywasm_args_wgpuDeviceRelease {
    uint64_t device;
};

struct ywasm_args_wgpuAdapterRelease {
    uint64_t adapter;
};

struct ywasm_args_wgpuDeviceCreateCommandEncoder {
    uint64_t device;
    uint64_t result_handle;
};

struct ywasm_args_wgpuCommandEncoderRelease {
    uint64_t encoder;
};

struct ywasm_args_wgpuCommandEncoderFinish {
    uint64_t encoder;
    uint64_t result_handle;
};

struct ywasm_args_wgpuCommandBufferRelease {
    uint64_t buffer;
};

struct ywasm_args_wgpuInstanceRequestAdapter {
    uint64_t instance;
    uint64_t result_handle;
};

struct ywasm_args_wgpuAdapterRequestDevice {
    uint64_t adapter;
    uint64_t result_handle;
};

struct ywasm_args_yetty_ywasm_present_frame {
    uint32_t width;
    uint32_t height;
    uint32_t format;
    uint32_t payload_ref;
};

struct ywasm_args_wgpuAdapterAddRef {
    uint64_t adapter;
};

struct ywasm_args_wgpuAdapterCreateDevice {
    uint64_t adapter;
    WGPUDeviceDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuAdapterGetFeatures {
    uint64_t adapter;
    WGPUSupportedFeatures features;
};

struct ywasm_args_wgpuAdapterGetFormatCapabilities {
    uint64_t adapter;
    uint32_t format;
    WGPUDawnFormatCapabilities capabilities;
};

struct ywasm_args_wgpuAdapterGetInfo {
    uint64_t adapter;
    WGPUAdapterInfo info;
};

struct ywasm_args_wgpuAdapterGetInstance {
    uint64_t adapter;
    uint64_t result_handle;
};

struct ywasm_args_wgpuAdapterGetLimits {
    uint64_t adapter;
    WGPULimits limits;
};

struct ywasm_args_wgpuAdapterHasFeature {
    uint64_t adapter;
    uint32_t feature;
};

struct ywasm_args_wgpuAdapterInfoFreeMembers {
    uint64_t adapterInfo;
};

struct ywasm_args_wgpuAdapterPropertiesMemoryHeapsFreeMembers {
    uint64_t adapterPropertiesMemoryHeaps;
};

struct ywasm_args_wgpuAdapterPropertiesSubgroupMatrixConfigsFreeMembers {
    uint64_t adapterPropertiesSubgroupMatrixConfigs;
};

struct ywasm_args_wgpuBindGroupAddRef {
    uint64_t bindGroup;
};

struct ywasm_args_wgpuBindGroupLayoutAddRef {
    uint64_t bindGroupLayout;
};

struct ywasm_args_wgpuBindGroupLayoutRelease {
    uint64_t bindGroupLayout;
};

struct ywasm_args_wgpuBindGroupLayoutSetLabel {
    uint64_t bindGroupLayout;
    WGPUStringView label;
};

struct ywasm_args_wgpuBindGroupRelease {
    uint64_t bindGroup;
};

struct ywasm_args_wgpuBindGroupSetLabel {
    uint64_t bindGroup;
    WGPUStringView label;
};

struct ywasm_args_wgpuBufferAddRef {
    uint64_t buffer;
};

struct ywasm_args_wgpuBufferCreateTexelView {
    uint64_t buffer;
    WGPUTexelBufferViewDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuBufferDestroy {
    uint64_t buffer;
};

struct ywasm_args_wgpuBufferGetConstMappedRange {
    uint64_t buffer;
    size_t offset;
    size_t size;
    uint64_t result_handle;
};

struct ywasm_args_wgpuBufferGetMapState {
    uint64_t buffer;
};

struct ywasm_args_wgpuBufferGetMappedRange {
    uint64_t buffer;
    size_t offset;
    size_t size;
    uint64_t result_handle;
};

struct ywasm_args_wgpuBufferGetSize {
    uint64_t buffer;
};

struct ywasm_args_wgpuBufferGetUsage {
    uint64_t buffer;
};

struct ywasm_args_wgpuBufferMapAsync {
    uint64_t buffer;
    uint32_t mode;
    size_t offset;
    size_t size;
    WGPUBufferMapCallbackInfo callbackInfo;
};

struct ywasm_args_wgpuBufferReadMappedRange {
    uint64_t buffer;
    size_t offset;
    size_t size;
    uint8_t data;
};

struct ywasm_args_wgpuBufferRelease {
    uint64_t buffer;
};

struct ywasm_args_wgpuBufferSetLabel {
    uint64_t buffer;
    WGPUStringView label;
};

struct ywasm_args_wgpuBufferUnmap {
    uint64_t buffer;
};

struct ywasm_args_wgpuBufferWriteMappedRange {
    uint64_t buffer;
    size_t offset;
    size_t size;
    uint8_t data;
};

struct ywasm_args_wgpuCommandBufferAddRef {
    uint64_t commandBuffer;
};

struct ywasm_args_wgpuCommandBufferSetLabel {
    uint64_t commandBuffer;
    WGPUStringView label;
};

struct ywasm_args_wgpuCommandEncoderAddRef {
    uint64_t commandEncoder;
};

struct ywasm_args_wgpuCommandEncoderBeginComputePass {
    uint64_t commandEncoder;
    WGPUComputePassDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuCommandEncoderBeginRenderPass {
    uint64_t commandEncoder;
    WGPURenderPassDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuCommandEncoderClearBuffer {
    uint64_t commandEncoder;
    uint64_t buffer;
    uint64_t offset;
    uint64_t size;
};

struct ywasm_args_wgpuCommandEncoderCopyBufferToBuffer {
    uint64_t commandEncoder;
    uint64_t source;
    uint64_t sourceOffset;
    uint64_t destination;
    uint64_t destinationOffset;
    uint64_t size;
};

struct ywasm_args_wgpuCommandEncoderCopyBufferToTexture {
    uint64_t commandEncoder;
    WGPUTexelCopyBufferInfo source;
    WGPUTexelCopyTextureInfo destination;
    uint32_t copySize_present;
    WGPUExtent3D copySize;
};

struct ywasm_args_wgpuCommandEncoderCopyTextureToBuffer {
    uint64_t commandEncoder;
    WGPUTexelCopyTextureInfo source;
    WGPUTexelCopyBufferInfo destination;
    uint32_t copySize_present;
    WGPUExtent3D copySize;
};

struct ywasm_args_wgpuCommandEncoderCopyTextureToTexture {
    uint64_t commandEncoder;
    WGPUTexelCopyTextureInfo source;
    WGPUTexelCopyTextureInfo destination;
    uint32_t copySize_present;
    WGPUExtent3D copySize;
};

struct ywasm_args_wgpuCommandEncoderInjectValidationError {
    uint64_t commandEncoder;
    WGPUStringView message;
};

struct ywasm_args_wgpuCommandEncoderInsertDebugMarker {
    uint64_t commandEncoder;
    WGPUStringView markerLabel;
};

struct ywasm_args_wgpuCommandEncoderPopDebugGroup {
    uint64_t commandEncoder;
};

struct ywasm_args_wgpuCommandEncoderPushDebugGroup {
    uint64_t commandEncoder;
    WGPUStringView groupLabel;
};

struct ywasm_args_wgpuCommandEncoderResolveQuerySet {
    uint64_t commandEncoder;
    uint64_t querySet;
    uint32_t firstQuery;
    uint32_t queryCount;
    uint64_t destination;
    uint64_t destinationOffset;
};

struct ywasm_args_wgpuCommandEncoderSetLabel {
    uint64_t commandEncoder;
    WGPUStringView label;
};

struct ywasm_args_wgpuCommandEncoderWriteBuffer {
    uint64_t commandEncoder;
    uint64_t buffer;
    uint64_t bufferOffset;
    size_t size;
    uint8_t data;
};

struct ywasm_args_wgpuCommandEncoderWriteTimestamp {
    uint64_t commandEncoder;
    uint64_t querySet;
    uint32_t queryIndex;
};

struct ywasm_args_wgpuComputePassEncoderAddRef {
    uint64_t computePassEncoder;
};

struct ywasm_args_wgpuComputePassEncoderDispatchWorkgroups {
    uint64_t computePassEncoder;
    uint32_t workgroupCountX;
    uint32_t workgroupCountY;
    uint32_t workgroupCountZ;
};

struct ywasm_args_wgpuComputePassEncoderDispatchWorkgroupsIndirect {
    uint64_t computePassEncoder;
    uint64_t indirectBuffer;
    uint64_t indirectOffset;
};

struct ywasm_args_wgpuComputePassEncoderEnd {
    uint64_t computePassEncoder;
};

struct ywasm_args_wgpuComputePassEncoderInsertDebugMarker {
    uint64_t computePassEncoder;
    WGPUStringView markerLabel;
};

struct ywasm_args_wgpuComputePassEncoderPopDebugGroup {
    uint64_t computePassEncoder;
};

struct ywasm_args_wgpuComputePassEncoderPushDebugGroup {
    uint64_t computePassEncoder;
    WGPUStringView groupLabel;
};

struct ywasm_args_wgpuComputePassEncoderRelease {
    uint64_t computePassEncoder;
};

struct ywasm_args_wgpuComputePassEncoderSetBindGroup {
    uint64_t computePassEncoder;
    uint32_t groupIndex;
    uint64_t group;
    size_t dynamicOffsetCount;
    uint32_t dynamicOffsets;
};

struct ywasm_args_wgpuComputePassEncoderSetImmediates {
    uint64_t computePassEncoder;
    uint32_t offset;
    size_t size;
    uint8_t data;
};

struct ywasm_args_wgpuComputePassEncoderSetLabel {
    uint64_t computePassEncoder;
    WGPUStringView label;
};

struct ywasm_args_wgpuComputePassEncoderSetPipeline {
    uint64_t computePassEncoder;
    uint64_t pipeline;
};

struct ywasm_args_wgpuComputePassEncoderSetResourceTable {
    uint64_t computePassEncoder;
    uint64_t table;
};

struct ywasm_args_wgpuComputePassEncoderWriteTimestamp {
    uint64_t computePassEncoder;
    uint64_t querySet;
    uint32_t queryIndex;
};

struct ywasm_args_wgpuComputePipelineAddRef {
    uint64_t computePipeline;
};

struct ywasm_args_wgpuComputePipelineGetBindGroupLayout {
    uint64_t computePipeline;
    uint32_t groupIndex;
    uint64_t result_handle;
};

struct ywasm_args_wgpuComputePipelineRelease {
    uint64_t computePipeline;
};

struct ywasm_args_wgpuComputePipelineSetLabel {
    uint64_t computePipeline;
    WGPUStringView label;
};

struct ywasm_args_wgpuDawnDrmFormatCapabilitiesFreeMembers {
    uint64_t dawnDrmFormatCapabilities;
};

struct ywasm_args_wgpuDeviceAddRef {
    uint64_t device;
};

struct ywasm_args_wgpuDeviceCreateBindGroup {
    uint64_t device;
    WGPUBindGroupDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuDeviceCreateBindGroupLayout {
    uint64_t device;
    WGPUBindGroupLayoutDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuDeviceCreateBuffer {
    uint64_t device;
    WGPUBufferDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuDeviceCreateComputePipeline {
    uint64_t device;
    WGPUComputePipelineDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuDeviceCreateComputePipelineAsync {
    uint64_t device;
    WGPUComputePipelineDescriptor descriptor;
    WGPUCreateComputePipelineAsyncCallbackInfo callbackInfo;
};

struct ywasm_args_wgpuDeviceCreateErrorBuffer {
    uint64_t device;
    WGPUBufferDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuDeviceCreateErrorExternalTexture {
    uint64_t device;
    uint64_t result_handle;
};

struct ywasm_args_wgpuDeviceCreateErrorShaderModule {
    uint64_t device;
    WGPUShaderModuleDescriptor descriptor;
    WGPUStringView errorMessage;
    uint64_t result_handle;
};

struct ywasm_args_wgpuDeviceCreateErrorTexture {
    uint64_t device;
    WGPUTextureDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuDeviceCreateExternalTexture {
    uint64_t device;
    WGPUExternalTextureDescriptor externalTextureDescriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuDeviceCreatePipelineLayout {
    uint64_t device;
    WGPUPipelineLayoutDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuDeviceCreateQuerySet {
    uint64_t device;
    WGPUQuerySetDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuDeviceCreateRenderBundleEncoder {
    uint64_t device;
    WGPURenderBundleEncoderDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuDeviceCreateRenderPipeline {
    uint64_t device;
    WGPURenderPipelineDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuDeviceCreateRenderPipelineAsync {
    uint64_t device;
    WGPURenderPipelineDescriptor descriptor;
    WGPUCreateRenderPipelineAsyncCallbackInfo callbackInfo;
};

struct ywasm_args_wgpuDeviceCreateResourceTable {
    uint64_t device;
    WGPUResourceTableDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuDeviceCreateSampler {
    uint64_t device;
    WGPUSamplerDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuDeviceCreateShaderModule {
    uint64_t device;
    WGPUShaderModuleDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuDeviceCreateTexture {
    uint64_t device;
    WGPUTextureDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuDeviceDestroy {
    uint64_t device;
};

struct ywasm_args_wgpuDeviceForceLoss {
    uint64_t device;
    uint32_t type;
    WGPUStringView message;
};

struct ywasm_args_wgpuDeviceGetAHardwareBufferProperties {
    uint64_t device;
    uint64_t handle;
    WGPUAHardwareBufferProperties properties;
};

struct ywasm_args_wgpuDeviceGetAdapter {
    uint64_t device;
    uint64_t result_handle;
};

struct ywasm_args_wgpuDeviceGetAdapterInfo {
    uint64_t device;
    WGPUAdapterInfo adapterInfo;
};

struct ywasm_args_wgpuDeviceGetFeatures {
    uint64_t device;
    WGPUSupportedFeatures features;
};

struct ywasm_args_wgpuDeviceGetLimits {
    uint64_t device;
    WGPULimits limits;
};

struct ywasm_args_wgpuDeviceGetLostFuture {
    uint64_t device;
};

struct ywasm_args_wgpuDeviceHasFeature {
    uint64_t device;
    uint32_t feature;
};

struct ywasm_args_wgpuDeviceImportSharedBufferMemory {
    uint64_t device;
    WGPUSharedBufferMemoryDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuDeviceImportSharedFence {
    uint64_t device;
    WGPUSharedFenceDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuDeviceImportSharedTextureMemory {
    uint64_t device;
    WGPUSharedTextureMemoryDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuDeviceInjectError {
    uint64_t device;
    uint32_t type;
    WGPUStringView message;
};

struct ywasm_args_wgpuDevicePopErrorScope {
    uint64_t device;
    WGPUPopErrorScopeCallbackInfo callbackInfo;
};

struct ywasm_args_wgpuDevicePushErrorScope {
    uint64_t device;
    uint32_t filter;
};

struct ywasm_args_wgpuDeviceSetLabel {
    uint64_t device;
    WGPUStringView label;
};

struct ywasm_args_wgpuDeviceSetLoggingCallback {
    uint64_t device;
    WGPULoggingCallbackInfo callbackInfo;
};

struct ywasm_args_wgpuDeviceValidateTextureDescriptor {
    uint64_t device;
    WGPUTextureDescriptor descriptor;
};

struct ywasm_args_wgpuExternalTextureAddRef {
    uint64_t externalTexture;
};

struct ywasm_args_wgpuExternalTextureDestroy {
    uint64_t externalTexture;
};

struct ywasm_args_wgpuExternalTextureExpire {
    uint64_t externalTexture;
};

struct ywasm_args_wgpuExternalTextureRefresh {
    uint64_t externalTexture;
};

struct ywasm_args_wgpuExternalTextureRelease {
    uint64_t externalTexture;
};

struct ywasm_args_wgpuExternalTextureSetLabel {
    uint64_t externalTexture;
    WGPUStringView label;
};

struct ywasm_args_wgpuGetInstanceFeatures {
    WGPUSupportedInstanceFeatures features;
};

struct ywasm_args_wgpuGetInstanceLimits {
    WGPUInstanceLimits limits;
};

struct ywasm_args_wgpuGetProcAddress {
    WGPUStringView procName;
    uint64_t result_handle;
};

struct ywasm_args_wgpuHasInstanceFeature {
    uint32_t feature;
};

struct ywasm_args_wgpuInstanceAddRef {
    uint64_t instance;
};

struct ywasm_args_wgpuInstanceCreateSurface {
    uint64_t instance;
    WGPUSurfaceDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuInstanceGetWGSLLanguageFeatures {
    uint64_t instance;
    WGPUSupportedWGSLLanguageFeatures features;
};

struct ywasm_args_wgpuInstanceHasWGSLLanguageFeature {
    uint64_t instance;
    uint32_t feature;
};

struct ywasm_args_wgpuInstanceProcessEvents {
    uint64_t instance;
};

struct ywasm_args_wgpuInstanceWaitAny {
    uint64_t instance;
    size_t futureCount;
    uint32_t futures_present;
    WGPUFutureWaitInfo futures;
    uint64_t timeoutNS;
};

struct ywasm_args_wgpuPipelineLayoutAddRef {
    uint64_t pipelineLayout;
};

struct ywasm_args_wgpuPipelineLayoutRelease {
    uint64_t pipelineLayout;
};

struct ywasm_args_wgpuPipelineLayoutSetLabel {
    uint64_t pipelineLayout;
    WGPUStringView label;
};

struct ywasm_args_wgpuQuerySetAddRef {
    uint64_t querySet;
};

struct ywasm_args_wgpuQuerySetDestroy {
    uint64_t querySet;
};

struct ywasm_args_wgpuQuerySetGetCount {
    uint64_t querySet;
};

struct ywasm_args_wgpuQuerySetGetType {
    uint64_t querySet;
};

struct ywasm_args_wgpuQuerySetRelease {
    uint64_t querySet;
};

struct ywasm_args_wgpuQuerySetSetLabel {
    uint64_t querySet;
    WGPUStringView label;
};

struct ywasm_args_wgpuQueueAddRef {
    uint64_t queue;
};

struct ywasm_args_wgpuQueueCopyExternalTextureForBrowser {
    uint64_t queue;
    WGPUImageCopyExternalTexture source;
    WGPUTexelCopyTextureInfo destination;
    uint32_t copySize_present;
    WGPUExtent3D copySize;
    WGPUCopyTextureForBrowserOptions options;
};

struct ywasm_args_wgpuQueueCopyTextureForBrowser {
    uint64_t queue;
    WGPUTexelCopyTextureInfo source;
    WGPUTexelCopyTextureInfo destination;
    uint32_t copySize_present;
    WGPUExtent3D copySize;
    WGPUCopyTextureForBrowserOptions options;
};

struct ywasm_args_wgpuQueueOnSubmittedWorkDone {
    uint64_t queue;
    WGPUQueueWorkDoneCallbackInfo callbackInfo;
};

struct ywasm_args_wgpuQueueSetLabel {
    uint64_t queue;
    WGPUStringView label;
};

struct ywasm_args_wgpuQueueSubmit {
    uint64_t queue;
    size_t commandCount;
    WGPUCommandBuffer commands;
};

struct ywasm_args_wgpuQueueWriteBuffer {
    uint64_t queue;
    uint64_t buffer;
    uint64_t bufferOffset;
    size_t size;
    uint8_t data;
};

struct ywasm_args_wgpuQueueWriteTexture {
    uint64_t queue;
    WGPUTexelCopyTextureInfo destination;
    size_t dataSize;
    uint8_t data;
    uint32_t dataLayout_present;
    WGPUTexelCopyBufferLayout dataLayout;
    uint32_t writeSize_present;
    WGPUExtent3D writeSize;
};

struct ywasm_args_wgpuRenderBundleAddRef {
    uint64_t renderBundle;
};

struct ywasm_args_wgpuRenderBundleEncoderAddRef {
    uint64_t renderBundleEncoder;
};

struct ywasm_args_wgpuRenderBundleEncoderDraw {
    uint64_t renderBundleEncoder;
    uint32_t vertexCount;
    uint32_t instanceCount;
    uint32_t firstVertex;
    uint32_t firstInstance;
};

struct ywasm_args_wgpuRenderBundleEncoderDrawIndexed {
    uint64_t renderBundleEncoder;
    uint32_t indexCount;
    uint32_t instanceCount;
    uint32_t firstIndex;
    int32_t baseVertex;
    uint32_t firstInstance;
};

struct ywasm_args_wgpuRenderBundleEncoderDrawIndexedIndirect {
    uint64_t renderBundleEncoder;
    uint64_t indirectBuffer;
    uint64_t indirectOffset;
};

struct ywasm_args_wgpuRenderBundleEncoderDrawIndirect {
    uint64_t renderBundleEncoder;
    uint64_t indirectBuffer;
    uint64_t indirectOffset;
};

struct ywasm_args_wgpuRenderBundleEncoderFinish {
    uint64_t renderBundleEncoder;
    WGPURenderBundleDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuRenderBundleEncoderInsertDebugMarker {
    uint64_t renderBundleEncoder;
    WGPUStringView markerLabel;
};

struct ywasm_args_wgpuRenderBundleEncoderPopDebugGroup {
    uint64_t renderBundleEncoder;
};

struct ywasm_args_wgpuRenderBundleEncoderPushDebugGroup {
    uint64_t renderBundleEncoder;
    WGPUStringView groupLabel;
};

struct ywasm_args_wgpuRenderBundleEncoderRelease {
    uint64_t renderBundleEncoder;
};

struct ywasm_args_wgpuRenderBundleEncoderSetBindGroup {
    uint64_t renderBundleEncoder;
    uint32_t groupIndex;
    uint64_t group;
    size_t dynamicOffsetCount;
    uint32_t dynamicOffsets;
};

struct ywasm_args_wgpuRenderBundleEncoderSetImmediates {
    uint64_t renderBundleEncoder;
    uint32_t offset;
    size_t size;
    uint8_t data;
};

struct ywasm_args_wgpuRenderBundleEncoderSetIndexBuffer {
    uint64_t renderBundleEncoder;
    uint64_t buffer;
    uint32_t format;
    uint64_t offset;
    uint64_t size;
};

struct ywasm_args_wgpuRenderBundleEncoderSetLabel {
    uint64_t renderBundleEncoder;
    WGPUStringView label;
};

struct ywasm_args_wgpuRenderBundleEncoderSetPipeline {
    uint64_t renderBundleEncoder;
    uint64_t pipeline;
};

struct ywasm_args_wgpuRenderBundleEncoderSetResourceTable {
    uint64_t renderBundleEncoder;
    uint64_t table;
};

struct ywasm_args_wgpuRenderBundleEncoderSetVertexBuffer {
    uint64_t renderBundleEncoder;
    uint32_t slot;
    uint64_t buffer;
    uint64_t offset;
    uint64_t size;
};

struct ywasm_args_wgpuRenderBundleRelease {
    uint64_t renderBundle;
};

struct ywasm_args_wgpuRenderBundleSetLabel {
    uint64_t renderBundle;
    WGPUStringView label;
};

struct ywasm_args_wgpuRenderPassEncoderAddRef {
    uint64_t renderPassEncoder;
};

struct ywasm_args_wgpuRenderPassEncoderBeginOcclusionQuery {
    uint64_t renderPassEncoder;
    uint32_t queryIndex;
};

struct ywasm_args_wgpuRenderPassEncoderDraw {
    uint64_t renderPassEncoder;
    uint32_t vertexCount;
    uint32_t instanceCount;
    uint32_t firstVertex;
    uint32_t firstInstance;
};

struct ywasm_args_wgpuRenderPassEncoderDrawIndexed {
    uint64_t renderPassEncoder;
    uint32_t indexCount;
    uint32_t instanceCount;
    uint32_t firstIndex;
    int32_t baseVertex;
    uint32_t firstInstance;
};

struct ywasm_args_wgpuRenderPassEncoderDrawIndexedIndirect {
    uint64_t renderPassEncoder;
    uint64_t indirectBuffer;
    uint64_t indirectOffset;
};

struct ywasm_args_wgpuRenderPassEncoderDrawIndirect {
    uint64_t renderPassEncoder;
    uint64_t indirectBuffer;
    uint64_t indirectOffset;
};

struct ywasm_args_wgpuRenderPassEncoderEnd {
    uint64_t renderPassEncoder;
};

struct ywasm_args_wgpuRenderPassEncoderEndOcclusionQuery {
    uint64_t renderPassEncoder;
};

struct ywasm_args_wgpuRenderPassEncoderExecuteBundles {
    uint64_t renderPassEncoder;
    size_t bundleCount;
    WGPURenderBundle bundles;
};

struct ywasm_args_wgpuRenderPassEncoderInsertDebugMarker {
    uint64_t renderPassEncoder;
    WGPUStringView markerLabel;
};

struct ywasm_args_wgpuRenderPassEncoderMultiDrawIndexedIndirect {
    uint64_t renderPassEncoder;
    uint64_t indirectBuffer;
    uint64_t indirectOffset;
    uint32_t maxDrawCount;
    uint64_t drawCountBuffer;
    uint64_t drawCountBufferOffset;
};

struct ywasm_args_wgpuRenderPassEncoderMultiDrawIndirect {
    uint64_t renderPassEncoder;
    uint64_t indirectBuffer;
    uint64_t indirectOffset;
    uint32_t maxDrawCount;
    uint64_t drawCountBuffer;
    uint64_t drawCountBufferOffset;
};

struct ywasm_args_wgpuRenderPassEncoderPixelLocalStorageBarrier {
    uint64_t renderPassEncoder;
};

struct ywasm_args_wgpuRenderPassEncoderPopDebugGroup {
    uint64_t renderPassEncoder;
};

struct ywasm_args_wgpuRenderPassEncoderPushDebugGroup {
    uint64_t renderPassEncoder;
    WGPUStringView groupLabel;
};

struct ywasm_args_wgpuRenderPassEncoderRelease {
    uint64_t renderPassEncoder;
};

struct ywasm_args_wgpuRenderPassEncoderSetBindGroup {
    uint64_t renderPassEncoder;
    uint32_t groupIndex;
    uint64_t group;
    size_t dynamicOffsetCount;
    uint32_t dynamicOffsets;
};

struct ywasm_args_wgpuRenderPassEncoderSetBlendConstant {
    uint64_t renderPassEncoder;
    uint32_t color_present;
    WGPUColor color;
};

struct ywasm_args_wgpuRenderPassEncoderSetImmediates {
    uint64_t renderPassEncoder;
    uint32_t offset;
    size_t size;
    uint8_t data;
};

struct ywasm_args_wgpuRenderPassEncoderSetIndexBuffer {
    uint64_t renderPassEncoder;
    uint64_t buffer;
    uint32_t format;
    uint64_t offset;
    uint64_t size;
};

struct ywasm_args_wgpuRenderPassEncoderSetLabel {
    uint64_t renderPassEncoder;
    WGPUStringView label;
};

struct ywasm_args_wgpuRenderPassEncoderSetPipeline {
    uint64_t renderPassEncoder;
    uint64_t pipeline;
};

struct ywasm_args_wgpuRenderPassEncoderSetResourceTable {
    uint64_t renderPassEncoder;
    uint64_t table;
};

struct ywasm_args_wgpuRenderPassEncoderSetScissorRect {
    uint64_t renderPassEncoder;
    uint32_t x;
    uint32_t y;
    uint32_t width;
    uint32_t height;
};

struct ywasm_args_wgpuRenderPassEncoderSetStencilReference {
    uint64_t renderPassEncoder;
    uint32_t reference;
};

struct ywasm_args_wgpuRenderPassEncoderSetVertexBuffer {
    uint64_t renderPassEncoder;
    uint32_t slot;
    uint64_t buffer;
    uint64_t offset;
    uint64_t size;
};

struct ywasm_args_wgpuRenderPassEncoderSetViewport {
    uint64_t renderPassEncoder;
    float x;
    float y;
    float width;
    float height;
    float minDepth;
    float maxDepth;
};

struct ywasm_args_wgpuRenderPassEncoderWriteTimestamp {
    uint64_t renderPassEncoder;
    uint64_t querySet;
    uint32_t queryIndex;
};

struct ywasm_args_wgpuRenderPipelineAddRef {
    uint64_t renderPipeline;
};

struct ywasm_args_wgpuRenderPipelineGetBindGroupLayout {
    uint64_t renderPipeline;
    uint32_t groupIndex;
    uint64_t result_handle;
};

struct ywasm_args_wgpuRenderPipelineRelease {
    uint64_t renderPipeline;
};

struct ywasm_args_wgpuRenderPipelineSetLabel {
    uint64_t renderPipeline;
    WGPUStringView label;
};

struct ywasm_args_wgpuResourceTableAddRef {
    uint64_t resourceTable;
};

struct ywasm_args_wgpuResourceTableDestroy {
    uint64_t resourceTable;
};

struct ywasm_args_wgpuResourceTableGetSize {
    uint64_t resourceTable;
};

struct ywasm_args_wgpuResourceTableInsertBinding {
    uint64_t resourceTable;
    WGPUBindingResource resource;
};

struct ywasm_args_wgpuResourceTableRelease {
    uint64_t resourceTable;
};

struct ywasm_args_wgpuResourceTableRemoveBinding {
    uint64_t resourceTable;
    uint32_t slot;
};

struct ywasm_args_wgpuResourceTableUpdate {
    uint64_t resourceTable;
    uint32_t slot;
    WGPUBindingResource resource;
};

struct ywasm_args_wgpuSamplerAddRef {
    uint64_t sampler;
};

struct ywasm_args_wgpuSamplerRelease {
    uint64_t sampler;
};

struct ywasm_args_wgpuSamplerSetLabel {
    uint64_t sampler;
    WGPUStringView label;
};

struct ywasm_args_wgpuShaderModuleAddRef {
    uint64_t shaderModule;
};

struct ywasm_args_wgpuShaderModuleGetCompilationInfo {
    uint64_t shaderModule;
    WGPUCompilationInfoCallbackInfo callbackInfo;
};

struct ywasm_args_wgpuShaderModuleRelease {
    uint64_t shaderModule;
};

struct ywasm_args_wgpuShaderModuleSetLabel {
    uint64_t shaderModule;
    WGPUStringView label;
};

struct ywasm_args_wgpuSharedBufferMemoryAddRef {
    uint64_t sharedBufferMemory;
};

struct ywasm_args_wgpuSharedBufferMemoryBeginAccess {
    uint64_t sharedBufferMemory;
    uint64_t buffer;
    WGPUSharedBufferMemoryBeginAccessDescriptor descriptor;
};

struct ywasm_args_wgpuSharedBufferMemoryCreateBuffer {
    uint64_t sharedBufferMemory;
    WGPUBufferDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuSharedBufferMemoryEndAccess {
    uint64_t sharedBufferMemory;
    uint64_t buffer;
    WGPUSharedBufferMemoryEndAccessState descriptor;
};

struct ywasm_args_wgpuSharedBufferMemoryEndAccessStateFreeMembers {
    uint64_t sharedBufferMemoryEndAccessState;
};

struct ywasm_args_wgpuSharedBufferMemoryGetProperties {
    uint64_t sharedBufferMemory;
    WGPUSharedBufferMemoryProperties properties;
};

struct ywasm_args_wgpuSharedBufferMemoryIsDeviceLost {
    uint64_t sharedBufferMemory;
};

struct ywasm_args_wgpuSharedBufferMemoryRelease {
    uint64_t sharedBufferMemory;
};

struct ywasm_args_wgpuSharedBufferMemorySetLabel {
    uint64_t sharedBufferMemory;
    WGPUStringView label;
};

struct ywasm_args_wgpuSharedFenceAddRef {
    uint64_t sharedFence;
};

struct ywasm_args_wgpuSharedFenceExportInfo {
    uint64_t sharedFence;
    WGPUSharedFenceExportInfo info;
};

struct ywasm_args_wgpuSharedFenceRelease {
    uint64_t sharedFence;
};

struct ywasm_args_wgpuSharedFenceSetLabel {
    uint64_t sharedFence;
    WGPUStringView label;
};

struct ywasm_args_wgpuSharedTextureMemoryAddRef {
    uint64_t sharedTextureMemory;
};

struct ywasm_args_wgpuSharedTextureMemoryBeginAccess {
    uint64_t sharedTextureMemory;
    uint64_t texture;
    WGPUSharedTextureMemoryBeginAccessDescriptor descriptor;
};

struct ywasm_args_wgpuSharedTextureMemoryCreateTexture {
    uint64_t sharedTextureMemory;
    WGPUTextureDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuSharedTextureMemoryEndAccess {
    uint64_t sharedTextureMemory;
    uint64_t texture;
    WGPUSharedTextureMemoryEndAccessState descriptor;
};

struct ywasm_args_wgpuSharedTextureMemoryEndAccessStateFreeMembers {
    uint64_t sharedTextureMemoryEndAccessState;
};

struct ywasm_args_wgpuSharedTextureMemoryGetProperties {
    uint64_t sharedTextureMemory;
    WGPUSharedTextureMemoryProperties properties;
};

struct ywasm_args_wgpuSharedTextureMemoryIsDeviceLost {
    uint64_t sharedTextureMemory;
};

struct ywasm_args_wgpuSharedTextureMemoryRelease {
    uint64_t sharedTextureMemory;
};

struct ywasm_args_wgpuSharedTextureMemorySetLabel {
    uint64_t sharedTextureMemory;
    WGPUStringView label;
};

struct ywasm_args_wgpuSupportedFeaturesFreeMembers {
    uint64_t supportedFeatures;
};

struct ywasm_args_wgpuSupportedInstanceFeaturesFreeMembers {
    uint64_t supportedInstanceFeatures;
};

struct ywasm_args_wgpuSupportedWGSLLanguageFeaturesFreeMembers {
    uint64_t supportedWGSLLanguageFeatures;
};

struct ywasm_args_wgpuSurfaceAddRef {
    uint64_t surface;
};

struct ywasm_args_wgpuSurfaceCapabilitiesFreeMembers {
    uint64_t surfaceCapabilities;
};

struct ywasm_args_wgpuSurfaceConfigure {
    uint64_t surface;
    WGPUSurfaceConfiguration config;
};

struct ywasm_args_wgpuSurfaceGetCapabilities {
    uint64_t surface;
    uint64_t adapter;
    WGPUSurfaceCapabilities capabilities;
};

struct ywasm_args_wgpuSurfaceGetCurrentTexture {
    uint64_t surface;
    WGPUSurfaceTexture surfaceTexture;
};

struct ywasm_args_wgpuSurfacePresent {
    uint64_t surface;
};

struct ywasm_args_wgpuSurfaceRelease {
    uint64_t surface;
};

struct ywasm_args_wgpuSurfaceSetLabel {
    uint64_t surface;
    WGPUStringView label;
};

struct ywasm_args_wgpuSurfaceUnconfigure {
    uint64_t surface;
};

struct ywasm_args_wgpuTexelBufferViewAddRef {
    uint64_t texelBufferView;
};

struct ywasm_args_wgpuTexelBufferViewRelease {
    uint64_t texelBufferView;
};

struct ywasm_args_wgpuTexelBufferViewSetLabel {
    uint64_t texelBufferView;
    WGPUStringView label;
};

struct ywasm_args_wgpuTextureAddRef {
    uint64_t texture;
};

struct ywasm_args_wgpuTextureCreateErrorView {
    uint64_t texture;
    WGPUTextureViewDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuTextureCreateView {
    uint64_t texture;
    WGPUTextureViewDescriptor descriptor;
    uint64_t result_handle;
};

struct ywasm_args_wgpuTextureDestroy {
    uint64_t texture;
};

struct ywasm_args_wgpuTextureGetDepthOrArrayLayers {
    uint64_t texture;
};

struct ywasm_args_wgpuTextureGetDimension {
    uint64_t texture;
};

struct ywasm_args_wgpuTextureGetFormat {
    uint64_t texture;
};

struct ywasm_args_wgpuTextureGetHeight {
    uint64_t texture;
};

struct ywasm_args_wgpuTextureGetMipLevelCount {
    uint64_t texture;
};

struct ywasm_args_wgpuTextureGetSampleCount {
    uint64_t texture;
};

struct ywasm_args_wgpuTextureGetTextureBindingViewDimension {
    uint64_t texture;
};

struct ywasm_args_wgpuTextureGetUsage {
    uint64_t texture;
};

struct ywasm_args_wgpuTextureGetWidth {
    uint64_t texture;
};

struct ywasm_args_wgpuTexturePin {
    uint64_t texture;
    uint32_t usage;
};

struct ywasm_args_wgpuTextureRelease {
    uint64_t texture;
};

struct ywasm_args_wgpuTextureSetLabel {
    uint64_t texture;
    WGPUStringView label;
};

struct ywasm_args_wgpuTextureSetOwnershipForMemoryDump {
    uint64_t texture;
    uint64_t ownerGuid;
};

struct ywasm_args_wgpuTextureUnpin {
    uint64_t texture;
};

struct ywasm_args_wgpuTextureViewAddRef {
    uint64_t textureView;
};

struct ywasm_args_wgpuTextureViewRelease {
    uint64_t textureView;
};

struct ywasm_args_wgpuTextureViewSetLabel {
    uint64_t textureView;
    WGPUStringView label;
};

struct yetty_ywasm_client;
typedef void (*yetty_ywasm_reply_cb)(void *user, uint32_t status, uint32_t method_id,
                                     const uint8_t *body, size_t body_len);

uint64_t ywasm_client_wgpuCreateInstance(struct yetty_ywasm_client *c);
struct yetty_ycore_void_result ywasm_client_wgpuInstanceRelease(struct yetty_ywasm_client *c, uint64_t instance);
struct yetty_ycore_void_result ywasm_client_wgpuDeviceTick(struct yetty_ywasm_client *c, uint64_t device);
uint64_t ywasm_client_wgpuDeviceGetQueue(struct yetty_ywasm_client *c, uint64_t device);
struct yetty_ycore_void_result ywasm_client_wgpuQueueRelease(struct yetty_ywasm_client *c, uint64_t queue);
struct yetty_ycore_void_result ywasm_client_wgpuDeviceRelease(struct yetty_ywasm_client *c, uint64_t device);
struct yetty_ycore_void_result ywasm_client_wgpuAdapterRelease(struct yetty_ywasm_client *c, uint64_t adapter);
uint64_t ywasm_client_wgpuDeviceCreateCommandEncoder(struct yetty_ywasm_client *c, uint64_t device);
struct yetty_ycore_void_result ywasm_client_wgpuCommandEncoderRelease(struct yetty_ywasm_client *c, uint64_t encoder);
uint64_t ywasm_client_wgpuCommandEncoderFinish(struct yetty_ywasm_client *c, uint64_t encoder);
struct yetty_ycore_void_result ywasm_client_wgpuCommandBufferRelease(struct yetty_ywasm_client *c, uint64_t buffer);
uint64_t ywasm_client_wgpuInstanceRequestAdapter(struct yetty_ywasm_client *c, uint64_t instance, yetty_ywasm_reply_cb cb, void *user);
uint64_t ywasm_client_wgpuAdapterRequestDevice(struct yetty_ywasm_client *c, uint64_t adapter, yetty_ywasm_reply_cb cb, void *user);
struct yetty_ycore_void_result ywasm_client_wgpuAdapterAddRef(struct yetty_ywasm_client *c, uint64_t adapter);
uint64_t ywasm_client_wgpuAdapterCreateDevice(struct yetty_ywasm_client *c, uint64_t adapter, WGPUDeviceDescriptor const *descriptor);
struct yetty_ycore_void_result ywasm_client_wgpuAdapterGetFeatures(struct yetty_ywasm_client *c, uint64_t adapter, WGPUSupportedFeatures *features);
WGPUStatus ywasm_client_wgpuAdapterGetFormatCapabilities(struct yetty_ywasm_client *c, uint64_t adapter, uint32_t format, WGPUDawnFormatCapabilities *capabilities);
WGPUStatus ywasm_client_wgpuAdapterGetInfo(struct yetty_ywasm_client *c, uint64_t adapter, WGPUAdapterInfo *info);
uint64_t ywasm_client_wgpuAdapterGetInstance(struct yetty_ywasm_client *c, uint64_t adapter);
WGPUStatus ywasm_client_wgpuAdapterGetLimits(struct yetty_ywasm_client *c, uint64_t adapter, WGPULimits *limits);
WGPUBool ywasm_client_wgpuAdapterHasFeature(struct yetty_ywasm_client *c, uint64_t adapter, uint32_t feature);
void ywasm_client_wgpuAdapterInfoFreeMembers(struct yetty_ywasm_client *c, WGPUAdapterInfo adapterInfo);
void ywasm_client_wgpuAdapterPropertiesMemoryHeapsFreeMembers(struct yetty_ywasm_client *c, WGPUAdapterPropertiesMemoryHeaps adapterPropertiesMemoryHeaps);
void ywasm_client_wgpuAdapterPropertiesSubgroupMatrixConfigsFreeMembers(struct yetty_ywasm_client *c, WGPUAdapterPropertiesSubgroupMatrixConfigs adapterPropertiesSubgroupMatrixConfigs);
struct yetty_ycore_void_result ywasm_client_wgpuBindGroupAddRef(struct yetty_ywasm_client *c, uint64_t bindGroup);
struct yetty_ycore_void_result ywasm_client_wgpuBindGroupLayoutAddRef(struct yetty_ywasm_client *c, uint64_t bindGroupLayout);
struct yetty_ycore_void_result ywasm_client_wgpuBindGroupLayoutRelease(struct yetty_ywasm_client *c, uint64_t bindGroupLayout);
struct yetty_ycore_void_result ywasm_client_wgpuBindGroupLayoutSetLabel(struct yetty_ywasm_client *c, uint64_t bindGroupLayout, WGPUStringView label);
struct yetty_ycore_void_result ywasm_client_wgpuBindGroupRelease(struct yetty_ywasm_client *c, uint64_t bindGroup);
struct yetty_ycore_void_result ywasm_client_wgpuBindGroupSetLabel(struct yetty_ywasm_client *c, uint64_t bindGroup, WGPUStringView label);
struct yetty_ycore_void_result ywasm_client_wgpuBufferAddRef(struct yetty_ywasm_client *c, uint64_t buffer);
uint64_t ywasm_client_wgpuBufferCreateTexelView(struct yetty_ywasm_client *c, uint64_t buffer, WGPUTexelBufferViewDescriptor const *descriptor);
struct yetty_ycore_void_result ywasm_client_wgpuBufferDestroy(struct yetty_ywasm_client *c, uint64_t buffer);
uint64_t ywasm_client_wgpuBufferGetConstMappedRange(struct yetty_ywasm_client *c, uint64_t buffer, size_t offset, size_t size);
WGPUBufferMapState ywasm_client_wgpuBufferGetMapState(struct yetty_ywasm_client *c, uint64_t buffer);
uint64_t ywasm_client_wgpuBufferGetMappedRange(struct yetty_ywasm_client *c, uint64_t buffer, size_t offset, size_t size);
uint64_t ywasm_client_wgpuBufferGetSize(struct yetty_ywasm_client *c, uint64_t buffer);
WGPUBufferUsage ywasm_client_wgpuBufferGetUsage(struct yetty_ywasm_client *c, uint64_t buffer);
WGPUFuture ywasm_client_wgpuBufferMapAsync(struct yetty_ywasm_client *c, uint64_t buffer, uint32_t mode, size_t offset, size_t size, yetty_ywasm_reply_cb cb, void *user);
WGPUStatus ywasm_client_wgpuBufferReadMappedRange(struct yetty_ywasm_client *c, uint64_t buffer, size_t offset, void *data, size_t size);
struct yetty_ycore_void_result ywasm_client_wgpuBufferRelease(struct yetty_ywasm_client *c, uint64_t buffer);
struct yetty_ycore_void_result ywasm_client_wgpuBufferSetLabel(struct yetty_ywasm_client *c, uint64_t buffer, WGPUStringView label);
struct yetty_ycore_void_result ywasm_client_wgpuBufferUnmap(struct yetty_ywasm_client *c, uint64_t buffer);
WGPUStatus ywasm_client_wgpuBufferWriteMappedRange(struct yetty_ywasm_client *c, uint64_t buffer, size_t offset, void const *data, size_t size);
struct yetty_ycore_void_result ywasm_client_wgpuCommandBufferAddRef(struct yetty_ywasm_client *c, uint64_t commandBuffer);
struct yetty_ycore_void_result ywasm_client_wgpuCommandBufferSetLabel(struct yetty_ywasm_client *c, uint64_t commandBuffer, WGPUStringView label);
struct yetty_ycore_void_result ywasm_client_wgpuCommandEncoderAddRef(struct yetty_ywasm_client *c, uint64_t commandEncoder);
uint64_t ywasm_client_wgpuCommandEncoderBeginComputePass(struct yetty_ywasm_client *c, uint64_t commandEncoder, WGPUComputePassDescriptor const *descriptor);
uint64_t ywasm_client_wgpuCommandEncoderBeginRenderPass(struct yetty_ywasm_client *c, uint64_t commandEncoder, WGPURenderPassDescriptor const *descriptor);
struct yetty_ycore_void_result ywasm_client_wgpuCommandEncoderClearBuffer(struct yetty_ywasm_client *c, uint64_t commandEncoder, uint64_t buffer, uint64_t offset, uint64_t size);
struct yetty_ycore_void_result ywasm_client_wgpuCommandEncoderCopyBufferToBuffer(struct yetty_ywasm_client *c, uint64_t commandEncoder, uint64_t source, uint64_t sourceOffset, uint64_t destination, uint64_t destinationOffset, uint64_t size);
struct yetty_ycore_void_result ywasm_client_wgpuCommandEncoderCopyBufferToTexture(struct yetty_ywasm_client *c, uint64_t commandEncoder, WGPUTexelCopyBufferInfo const *source, WGPUTexelCopyTextureInfo const *destination, WGPUExtent3D const *copySize);
struct yetty_ycore_void_result ywasm_client_wgpuCommandEncoderCopyTextureToBuffer(struct yetty_ywasm_client *c, uint64_t commandEncoder, WGPUTexelCopyTextureInfo const *source, WGPUTexelCopyBufferInfo const *destination, WGPUExtent3D const *copySize);
struct yetty_ycore_void_result ywasm_client_wgpuCommandEncoderCopyTextureToTexture(struct yetty_ywasm_client *c, uint64_t commandEncoder, WGPUTexelCopyTextureInfo const *source, WGPUTexelCopyTextureInfo const *destination, WGPUExtent3D const *copySize);
struct yetty_ycore_void_result ywasm_client_wgpuCommandEncoderInjectValidationError(struct yetty_ywasm_client *c, uint64_t commandEncoder, WGPUStringView message);
struct yetty_ycore_void_result ywasm_client_wgpuCommandEncoderInsertDebugMarker(struct yetty_ywasm_client *c, uint64_t commandEncoder, WGPUStringView markerLabel);
struct yetty_ycore_void_result ywasm_client_wgpuCommandEncoderPopDebugGroup(struct yetty_ywasm_client *c, uint64_t commandEncoder);
struct yetty_ycore_void_result ywasm_client_wgpuCommandEncoderPushDebugGroup(struct yetty_ywasm_client *c, uint64_t commandEncoder, WGPUStringView groupLabel);
struct yetty_ycore_void_result ywasm_client_wgpuCommandEncoderResolveQuerySet(struct yetty_ywasm_client *c, uint64_t commandEncoder, uint64_t querySet, uint32_t firstQuery, uint32_t queryCount, uint64_t destination, uint64_t destinationOffset);
struct yetty_ycore_void_result ywasm_client_wgpuCommandEncoderSetLabel(struct yetty_ywasm_client *c, uint64_t commandEncoder, WGPUStringView label);
struct yetty_ycore_void_result ywasm_client_wgpuCommandEncoderWriteBuffer(struct yetty_ywasm_client *c, uint64_t commandEncoder, uint64_t buffer, uint64_t bufferOffset, void const *data, size_t size);
struct yetty_ycore_void_result ywasm_client_wgpuCommandEncoderWriteTimestamp(struct yetty_ywasm_client *c, uint64_t commandEncoder, uint64_t querySet, uint32_t queryIndex);
struct yetty_ycore_void_result ywasm_client_wgpuComputePassEncoderAddRef(struct yetty_ywasm_client *c, uint64_t computePassEncoder);
struct yetty_ycore_void_result ywasm_client_wgpuComputePassEncoderDispatchWorkgroups(struct yetty_ywasm_client *c, uint64_t computePassEncoder, uint32_t workgroupCountX, uint32_t workgroupCountY, uint32_t workgroupCountZ);
struct yetty_ycore_void_result ywasm_client_wgpuComputePassEncoderDispatchWorkgroupsIndirect(struct yetty_ywasm_client *c, uint64_t computePassEncoder, uint64_t indirectBuffer, uint64_t indirectOffset);
struct yetty_ycore_void_result ywasm_client_wgpuComputePassEncoderEnd(struct yetty_ywasm_client *c, uint64_t computePassEncoder);
struct yetty_ycore_void_result ywasm_client_wgpuComputePassEncoderInsertDebugMarker(struct yetty_ywasm_client *c, uint64_t computePassEncoder, WGPUStringView markerLabel);
struct yetty_ycore_void_result ywasm_client_wgpuComputePassEncoderPopDebugGroup(struct yetty_ywasm_client *c, uint64_t computePassEncoder);
struct yetty_ycore_void_result ywasm_client_wgpuComputePassEncoderPushDebugGroup(struct yetty_ywasm_client *c, uint64_t computePassEncoder, WGPUStringView groupLabel);
struct yetty_ycore_void_result ywasm_client_wgpuComputePassEncoderRelease(struct yetty_ywasm_client *c, uint64_t computePassEncoder);
struct yetty_ycore_void_result ywasm_client_wgpuComputePassEncoderSetBindGroup(struct yetty_ywasm_client *c, uint64_t computePassEncoder, uint32_t groupIndex, uint64_t group, size_t dynamicOffsetCount, uint32_t const *dynamicOffsets);
struct yetty_ycore_void_result ywasm_client_wgpuComputePassEncoderSetImmediates(struct yetty_ywasm_client *c, uint64_t computePassEncoder, uint32_t offset, void const *data, size_t size);
struct yetty_ycore_void_result ywasm_client_wgpuComputePassEncoderSetLabel(struct yetty_ywasm_client *c, uint64_t computePassEncoder, WGPUStringView label);
struct yetty_ycore_void_result ywasm_client_wgpuComputePassEncoderSetPipeline(struct yetty_ywasm_client *c, uint64_t computePassEncoder, uint64_t pipeline);
struct yetty_ycore_void_result ywasm_client_wgpuComputePassEncoderSetResourceTable(struct yetty_ywasm_client *c, uint64_t computePassEncoder, uint64_t table);
struct yetty_ycore_void_result ywasm_client_wgpuComputePassEncoderWriteTimestamp(struct yetty_ywasm_client *c, uint64_t computePassEncoder, uint64_t querySet, uint32_t queryIndex);
struct yetty_ycore_void_result ywasm_client_wgpuComputePipelineAddRef(struct yetty_ywasm_client *c, uint64_t computePipeline);
uint64_t ywasm_client_wgpuComputePipelineGetBindGroupLayout(struct yetty_ywasm_client *c, uint64_t computePipeline, uint32_t groupIndex);
struct yetty_ycore_void_result ywasm_client_wgpuComputePipelineRelease(struct yetty_ywasm_client *c, uint64_t computePipeline);
struct yetty_ycore_void_result ywasm_client_wgpuComputePipelineSetLabel(struct yetty_ywasm_client *c, uint64_t computePipeline, WGPUStringView label);
void ywasm_client_wgpuDawnDrmFormatCapabilitiesFreeMembers(struct yetty_ywasm_client *c, WGPUDawnDrmFormatCapabilities dawnDrmFormatCapabilities);
struct yetty_ycore_void_result ywasm_client_wgpuDeviceAddRef(struct yetty_ywasm_client *c, uint64_t device);
uint64_t ywasm_client_wgpuDeviceCreateBindGroup(struct yetty_ywasm_client *c, uint64_t device, WGPUBindGroupDescriptor const *descriptor);
uint64_t ywasm_client_wgpuDeviceCreateBindGroupLayout(struct yetty_ywasm_client *c, uint64_t device, WGPUBindGroupLayoutDescriptor const *descriptor);
uint64_t ywasm_client_wgpuDeviceCreateBuffer(struct yetty_ywasm_client *c, uint64_t device, WGPUBufferDescriptor const *descriptor);
uint64_t ywasm_client_wgpuDeviceCreateComputePipeline(struct yetty_ywasm_client *c, uint64_t device, WGPUComputePipelineDescriptor const *descriptor);
WGPUFuture ywasm_client_wgpuDeviceCreateComputePipelineAsync(struct yetty_ywasm_client *c, uint64_t device, WGPUComputePipelineDescriptor const *descriptor, yetty_ywasm_reply_cb cb, void *user);
uint64_t ywasm_client_wgpuDeviceCreateErrorBuffer(struct yetty_ywasm_client *c, uint64_t device, WGPUBufferDescriptor const *descriptor);
uint64_t ywasm_client_wgpuDeviceCreateErrorExternalTexture(struct yetty_ywasm_client *c, uint64_t device);
uint64_t ywasm_client_wgpuDeviceCreateErrorShaderModule(struct yetty_ywasm_client *c, uint64_t device, WGPUShaderModuleDescriptor const *descriptor, WGPUStringView errorMessage);
uint64_t ywasm_client_wgpuDeviceCreateErrorTexture(struct yetty_ywasm_client *c, uint64_t device, WGPUTextureDescriptor const *descriptor);
uint64_t ywasm_client_wgpuDeviceCreateExternalTexture(struct yetty_ywasm_client *c, uint64_t device, WGPUExternalTextureDescriptor const *externalTextureDescriptor);
uint64_t ywasm_client_wgpuDeviceCreatePipelineLayout(struct yetty_ywasm_client *c, uint64_t device, WGPUPipelineLayoutDescriptor const *descriptor);
uint64_t ywasm_client_wgpuDeviceCreateQuerySet(struct yetty_ywasm_client *c, uint64_t device, WGPUQuerySetDescriptor const *descriptor);
uint64_t ywasm_client_wgpuDeviceCreateRenderBundleEncoder(struct yetty_ywasm_client *c, uint64_t device, WGPURenderBundleEncoderDescriptor const *descriptor);
uint64_t ywasm_client_wgpuDeviceCreateRenderPipeline(struct yetty_ywasm_client *c, uint64_t device, WGPURenderPipelineDescriptor const *descriptor);
WGPUFuture ywasm_client_wgpuDeviceCreateRenderPipelineAsync(struct yetty_ywasm_client *c, uint64_t device, WGPURenderPipelineDescriptor const *descriptor, yetty_ywasm_reply_cb cb, void *user);
uint64_t ywasm_client_wgpuDeviceCreateResourceTable(struct yetty_ywasm_client *c, uint64_t device, WGPUResourceTableDescriptor const *descriptor);
uint64_t ywasm_client_wgpuDeviceCreateSampler(struct yetty_ywasm_client *c, uint64_t device, WGPUSamplerDescriptor const *descriptor);
uint64_t ywasm_client_wgpuDeviceCreateShaderModule(struct yetty_ywasm_client *c, uint64_t device, WGPUShaderModuleDescriptor const *descriptor);
uint64_t ywasm_client_wgpuDeviceCreateTexture(struct yetty_ywasm_client *c, uint64_t device, WGPUTextureDescriptor const *descriptor);
struct yetty_ycore_void_result ywasm_client_wgpuDeviceDestroy(struct yetty_ywasm_client *c, uint64_t device);
struct yetty_ycore_void_result ywasm_client_wgpuDeviceForceLoss(struct yetty_ywasm_client *c, uint64_t device, uint32_t type, WGPUStringView message);
WGPUStatus ywasm_client_wgpuDeviceGetAHardwareBufferProperties(struct yetty_ywasm_client *c, uint64_t device, uint64_t handle, WGPUAHardwareBufferProperties *properties);
uint64_t ywasm_client_wgpuDeviceGetAdapter(struct yetty_ywasm_client *c, uint64_t device);
WGPUStatus ywasm_client_wgpuDeviceGetAdapterInfo(struct yetty_ywasm_client *c, uint64_t device, WGPUAdapterInfo *adapterInfo);
struct yetty_ycore_void_result ywasm_client_wgpuDeviceGetFeatures(struct yetty_ywasm_client *c, uint64_t device, WGPUSupportedFeatures *features);
WGPUStatus ywasm_client_wgpuDeviceGetLimits(struct yetty_ywasm_client *c, uint64_t device, WGPULimits *limits);
WGPUFuture ywasm_client_wgpuDeviceGetLostFuture(struct yetty_ywasm_client *c, uint64_t device);
WGPUBool ywasm_client_wgpuDeviceHasFeature(struct yetty_ywasm_client *c, uint64_t device, uint32_t feature);
uint64_t ywasm_client_wgpuDeviceImportSharedBufferMemory(struct yetty_ywasm_client *c, uint64_t device, WGPUSharedBufferMemoryDescriptor const *descriptor);
uint64_t ywasm_client_wgpuDeviceImportSharedFence(struct yetty_ywasm_client *c, uint64_t device, WGPUSharedFenceDescriptor const *descriptor);
uint64_t ywasm_client_wgpuDeviceImportSharedTextureMemory(struct yetty_ywasm_client *c, uint64_t device, WGPUSharedTextureMemoryDescriptor const *descriptor);
struct yetty_ycore_void_result ywasm_client_wgpuDeviceInjectError(struct yetty_ywasm_client *c, uint64_t device, uint32_t type, WGPUStringView message);
WGPUFuture ywasm_client_wgpuDevicePopErrorScope(struct yetty_ywasm_client *c, uint64_t device, yetty_ywasm_reply_cb cb, void *user);
struct yetty_ycore_void_result ywasm_client_wgpuDevicePushErrorScope(struct yetty_ywasm_client *c, uint64_t device, uint32_t filter);
struct yetty_ycore_void_result ywasm_client_wgpuDeviceSetLabel(struct yetty_ywasm_client *c, uint64_t device, WGPUStringView label);
struct yetty_ycore_void_result ywasm_client_wgpuDeviceSetLoggingCallback(struct yetty_ywasm_client *c, uint64_t device, yetty_ywasm_reply_cb cb, void *user);
struct yetty_ycore_void_result ywasm_client_wgpuDeviceValidateTextureDescriptor(struct yetty_ywasm_client *c, uint64_t device, WGPUTextureDescriptor const *descriptor);
struct yetty_ycore_void_result ywasm_client_wgpuExternalTextureAddRef(struct yetty_ywasm_client *c, uint64_t externalTexture);
struct yetty_ycore_void_result ywasm_client_wgpuExternalTextureDestroy(struct yetty_ywasm_client *c, uint64_t externalTexture);
struct yetty_ycore_void_result ywasm_client_wgpuExternalTextureExpire(struct yetty_ywasm_client *c, uint64_t externalTexture);
struct yetty_ycore_void_result ywasm_client_wgpuExternalTextureRefresh(struct yetty_ywasm_client *c, uint64_t externalTexture);
struct yetty_ycore_void_result ywasm_client_wgpuExternalTextureRelease(struct yetty_ywasm_client *c, uint64_t externalTexture);
struct yetty_ycore_void_result ywasm_client_wgpuExternalTextureSetLabel(struct yetty_ywasm_client *c, uint64_t externalTexture, WGPUStringView label);
struct yetty_ycore_void_result ywasm_client_wgpuGetInstanceFeatures(struct yetty_ywasm_client *c, WGPUSupportedInstanceFeatures *features);
WGPUStatus ywasm_client_wgpuGetInstanceLimits(struct yetty_ywasm_client *c, WGPUInstanceLimits *limits);
uint64_t ywasm_client_wgpuGetProcAddress(struct yetty_ywasm_client *c, WGPUStringView procName);
WGPUBool ywasm_client_wgpuHasInstanceFeature(struct yetty_ywasm_client *c, uint32_t feature);
struct yetty_ycore_void_result ywasm_client_wgpuInstanceAddRef(struct yetty_ywasm_client *c, uint64_t instance);
uint64_t ywasm_client_wgpuInstanceCreateSurface(struct yetty_ywasm_client *c, uint64_t instance, WGPUSurfaceDescriptor const *descriptor);
struct yetty_ycore_void_result ywasm_client_wgpuInstanceGetWGSLLanguageFeatures(struct yetty_ywasm_client *c, uint64_t instance, WGPUSupportedWGSLLanguageFeatures *features);
WGPUBool ywasm_client_wgpuInstanceHasWGSLLanguageFeature(struct yetty_ywasm_client *c, uint64_t instance, uint32_t feature);
struct yetty_ycore_void_result ywasm_client_wgpuInstanceProcessEvents(struct yetty_ywasm_client *c, uint64_t instance);
WGPUWaitStatus ywasm_client_wgpuInstanceWaitAny(struct yetty_ywasm_client *c, uint64_t instance, size_t futureCount, WGPUFutureWaitInfo const *futures, uint64_t timeoutNS);
struct yetty_ycore_void_result ywasm_client_wgpuPipelineLayoutAddRef(struct yetty_ywasm_client *c, uint64_t pipelineLayout);
struct yetty_ycore_void_result ywasm_client_wgpuPipelineLayoutRelease(struct yetty_ywasm_client *c, uint64_t pipelineLayout);
struct yetty_ycore_void_result ywasm_client_wgpuPipelineLayoutSetLabel(struct yetty_ywasm_client *c, uint64_t pipelineLayout, WGPUStringView label);
struct yetty_ycore_void_result ywasm_client_wgpuQuerySetAddRef(struct yetty_ywasm_client *c, uint64_t querySet);
struct yetty_ycore_void_result ywasm_client_wgpuQuerySetDestroy(struct yetty_ywasm_client *c, uint64_t querySet);
uint32_t ywasm_client_wgpuQuerySetGetCount(struct yetty_ywasm_client *c, uint64_t querySet);
WGPUQueryType ywasm_client_wgpuQuerySetGetType(struct yetty_ywasm_client *c, uint64_t querySet);
struct yetty_ycore_void_result ywasm_client_wgpuQuerySetRelease(struct yetty_ywasm_client *c, uint64_t querySet);
struct yetty_ycore_void_result ywasm_client_wgpuQuerySetSetLabel(struct yetty_ywasm_client *c, uint64_t querySet, WGPUStringView label);
struct yetty_ycore_void_result ywasm_client_wgpuQueueAddRef(struct yetty_ywasm_client *c, uint64_t queue);
struct yetty_ycore_void_result ywasm_client_wgpuQueueCopyExternalTextureForBrowser(struct yetty_ywasm_client *c, uint64_t queue, WGPUImageCopyExternalTexture const *source, WGPUTexelCopyTextureInfo const *destination, WGPUExtent3D const *copySize, WGPUCopyTextureForBrowserOptions const *options);
struct yetty_ycore_void_result ywasm_client_wgpuQueueCopyTextureForBrowser(struct yetty_ywasm_client *c, uint64_t queue, WGPUTexelCopyTextureInfo const *source, WGPUTexelCopyTextureInfo const *destination, WGPUExtent3D const *copySize, WGPUCopyTextureForBrowserOptions const *options);
WGPUFuture ywasm_client_wgpuQueueOnSubmittedWorkDone(struct yetty_ywasm_client *c, uint64_t queue, yetty_ywasm_reply_cb cb, void *user);
struct yetty_ycore_void_result ywasm_client_wgpuQueueSetLabel(struct yetty_ywasm_client *c, uint64_t queue, WGPUStringView label);
struct yetty_ycore_void_result ywasm_client_wgpuQueueSubmit(struct yetty_ywasm_client *c, uint64_t queue, size_t commandCount, WGPUCommandBuffer const *commands);
struct yetty_ycore_void_result ywasm_client_wgpuQueueWriteBuffer(struct yetty_ywasm_client *c, uint64_t queue, uint64_t buffer, uint64_t bufferOffset, void const *data, size_t size);
struct yetty_ycore_void_result ywasm_client_wgpuQueueWriteTexture(struct yetty_ywasm_client *c, uint64_t queue, WGPUTexelCopyTextureInfo const *destination, void const *data, size_t dataSize, WGPUTexelCopyBufferLayout const *dataLayout, WGPUExtent3D const *writeSize);
struct yetty_ycore_void_result ywasm_client_wgpuRenderBundleAddRef(struct yetty_ywasm_client *c, uint64_t renderBundle);
struct yetty_ycore_void_result ywasm_client_wgpuRenderBundleEncoderAddRef(struct yetty_ywasm_client *c, uint64_t renderBundleEncoder);
struct yetty_ycore_void_result ywasm_client_wgpuRenderBundleEncoderDraw(struct yetty_ywasm_client *c, uint64_t renderBundleEncoder, uint32_t vertexCount, uint32_t instanceCount, uint32_t firstVertex, uint32_t firstInstance);
struct yetty_ycore_void_result ywasm_client_wgpuRenderBundleEncoderDrawIndexed(struct yetty_ywasm_client *c, uint64_t renderBundleEncoder, uint32_t indexCount, uint32_t instanceCount, uint32_t firstIndex, int32_t baseVertex, uint32_t firstInstance);
struct yetty_ycore_void_result ywasm_client_wgpuRenderBundleEncoderDrawIndexedIndirect(struct yetty_ywasm_client *c, uint64_t renderBundleEncoder, uint64_t indirectBuffer, uint64_t indirectOffset);
struct yetty_ycore_void_result ywasm_client_wgpuRenderBundleEncoderDrawIndirect(struct yetty_ywasm_client *c, uint64_t renderBundleEncoder, uint64_t indirectBuffer, uint64_t indirectOffset);
uint64_t ywasm_client_wgpuRenderBundleEncoderFinish(struct yetty_ywasm_client *c, uint64_t renderBundleEncoder, WGPURenderBundleDescriptor const *descriptor);
struct yetty_ycore_void_result ywasm_client_wgpuRenderBundleEncoderInsertDebugMarker(struct yetty_ywasm_client *c, uint64_t renderBundleEncoder, WGPUStringView markerLabel);
struct yetty_ycore_void_result ywasm_client_wgpuRenderBundleEncoderPopDebugGroup(struct yetty_ywasm_client *c, uint64_t renderBundleEncoder);
struct yetty_ycore_void_result ywasm_client_wgpuRenderBundleEncoderPushDebugGroup(struct yetty_ywasm_client *c, uint64_t renderBundleEncoder, WGPUStringView groupLabel);
struct yetty_ycore_void_result ywasm_client_wgpuRenderBundleEncoderRelease(struct yetty_ywasm_client *c, uint64_t renderBundleEncoder);
struct yetty_ycore_void_result ywasm_client_wgpuRenderBundleEncoderSetBindGroup(struct yetty_ywasm_client *c, uint64_t renderBundleEncoder, uint32_t groupIndex, uint64_t group, size_t dynamicOffsetCount, uint32_t const *dynamicOffsets);
struct yetty_ycore_void_result ywasm_client_wgpuRenderBundleEncoderSetImmediates(struct yetty_ywasm_client *c, uint64_t renderBundleEncoder, uint32_t offset, void const *data, size_t size);
struct yetty_ycore_void_result ywasm_client_wgpuRenderBundleEncoderSetIndexBuffer(struct yetty_ywasm_client *c, uint64_t renderBundleEncoder, uint64_t buffer, uint32_t format, uint64_t offset, uint64_t size);
struct yetty_ycore_void_result ywasm_client_wgpuRenderBundleEncoderSetLabel(struct yetty_ywasm_client *c, uint64_t renderBundleEncoder, WGPUStringView label);
struct yetty_ycore_void_result ywasm_client_wgpuRenderBundleEncoderSetPipeline(struct yetty_ywasm_client *c, uint64_t renderBundleEncoder, uint64_t pipeline);
struct yetty_ycore_void_result ywasm_client_wgpuRenderBundleEncoderSetResourceTable(struct yetty_ywasm_client *c, uint64_t renderBundleEncoder, uint64_t table);
struct yetty_ycore_void_result ywasm_client_wgpuRenderBundleEncoderSetVertexBuffer(struct yetty_ywasm_client *c, uint64_t renderBundleEncoder, uint32_t slot, uint64_t buffer, uint64_t offset, uint64_t size);
struct yetty_ycore_void_result ywasm_client_wgpuRenderBundleRelease(struct yetty_ywasm_client *c, uint64_t renderBundle);
struct yetty_ycore_void_result ywasm_client_wgpuRenderBundleSetLabel(struct yetty_ywasm_client *c, uint64_t renderBundle, WGPUStringView label);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderAddRef(struct yetty_ywasm_client *c, uint64_t renderPassEncoder);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderBeginOcclusionQuery(struct yetty_ywasm_client *c, uint64_t renderPassEncoder, uint32_t queryIndex);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderDraw(struct yetty_ywasm_client *c, uint64_t renderPassEncoder, uint32_t vertexCount, uint32_t instanceCount, uint32_t firstVertex, uint32_t firstInstance);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderDrawIndexed(struct yetty_ywasm_client *c, uint64_t renderPassEncoder, uint32_t indexCount, uint32_t instanceCount, uint32_t firstIndex, int32_t baseVertex, uint32_t firstInstance);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderDrawIndexedIndirect(struct yetty_ywasm_client *c, uint64_t renderPassEncoder, uint64_t indirectBuffer, uint64_t indirectOffset);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderDrawIndirect(struct yetty_ywasm_client *c, uint64_t renderPassEncoder, uint64_t indirectBuffer, uint64_t indirectOffset);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderEnd(struct yetty_ywasm_client *c, uint64_t renderPassEncoder);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderEndOcclusionQuery(struct yetty_ywasm_client *c, uint64_t renderPassEncoder);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderExecuteBundles(struct yetty_ywasm_client *c, uint64_t renderPassEncoder, size_t bundleCount, WGPURenderBundle const *bundles);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderInsertDebugMarker(struct yetty_ywasm_client *c, uint64_t renderPassEncoder, WGPUStringView markerLabel);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderMultiDrawIndexedIndirect(struct yetty_ywasm_client *c, uint64_t renderPassEncoder, uint64_t indirectBuffer, uint64_t indirectOffset, uint32_t maxDrawCount, uint64_t drawCountBuffer, uint64_t drawCountBufferOffset);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderMultiDrawIndirect(struct yetty_ywasm_client *c, uint64_t renderPassEncoder, uint64_t indirectBuffer, uint64_t indirectOffset, uint32_t maxDrawCount, uint64_t drawCountBuffer, uint64_t drawCountBufferOffset);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderPixelLocalStorageBarrier(struct yetty_ywasm_client *c, uint64_t renderPassEncoder);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderPopDebugGroup(struct yetty_ywasm_client *c, uint64_t renderPassEncoder);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderPushDebugGroup(struct yetty_ywasm_client *c, uint64_t renderPassEncoder, WGPUStringView groupLabel);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderRelease(struct yetty_ywasm_client *c, uint64_t renderPassEncoder);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderSetBindGroup(struct yetty_ywasm_client *c, uint64_t renderPassEncoder, uint32_t groupIndex, uint64_t group, size_t dynamicOffsetCount, uint32_t const *dynamicOffsets);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderSetBlendConstant(struct yetty_ywasm_client *c, uint64_t renderPassEncoder, WGPUColor const *color);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderSetImmediates(struct yetty_ywasm_client *c, uint64_t renderPassEncoder, uint32_t offset, void const *data, size_t size);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderSetIndexBuffer(struct yetty_ywasm_client *c, uint64_t renderPassEncoder, uint64_t buffer, uint32_t format, uint64_t offset, uint64_t size);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderSetLabel(struct yetty_ywasm_client *c, uint64_t renderPassEncoder, WGPUStringView label);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderSetPipeline(struct yetty_ywasm_client *c, uint64_t renderPassEncoder, uint64_t pipeline);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderSetResourceTable(struct yetty_ywasm_client *c, uint64_t renderPassEncoder, uint64_t table);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderSetScissorRect(struct yetty_ywasm_client *c, uint64_t renderPassEncoder, uint32_t x, uint32_t y, uint32_t width, uint32_t height);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderSetStencilReference(struct yetty_ywasm_client *c, uint64_t renderPassEncoder, uint32_t reference);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderSetVertexBuffer(struct yetty_ywasm_client *c, uint64_t renderPassEncoder, uint32_t slot, uint64_t buffer, uint64_t offset, uint64_t size);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderSetViewport(struct yetty_ywasm_client *c, uint64_t renderPassEncoder, float x, float y, float width, float height, float minDepth, float maxDepth);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPassEncoderWriteTimestamp(struct yetty_ywasm_client *c, uint64_t renderPassEncoder, uint64_t querySet, uint32_t queryIndex);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPipelineAddRef(struct yetty_ywasm_client *c, uint64_t renderPipeline);
uint64_t ywasm_client_wgpuRenderPipelineGetBindGroupLayout(struct yetty_ywasm_client *c, uint64_t renderPipeline, uint32_t groupIndex);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPipelineRelease(struct yetty_ywasm_client *c, uint64_t renderPipeline);
struct yetty_ycore_void_result ywasm_client_wgpuRenderPipelineSetLabel(struct yetty_ywasm_client *c, uint64_t renderPipeline, WGPUStringView label);
struct yetty_ycore_void_result ywasm_client_wgpuResourceTableAddRef(struct yetty_ywasm_client *c, uint64_t resourceTable);
struct yetty_ycore_void_result ywasm_client_wgpuResourceTableDestroy(struct yetty_ywasm_client *c, uint64_t resourceTable);
uint32_t ywasm_client_wgpuResourceTableGetSize(struct yetty_ywasm_client *c, uint64_t resourceTable);
uint32_t ywasm_client_wgpuResourceTableInsertBinding(struct yetty_ywasm_client *c, uint64_t resourceTable, WGPUBindingResource const *resource);
struct yetty_ycore_void_result ywasm_client_wgpuResourceTableRelease(struct yetty_ywasm_client *c, uint64_t resourceTable);
WGPUStatus ywasm_client_wgpuResourceTableRemoveBinding(struct yetty_ywasm_client *c, uint64_t resourceTable, uint32_t slot);
WGPUStatus ywasm_client_wgpuResourceTableUpdate(struct yetty_ywasm_client *c, uint64_t resourceTable, uint32_t slot, WGPUBindingResource const *resource);
struct yetty_ycore_void_result ywasm_client_wgpuSamplerAddRef(struct yetty_ywasm_client *c, uint64_t sampler);
struct yetty_ycore_void_result ywasm_client_wgpuSamplerRelease(struct yetty_ywasm_client *c, uint64_t sampler);
struct yetty_ycore_void_result ywasm_client_wgpuSamplerSetLabel(struct yetty_ywasm_client *c, uint64_t sampler, WGPUStringView label);
struct yetty_ycore_void_result ywasm_client_wgpuShaderModuleAddRef(struct yetty_ywasm_client *c, uint64_t shaderModule);
WGPUFuture ywasm_client_wgpuShaderModuleGetCompilationInfo(struct yetty_ywasm_client *c, uint64_t shaderModule, yetty_ywasm_reply_cb cb, void *user);
struct yetty_ycore_void_result ywasm_client_wgpuShaderModuleRelease(struct yetty_ywasm_client *c, uint64_t shaderModule);
struct yetty_ycore_void_result ywasm_client_wgpuShaderModuleSetLabel(struct yetty_ywasm_client *c, uint64_t shaderModule, WGPUStringView label);
struct yetty_ycore_void_result ywasm_client_wgpuSharedBufferMemoryAddRef(struct yetty_ywasm_client *c, uint64_t sharedBufferMemory);
WGPUStatus ywasm_client_wgpuSharedBufferMemoryBeginAccess(struct yetty_ywasm_client *c, uint64_t sharedBufferMemory, uint64_t buffer, WGPUSharedBufferMemoryBeginAccessDescriptor const *descriptor);
uint64_t ywasm_client_wgpuSharedBufferMemoryCreateBuffer(struct yetty_ywasm_client *c, uint64_t sharedBufferMemory, WGPUBufferDescriptor const *descriptor);
WGPUStatus ywasm_client_wgpuSharedBufferMemoryEndAccess(struct yetty_ywasm_client *c, uint64_t sharedBufferMemory, uint64_t buffer, WGPUSharedBufferMemoryEndAccessState *descriptor);
void ywasm_client_wgpuSharedBufferMemoryEndAccessStateFreeMembers(struct yetty_ywasm_client *c, WGPUSharedBufferMemoryEndAccessState sharedBufferMemoryEndAccessState);
WGPUStatus ywasm_client_wgpuSharedBufferMemoryGetProperties(struct yetty_ywasm_client *c, uint64_t sharedBufferMemory, WGPUSharedBufferMemoryProperties *properties);
WGPUBool ywasm_client_wgpuSharedBufferMemoryIsDeviceLost(struct yetty_ywasm_client *c, uint64_t sharedBufferMemory);
struct yetty_ycore_void_result ywasm_client_wgpuSharedBufferMemoryRelease(struct yetty_ywasm_client *c, uint64_t sharedBufferMemory);
struct yetty_ycore_void_result ywasm_client_wgpuSharedBufferMemorySetLabel(struct yetty_ywasm_client *c, uint64_t sharedBufferMemory, WGPUStringView label);
struct yetty_ycore_void_result ywasm_client_wgpuSharedFenceAddRef(struct yetty_ywasm_client *c, uint64_t sharedFence);
struct yetty_ycore_void_result ywasm_client_wgpuSharedFenceExportInfo(struct yetty_ywasm_client *c, uint64_t sharedFence, WGPUSharedFenceExportInfo *info);
struct yetty_ycore_void_result ywasm_client_wgpuSharedFenceRelease(struct yetty_ywasm_client *c, uint64_t sharedFence);
struct yetty_ycore_void_result ywasm_client_wgpuSharedFenceSetLabel(struct yetty_ywasm_client *c, uint64_t sharedFence, WGPUStringView label);
struct yetty_ycore_void_result ywasm_client_wgpuSharedTextureMemoryAddRef(struct yetty_ywasm_client *c, uint64_t sharedTextureMemory);
WGPUStatus ywasm_client_wgpuSharedTextureMemoryBeginAccess(struct yetty_ywasm_client *c, uint64_t sharedTextureMemory, uint64_t texture, WGPUSharedTextureMemoryBeginAccessDescriptor const *descriptor);
uint64_t ywasm_client_wgpuSharedTextureMemoryCreateTexture(struct yetty_ywasm_client *c, uint64_t sharedTextureMemory, WGPUTextureDescriptor const *descriptor);
WGPUStatus ywasm_client_wgpuSharedTextureMemoryEndAccess(struct yetty_ywasm_client *c, uint64_t sharedTextureMemory, uint64_t texture, WGPUSharedTextureMemoryEndAccessState *descriptor);
void ywasm_client_wgpuSharedTextureMemoryEndAccessStateFreeMembers(struct yetty_ywasm_client *c, WGPUSharedTextureMemoryEndAccessState sharedTextureMemoryEndAccessState);
WGPUStatus ywasm_client_wgpuSharedTextureMemoryGetProperties(struct yetty_ywasm_client *c, uint64_t sharedTextureMemory, WGPUSharedTextureMemoryProperties *properties);
WGPUBool ywasm_client_wgpuSharedTextureMemoryIsDeviceLost(struct yetty_ywasm_client *c, uint64_t sharedTextureMemory);
struct yetty_ycore_void_result ywasm_client_wgpuSharedTextureMemoryRelease(struct yetty_ywasm_client *c, uint64_t sharedTextureMemory);
struct yetty_ycore_void_result ywasm_client_wgpuSharedTextureMemorySetLabel(struct yetty_ywasm_client *c, uint64_t sharedTextureMemory, WGPUStringView label);
void ywasm_client_wgpuSupportedFeaturesFreeMembers(struct yetty_ywasm_client *c, WGPUSupportedFeatures supportedFeatures);
void ywasm_client_wgpuSupportedInstanceFeaturesFreeMembers(struct yetty_ywasm_client *c, WGPUSupportedInstanceFeatures supportedInstanceFeatures);
void ywasm_client_wgpuSupportedWGSLLanguageFeaturesFreeMembers(struct yetty_ywasm_client *c, WGPUSupportedWGSLLanguageFeatures supportedWGSLLanguageFeatures);
struct yetty_ycore_void_result ywasm_client_wgpuSurfaceAddRef(struct yetty_ywasm_client *c, uint64_t surface);
void ywasm_client_wgpuSurfaceCapabilitiesFreeMembers(struct yetty_ywasm_client *c, WGPUSurfaceCapabilities surfaceCapabilities);
struct yetty_ycore_void_result ywasm_client_wgpuSurfaceConfigure(struct yetty_ywasm_client *c, uint64_t surface, WGPUSurfaceConfiguration const *config);
WGPUStatus ywasm_client_wgpuSurfaceGetCapabilities(struct yetty_ywasm_client *c, uint64_t surface, uint64_t adapter, WGPUSurfaceCapabilities *capabilities);
struct yetty_ycore_void_result ywasm_client_wgpuSurfaceGetCurrentTexture(struct yetty_ywasm_client *c, uint64_t surface, WGPUSurfaceTexture *surfaceTexture);
WGPUStatus ywasm_client_wgpuSurfacePresent(struct yetty_ywasm_client *c, uint64_t surface);
struct yetty_ycore_void_result ywasm_client_wgpuSurfaceRelease(struct yetty_ywasm_client *c, uint64_t surface);
struct yetty_ycore_void_result ywasm_client_wgpuSurfaceSetLabel(struct yetty_ywasm_client *c, uint64_t surface, WGPUStringView label);
struct yetty_ycore_void_result ywasm_client_wgpuSurfaceUnconfigure(struct yetty_ywasm_client *c, uint64_t surface);
struct yetty_ycore_void_result ywasm_client_wgpuTexelBufferViewAddRef(struct yetty_ywasm_client *c, uint64_t texelBufferView);
struct yetty_ycore_void_result ywasm_client_wgpuTexelBufferViewRelease(struct yetty_ywasm_client *c, uint64_t texelBufferView);
struct yetty_ycore_void_result ywasm_client_wgpuTexelBufferViewSetLabel(struct yetty_ywasm_client *c, uint64_t texelBufferView, WGPUStringView label);
struct yetty_ycore_void_result ywasm_client_wgpuTextureAddRef(struct yetty_ywasm_client *c, uint64_t texture);
uint64_t ywasm_client_wgpuTextureCreateErrorView(struct yetty_ywasm_client *c, uint64_t texture, WGPUTextureViewDescriptor const *descriptor);
uint64_t ywasm_client_wgpuTextureCreateView(struct yetty_ywasm_client *c, uint64_t texture, WGPUTextureViewDescriptor const *descriptor);
struct yetty_ycore_void_result ywasm_client_wgpuTextureDestroy(struct yetty_ywasm_client *c, uint64_t texture);
uint32_t ywasm_client_wgpuTextureGetDepthOrArrayLayers(struct yetty_ywasm_client *c, uint64_t texture);
WGPUTextureDimension ywasm_client_wgpuTextureGetDimension(struct yetty_ywasm_client *c, uint64_t texture);
WGPUTextureFormat ywasm_client_wgpuTextureGetFormat(struct yetty_ywasm_client *c, uint64_t texture);
uint32_t ywasm_client_wgpuTextureGetHeight(struct yetty_ywasm_client *c, uint64_t texture);
uint32_t ywasm_client_wgpuTextureGetMipLevelCount(struct yetty_ywasm_client *c, uint64_t texture);
uint32_t ywasm_client_wgpuTextureGetSampleCount(struct yetty_ywasm_client *c, uint64_t texture);
WGPUTextureViewDimension ywasm_client_wgpuTextureGetTextureBindingViewDimension(struct yetty_ywasm_client *c, uint64_t texture);
WGPUTextureUsage ywasm_client_wgpuTextureGetUsage(struct yetty_ywasm_client *c, uint64_t texture);
uint32_t ywasm_client_wgpuTextureGetWidth(struct yetty_ywasm_client *c, uint64_t texture);
struct yetty_ycore_void_result ywasm_client_wgpuTexturePin(struct yetty_ywasm_client *c, uint64_t texture, uint32_t usage);
struct yetty_ycore_void_result ywasm_client_wgpuTextureRelease(struct yetty_ywasm_client *c, uint64_t texture);
struct yetty_ycore_void_result ywasm_client_wgpuTextureSetLabel(struct yetty_ywasm_client *c, uint64_t texture, WGPUStringView label);
struct yetty_ycore_void_result ywasm_client_wgpuTextureSetOwnershipForMemoryDump(struct yetty_ywasm_client *c, uint64_t texture, uint64_t ownerGuid);
struct yetty_ycore_void_result ywasm_client_wgpuTextureUnpin(struct yetty_ywasm_client *c, uint64_t texture);
struct yetty_ycore_void_result ywasm_client_wgpuTextureViewAddRef(struct yetty_ywasm_client *c, uint64_t textureView);
struct yetty_ycore_void_result ywasm_client_wgpuTextureViewRelease(struct yetty_ywasm_client *c, uint64_t textureView);
struct yetty_ycore_void_result ywasm_client_wgpuTextureViewSetLabel(struct yetty_ywasm_client *c, uint64_t textureView, WGPUStringView label);

#ifdef __cplusplus
}
#endif

#endif /* YETTY_YWASM_METHODS_GEN_H */
