/*
 * ynotebook:mime_bundle — the nbformat mimebundle modelled as a yclass class.
 *
 * A Jupyter output carries a set of alternative representations (nbformat's
 * `data` object plus an optional per-representation `metadata` object). This
 * class holds that set. Each representation keeps its payload in the shape
 * nbformat actually stores it — the payload is NOT uniformly bytes:
 *
 *   - text   — UTF-8 text (an nbformat string or list-of-lines, joined);
 *   - binary — decoded bytes (base64 in the .ipynb, decoded in memory);
 *   - json   — a retained JSON value (application/json, any vendor `+json`, or
 *              any value that is not a string / list-of-strings), kept
 *              structured so a load/serialize cycle does not stringify it.
 *
 * Scope note: the MIME model lives inside ynotebook for now. It is expected to
 * split into a leaf `ymime` bundle library plus a `yrender-mime` renderer
 * registry later (see docs/ynotebook.md). The public interface is generated by
 * yclass codegen from the annotations below — never hand-write mime-bundle.h.
 *
 * JSON is parsed/written internally with yyjson; that dependency stays out of
 * the public method surface (load/serialize take/return JSON text), so the
 * generated header does not leak the codec.
 */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include <yyjson.h>

#include <yetty/yclass/class.h>
#include <yetty/ycore/result.h>
#include <yetty/ycore/types.h> /* struct yetty_ycore_buffer + base64 result */
#include <yetty/ycore/util.h>  /* yetty_ycore_base64_decode / _encode */

/*=============================================================================
 * Internal representation model (private to this translation unit)
 *===========================================================================*/

enum yetty_ynotebook_mime_kind {
    YETTY_YNOTEBOOK_MIME_KIND_TEXT = 0,
    YETTY_YNOTEBOOK_MIME_KIND_BINARY,
    YETTY_YNOTEBOOK_MIME_KIND_JSON,
};

struct yetty_ynotebook_mime_repr {
    char *mime_type; /* owned, e.g. "image/png" */
    enum yetty_ynotebook_mime_kind kind;

    /* text / binary payload: NUL-terminated for text (terminator excluded from
     * bytes_len); raw decoded bytes for binary; NULL for json. */
    uint8_t *bytes;
    size_t bytes_len;

    /* json payload (kind == JSON): a document whose root is the retained value;
     * NULL otherwise. */
    yyjson_mut_doc *json;

    /* per-representation metadata (nbformat metadata[mime]); NULL when absent. */
    yyjson_mut_doc *metadata;
};

static const char *kind_name(enum yetty_ynotebook_mime_kind kind)
{
    switch (kind) {
    case YETTY_YNOTEBOOK_MIME_KIND_TEXT:
        return "text";
    case YETTY_YNOTEBOOK_MIME_KIND_BINARY:
        return "binary";
    case YETTY_YNOTEBOOK_MIME_KIND_JSON:
        return "json";
    }
    return "unknown";
}

/*=============================================================================
 * Class data
 *===========================================================================*/

struct YETTY_ANNOTATE("class@ynotebook:mime_bundle") yetty_ynotebook_mime_bundle {
    struct yetty_ynotebook_mime_repr *reprs; /* owned, ordered */
    size_t count;
    size_t cap;
};

/* Result wrapper for the bundle handle. Declared here (not pulled from the
 * generated mime-bundle.h, which this TU does not include) so the appended
 * mime-bundle.gen.c has the type in scope. */
YETTY_YRESULT_DECLARE(yetty_ynotebook_mime_bundle_ptr, struct yetty_ynotebook_mime_bundle *);

/* Defined in the appended mime-bundle.gen.c (foot of this TU). */
struct yetty_yclass_ptr_result yetty_ynotebook_mime_bundle_class_get(void);
struct yetty_ynotebook_mime_bundle_ptr_result yetty_ynotebook_mime_bundle_from(
    struct yetty_yclass_object *obj);

static struct yetty_yclass_void_ptr_result bundle_from_obj(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_ptr_result class_r = yetty_ynotebook_mime_bundle_class_get();
    YETTY_RETURN_IF_ERR(yetty_yclass_void_ptr, class_r, "mime_bundle from_obj: class_get");
    return yetty_yclass_object_data(obj, class_r.value);
}

/*=============================================================================
 * MIME-type classification
 *===========================================================================*/

static bool str_ends_with(const char *str, const char *suffix)
{
    size_t str_len = strlen(str);
    size_t suffix_len = strlen(suffix);
    return suffix_len <= str_len && memcmp(str + str_len - suffix_len, suffix, suffix_len) == 0;
}

static bool str_starts_with(const char *str, const char *prefix)
{
    return strncmp(str, prefix, strlen(prefix)) == 0;
}

/* application/json and every vendor `+json` type carry a structured JSON value
 * rather than serialized text. */
static bool mime_is_json(const char *mime)
{
    return strcmp(mime, "application/json") == 0 || str_ends_with(mime, "+json");
}

/* Text-shaped MIME types whose nbformat value is a string / list-of-strings and
 * is meant to stay text (not base64). Everything else that is not JSON is
 * treated as binary base64 (image/png, image/jpeg, application/pdf, …). */
static bool mime_is_text(const char *mime)
{
    return str_starts_with(mime, "text/") || str_ends_with(mime, "+xml") ||
           strcmp(mime, "application/xml") == 0 || strcmp(mime, "application/javascript") == 0 ||
           strcmp(mime, "application/ecmascript") == 0;
}

/*=============================================================================
 * yyjson helpers
 *===========================================================================*/

/* Join an nbformat text value (a string, or a list-of-strings concatenated with
 * no added separators) into an owned, NUL-terminated buffer. Returns false when
 * `val` is neither a string nor an all-strings array (caller preserves it as
 * JSON instead), or on allocation failure. */
static bool join_text(yyjson_val *val, uint8_t **out_bytes, size_t *out_len)
{
    if (yyjson_is_str(val)) {
        size_t len = yyjson_get_len(val);
        uint8_t *buf = malloc(len + 1);
        if (!buf) {
            return false;
        }
        memcpy(buf, yyjson_get_str(val), len);
        buf[len] = 0;
        *out_bytes = buf;
        *out_len = len;
        return true;
    }

    if (yyjson_is_arr(val)) {
        size_t idx, max;
        yyjson_val *item;
        size_t total = 0;
        yyjson_arr_foreach(val, idx, max, item)
        {
            if (!yyjson_is_str(item)) {
                return false;
            }
            total += yyjson_get_len(item);
        }
        uint8_t *buf = malloc(total + 1);
        if (!buf) {
            return false;
        }
        size_t offset = 0;
        yyjson_arr_foreach(val, idx, max, item)
        {
            size_t len = yyjson_get_len(item);
            memcpy(buf + offset, yyjson_get_str(item), len);
            offset += len;
        }
        buf[total] = 0;
        *out_bytes = buf;
        *out_len = total;
        return true;
    }

    return false;
}

/* Deep-copy an immutable value into a freshly-owned mutable document whose root
 * is the copy. Returns NULL on failure. */
static yyjson_mut_doc *retain_json(yyjson_val *val)
{
    yyjson_mut_doc *doc = yyjson_mut_doc_new(NULL);
    if (!doc) {
        return NULL;
    }
    yyjson_mut_val *root = yyjson_val_mut_copy(doc, val);
    if (!root) {
        yyjson_mut_doc_free(doc);
        return NULL;
    }
    yyjson_mut_doc_set_root(doc, root);
    return doc;
}

/*=============================================================================
 * Bundle storage
 *===========================================================================*/

static struct yetty_ynotebook_mime_repr *bundle_push(struct yetty_ynotebook_mime_bundle *bundle)
{
    if (bundle->count == bundle->cap) {
        size_t new_cap = bundle->cap ? bundle->cap * 2 : 4;
        struct yetty_ynotebook_mime_repr *grown = realloc(bundle->reprs, new_cap * sizeof(*grown));
        if (!grown) {
            return NULL;
        }
        bundle->reprs = grown;
        bundle->cap = new_cap;
    }
    struct yetty_ynotebook_mime_repr *repr = &bundle->reprs[bundle->count++];
    memset(repr, 0, sizeof(*repr));
    return repr;
}

static void repr_destroy(struct yetty_ynotebook_mime_repr *repr)
{
    free(repr->mime_type);
    free(repr->bytes);
    if (repr->json) {
        yyjson_mut_doc_free(repr->json);
    }
    if (repr->metadata) {
        yyjson_mut_doc_free(repr->metadata);
    }
}

static void bundle_clear(struct yetty_ynotebook_mime_bundle *bundle)
{
    for (size_t i = 0; i < bundle->count; i++) {
        repr_destroy(&bundle->reprs[i]);
    }
    free(bundle->reprs);
    bundle->reprs = NULL;
    bundle->count = 0;
    bundle->cap = 0;
}

/*=============================================================================
 * Load / emit against yyjson objects (internal)
 *===========================================================================*/

static struct yetty_ycore_void_result bundle_load(struct yetty_ynotebook_mime_bundle *bundle,
                                                  yyjson_val *data_obj, yyjson_val *metadata_obj)
{
    bundle_clear(bundle);

    if (!data_obj || !yyjson_is_obj(data_obj)) {
        return YETTY_OK_VOID(); /* absent or empty data — a valid empty bundle */
    }

    bool have_metadata = metadata_obj && yyjson_is_obj(metadata_obj);

    size_t idx, max;
    yyjson_val *key, *val;
    yyjson_obj_foreach(data_obj, idx, max, key, val)
    {
        const char *mime = yyjson_get_str(key);
        if (!mime) {
            continue;
        }

        struct yetty_ynotebook_mime_repr *repr = bundle_push(bundle);
        if (!repr) {
            return YETTY_ERR(yetty_ycore_void, "mime_bundle load: representation alloc failed");
        }

        repr->mime_type = strdup(mime);
        if (!repr->mime_type) {
            return YETTY_ERR(yetty_ycore_void, "mime_bundle load: mime string dup failed");
        }

        if (mime_is_json(mime)) {
            repr->kind = YETTY_YNOTEBOOK_MIME_KIND_JSON;
            repr->json = retain_json(val);
            if (!repr->json) {
                return YETTY_ERR(yetty_ycore_void, "mime_bundle load: json retain failed");
            }
        } else {
            uint8_t *text = NULL;
            size_t text_len = 0;
            if (!join_text(val, &text, &text_len)) {
                /* Not string / list-of-strings — preserve it structurally. */
                repr->kind = YETTY_YNOTEBOOK_MIME_KIND_JSON;
                repr->json = retain_json(val);
                if (!repr->json) {
                    return YETTY_ERR(yetty_ycore_void, "mime_bundle load: json retain failed");
                }
            } else if (mime_is_text(mime)) {
                repr->kind = YETTY_YNOTEBOOK_MIME_KIND_TEXT;
                repr->bytes = text;
                repr->bytes_len = text_len;
            } else {
                /* Binary type: the joined text is base64; decode it. */
                repr->kind = YETTY_YNOTEBOOK_MIME_KIND_BINARY;
                size_t cap = text_len ? text_len : 1; /* decoded size <= encoded */
                uint8_t *decoded = malloc(cap);
                if (!decoded) {
                    free(text);
                    return YETTY_ERR(yetty_ycore_void,
                                     "mime_bundle load: base64 buffer alloc failed");
                }
                size_t written =
                    yetty_ycore_base64_decode((const char *)text, text_len, (char *)decoded, cap);
                free(text);
                repr->bytes = decoded;
                repr->bytes_len = written;
            }
        }

        if (have_metadata) {
            yyjson_val *meta = yyjson_obj_get(metadata_obj, mime);
            if (meta && !yyjson_is_null(meta)) {
                repr->metadata = retain_json(meta);
                if (!repr->metadata) {
                    return YETTY_ERR(yetty_ycore_void, "mime_bundle load: metadata retain failed");
                }
            }
        }
    }

    return YETTY_OK_VOID();
}

static struct yetty_ycore_void_result bundle_emit(const struct yetty_ynotebook_mime_bundle *bundle,
                                                  yyjson_mut_doc *out_doc,
                                                  yyjson_mut_val **out_data,
                                                  yyjson_mut_val **out_metadata)
{
    yyjson_mut_val *data = yyjson_mut_obj(out_doc);
    yyjson_mut_val *metadata = out_metadata ? yyjson_mut_obj(out_doc) : NULL;
    if (!data || (out_metadata && !metadata)) {
        return YETTY_ERR(yetty_ycore_void, "mime_bundle emit: object allocation failed");
    }

    for (size_t i = 0; i < bundle->count; i++) {
        const struct yetty_ynotebook_mime_repr *repr = &bundle->reprs[i];
        yyjson_mut_val *key = yyjson_mut_strcpy(out_doc, repr->mime_type);
        yyjson_mut_val *value = NULL;

        switch (repr->kind) {
        case YETTY_YNOTEBOOK_MIME_KIND_TEXT:
            value = yyjson_mut_strncpy(out_doc, repr->bytes ? (const char *)repr->bytes : "",
                                       repr->bytes_len);
            break;
        case YETTY_YNOTEBOOK_MIME_KIND_BINARY: {
            struct yetty_ycore_buffer_result encoded =
                yetty_ycore_base64_encode(repr->bytes, repr->bytes_len);
            if (YETTY_IS_ERR(encoded)) {
                return YETTY_ERR(yetty_ycore_void, "mime_bundle emit: base64 encode failed",
                                 encoded);
            }
            value =
                yyjson_mut_strncpy(out_doc, (const char *)encoded.value.data, encoded.value.size);
            yetty_ycore_buffer_destroy(&encoded.value);
            break;
        }
        case YETTY_YNOTEBOOK_MIME_KIND_JSON:
            value = repr->json
                        ? yyjson_mut_val_mut_copy(out_doc, yyjson_mut_doc_get_root(repr->json))
                        : yyjson_mut_null(out_doc);
            break;
        }

        if (!key || !value) {
            return YETTY_ERR(yetty_ycore_void, "mime_bundle emit: value allocation failed");
        }
        yyjson_mut_obj_add(data, key, value);

        if (metadata && repr->metadata) {
            yyjson_mut_val *meta_key = yyjson_mut_strcpy(out_doc, repr->mime_type);
            yyjson_mut_val *meta_value =
                yyjson_mut_val_mut_copy(out_doc, yyjson_mut_doc_get_root(repr->metadata));
            if (!meta_key || !meta_value) {
                return YETTY_ERR(yetty_ycore_void, "mime_bundle emit: metadata copy failed");
            }
            yyjson_mut_obj_add(metadata, meta_key, meta_value);
        }
    }

    *out_data = data;
    if (out_metadata) {
        *out_metadata = metadata;
    }
    return YETTY_OK_VOID();
}

/*=============================================================================
 * Method slots
 *===========================================================================*/

/* from_json_text: replace the bundle's contents from an nbformat `data` object
 * (JSON text). `metadata_json` is the matching `metadata` object as JSON text,
 * or NULL / "" for none. Each representation is classified as text, binary
 * (base64-decoded), or a retained JSON value. */
YETTY_ANNOTATE("virtual@ynotebook:mime_bundle:mime_bundle_from_json_text")
YETTY_ANNOTATE("local@ynotebook:mime_bundle_from_json_text")
static struct yetty_ycore_void_result mime_bundle_from_json_text(struct yetty_yclass_object *obj,
                                                                 const char *data_json,
                                                                 const char *metadata_json)
{
    struct yetty_yclass_void_ptr_result bundle_r = bundle_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, bundle_r, "mime_bundle from_json_text: from_obj");
    struct yetty_ynotebook_mime_bundle *bundle = bundle_r.value;

    if (!data_json) {
        return YETTY_ERR(yetty_ycore_void, "mime_bundle from_json_text: NULL data_json");
    }

    yyjson_doc *data_doc = yyjson_read(data_json, strlen(data_json), 0);
    if (!data_doc) {
        return YETTY_ERR(yetty_ycore_void, "mime_bundle from_json_text: data parse failed");
    }

    yyjson_doc *meta_doc = NULL;
    if (metadata_json && metadata_json[0]) {
        meta_doc = yyjson_read(metadata_json, strlen(metadata_json), 0);
        if (!meta_doc) {
            yyjson_doc_free(data_doc);
            return YETTY_ERR(yetty_ycore_void, "mime_bundle from_json_text: metadata parse failed");
        }
    }

    struct yetty_ycore_void_result load_r = bundle_load(
        bundle, yyjson_doc_get_root(data_doc), meta_doc ? yyjson_doc_get_root(meta_doc) : NULL);

    yyjson_doc_free(data_doc);
    if (meta_doc) {
        yyjson_doc_free(meta_doc);
    }
    return load_r;
}

/* to_json_text: serialize the bundle as an nbformat `data` object (JSON text).
 * Caller owns the returned string and frees it with free(). */
YETTY_ANNOTATE("virtual@ynotebook:mime_bundle:mime_bundle_to_json_text")
YETTY_ANNOTATE("local@ynotebook:mime_bundle_to_json_text")
static struct yetty_ycore_char_ptr_result mime_bundle_to_json_text(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result bundle_r = bundle_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_char_ptr, bundle_r, "mime_bundle to_json_text: from_obj");
    struct yetty_ynotebook_mime_bundle *bundle = bundle_r.value;

    yyjson_mut_doc *out = yyjson_mut_doc_new(NULL);
    if (!out) {
        return YETTY_ERR(yetty_ycore_char_ptr, "mime_bundle to_json_text: doc alloc failed");
    }

    yyjson_mut_val *data = NULL;
    struct yetty_ycore_void_result emit_r = bundle_emit(bundle, out, &data, NULL);
    if (YETTY_IS_ERR(emit_r)) {
        yyjson_mut_doc_free(out);
        return YETTY_ERR(yetty_ycore_char_ptr, "mime_bundle to_json_text: emit failed", emit_r);
    }
    yyjson_mut_doc_set_root(out, data);

    char *text = yyjson_mut_write(out, 0, NULL);
    yyjson_mut_doc_free(out);
    if (!text) {
        return YETTY_ERR(yetty_ycore_char_ptr, "mime_bundle to_json_text: write failed");
    }
    return YETTY_OK(yetty_ycore_char_ptr, text);
}

/* count: number of representations. */
YETTY_ANNOTATE("virtual@ynotebook:mime_bundle:mime_bundle_count")
YETTY_ANNOTATE("local@ynotebook:mime_bundle_count")
static struct yetty_ycore_size_result mime_bundle_count(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result bundle_r = bundle_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_size, bundle_r, "mime_bundle count: from_obj");
    struct yetty_ynotebook_mime_bundle *bundle = bundle_r.value;
    return YETTY_OK(yetty_ycore_size, bundle->count);
}

/* mime_at: the MIME type string of representation `index` (borrowed). */
YETTY_ANNOTATE("virtual@ynotebook:mime_bundle:mime_bundle_mime_at")
YETTY_ANNOTATE("local@ynotebook:mime_bundle_mime_at")
static struct yetty_ycore_const_char_ptr_result mime_bundle_mime_at(struct yetty_yclass_object *obj,
                                                                    size_t index)
{
    struct yetty_yclass_void_ptr_result bundle_r = bundle_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_const_char_ptr, bundle_r, "mime_bundle mime_at: from_obj");
    struct yetty_ynotebook_mime_bundle *bundle = bundle_r.value;
    if (index >= bundle->count) {
        return YETTY_ERR(yetty_ycore_const_char_ptr, "mime_bundle mime_at: index out of range");
    }
    return YETTY_OK(yetty_ycore_const_char_ptr, bundle->reprs[index].mime_type);
}

/* kind_at: payload kind of representation `index` — "text", "binary", or
 * "json" (borrowed static string). */
YETTY_ANNOTATE("virtual@ynotebook:mime_bundle:mime_bundle_kind_at")
YETTY_ANNOTATE("local@ynotebook:mime_bundle_kind_at")
static struct yetty_ycore_const_char_ptr_result mime_bundle_kind_at(struct yetty_yclass_object *obj,
                                                                    size_t index)
{
    struct yetty_yclass_void_ptr_result bundle_r = bundle_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_const_char_ptr, bundle_r, "mime_bundle kind_at: from_obj");
    struct yetty_ynotebook_mime_bundle *bundle = bundle_r.value;
    if (index >= bundle->count) {
        return YETTY_ERR(yetty_ycore_const_char_ptr, "mime_bundle kind_at: index out of range");
    }
    return YETTY_OK(yetty_ycore_const_char_ptr, kind_name(bundle->reprs[index].kind));
}

/* bytes_at: the text/binary payload of representation `index` (borrowed, points
 * into the bundle). Yields NULL/0 for a json representation. Local: it returns
 * a borrowed buffer through out-pointers. */
YETTY_ANNOTATE("virtual@ynotebook:mime_bundle:mime_bundle_bytes_at")
YETTY_ANNOTATE("local@ynotebook:mime_bundle_bytes_at")
static struct yetty_ycore_void_result mime_bundle_bytes_at(struct yetty_yclass_object *obj,
                                                           size_t index, const uint8_t **out_bytes,
                                                           size_t *out_len)
{
    struct yetty_yclass_void_ptr_result bundle_r = bundle_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, bundle_r, "mime_bundle bytes_at: from_obj");
    struct yetty_ynotebook_mime_bundle *bundle = bundle_r.value;
    if (index >= bundle->count) {
        return YETTY_ERR(yetty_ycore_void, "mime_bundle bytes_at: index out of range");
    }
    const struct yetty_ynotebook_mime_repr *repr = &bundle->reprs[index];
    if (out_bytes) {
        *out_bytes = repr->bytes;
    }
    if (out_len) {
        *out_len = repr->bytes_len;
    }
    return YETTY_OK_VOID();
}

/* json_at: representation `index` serialized as pretty JSON text (owned; caller
 * frees). Empty string for a non-json representation — bytes_at covers those.
 * Local: it allocates and returns owned text. */
YETTY_ANNOTATE("virtual@ynotebook:mime_bundle:mime_bundle_json_at")
YETTY_ANNOTATE("local@ynotebook:mime_bundle_json_at")
static struct yetty_ycore_char_ptr_result mime_bundle_json_at(struct yetty_yclass_object *obj,
                                                              size_t index)
{
    struct yetty_yclass_void_ptr_result bundle_r = bundle_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_char_ptr, bundle_r, "mime_bundle json_at: from_obj");
    struct yetty_ynotebook_mime_bundle *bundle = bundle_r.value;
    if (index >= bundle->count) {
        return YETTY_ERR(yetty_ycore_char_ptr, "mime_bundle json_at: index out of range");
    }
    const struct yetty_ynotebook_mime_repr *repr = &bundle->reprs[index];
    char *text = NULL;
    if (repr->kind == YETTY_YNOTEBOOK_MIME_KIND_JSON && repr->json) {
        text = yyjson_mut_write(repr->json, YYJSON_WRITE_PRETTY, NULL);
    }
    if (!text) {
        text = strdup("");
    }
    if (!text) {
        return YETTY_ERR(yetty_ycore_char_ptr, "mime_bundle json_at: alloc failed");
    }
    return YETTY_OK(yetty_ycore_char_ptr, text);
}

/* destroy: free the representations and the yclass allocation. */
YETTY_ANNOTATE("virtual@ynotebook:mime_bundle:mime_bundle_destroy")
YETTY_ANNOTATE("local@ynotebook:mime_bundle_destroy")
static struct yetty_ycore_void_result mime_bundle_destroy(struct yetty_yclass_object *obj)
{
    if (!obj) {
        return YETTY_OK_VOID();
    }
    struct yetty_yclass_void_ptr_result bundle_r = bundle_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, bundle_r, "mime_bundle destroy: from_obj");
    bundle_clear(bundle_r.value);
    return yetty_yclass_object_free(obj);
}

#include "mime-bundle.gen.c"
