/*
 * ynotebook document model — the nbformat 4 notebook, its cells, and their
 * outputs, as yclass classes.
 *
 *   ynotebook:notebook  — the document. Owns a master mutable JSON tree (the
 *                         whole .ipynb) plus a vector of cell view-objects.
 *   ynotebook:cell      — one cell: a typed view over its node in the master
 *                         tree, plus a vector of output view-objects.
 *   ynotebook:output    — one output: a typed view over its node, plus a
 *                         `mime_bundle` object for display_data / execute_result.
 *
 * Fidelity: the cells and outputs are *views* over the retained master tree, so
 * serializing the notebook re-emits that tree — unknown fields, metadata, and
 * representations Yetty does not model all survive a load/save cycle. Edits go
 * through methods that mutate the same tree.
 *
 * The public interface is generated by yclass codegen from the annotations
 * below — never hand-write notebook.h. JSON is parsed/written with yyjson;
 * that dependency stays out of the public method surface (load/serialize take
 * and return JSON text).
 */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <yyjson.h>

#include <yetty/yclass/class.h>
#include <yetty/ycore/result.h>
#include <yetty/ycore/types.h>
#include <yetty/ycore/util.h>

#include "yetty/gen/impl/ynotebook/mime-bundle.h" /* mime_bundle create / load / destroy */

/*=============================================================================
 * Class data
 *===========================================================================*/

struct YETTY_ANNOTATE("class@ynotebook:output") yetty_ynotebook_output {
    yyjson_mut_doc *doc;  /* master doc (borrowed; notebook owns it) */
    yyjson_mut_val *node; /* this output's object node in the master */
    struct yetty_yclass_object
        *bundle; /* mime_bundle for display/execute_result; owned; else NULL */
};

struct YETTY_ANNOTATE("class@ynotebook:cell") yetty_ynotebook_cell {
    yyjson_mut_doc *doc;                  /* master doc (borrowed) */
    yyjson_mut_val *node;                 /* this cell's object node in the master */
    struct yetty_yclass_object **outputs; /* output view-objects; owned vector */
    size_t output_count;
    int pending_clear; /* a clear_output(wait=true) is deferred to the next output */
};

struct YETTY_ANNOTATE("class@ynotebook:notebook") yetty_ynotebook_notebook {
    yyjson_mut_doc *doc;                /* master document; owns all JSON. NULL until load. */
    yyjson_mut_val *root;               /* root object of `doc` */
    struct yetty_yclass_object **cells; /* cell view-objects; owned vector */
    size_t cell_count;
};

/* Result wrappers, declared here so the appended notebook.gen.c has them in
 * scope (this TU does not include the generated notebook.h). */
YETTY_YRESULT_DECLARE(yetty_ynotebook_output_ptr, struct yetty_ynotebook_output *);
YETTY_YRESULT_DECLARE(yetty_ynotebook_cell_ptr, struct yetty_ynotebook_cell *);
YETTY_YRESULT_DECLARE(yetty_ynotebook_notebook_ptr, struct yetty_ynotebook_notebook *);

/* Defined in the appended notebook.gen.c (foot of this TU). */
struct yetty_yclass_ptr_result yetty_ynotebook_output_class_get(void);
struct yetty_yclass_ptr_result yetty_ynotebook_cell_class_get(void);
struct yetty_yclass_ptr_result yetty_ynotebook_notebook_class_get(void);
struct yetty_yclass_object_ptr_result yetty_ynotebook_output_create(struct yetty_yclass_ctx *ctx);
struct yetty_yclass_object_ptr_result yetty_ynotebook_cell_create(struct yetty_yclass_ctx *ctx);
struct yetty_yclass_object_ptr_result yetty_ynotebook_notebook_create(struct yetty_yclass_ctx *ctx);

static struct yetty_yclass_void_ptr_result output_from_obj(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_ptr_result class_r = yetty_ynotebook_output_class_get();
    YETTY_RETURN_IF_ERR(yetty_yclass_void_ptr, class_r, "output from_obj: class_get");
    return yetty_yclass_object_data(obj, class_r.value);
}

static struct yetty_yclass_void_ptr_result cell_from_obj(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_ptr_result class_r = yetty_ynotebook_cell_class_get();
    YETTY_RETURN_IF_ERR(yetty_yclass_void_ptr, class_r, "cell from_obj: class_get");
    return yetty_yclass_object_data(obj, class_r.value);
}

static struct yetty_yclass_void_ptr_result notebook_from_obj(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_ptr_result class_r = yetty_ynotebook_notebook_class_get();
    YETTY_RETURN_IF_ERR(yetty_yclass_void_ptr, class_r, "notebook from_obj: class_get");
    return yetty_yclass_object_data(obj, class_r.value);
}

/*=============================================================================
 * yyjson read helpers (over the mutable master tree)
 *===========================================================================*/

static const char *mut_cstr(yyjson_mut_val *obj, const char *key)
{
    yyjson_mut_val *val = yyjson_mut_obj_get(obj, key);
    return (val && yyjson_mut_is_str(val)) ? yyjson_mut_get_str(val) : NULL;
}

static long mut_cint(yyjson_mut_val *obj, const char *key, long fallback)
{
    yyjson_mut_val *val = yyjson_mut_obj_get(obj, key);
    return (val && yyjson_mut_is_int(val)) ? (long)yyjson_mut_get_sint(val) : fallback;
}

static bool mut_cbool(yyjson_mut_val *obj, const char *key, bool fallback)
{
    yyjson_mut_val *val = yyjson_mut_obj_get(obj, key);
    return (val && yyjson_mut_is_bool(val)) ? yyjson_mut_get_bool(val) : fallback;
}

/* Join an nbformat text value (a string, or a list-of-strings concatenated with
 * no added separators) into an owned, NUL-terminated buffer. Returns NULL when
 * absent or not string-shaped. */
static char *join_mut_text(yyjson_mut_val *val)
{
    if (!val) {
        return NULL;
    }
    if (yyjson_mut_is_str(val)) {
        size_t len = yyjson_mut_get_len(val);
        char *buf = malloc(len + 1);
        if (!buf) {
            return NULL;
        }
        memcpy(buf, yyjson_mut_get_str(val), len);
        buf[len] = 0;
        return buf;
    }
    if (yyjson_mut_is_arr(val)) {
        size_t count = yyjson_mut_arr_size(val);
        size_t total = 0;
        for (size_t i = 0; i < count; i++) {
            yyjson_mut_val *item = yyjson_mut_arr_get(val, i);
            if (!item || !yyjson_mut_is_str(item)) {
                return NULL;
            }
            total += yyjson_mut_get_len(item);
        }
        char *buf = malloc(total + 1);
        if (!buf) {
            return NULL;
        }
        size_t offset = 0;
        for (size_t i = 0; i < count; i++) {
            yyjson_mut_val *item = yyjson_mut_arr_get(val, i);
            size_t len = yyjson_mut_get_len(item);
            memcpy(buf + offset, yyjson_mut_get_str(item), len);
            offset += len;
        }
        buf[total] = 0;
        return buf;
    }
    return NULL;
}

/* Join an array-of-strings with a newline between elements (an owned,
 * NUL-terminated buffer). Used for an error output's "traceback" frames, whose
 * elements are individual lines carrying no trailing newline. NULL when absent
 * or not an array-of-strings. */
static char *join_mut_lines(yyjson_mut_val *val)
{
    if (!val || !yyjson_mut_is_arr(val)) {
        return NULL;
    }
    size_t count = yyjson_mut_arr_size(val);
    size_t total = 0;
    for (size_t i = 0; i < count; i++) {
        yyjson_mut_val *item = yyjson_mut_arr_get(val, i);
        if (!item || !yyjson_mut_is_str(item)) {
            return NULL;
        }
        total += yyjson_mut_get_len(item) + 1; /* + newline */
    }
    char *buf = malloc(total + 1);
    if (!buf) {
        return NULL;
    }
    size_t offset = 0;
    for (size_t i = 0; i < count; i++) {
        yyjson_mut_val *item = yyjson_mut_arr_get(val, i);
        size_t len = yyjson_mut_get_len(item);
        memcpy(buf + offset, yyjson_mut_get_str(item), len);
        offset += len;
        buf[offset++] = '\n';
    }
    buf[offset] = 0;
    return buf;
}

/* Serialize one node to owned JSON text (NULL on absent/failure). */
static char *mut_val_to_text(yyjson_mut_val *val)
{
    return val ? yyjson_mut_val_write(val, 0, NULL) : NULL;
}

/*=============================================================================
 * Teardown
 *===========================================================================*/

static void output_free_fields(struct yetty_ynotebook_output *output)
{
    if (output->bundle) {
        yetty_ynotebook_mime_bundle_destroy(output->bundle);
        output->bundle = NULL;
    }
}

static void cell_free_fields(struct yetty_ynotebook_cell *cell)
{
    for (size_t i = 0; i < cell->output_count; i++) {
        struct yetty_yclass_object *output_obj = cell->outputs[i];
        if (!output_obj) {
            continue;
        }
        struct yetty_yclass_void_ptr_result output_r = output_from_obj(output_obj);
        if (YETTY_IS_OK(output_r)) {
            output_free_fields(output_r.value);
        }
        yetty_yclass_object_free(output_obj);
    }
    free(cell->outputs);
    cell->outputs = NULL;
    cell->output_count = 0;
}

static void notebook_clear(struct yetty_ynotebook_notebook *notebook)
{
    for (size_t i = 0; i < notebook->cell_count; i++) {
        struct yetty_yclass_object *cell_obj = notebook->cells[i];
        if (!cell_obj) {
            continue;
        }
        struct yetty_yclass_void_ptr_result cell_r = cell_from_obj(cell_obj);
        if (YETTY_IS_OK(cell_r)) {
            cell_free_fields(cell_r.value);
        }
        yetty_yclass_object_free(cell_obj);
    }
    free(notebook->cells);
    notebook->cells = NULL;
    notebook->cell_count = 0;
    if (notebook->doc) {
        yyjson_mut_doc_free(notebook->doc);
        notebook->doc = NULL;
    }
    notebook->root = NULL;
}

/*=============================================================================
 * Parse: build view-objects over the master tree
 *===========================================================================*/

/* For a display_data / execute_result output, build a mime_bundle object from
 * the output's `data` (+ `metadata`) sub-objects. */
static struct yetty_ycore_void_result output_build_bundle(struct yetty_ynotebook_output *output)
{
    const char *type = mut_cstr(output->node, "output_type");
    if (!type) {
        return YETTY_OK_VOID();
    }
    if (strcmp(type, "display_data") != 0 && strcmp(type, "execute_result") != 0) {
        return YETTY_OK_VOID();
    }

    char *data_text = mut_val_to_text(yyjson_mut_obj_get(output->node, "data"));
    char *metadata_text = mut_val_to_text(yyjson_mut_obj_get(output->node, "metadata"));

    struct yetty_yclass_ctx ctx = {0};
    struct yetty_yclass_object_ptr_result bundle_r = yetty_ynotebook_mime_bundle_create(&ctx);
    if (YETTY_IS_ERR(bundle_r)) {
        free(data_text);
        free(metadata_text);
        return YETTY_ERR(yetty_ycore_void, "output build_bundle: create failed", bundle_r);
    }
    output->bundle = bundle_r.value;

    struct yetty_ycore_void_result load_r = yetty_ynotebook_mime_bundle_from_json_text(
        output->bundle, data_text ? data_text : "{}", metadata_text);
    free(data_text);
    free(metadata_text);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, load_r, "output build_bundle: bundle load");
    return YETTY_OK_VOID();
}

static struct yetty_ycore_void_result cell_build_outputs(struct yetty_ynotebook_cell *cell)
{
    yyjson_mut_val *outputs = yyjson_mut_obj_get(cell->node, "outputs");
    if (!outputs || !yyjson_mut_is_arr(outputs)) {
        return YETTY_OK_VOID();
    }

    size_t count = yyjson_mut_arr_size(outputs);
    if (count == 0) {
        return YETTY_OK_VOID();
    }

    cell->outputs = calloc(count, sizeof(*cell->outputs));
    if (!cell->outputs) {
        return YETTY_ERR(yetty_ycore_void, "cell build_outputs: vector alloc failed");
    }

    for (size_t i = 0; i < count; i++) {
        yyjson_mut_val *output_node = yyjson_mut_arr_get(outputs, i);
        struct yetty_yclass_ctx ctx = {0};
        struct yetty_yclass_object_ptr_result output_r = yetty_ynotebook_output_create(&ctx);
        YETTY_RETURN_IF_ERR(yetty_ycore_void, output_r, "cell build_outputs: output create");
        struct yetty_yclass_object *output_obj = output_r.value;

        struct yetty_yclass_void_ptr_result data_r = output_from_obj(output_obj);
        YETTY_RETURN_IF_ERR(yetty_ycore_void, data_r, "cell build_outputs: output from_obj");
        struct yetty_ynotebook_output *output = data_r.value;
        output->doc = cell->doc;
        output->node = output_node;

        struct yetty_ycore_void_result bundle_r = output_build_bundle(output);
        if (YETTY_IS_ERR(bundle_r)) {
            yetty_yclass_object_free(output_obj);
            return YETTY_ERR(yetty_ycore_void, "cell build_outputs: build bundle", bundle_r);
        }

        cell->outputs[cell->output_count++] = output_obj;
    }
    return YETTY_OK_VOID();
}

static struct yetty_ycore_void_result notebook_populate(struct yetty_ynotebook_notebook *notebook,
                                                        const char *json, size_t len)
{
    yyjson_doc *input = yyjson_read(json, len, 0);
    if (!input) {
        return YETTY_ERR(yetty_ycore_void, "notebook load: JSON parse failed");
    }
    yyjson_mut_doc *master = yyjson_doc_mut_copy(input, NULL);
    yyjson_doc_free(input);
    if (!master) {
        return YETTY_ERR(yetty_ycore_void, "notebook load: mutable copy failed");
    }

    yyjson_mut_val *root = yyjson_mut_doc_get_root(master);
    if (!root || !yyjson_mut_is_obj(root)) {
        yyjson_mut_doc_free(master);
        return YETTY_ERR(yetty_ycore_void, "notebook load: root is not a JSON object");
    }

    notebook_clear(notebook);
    notebook->doc = master;
    notebook->root = root;

    yyjson_mut_val *cells = yyjson_mut_obj_get(root, "cells");
    if (!cells || !yyjson_mut_is_arr(cells)) {
        return YETTY_OK_VOID(); /* a notebook with no cells is valid */
    }

    size_t count = yyjson_mut_arr_size(cells);
    if (count == 0) {
        return YETTY_OK_VOID();
    }

    notebook->cells = calloc(count, sizeof(*notebook->cells));
    if (!notebook->cells) {
        return YETTY_ERR(yetty_ycore_void, "notebook load: cell vector alloc failed");
    }

    for (size_t i = 0; i < count; i++) {
        yyjson_mut_val *cell_node = yyjson_mut_arr_get(cells, i);
        struct yetty_yclass_ctx ctx = {0};
        struct yetty_yclass_object_ptr_result cell_r = yetty_ynotebook_cell_create(&ctx);
        YETTY_RETURN_IF_ERR(yetty_ycore_void, cell_r, "notebook load: cell create");
        struct yetty_yclass_object *cell_obj = cell_r.value;

        struct yetty_yclass_void_ptr_result data_r = cell_from_obj(cell_obj);
        YETTY_RETURN_IF_ERR(yetty_ycore_void, data_r, "notebook load: cell from_obj");
        struct yetty_ynotebook_cell *cell = data_r.value;
        cell->doc = master;
        cell->node = cell_node;

        struct yetty_ycore_void_result outputs_r = cell_build_outputs(cell);
        if (YETTY_IS_ERR(outputs_r)) {
            cell_free_fields(cell);
            yetty_yclass_object_free(cell_obj);
            return YETTY_ERR(yetty_ycore_void, "notebook load: build outputs", outputs_r);
        }

        notebook->cells[notebook->cell_count++] = cell_obj;
    }
    return YETTY_OK_VOID();
}

/*=============================================================================
 * output method slots
 *===========================================================================*/

/* output_type: "stream", "display_data", "execute_result", "error", or the raw
 * type string of an output kind Yetty does not model. */
YETTY_ANNOTATE("virtual@ynotebook:output:output_type")
YETTY_ANNOTATE("local@ynotebook:output_type")
static struct yetty_ycore_const_char_ptr_result output_type(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result output_r = output_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_const_char_ptr, output_r, "output_type: from_obj");
    struct yetty_ynotebook_output *output = output_r.value;
    const char *type = mut_cstr(output->node, "output_type");
    return YETTY_OK(yetty_ycore_const_char_ptr, type ? type : "");
}

/* stream_name: "stdout" / "stderr" for a stream output; "" otherwise. */
YETTY_ANNOTATE("virtual@ynotebook:output:output_stream_name")
YETTY_ANNOTATE("local@ynotebook:output_stream_name")
static struct yetty_ycore_const_char_ptr_result output_stream_name(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result output_r = output_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_const_char_ptr, output_r, "output_stream_name: from_obj");
    struct yetty_ynotebook_output *output = output_r.value;
    const char *name = mut_cstr(output->node, "name");
    return YETTY_OK(yetty_ycore_const_char_ptr, name ? name : "");
}

/* text: the stream text of a stream output (owned; caller frees). Empty string
 * for non-stream outputs. */
YETTY_ANNOTATE("virtual@ynotebook:output:output_text")
YETTY_ANNOTATE("local@ynotebook:output_text")
static struct yetty_ycore_char_ptr_result output_text(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result output_r = output_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_char_ptr, output_r, "output_text: from_obj");
    struct yetty_ynotebook_output *output = output_r.value;
    /* stream outputs carry a "text" field; error outputs carry the frames in a
     * "traceback" array instead — fall back to it so errors are not blank. */
    char *text = join_mut_text(yyjson_mut_obj_get(output->node, "text"));
    if (!text) {
        text = join_mut_lines(yyjson_mut_obj_get(output->node, "traceback"));
    }
    if (!text) {
        text = strdup("");
    }
    if (!text) {
        return YETTY_ERR(yetty_ycore_char_ptr, "output_text: alloc failed");
    }
    return YETTY_OK(yetty_ycore_char_ptr, text);
}

/* execution_count: the execute_result prompt number, or -1 when absent/null. */
YETTY_ANNOTATE("virtual@ynotebook:output:output_execution_count")
YETTY_ANNOTATE("local@ynotebook:output_execution_count")
static struct yetty_ycore_int_result output_execution_count(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result output_r = output_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_int, output_r, "output_execution_count: from_obj");
    struct yetty_ynotebook_output *output = output_r.value;
    return YETTY_OK(yetty_ycore_int, (int)mut_cint(output->node, "execution_count", -1));
}

/* error_name / error_value: the ename / evalue of an error output; "" else. */
YETTY_ANNOTATE("virtual@ynotebook:output:output_error_name")
YETTY_ANNOTATE("local@ynotebook:output_error_name")
static struct yetty_ycore_const_char_ptr_result output_error_name(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result output_r = output_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_const_char_ptr, output_r, "output_error_name: from_obj");
    struct yetty_ynotebook_output *output = output_r.value;
    const char *name = mut_cstr(output->node, "ename");
    return YETTY_OK(yetty_ycore_const_char_ptr, name ? name : "");
}

YETTY_ANNOTATE("virtual@ynotebook:output:output_error_value")
YETTY_ANNOTATE("local@ynotebook:output_error_value")
static struct yetty_ycore_const_char_ptr_result output_error_value(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result output_r = output_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_const_char_ptr, output_r, "output_error_value: from_obj");
    struct yetty_ynotebook_output *output = output_r.value;
    const char *value = mut_cstr(output->node, "evalue");
    return YETTY_OK(yetty_ycore_const_char_ptr, value ? value : "");
}

/* bundle: the mime_bundle object for a display_data / execute_result output.
 * Errors when the output carries no rich data. The bundle is owned by the
 * output — do not destroy it directly. */
YETTY_ANNOTATE("virtual@ynotebook:output:output_bundle")
YETTY_ANNOTATE("local@ynotebook:output_bundle")
static struct yetty_yclass_object_ptr_result output_bundle(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result output_r = output_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_yclass_object_ptr, output_r, "output_bundle: from_obj");
    struct yetty_ynotebook_output *output = output_r.value;
    if (!output->bundle) {
        return YETTY_ERR(yetty_yclass_object_ptr, "output_bundle: output has no rich data");
    }
    return YETTY_OK(yetty_yclass_object_ptr, output->bundle);
}

/* destroy: free the mime_bundle and the yclass allocation. */
YETTY_ANNOTATE("virtual@ynotebook:output:output_destroy")
YETTY_ANNOTATE("local@ynotebook:output_destroy")
static struct yetty_ycore_void_result output_destroy(struct yetty_yclass_object *obj)
{
    if (!obj) {
        return YETTY_OK_VOID();
    }
    struct yetty_yclass_void_ptr_result output_r = output_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, output_r, "output_destroy: from_obj");
    output_free_fields(output_r.value);
    return yetty_yclass_object_free(obj);
}

/*=============================================================================
 * cell method slots
 *===========================================================================*/

/* cell_type: "code", "markdown", "raw", or a raw type Yetty does not model. */
YETTY_ANNOTATE("virtual@ynotebook:cell:cell_type")
YETTY_ANNOTATE("local@ynotebook:cell_type")
static struct yetty_ycore_const_char_ptr_result cell_type(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result cell_r = cell_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_const_char_ptr, cell_r, "cell_type: from_obj");
    struct yetty_ynotebook_cell *cell = cell_r.value;
    const char *type = mut_cstr(cell->node, "cell_type");
    return YETTY_OK(yetty_ycore_const_char_ptr, type ? type : "");
}

/* cell_id: the cell id (nbformat 4.5+); "" when absent. */
YETTY_ANNOTATE("virtual@ynotebook:cell:cell_id")
YETTY_ANNOTATE("local@ynotebook:cell_id")
static struct yetty_ycore_const_char_ptr_result cell_id(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result cell_r = cell_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_const_char_ptr, cell_r, "cell_id: from_obj");
    struct yetty_ynotebook_cell *cell = cell_r.value;
    const char *id = mut_cstr(cell->node, "id");
    return YETTY_OK(yetty_ycore_const_char_ptr, id ? id : "");
}

/* cell_source: the cell source, joined to one string (owned; caller frees). */
YETTY_ANNOTATE("virtual@ynotebook:cell:cell_source")
YETTY_ANNOTATE("local@ynotebook:cell_source")
static struct yetty_ycore_char_ptr_result cell_source(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result cell_r = cell_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_char_ptr, cell_r, "cell_source: from_obj");
    struct yetty_ynotebook_cell *cell = cell_r.value;
    char *source = join_mut_text(yyjson_mut_obj_get(cell->node, "source"));
    if (!source) {
        source = strdup("");
    }
    if (!source) {
        return YETTY_ERR(yetty_ycore_char_ptr, "cell_source: alloc failed");
    }
    return YETTY_OK(yetty_ycore_char_ptr, source);
}

/* cell_set_source: replace the cell source with `text` (stored as one string). */
YETTY_ANNOTATE("virtual@ynotebook:cell:cell_set_source")
YETTY_ANNOTATE("local@ynotebook:cell_set_source")
static struct yetty_ycore_void_result cell_set_source(struct yetty_yclass_object *obj,
                                                      const char *text)
{
    struct yetty_yclass_void_ptr_result cell_r = cell_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, cell_r, "cell_set_source: from_obj");
    struct yetty_ynotebook_cell *cell = cell_r.value;
    if (!cell->doc) {
        return YETTY_ERR(yetty_ycore_void, "cell_set_source: detached cell");
    }
    yyjson_mut_obj_remove_key(cell->node, "source");
    if (!yyjson_mut_obj_add_strcpy(cell->doc, cell->node, "source", text ? text : "")) {
        return YETTY_ERR(yetty_ycore_void, "cell_set_source: write failed");
    }
    return YETTY_OK_VOID();
}

/* cell_execution_count: code-cell prompt number, or -1 when absent/null. */
YETTY_ANNOTATE("virtual@ynotebook:cell:cell_execution_count")
YETTY_ANNOTATE("local@ynotebook:cell_execution_count")
static struct yetty_ycore_int_result cell_execution_count(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result cell_r = cell_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_int, cell_r, "cell_execution_count: from_obj");
    struct yetty_ynotebook_cell *cell = cell_r.value;
    return YETTY_OK(yetty_ycore_int, (int)mut_cint(cell->node, "execution_count", -1));
}

/* cell_output_count: number of outputs (code cells). */
YETTY_ANNOTATE("virtual@ynotebook:cell:cell_output_count")
YETTY_ANNOTATE("local@ynotebook:cell_output_count")
static struct yetty_ycore_size_result cell_output_count(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result cell_r = cell_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_size, cell_r, "cell_output_count: from_obj");
    struct yetty_ynotebook_cell *cell = cell_r.value;
    return YETTY_OK(yetty_ycore_size, cell->output_count);
}

/* cell_output_at: the output object at `index` (owned by the cell). */
YETTY_ANNOTATE("virtual@ynotebook:cell:cell_output_at")
YETTY_ANNOTATE("local@ynotebook:cell_output_at")
static struct yetty_yclass_object_ptr_result cell_output_at(struct yetty_yclass_object *obj,
                                                            size_t index)
{
    struct yetty_yclass_void_ptr_result cell_r = cell_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_yclass_object_ptr, cell_r, "cell_output_at: from_obj");
    struct yetty_ynotebook_cell *cell = cell_r.value;
    if (index >= cell->output_count) {
        return YETTY_ERR(yetty_yclass_object_ptr, "cell_output_at: index out of range");
    }
    return YETTY_OK(yetty_yclass_object_ptr, cell->outputs[index]);
}

/* cell_metadata_json: the cell metadata object as JSON text (owned). */
YETTY_ANNOTATE("virtual@ynotebook:cell:cell_metadata_json")
YETTY_ANNOTATE("local@ynotebook:cell_metadata_json")
static struct yetty_ycore_char_ptr_result cell_metadata_json(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result cell_r = cell_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_char_ptr, cell_r, "cell_metadata_json: from_obj");
    struct yetty_ynotebook_cell *cell = cell_r.value;
    char *text = mut_val_to_text(yyjson_mut_obj_get(cell->node, "metadata"));
    if (!text) {
        text = strdup("{}");
    }
    if (!text) {
        return YETTY_ERR(yetty_ycore_char_ptr, "cell_metadata_json: alloc failed");
    }
    return YETTY_OK(yetty_ycore_char_ptr, text);
}

/* Replace the cell's outputs with a fresh empty array. */
static void cell_clear_outputs_array(struct yetty_ynotebook_cell *cell)
{
    yyjson_mut_obj_remove_key(cell->node, "outputs");
    yyjson_mut_val *empty = yyjson_mut_arr(cell->doc);
    if (empty) {
        yyjson_mut_obj_add_val(cell->doc, cell->node, "outputs", empty);
    }
}

static yyjson_mut_val *cell_ensure_outputs_array(struct yetty_ynotebook_cell *cell)
{
    yyjson_mut_val *outputs = yyjson_mut_obj_get(cell->node, "outputs");
    if (outputs && yyjson_mut_is_arr(outputs)) {
        return outputs;
    }
    yyjson_mut_obj_remove_key(cell->node, "outputs");
    outputs = yyjson_mut_arr(cell->doc);
    if (outputs) {
        yyjson_mut_obj_add_val(cell->doc, cell->node, "outputs", outputs);
    }
    return outputs;
}

/* Append a stream record, coalescing with the previous output when it is a
 * stream of the same name (nbformat's stream-coalescing rule). */
static struct yetty_ycore_void_result cell_append_stream(struct yetty_ynotebook_cell *cell,
                                                         yyjson_mut_val *outputs,
                                                         yyjson_mut_val *content)
{
    const char *name = content ? mut_cstr(content, "name") : NULL;
    if (!name) {
        name = "stdout";
    }
    char *text = content ? join_mut_text(yyjson_mut_obj_get(content, "text")) : NULL;
    const char *text_str = text ? text : "";

    size_t count = yyjson_mut_arr_size(outputs);
    yyjson_mut_val *last = count ? yyjson_mut_arr_get(outputs, count - 1) : NULL;
    const char *last_type = last ? mut_cstr(last, "output_type") : NULL;
    const char *last_name = last ? mut_cstr(last, "name") : NULL;

    if (last && last_type && strcmp(last_type, "stream") == 0 && last_name &&
        strcmp(last_name, name) == 0) {
        char *existing = join_mut_text(yyjson_mut_obj_get(last, "text"));
        size_t existing_len = existing ? strlen(existing) : 0;
        size_t text_len = strlen(text_str);
        char *combined = malloc(existing_len + text_len + 1);
        if (!combined) {
            free(existing);
            free(text);
            return YETTY_ERR(yetty_ycore_void, "cell stream coalesce: alloc failed");
        }
        if (existing_len) {
            memcpy(combined, existing, existing_len);
        }
        memcpy(combined + existing_len, text_str, text_len);
        combined[existing_len + text_len] = 0;
        free(existing);
        yyjson_mut_obj_remove_key(last, "text");
        yyjson_mut_obj_add_strcpy(cell->doc, last, "text", combined);
        free(combined);
    } else {
        yyjson_mut_val *node = yyjson_mut_obj(cell->doc);
        yyjson_mut_obj_add_strcpy(cell->doc, node, "output_type", "stream");
        yyjson_mut_obj_add_strcpy(cell->doc, node, "name", name);
        yyjson_mut_obj_add_strcpy(cell->doc, node, "text", text_str);
        yyjson_mut_arr_append(outputs, node);
    }
    free(text);
    return YETTY_OK_VOID();
}

/* Append a display_data / execute_result / error output: the message content is
 * the output object minus its output_type, which we add. */
static struct yetty_ycore_void_result cell_append_rich(struct yetty_ynotebook_cell *cell,
                                                       yyjson_mut_val *outputs,
                                                       const char *msg_type,
                                                       yyjson_mut_val *content)
{
    yyjson_mut_val *node =
        content ? yyjson_mut_val_mut_copy(cell->doc, content) : yyjson_mut_obj(cell->doc);
    if (!node || !yyjson_mut_is_obj(node)) {
        node = yyjson_mut_obj(cell->doc);
    }
    if (!node) {
        return YETTY_ERR(yetty_ycore_void, "cell append_rich: node alloc failed");
    }
    yyjson_mut_obj_remove_key(node, "output_type");
    yyjson_mut_obj_add_strcpy(cell->doc, node, "output_type", msg_type);
    yyjson_mut_arr_append(outputs, node);
    return YETTY_OK_VOID();
}

/* apply_message: fold a decoded IOPub output message (msg_type + its content as
 * JSON text) into this cell's outputs, mutating the retained tree. Implements
 * the nbformat output rules: consecutive same-name stream records coalesce;
 * clear_output(wait=true) defers the clear until the next output arrives;
 * display_data / execute_result / error append. Non-output message types
 * (status, execute_input, …) are ignored. */
YETTY_ANNOTATE("virtual@ynotebook:cell:cell_apply_message")
YETTY_ANNOTATE("local@ynotebook:cell_apply_message")
static struct yetty_ycore_void_result cell_apply_message(struct yetty_yclass_object *obj,
                                                         const char *msg_type,
                                                         const char *content_json)
{
    struct yetty_yclass_void_ptr_result cell_r = cell_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, cell_r, "cell_apply_message: from_obj");
    struct yetty_ynotebook_cell *cell = cell_r.value;
    if (!cell->doc) {
        return YETTY_ERR(yetty_ycore_void, "cell_apply_message: detached cell");
    }
    if (!msg_type) {
        return YETTY_ERR(yetty_ycore_void, "cell_apply_message: NULL msg_type");
    }

    yyjson_mut_doc *content_doc = NULL;
    yyjson_mut_val *content = NULL;
    if (content_json && content_json[0]) {
        yyjson_doc *parsed = yyjson_read(content_json, strlen(content_json), 0);
        if (parsed) {
            content_doc = yyjson_doc_mut_copy(parsed, NULL);
            yyjson_doc_free(parsed);
            if (content_doc) {
                content = yyjson_mut_doc_get_root(content_doc);
            }
        }
    }

    bool is_stream = strcmp(msg_type, "stream") == 0;
    bool is_rich = strcmp(msg_type, "display_data") == 0 ||
                   strcmp(msg_type, "execute_result") == 0 || strcmp(msg_type, "error") == 0;
    bool is_clear = strcmp(msg_type, "clear_output") == 0;

    struct yetty_ycore_void_result result = YETTY_OK_VOID();
    bool mutated = false;

    if (is_clear) {
        if (content && mut_cbool(content, "wait", false)) {
            cell->pending_clear = 1;
        } else {
            cell_clear_outputs_array(cell);
            cell->pending_clear = 0;
            mutated = true;
        }
    } else if (is_stream || is_rich) {
        if (cell->pending_clear) {
            cell_clear_outputs_array(cell);
            cell->pending_clear = 0;
        }
        yyjson_mut_val *outputs = cell_ensure_outputs_array(cell);
        if (!outputs) {
            result = YETTY_ERR(yetty_ycore_void, "cell_apply_message: outputs array");
        } else if (is_stream) {
            result = cell_append_stream(cell, outputs, content);
        } else {
            result = cell_append_rich(cell, outputs, msg_type, content);
        }
        mutated = true;
    }

    if (content_doc) {
        yyjson_mut_doc_free(content_doc);
    }
    YETTY_RETURN_IF_ERR(yetty_ycore_void, result, "cell_apply_message: apply");

    if (mutated) {
        cell_free_fields(cell);
        return cell_build_outputs(cell);
    }
    return YETTY_OK_VOID();
}

/* destroy: free the output objects and the yclass allocation. */
YETTY_ANNOTATE("virtual@ynotebook:cell:cell_destroy")
YETTY_ANNOTATE("local@ynotebook:cell_destroy")
static struct yetty_ycore_void_result cell_destroy(struct yetty_yclass_object *obj)
{
    if (!obj) {
        return YETTY_OK_VOID();
    }
    struct yetty_yclass_void_ptr_result cell_r = cell_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, cell_r, "cell_destroy: from_obj");
    cell_free_fields(cell_r.value);
    return yetty_yclass_object_free(obj);
}

/*=============================================================================
 * notebook method slots
 *===========================================================================*/

/* load_text: parse an .ipynb document from JSON text, replacing any current
 * content. */
YETTY_ANNOTATE("virtual@ynotebook:notebook:notebook_load_text")
YETTY_ANNOTATE("local@ynotebook:notebook_load_text")
static struct yetty_ycore_void_result notebook_load_text(struct yetty_yclass_object *obj,
                                                         const char *json)
{
    struct yetty_yclass_void_ptr_result notebook_r = notebook_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, notebook_r, "notebook_load_text: from_obj");
    if (!json) {
        return YETTY_ERR(yetty_ycore_void, "notebook_load_text: NULL json");
    }
    return notebook_populate(notebook_r.value, json, strlen(json));
}

/* load_file: read and parse an .ipynb file, replacing any current content. */
YETTY_ANNOTATE("virtual@ynotebook:notebook:notebook_load_file")
YETTY_ANNOTATE("local@ynotebook:notebook_load_file")
static struct yetty_ycore_void_result notebook_load_file(struct yetty_yclass_object *obj,
                                                         const char *path)
{
    struct yetty_yclass_void_ptr_result notebook_r = notebook_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, notebook_r, "notebook_load_file: from_obj");
    if (!path) {
        return YETTY_ERR(yetty_ycore_void, "notebook_load_file: NULL path");
    }

    struct yetty_ycore_buffer_result file_r = yetty_ycore_read_file(path);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, file_r, "notebook_load_file: read failed");
    struct yetty_ycore_void_result load_r =
        notebook_populate(notebook_r.value, (const char *)file_r.value.data, file_r.value.size);
    yetty_ycore_buffer_destroy(&file_r.value);
    return load_r;
}

/* to_text: serialize the notebook to nbformat JSON text (owned; caller frees).
 * The retained document tree is re-emitted, so unknown fields survive. */
YETTY_ANNOTATE("virtual@ynotebook:notebook:notebook_to_text")
YETTY_ANNOTATE("local@ynotebook:notebook_to_text")
static struct yetty_ycore_char_ptr_result notebook_to_text(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result notebook_r = notebook_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_char_ptr, notebook_r, "notebook_to_text: from_obj");
    struct yetty_ynotebook_notebook *notebook = notebook_r.value;
    if (!notebook->doc) {
        return YETTY_ERR(yetty_ycore_char_ptr, "notebook_to_text: no document loaded");
    }
    char *text = yyjson_mut_write(notebook->doc, YYJSON_WRITE_PRETTY, NULL);
    if (!text) {
        return YETTY_ERR(yetty_ycore_char_ptr, "notebook_to_text: write failed");
    }
    return YETTY_OK(yetty_ycore_char_ptr, text);
}

/* save_file: serialize and write the notebook atomically (temp sibling then
 * rename over the target). */
YETTY_ANNOTATE("virtual@ynotebook:notebook:notebook_save_file")
YETTY_ANNOTATE("local@ynotebook:notebook_save_file")
static struct yetty_ycore_void_result notebook_save_file(struct yetty_yclass_object *obj,
                                                         const char *path)
{
    struct yetty_yclass_void_ptr_result notebook_r = notebook_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, notebook_r, "notebook_save_file: from_obj");
    struct yetty_ynotebook_notebook *notebook = notebook_r.value;
    if (!notebook->doc) {
        return YETTY_ERR(yetty_ycore_void, "notebook_save_file: no document loaded");
    }
    if (!path) {
        return YETTY_ERR(yetty_ycore_void, "notebook_save_file: NULL path");
    }

    size_t text_len = 0;
    char *text = yyjson_mut_write(notebook->doc, YYJSON_WRITE_PRETTY, &text_len);
    if (!text) {
        return YETTY_ERR(yetty_ycore_void, "notebook_save_file: write failed");
    }

    size_t path_len = strlen(path);
    char *temp = malloc(path_len + 5);
    if (!temp) {
        free(text);
        return YETTY_ERR(yetty_ycore_void, "notebook_save_file: temp path alloc failed");
    }
    memcpy(temp, path, path_len);
    memcpy(temp + path_len, ".tmp", 5);

    struct yetty_ycore_void_result result = YETTY_OK_VOID();
    FILE *file = fopen(temp, "wb");
    if (!file) {
        result = YETTY_ERR(yetty_ycore_void, "notebook_save_file: cannot open temp file");
    } else {
        size_t written = fwrite(text, 1, text_len, file);
        int closed = fclose(file);
        if (written != text_len || closed != 0) {
            remove(temp);
            result = YETTY_ERR(yetty_ycore_void, "notebook_save_file: write to temp failed");
        } else if (rename(temp, path) != 0) {
            remove(temp);
            result = YETTY_ERR(yetty_ycore_void, "notebook_save_file: rename over target failed");
        }
    }

    free(temp);
    free(text);
    return result;
}

/* nbformat / nbformat_minor: the document format version. */
YETTY_ANNOTATE("virtual@ynotebook:notebook:notebook_nbformat")
YETTY_ANNOTATE("local@ynotebook:notebook_nbformat")
static struct yetty_ycore_int_result notebook_nbformat(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result notebook_r = notebook_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_int, notebook_r, "notebook_nbformat: from_obj");
    struct yetty_ynotebook_notebook *notebook = notebook_r.value;
    return YETTY_OK(yetty_ycore_int,
                    notebook->root ? (int)mut_cint(notebook->root, "nbformat", 0) : 0);
}

YETTY_ANNOTATE("virtual@ynotebook:notebook:notebook_nbformat_minor")
YETTY_ANNOTATE("local@ynotebook:notebook_nbformat_minor")
static struct yetty_ycore_int_result notebook_nbformat_minor(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result notebook_r = notebook_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_int, notebook_r, "notebook_nbformat_minor: from_obj");
    struct yetty_ynotebook_notebook *notebook = notebook_r.value;
    return YETTY_OK(yetty_ycore_int,
                    notebook->root ? (int)mut_cint(notebook->root, "nbformat_minor", 0) : 0);
}

/* cell_count: number of cells. */
YETTY_ANNOTATE("virtual@ynotebook:notebook:notebook_cell_count")
YETTY_ANNOTATE("local@ynotebook:notebook_cell_count")
static struct yetty_ycore_size_result notebook_cell_count(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result notebook_r = notebook_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_size, notebook_r, "notebook_cell_count: from_obj");
    struct yetty_ynotebook_notebook *notebook = notebook_r.value;
    return YETTY_OK(yetty_ycore_size, notebook->cell_count);
}

/* cell_at: the cell object at `index` (owned by the notebook). */
YETTY_ANNOTATE("virtual@ynotebook:notebook:notebook_cell_at")
YETTY_ANNOTATE("local@ynotebook:notebook_cell_at")
static struct yetty_yclass_object_ptr_result notebook_cell_at(struct yetty_yclass_object *obj,
                                                              size_t index)
{
    struct yetty_yclass_void_ptr_result notebook_r = notebook_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_yclass_object_ptr, notebook_r, "notebook_cell_at: from_obj");
    struct yetty_ynotebook_notebook *notebook = notebook_r.value;
    if (index >= notebook->cell_count) {
        return YETTY_ERR(yetty_yclass_object_ptr, "notebook_cell_at: index out of range");
    }
    return YETTY_OK(yetty_yclass_object_ptr, notebook->cells[index]);
}

/* metadata_json: the notebook-level metadata object as JSON text (owned). */
YETTY_ANNOTATE("virtual@ynotebook:notebook:notebook_metadata_json")
YETTY_ANNOTATE("local@ynotebook:notebook_metadata_json")
static struct yetty_ycore_char_ptr_result notebook_metadata_json(struct yetty_yclass_object *obj)
{
    struct yetty_yclass_void_ptr_result notebook_r = notebook_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_char_ptr, notebook_r, "notebook_metadata_json: from_obj");
    struct yetty_ynotebook_notebook *notebook = notebook_r.value;
    char *text =
        notebook->root ? mut_val_to_text(yyjson_mut_obj_get(notebook->root, "metadata")) : NULL;
    if (!text) {
        text = strdup("{}");
    }
    if (!text) {
        return YETTY_ERR(yetty_ycore_char_ptr, "notebook_metadata_json: alloc failed");
    }
    return YETTY_OK(yetty_ycore_char_ptr, text);
}

/* destroy: free every cell/output, the master document, and the allocation. */
YETTY_ANNOTATE("virtual@ynotebook:notebook:notebook_destroy")
YETTY_ANNOTATE("local@ynotebook:notebook_destroy")
static struct yetty_ycore_void_result notebook_destroy(struct yetty_yclass_object *obj)
{
    if (!obj) {
        return YETTY_OK_VOID();
    }
    struct yetty_yclass_void_ptr_result notebook_r = notebook_from_obj(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, notebook_r, "notebook_destroy: from_obj");
    notebook_clear(notebook_r.value);
    return yetty_yclass_object_free(obj);
}

#include "yetty/gen/impl/ynotebook/notebook.c"
