/*
 * grid.c — the unified terminal model as a yclass class: class@yvterm:grid.
 *
 * This class owns the ONE CPU-side terminal truth: text cells, per-cell rich
 * refs, and anchored primitive/composite storage on a scrolling line ring, plus
 * the libvterm State machine that drives it and the keyboard/PTY I/O. The
 * renderer (class@yvterm:vterm, a yfigure) composes a grid instance and reads it
 * through the exposed cell type + the bulk accessor methods at the foot of this
 * file. Concerns are split: grid.c = model + I/O, vterm.c = GPU figure renderer.
 *
 * The public header (grid.h) is generated by codegen from the annotations here.
 */
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include <vterm.h>
#include <vterm_keycodes.h>

#include <yetty/yclass/class.h>
#include <yetty/ycore/result.h>
#include <yetty/ycore/types.h>
#include <yetty/ytrace/ytrace.h>
#include <yetty/ywire/wire-statemachine.h>

/* `struct yetty_ydraw_composite` is kept opaque on purpose: it is defined in
 * BOTH ydraw-core/figure.h and ydraw-factory/composite-factory.h (a pre-existing
 * duplicate), so pulling either defining header clashes in any consumer that
 * includes the other. Used by pointer only; the teardown + render free functions
 * are hand-declared (defined in ydraw-factory). */
struct yetty_ydraw_composite;
void yetty_ydraw_composite_destroy(struct yetty_ydraw_composite *instance);

/* PTY write callback — keyboard output + libvterm query responses go back to the
 * child through this. Own typedef (rather than yterminal's) so the model has no
 * dependency on yterminal; the terminal passes a signature-compatible function.
 *
 * Text attributes copied from libvterm pen state into each written cell, exposed
 * so the renderer can read attrs for bold/italic/underline/strike.
 *
 * Defined plainly in the owning .c. The typedef is reproduced into grid.h
 * when an exposed signature references it; the enum is published via its
 * `expose` annotation. */
typedef struct yetty_ycore_void_result (*yetty_yvterm_grid_pty_write_fn)(const char *bytes,
                                                                         size_t len,
                                                                         void *userdata);
enum [[clang::annotate("expose")]] yetty_yvterm_text_attr {
    YETTY_YVTERM_ATTR_BOLD = 1u << 0,
    YETTY_YVTERM_ATTR_UNDERLINE = 1u << 1,
    YETTY_YVTERM_ATTR_UNDERLINE2 = 1u << 2,
    YETTY_YVTERM_ATTR_ITALIC = 1u << 3,
    YETTY_YVTERM_ATTR_REVERSE = 1u << 4,
    YETTY_YVTERM_ATTR_BLINK = 1u << 5,
    YETTY_YVTERM_ATTR_STRIKE = 1u << 6,
    YETTY_YVTERM_ATTR_CONCEAL = 1u << 7,
};

/* One terminal text cell. Glyph lookup is renderer-owned; the model stores the
 * source codepoint and style. width is 1 for normal cells, 2 for a wide glyph
 * head, and 0 for the wide glyph spill cell. Exposed so the renderer packs from
 * the bulk per-line accessor without copying. */
struct [[clang::annotate("expose")]] yetty_yvterm_text_cell {
    uint32_t glyph_index;
    uint32_t codepoint;
    uint32_t fg;
    uint32_t bg;
    uint16_t attrs;
    uint8_t width;
    uint8_t flags;
};

/* A simple primitive anchored on a terminal line. The primitive payload is a
 * span of u32 words in the owning line's arena. */
struct yetty_yvterm_primitive {
    uint32_t arena_offset;
    uint32_t word_count;
};

/* Borrowed reference from a covered cell to a primitive anchored on another
 * line. The anchor is below the covered cell: anchor_row = row + rel_line. */
struct yetty_yvterm_primitive_ref {
    uint16_t rel_line;
    uint16_t index_in_list;
};

/* Borrowed reference from a covered cell to a composite anchored on another
 * line, using the same downward-anchor convention as primitive refs. */
struct yetty_yvterm_composite_ref {
    uint16_t rel_line;
    uint16_t index_in_list;
};

/* Rich content covering one terminal cell. These are borrowed refs only; owned
 * primitive/composite storage lives on the anchor line. */
struct yetty_yvterm_drawable_refs {
    struct yetty_yvterm_primitive_ref *primitive_refs;
    uint16_t primitive_ref_count;
    uint16_t primitive_ref_capacity;

    struct yetty_yvterm_composite_ref *composite_refs;
    uint16_t composite_ref_count;
    uint16_t composite_ref_capacity;
};

/* One slot in the scrolling line ring. The line owns its text cells, per-cell
 * rich refs, primitive arena/descriptors, and anchored composites. */
struct yetty_yvterm_line {
    struct yetty_yvterm_text_cell *text_cells;
    struct yetty_yvterm_drawable_refs *drawable_refs;

    struct yetty_yvterm_primitive *primitives;
    uint32_t primitive_count;
    uint32_t primitive_capacity;

    uint32_t *arena;
    uint32_t arena_count;
    uint32_t arena_capacity;

    struct yetty_ydraw_composite **composites;
    uint32_t composite_count;
    uint32_t composite_capacity;

    int dirty;
};

/* Optional hook owned by the integration layer. Full-screen terminal clear may
 * need to drop external yfigures that the grid model does not own. Defined
 * plainly here; codegen reproduces it into grid.h when the exposed setter
 * references it. */
typedef struct yetty_ycore_void_result (*yetty_yvterm_grid_clear_hook_fn)(void *userdata);

/* The unified terminal grid — the yclass data block. visible row N maps to:
 *
 *     lines[(base + N) % visible_rows]
 *
 * Whole-screen scroll advances base and reuses rolled-off line slots. */
struct [[clang::annotate("class@yvterm:grid")]] yetty_yvterm_grid {
    struct yetty_yvterm_line *lines;
    uint32_t line_count;
    uint32_t visible_rows;
    uint32_t cols;
    uint32_t base;

    VTerm *vterm;
    VTermState *state;

    uint32_t pen_fg;
    uint32_t pen_bg;
    uint32_t default_fg;
    uint32_t default_bg;
    uint16_t pen_attrs;
    int pen_reverse;

    uint32_t cursor_row;
    uint32_t cursor_col;
    uint32_t cursor_visible;

    int alt_screen;
    int mouse_mode;

    yetty_yvterm_grid_clear_hook_fn clear_hook_fn;
    void *clear_hook_userdata;

    /* Keyboard output / libvterm query responses go to the child via this. */
    yetty_yvterm_grid_pty_write_fn pty_write_fn;
    void *pty_write_userdata;

    /* Selection rectangle in grid cells (terminal-driven). */
    int selection_active;
    uint32_t selection_anchor_row;
    uint32_t selection_anchor_col;
    uint32_t selection_head_row;
    uint32_t selection_head_col;

    int has_dirty;

    /* Absolute count of rows scrolled off the top — the rolling-row origin. The
     * top of the screen is at absolute row `total_scrolled`; the cursor's
     * absolute row is `total_scrolled + cursor_row`. Anchored rich content (the
     * ydraw ygrid) uses this to scroll in lockstep with the text. */
    uint32_t total_scrolled;
};

/* Result wrapper for the grid handle. Declared here (this TU does not include
 * its own generated header); grid.h publishes the identical declaration. */
YETTY_YRESULT_DECLARE(yetty_yvterm_grid_ptr, struct yetty_yvterm_grid *);

/* Defined in the appended grid.gen.c. */
struct yetty_yclass_ptr_result yetty_yvterm_grid_class_get(void);
struct yetty_yvterm_grid_ptr_result yetty_yvterm_grid_from(struct yetty_yclass_object *obj);

/*===========================================================================
 * Model helpers — operate on the unified grid datatypes from grid.c.
 *=========================================================================*/

static inline uint32_t pack_color(VTermColor color)
{
    return (uint32_t)color.red | ((uint32_t)color.green << 8) | ((uint32_t)color.blue << 16) |
           (0xFFu << 24);
}

/* Lines retained above the visible screen for mouse-wheel / copy-mode
 * scrollback. The line ring is sized to visible_rows + this; rolled-off lines
 * stay in the ring as history (their GPU cells persist), and the oldest is
 * evicted only when the ring wraps. */
#define YVTERM_SCROLLBACK_ROWS 2000u

/* Map a visible row [0, visible_rows) to its slot in the line ring. The ring
 * spans line_count = visible_rows + scrollback, so the modulo is over the FULL
 * ring (not visible_rows) — that is what keeps rolled-off history addressable. */
static inline uint32_t ring_slot(const struct yetty_yvterm_grid *grid, uint32_t row)
{
    if (!grid->line_count) {
        return row;
    }
    uint32_t slot = grid->base + row;
    while (slot >= grid->line_count) {
        slot -= grid->line_count;
    }
    return slot;
}

static inline struct yetty_yvterm_line *line_at(struct yetty_yvterm_grid *grid, uint32_t row)
{
    return &grid->lines[ring_slot(grid, row)];
}

static inline struct yetty_yvterm_text_cell *cell_at(struct yetty_yvterm_grid *grid, uint32_t row,
                                                     uint32_t col)
{
    return &line_at(grid, row)->text_cells[col];
}

static inline struct yetty_yvterm_drawable_refs *refs_at(struct yetty_yvterm_grid *grid,
                                                         uint32_t row, uint32_t col)
{
    return &line_at(grid, row)->drawable_refs[col];
}

static void destroy_composite(struct yetty_ydraw_composite *composite)
{
    if (composite) {
        yetty_ydraw_composite_destroy(composite);
    }
}

/* Growable backing arrays — each grows capacity (doubling, clamped to need). */

static struct yetty_ycore_void_result ensure_primitive_refs(struct yetty_yvterm_drawable_refs *refs,
                                                            uint16_t need)
{
    if (need <= refs->primitive_ref_capacity) {
        return YETTY_OK_VOID();
    }
    uint32_t new_cap = refs->primitive_ref_capacity ? refs->primitive_ref_capacity : 2u;
    while (new_cap < need) {
        new_cap *= 2u;
    }
    if (new_cap > UINT16_MAX) {
        new_cap = UINT16_MAX;
    }
    struct yetty_yvterm_primitive_ref *grown =
        realloc(refs->primitive_refs, (size_t)new_cap * sizeof(*grown));
    if (!grown) {
        return YETTY_ERR(yetty_ycore_void, "yvterm: primitive_refs grow failed");
    }
    refs->primitive_refs = grown;
    refs->primitive_ref_capacity = (uint16_t)new_cap;
    return YETTY_OK_VOID();
}

static struct yetty_ycore_void_result ensure_composite_refs(struct yetty_yvterm_drawable_refs *refs,
                                                            uint16_t need)
{
    if (need <= refs->composite_ref_capacity) {
        return YETTY_OK_VOID();
    }
    uint32_t new_cap = refs->composite_ref_capacity ? refs->composite_ref_capacity : 2u;
    while (new_cap < need) {
        new_cap *= 2u;
    }
    if (new_cap > UINT16_MAX) {
        new_cap = UINT16_MAX;
    }
    struct yetty_yvterm_composite_ref *grown =
        realloc(refs->composite_refs, (size_t)new_cap * sizeof(*grown));
    if (!grown) {
        return YETTY_ERR(yetty_ycore_void, "yvterm: composite_refs grow failed");
    }
    refs->composite_refs = grown;
    refs->composite_ref_capacity = (uint16_t)new_cap;
    return YETTY_OK_VOID();
}

static struct yetty_ycore_void_result ensure_arena(struct yetty_yvterm_line *line, uint32_t need)
{
    if (need <= line->arena_capacity) {
        return YETTY_OK_VOID();
    }
    uint32_t new_cap = line->arena_capacity ? line->arena_capacity : 16u;
    while (new_cap < need) {
        new_cap *= 2u;
    }
    uint32_t *grown = realloc(line->arena, (size_t)new_cap * sizeof(*grown));
    if (!grown) {
        return YETTY_ERR(yetty_ycore_void, "yvterm: arena grow failed");
    }
    line->arena = grown;
    line->arena_capacity = new_cap;
    return YETTY_OK_VOID();
}

static struct yetty_ycore_void_result ensure_primitives(struct yetty_yvterm_line *line,
                                                        uint32_t need)
{
    if (need <= line->primitive_capacity) {
        return YETTY_OK_VOID();
    }
    uint32_t new_cap = line->primitive_capacity ? line->primitive_capacity : 4u;
    while (new_cap < need) {
        new_cap *= 2u;
    }
    struct yetty_yvterm_primitive *grown =
        realloc(line->primitives, (size_t)new_cap * sizeof(*grown));
    if (!grown) {
        return YETTY_ERR(yetty_ycore_void, "yvterm: primitives grow failed");
    }
    line->primitives = grown;
    line->primitive_capacity = new_cap;
    return YETTY_OK_VOID();
}

static struct yetty_ycore_void_result ensure_composites(struct yetty_yvterm_line *line,
                                                        uint32_t need)
{
    if (need <= line->composite_capacity) {
        return YETTY_OK_VOID();
    }
    uint32_t new_cap = line->composite_capacity ? line->composite_capacity : 4u;
    while (new_cap < need) {
        new_cap *= 2u;
    }
    struct yetty_ydraw_composite **grown =
        realloc(line->composites, (size_t)new_cap * sizeof(struct yetty_ydraw_composite *));
    if (!grown) {
        return YETTY_ERR(yetty_ycore_void, "yvterm: composites grow failed");
    }
    line->composites = grown;
    line->composite_capacity = new_cap;
    return YETTY_OK_VOID();
}

static void free_refs(struct yetty_yvterm_drawable_refs *refs)
{
    free(refs->primitive_refs);
    refs->primitive_refs = NULL;
    refs->primitive_ref_count = 0;
    refs->primitive_ref_capacity = 0;

    free(refs->composite_refs);
    refs->composite_refs = NULL;
    refs->composite_ref_count = 0;
    refs->composite_ref_capacity = 0;
}

/* Per-cell borrow drop: forget which rich content covers this cell. Never
 * destroys the anchor line's owned content. */
static void clear_refs(struct yetty_yvterm_drawable_refs *refs)
{
    refs->primitive_ref_count = 0;
    refs->composite_ref_count = 0;
}

/* Full line ownership clear: drop every cell's borrows AND release the line's
 * owned rich content (arena/primitives reset, composites destroyed). */
static void clear_line_rich(struct yetty_yvterm_line *line, uint32_t cols)
{
    if (line->drawable_refs) {
        for (uint32_t col = 0; col < cols; ++col) {
            clear_refs(&line->drawable_refs[col]);
        }
    }
    line->primitive_count = 0;
    line->arena_count = 0;
    for (uint32_t i = 0; i < line->composite_count; ++i) {
        destroy_composite(line->composites[i]);
        line->composites[i] = NULL;
    }
    line->composite_count = 0;
}

/* Remove every borrowed ref (on any visible line) that points to anchor_row, so
 * clearing that anchor line's owned storage cannot leave a dangling ref behind.
 * The anchor convention is downward (anchor = covered_row + rel_line), so only
 * rows at or above anchor_row can reference it. */
static void drop_refs_to_anchor(struct yetty_yvterm_grid *grid, uint32_t anchor_row)
{
    if (anchor_row >= grid->visible_rows) {
        return;
    }
    for (uint32_t row = 0; row <= anchor_row; ++row) {
        struct yetty_yvterm_line *line = line_at(grid, row);
        if (!line->drawable_refs) {
            continue;
        }
        int touched = 0;
        for (uint32_t col = 0; col < grid->cols; ++col) {
            struct yetty_yvterm_drawable_refs *refs = &line->drawable_refs[col];
            uint16_t kept = 0;
            for (uint16_t i = 0; i < refs->primitive_ref_count; ++i) {
                if ((uint32_t)row + refs->primitive_refs[i].rel_line != anchor_row) {
                    refs->primitive_refs[kept++] = refs->primitive_refs[i];
                }
            }
            if (kept != refs->primitive_ref_count) {
                refs->primitive_ref_count = kept;
                touched = 1;
            }
            kept = 0;
            for (uint16_t i = 0; i < refs->composite_ref_count; ++i) {
                if ((uint32_t)row + refs->composite_refs[i].rel_line != anchor_row) {
                    refs->composite_refs[kept++] = refs->composite_refs[i];
                }
            }
            if (kept != refs->composite_ref_count) {
                refs->composite_ref_count = kept;
                touched = 1;
            }
        }
        if (touched) {
            line->dirty = 1;
            grid->has_dirty = 1;
        }
    }
}

static void blank_cell(struct yetty_yvterm_text_cell *cell, uint32_t fg, uint32_t bg)
{
    cell->glyph_index = 0;
    cell->codepoint = 0;
    cell->fg = fg;
    cell->bg = bg;
    cell->attrs = 0;
    cell->width = 1;
    cell->flags = 0;
}

static void reset_line(struct yetty_yvterm_grid *grid, struct yetty_yvterm_line *line)
{
    for (uint32_t col = 0; col < grid->cols; ++col) {
        blank_cell(&line->text_cells[col], grid->default_fg, grid->default_bg);
    }
    clear_line_rich(line, grid->cols);
}

static void blank_line(struct yetty_yvterm_grid *grid, uint32_t row)
{
    reset_line(grid, line_at(grid, row));
}

static void mark_dirty_row(struct yetty_yvterm_grid *grid, uint32_t row)
{
    if (row >= grid->visible_rows) {
        return;
    }
    line_at(grid, row)->dirty = 1;
    grid->has_dirty = 1;
}

static void mark_dirty_all(struct yetty_yvterm_grid *grid)
{
    for (uint32_t i = 0; i < grid->line_count; ++i) {
        grid->lines[i].dirty = 1;
    }
    grid->has_dirty = 1;
}

/* O(1) whole-screen scroll-up. The rolled-off top lines are NOT blanked — they
 * stay in the ring as scrollback history (their GPU cells persist for the
 * scrolled-back view). Instead the freshly-exposed bottom rows are blanked.
 * Because line_count = visible_rows + scrollback, slot (base + visible_rows)
 * aliases the oldest history slot, so blanking it there naturally evicts the
 * oldest line and reuses it as the new blank bottom. Advancing base moves the
 * whole view down by one row over the ring. */
static void roll_up(struct yetty_yvterm_grid *grid, uint32_t count)
{
    if (grid->visible_rows == 0 || grid->line_count == 0) {
        return;
    }
    if (count > grid->visible_rows) {
        count = grid->visible_rows;
    }
    for (uint32_t step = 0; step < count; ++step) {
        uint32_t slot = grid->base + grid->visible_rows + step;
        while (slot >= grid->line_count) {
            slot -= grid->line_count;
        }
        reset_line(grid, &grid->lines[slot]);
        grid->lines[slot].dirty = 1;
    }
    grid->base += count;
    grid->total_scrolled += count; /* rolling-row origin advances with scroll */
    while (grid->base >= grid->line_count) {
        grid->base -= grid->line_count;
    }
    grid->has_dirty = 1;
}

/* Move one cell's full state — text plus borrowed primitive/composite refs.
 *
 * Borrowed refs name their anchor relative to the *covered* row
 * (anchor = covered_row + rel_line). Moving a cell to a different row must keep
 * the absolute anchor fixed, so rel_line is rebased by (src_row - dst_row). A
 * ref whose rebased rel_line would point above the cell (negative — violating
 * the downward-anchor convention) or past the visible grid is dropped rather
 * than left dangling. Line-owned primitive/composite *storage* is not touched
 * here: it lives on its anchor line and is addressed by index, so a cell move
 * only needs to keep the references consistent. Best-effort on allocation: a
 * libvterm callback cannot propagate an error, so it keeps what fits. */
static void move_cell(struct yetty_yvterm_grid *grid, uint32_t dst_row, uint32_t dst_col,
                      uint32_t src_row, uint32_t src_col)
{
    *cell_at(grid, dst_row, dst_col) = *cell_at(grid, src_row, src_col);

    struct yetty_yvterm_drawable_refs *dst = refs_at(grid, dst_row, dst_col);
    struct yetty_yvterm_drawable_refs *src = refs_at(grid, src_row, src_col);
    int rel_delta = (int)src_row - (int)dst_row;
    dst->primitive_ref_count = 0;
    dst->composite_ref_count = 0;

    struct yetty_ycore_void_result pr = ensure_primitive_refs(dst, src->primitive_ref_count);
    if (YETTY_IS_OK(pr)) {
        for (uint16_t i = 0; i < src->primitive_ref_count; ++i) {
            int new_rel = (int)src->primitive_refs[i].rel_line + rel_delta;
            if (new_rel < 0 || new_rel > UINT16_MAX ||
                dst_row + (uint32_t)new_rel >= grid->visible_rows) {
                continue;
            }
            dst->primitive_refs[dst->primitive_ref_count].rel_line = (uint16_t)new_rel;
            dst->primitive_refs[dst->primitive_ref_count].index_in_list =
                src->primitive_refs[i].index_in_list;
            dst->primitive_ref_count++;
        }
    } else {
        yetty_ycore_error_destroy(pr.error);
    }

    struct yetty_ycore_void_result cr = ensure_composite_refs(dst, src->composite_ref_count);
    if (YETTY_IS_OK(cr)) {
        for (uint16_t i = 0; i < src->composite_ref_count; ++i) {
            int new_rel = (int)src->composite_refs[i].rel_line + rel_delta;
            if (new_rel < 0 || new_rel > UINT16_MAX ||
                dst_row + (uint32_t)new_rel >= grid->visible_rows) {
                continue;
            }
            dst->composite_refs[dst->composite_ref_count].rel_line = (uint16_t)new_rel;
            dst->composite_refs[dst->composite_ref_count].index_in_list =
                src->composite_refs[i].index_in_list;
            dst->composite_ref_count++;
        }
    } else {
        yetty_ycore_error_destroy(cr.error);
    }
}

/*===========================================================================
 * libvterm State callbacks — transform the one model. user = grid pointer.
 *=========================================================================*/

YETTY_EXTERNAL_CALLBACK
static int cb_putglyph(VTermGlyphInfo *info, VTermPos pos, void *user)
{
    struct yetty_yvterm_grid *grid = user;
    if (pos.row < 0 || pos.col < 0 || (uint32_t)pos.row >= grid->visible_rows ||
        (uint32_t)pos.col >= grid->cols) {
        return 1;
    }

    uint32_t fg = grid->pen_reverse ? grid->pen_bg : grid->pen_fg;
    uint32_t bg = grid->pen_reverse ? grid->pen_fg : grid->pen_bg;
    struct yetty_yvterm_text_cell *cell = cell_at(grid, (uint32_t)pos.row, (uint32_t)pos.col);
    cell->glyph_index = 0;
    cell->codepoint = (info->chars && info->chars[0]) ? info->chars[0] : 0u;
    cell->fg = fg;
    cell->bg = bg;
    cell->attrs = grid->pen_attrs;
    cell->width = (uint8_t)(info->width >= 2 ? 2 : 1);
    cell->flags = 0;

    /* A text write overwrites the cell, so its rich-content borrows go stale. */
    clear_refs(refs_at(grid, (uint32_t)pos.row, (uint32_t)pos.col));

    if (info->width == 2 && (uint32_t)pos.col + 1u < grid->cols) {
        struct yetty_yvterm_text_cell *next =
            cell_at(grid, (uint32_t)pos.row, (uint32_t)pos.col + 1u);
        next->glyph_index = 0;
        next->codepoint = 0;
        next->fg = fg;
        next->bg = bg;
        next->attrs = grid->pen_attrs;
        next->width = 0;
        next->flags = 0;
        clear_refs(refs_at(grid, (uint32_t)pos.row, (uint32_t)pos.col + 1u));
    }

    /* If this row anchors owned primitives/composites, writing text over it
     * invalidates that rich content: release the owned storage and drop every
     * borrowed ref (on any row) that pointed at this anchor, so nothing dangles.
     * primitive_count/composite_count drop to 0, so later glyphs on the same
     * line skip this cheaply. */
    struct yetty_yvterm_line *line = line_at(grid, (uint32_t)pos.row);
    if (line->primitive_count || line->composite_count) {
        clear_line_rich(line, grid->cols);
        drop_refs_to_anchor(grid, (uint32_t)pos.row);
    }

    mark_dirty_row(grid, (uint32_t)pos.row);
    return 1;
}

YETTY_EXTERNAL_CALLBACK
static int cb_movecursor(VTermPos pos, VTermPos oldpos, int visible, void *user)
{
    struct yetty_yvterm_grid *grid = user;
    if (oldpos.row >= 0) {
        mark_dirty_row(grid, (uint32_t)oldpos.row);
    }
    grid->cursor_row = pos.row >= 0 ? (uint32_t)pos.row : 0u;
    grid->cursor_col = pos.col >= 0 ? (uint32_t)pos.col : 0u;
    grid->cursor_visible = visible ? 1u : 0u;
    mark_dirty_row(grid, grid->cursor_row);
    return 1;
}

YETTY_EXTERNAL_CALLBACK
static int cb_moverect(VTermRect dest, VTermRect src, void *user)
{
    struct yetty_yvterm_grid *grid = user;
    int row_count = dest.end_row - dest.start_row;
    int col_count = dest.end_col - dest.start_col;
    if (row_count <= 0 || col_count <= 0) {
        return 1;
    }

    /* Respect overlap direction on BOTH axes exactly like memmove. Pick the row
     * and column traversal order independently from the sign of the shift: when
     * the destination is past the source on an axis, walk that axis backwards so
     * a source cell is always read before a later write can overwrite it. This
     * covers vertical moves, same-row horizontal moves, and diagonal moves. */
    int row_shift = dest.start_row - src.start_row;
    int col_shift = dest.start_col - src.start_col;
    for (int row_step = 0; row_step < row_count; ++row_step) {
        int row = (row_shift > 0) ? (row_count - 1 - row_step) : row_step;
        for (int col_step = 0; col_step < col_count; ++col_step) {
            int col = (col_shift > 0) ? (col_count - 1 - col_step) : col_step;
            move_cell(grid, (uint32_t)(dest.start_row + row), (uint32_t)(dest.start_col + col),
                      (uint32_t)(src.start_row + row), (uint32_t)(src.start_col + col));
        }
        mark_dirty_row(grid, (uint32_t)(dest.start_row + row));
    }
    return 1;
}

YETTY_EXTERNAL_CALLBACK
static int cb_erase(VTermRect rect, int selective, void *user)
{
    struct yetty_yvterm_grid *grid = user;
    (void)selective;

    int whole_screen = rect.start_row <= 0 && rect.start_col <= 0 &&
                       (uint32_t)rect.end_row >= grid->visible_rows &&
                       (uint32_t)rect.end_col >= grid->cols;

    if (whole_screen) {
        for (uint32_t row = 0; row < grid->visible_rows; ++row) {
            reset_line(grid, line_at(grid, row));
            mark_dirty_row(grid, row);
        }
        if (grid->clear_hook_fn) {
            struct yetty_ycore_void_result r = grid->clear_hook_fn(grid->clear_hook_userdata);
            if (YETTY_IS_ERR(r)) {
                yetty_ycore_error_destroy(r.error);
            }
        }
        return 1;
    }

    for (int row = rect.start_row; row < rect.end_row; ++row) {
        if (row < 0 || (uint32_t)row >= grid->visible_rows) {
            continue;
        }
        for (int col = rect.start_col; col < rect.end_col; ++col) {
            if (col < 0 || (uint32_t)col >= grid->cols) {
                continue;
            }
            blank_cell(cell_at(grid, (uint32_t)row, (uint32_t)col), grid->default_fg,
                       grid->default_bg);
            clear_refs(refs_at(grid, (uint32_t)row, (uint32_t)col));
        }
        /* Erasing cells on a row that anchors owned rich content invalidates
         * that content too — release it and drop refs pointing here, mirroring
         * cb_putglyph's anchor-line invalidation. */
        struct yetty_yvterm_line *line = line_at(grid, (uint32_t)row);
        if (line->primitive_count || line->composite_count) {
            clear_line_rich(line, grid->cols);
            drop_refs_to_anchor(grid, (uint32_t)row);
        }
        mark_dirty_row(grid, (uint32_t)row);
    }
    return 1;
}

YETTY_EXTERNAL_CALLBACK
static int cb_scrollrect(VTermRect rect, int downward, int rightward, void *user)
{
    struct yetty_yvterm_grid *grid = user;
    int whole_width = rect.start_col == 0 && (uint32_t)rect.end_col == grid->cols;
    int whole_height = rect.start_row == 0 && (uint32_t)rect.end_row == grid->visible_rows;
    /* The common whole-screen scroll-up is O(1): advance the ring. Everything
     * else decomposes through the unified move/erase callbacks. */
    if (rightward == 0 && downward > 0 && whole_width && whole_height) {
        roll_up(grid, (uint32_t)downward);
        return 1;
    }
    vterm_scroll_rect(rect, downward, rightward, cb_moverect, cb_erase, grid);
    return 1;
}

YETTY_EXTERNAL_CALLBACK
static int cb_initpen(void *user)
{
    struct yetty_yvterm_grid *grid = user;
    grid->pen_fg = grid->default_fg;
    grid->pen_bg = grid->default_bg;
    grid->pen_attrs = 0;
    grid->pen_reverse = 0;
    return 1;
}

YETTY_EXTERNAL_CALLBACK
static int cb_setpenattr(VTermAttr attr, VTermValue *val, void *user)
{
    struct yetty_yvterm_grid *grid = user;
    switch (attr) {
    case VTERM_ATTR_BOLD:
        grid->pen_attrs = val->boolean ? (grid->pen_attrs | YETTY_YVTERM_ATTR_BOLD)
                                       : (grid->pen_attrs & ~(uint16_t)YETTY_YVTERM_ATTR_BOLD);
        break;
    case VTERM_ATTR_UNDERLINE: {
        uint16_t mask = YETTY_YVTERM_ATTR_UNDERLINE | YETTY_YVTERM_ATTR_UNDERLINE2;
        grid->pen_attrs =
            (uint16_t)((grid->pen_attrs & ~mask) | (((uint16_t)(val->number & 0x3)) << 1));
        break;
    }
    case VTERM_ATTR_ITALIC:
        grid->pen_attrs = val->boolean ? (grid->pen_attrs | YETTY_YVTERM_ATTR_ITALIC)
                                       : (grid->pen_attrs & ~(uint16_t)YETTY_YVTERM_ATTR_ITALIC);
        break;
    case VTERM_ATTR_BLINK:
        grid->pen_attrs = val->boolean ? (grid->pen_attrs | YETTY_YVTERM_ATTR_BLINK)
                                       : (grid->pen_attrs & ~(uint16_t)YETTY_YVTERM_ATTR_BLINK);
        break;
    case VTERM_ATTR_STRIKE:
        grid->pen_attrs = val->boolean ? (grid->pen_attrs | YETTY_YVTERM_ATTR_STRIKE)
                                       : (grid->pen_attrs & ~(uint16_t)YETTY_YVTERM_ATTR_STRIKE);
        break;
    case VTERM_ATTR_CONCEAL:
        grid->pen_attrs = val->boolean ? (grid->pen_attrs | YETTY_YVTERM_ATTR_CONCEAL)
                                       : (grid->pen_attrs & ~(uint16_t)YETTY_YVTERM_ATTR_CONCEAL);
        break;
    case VTERM_ATTR_REVERSE:
        grid->pen_reverse = val->boolean ? 1 : 0;
        break;
    case VTERM_ATTR_FOREGROUND:
        grid->pen_fg = pack_color(val->color);
        break;
    case VTERM_ATTR_BACKGROUND:
        grid->pen_bg = pack_color(val->color);
        break;
    default:
        break;
    }
    return 1;
}

YETTY_EXTERNAL_CALLBACK
static int cb_settermprop(VTermProp prop, VTermValue *val, void *user)
{
    struct yetty_yvterm_grid *grid = user;
    switch (prop) {
    case VTERM_PROP_CURSORVISIBLE:
        grid->cursor_visible = val->boolean ? 1u : 0u;
        mark_dirty_row(grid, grid->cursor_row);
        break;
    case VTERM_PROP_ALTSCREEN:
        grid->alt_screen = val->boolean ? 1 : 0;
        mark_dirty_all(grid);
        break;
    case VTERM_PROP_MOUSE:
        grid->mouse_mode = (int)val->number;
        break;
    default:
        break;
    }
    return 1;
}

YETTY_EXTERNAL_CALLBACK
static int cb_bell(void *user)
{
    (void)user;
    return 1;
}

YETTY_EXTERNAL_CALLBACK
static int cb_resize(int rows, int cols, VTermStateFields *fields, void *user)
{
    (void)cols;
    (void)user;
    /* libvterm has already updated state->rows/state->cols and delegates the
     * lineinfo (re)allocation to this callback — its internal fallback is dead
     * code once a state resize callback is installed. Each non-NULL lineinfos[]
     * buffer must be grown/shrunk to `rows` entries here; otherwise the next
     * glyph indexes the old, shorter buffer out of bounds (heap corruption,
     * then a crash). The default vterm allocator is libc malloc/free, so plain
     * calloc/free matches what libvterm will later free. Our grid model blanks
     * every line on resize, so fresh zeroed lineinfo (no flag carry-over) is
     * the correct semantics — mirrors libvterm's own screen-layer resize. */
    int safe_rows = rows > 0 ? rows : 1;
    for (int bufidx = 0; bufidx < 2; ++bufidx) {
        if (!fields->lineinfos[bufidx]) {
            continue;
        }
        VTermLineInfo *resized = calloc((size_t)safe_rows, sizeof(VTermLineInfo));
        if (!resized) {
            /* Keep the existing buffer rather than crash; libvterm clamps the
             * cursor below, so a stale-but-valid buffer is the safer failure. */
            continue;
        }
        free(fields->lineinfos[bufidx]);
        fields->lineinfos[bufidx] = resized;
    }
    return 1;
}

static const VTermStateCallbacks *grid_state_callbacks(void)
{
    static const VTermStateCallbacks callbacks = {
        .putglyph = cb_putglyph,
        .movecursor = cb_movecursor,
        .scrollrect = cb_scrollrect,
        .moverect = cb_moverect,
        .erase = cb_erase,
        .initpen = cb_initpen,
        .setpenattr = cb_setpenattr,
        .settermprop = cb_settermprop,
        .bell = cb_bell,
        .resize = cb_resize,
        .setlineinfo = NULL,
        .sb_clear = NULL,
    };
    return &callbacks;
}

/*===========================================================================
 * Grid model lifecycle — the model lives embedded in the vterm object.
 *=========================================================================*/

static void grid_free_lines(struct yetty_yvterm_grid *grid)
{
    if (!grid->lines) {
        return;
    }
    for (uint32_t line = 0; line < grid->line_count; ++line) {
        struct yetty_yvterm_line *current = &grid->lines[line];
        if (current->drawable_refs) {
            for (uint32_t col = 0; col < grid->cols; ++col) {
                free_refs(&current->drawable_refs[col]);
            }
        }
        for (uint32_t i = 0; i < current->composite_count; ++i) {
            destroy_composite(current->composites[i]);
        }
        free(current->text_cells);
        free(current->drawable_refs);
        free(current->primitives);
        free(current->arena);
        free(current->composites);
    }
    free(grid->lines);
    grid->lines = NULL;
}

static struct yetty_ycore_void_result grid_alloc_lines(struct yetty_yvterm_grid *grid,
                                                       uint32_t rows, uint32_t cols)
{
    grid->lines = calloc(rows, sizeof(struct yetty_yvterm_line));
    if (!grid->lines) {
        return YETTY_ERR(yetty_ycore_void, "yvterm: line array allocation failed");
    }
    grid->line_count = rows;
    for (uint32_t line = 0; line < rows; ++line) {
        grid->lines[line].text_cells = calloc(cols, sizeof(struct yetty_yvterm_text_cell));
        grid->lines[line].drawable_refs = calloc(cols, sizeof(struct yetty_yvterm_drawable_refs));
        if (!grid->lines[line].text_cells || !grid->lines[line].drawable_refs) {
            grid_free_lines(grid);
            return YETTY_ERR(yetty_ycore_void, "yvterm: line allocation failed");
        }
    }
    return YETTY_OK_VOID();
}

static struct yetty_ycore_void_result grid_model_init(struct yetty_yvterm_grid *grid, uint32_t cols,
                                                      uint32_t rows)
{
    grid->cols = cols;
    grid->visible_rows = rows;

    /* Allocate visible + scrollback lines; only the first `rows` are on screen,
     * the rest hold rolled-off history (see ring_slot / roll_up). */
    struct yetty_ycore_void_result lines_r =
        grid_alloc_lines(grid, rows + YVTERM_SCROLLBACK_ROWS, cols);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, lines_r, "yvterm: grid_model_init alloc_lines");

    grid->vterm = vterm_new((int)rows, (int)cols);
    if (!grid->vterm) {
        grid_free_lines(grid);
        return YETTY_ERR(yetty_ycore_void, "yvterm: vterm_new failed");
    }
    vterm_set_utf8(grid->vterm, 1);
    grid->state = vterm_obtain_state(grid->vterm);
    vterm_state_set_callbacks(grid->state, grid_state_callbacks(), grid);

    VTermColor default_fg;
    VTermColor default_bg;
    vterm_state_get_default_colors(grid->state, &default_fg, &default_bg);
    grid->default_fg = pack_color(default_fg);
    grid->default_bg = pack_color(default_bg);

    vterm_state_reset(grid->state, 1);
    grid->pen_fg = grid->default_fg;
    grid->pen_bg = grid->default_bg;
    grid->cursor_visible = 1u;

    for (uint32_t row = 0; row < rows; ++row) {
        blank_line(grid, row);
    }
    mark_dirty_all(grid);
    return YETTY_OK_VOID();
}

static void grid_model_teardown(struct yetty_yvterm_grid *grid)
{
    if (grid->vterm) {
        vterm_free(grid->vterm);
        grid->vterm = NULL;
        grid->state = NULL;
    }
    grid_free_lines(grid);
}

static struct yetty_ycore_void_result grid_model_resize(struct yetty_yvterm_grid *grid,
                                                        uint32_t cols, uint32_t rows)
{
    struct yetty_yvterm_grid tmp = {0};
    tmp.cols = cols;
    tmp.visible_rows = rows;
    tmp.default_fg = grid->default_fg;
    tmp.default_bg = grid->default_bg;
    /* Reallocate the full ring (visible + scrollback). Resize drops the old
     * scrollback history rather than reflowing it to the new width. */
    struct yetty_ycore_void_result lines_r =
        grid_alloc_lines(&tmp, rows + YVTERM_SCROLLBACK_ROWS, cols);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, lines_r, "yvterm: grid_model_resize alloc_lines");

    grid_free_lines(grid);
    grid->lines = tmp.lines;
    grid->line_count = tmp.line_count;
    grid->cols = cols;
    grid->visible_rows = rows;
    grid->base = 0;
    grid->total_scrolled = 0;

    for (uint32_t row = 0; row < rows; ++row) {
        blank_line(grid, row);
    }
    vterm_set_size(grid->vterm, (int)rows, (int)cols);
    mark_dirty_all(grid);
    return YETTY_OK_VOID();
}

/*===========================================================================
 * Lifecycle — create/destroy the grid object (a plain yclass class).
 *=========================================================================*/

[[clang::annotate("expose")]]
struct yetty_yclass_object_ptr_result yetty_yvterm_grid_make(uint32_t cols, uint32_t rows)
{
    if (cols == 0 || rows == 0) {
        return YETTY_ERR(yetty_yclass_object_ptr, "yvterm grid_make: invalid size");
    }
    struct yetty_yclass_ptr_result class_res = yetty_yvterm_grid_class_get();
    YETTY_RETURN_IF_ERR(yetty_yclass_object_ptr, class_res, "yvterm grid_make: class");
    struct yetty_yclass_object_ptr_result object_res = yetty_yclass_object_alloc(class_res.value);
    YETTY_RETURN_IF_ERR(yetty_yclass_object_ptr, object_res, "yvterm grid_make: object_alloc");
    struct yetty_yclass_object *obj = object_res.value;

    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    if (YETTY_IS_ERR(grid_res)) {
        struct yetty_ycore_void_result free_res = yetty_yclass_object_free(obj);
        if (YETTY_IS_ERR(free_res)) {
            yetty_ycore_error_destroy(free_res.error);
        }
        return YETTY_ERR(yetty_yclass_object_ptr, "yvterm grid_make: from_obj", grid_res);
    }
    struct yetty_ycore_void_result init_res = grid_model_init(grid_res.value, cols, rows);
    if (YETTY_IS_ERR(init_res)) {
        struct yetty_ycore_void_result free_res = yetty_yclass_object_free(obj);
        if (YETTY_IS_ERR(free_res)) {
            yetty_ycore_error_destroy(free_res.error);
        }
        return YETTY_ERR(yetty_yclass_object_ptr, "yvterm grid_make: model_init", init_res);
    }
    return YETTY_OK(yetty_yclass_object_ptr, obj);
}

[[clang::annotate("expose")]]
struct yetty_ycore_void_result yetty_yvterm_grid_dispose(struct yetty_yclass_object *obj)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, grid_res, "yvterm grid_dispose: from_obj");
    grid_model_teardown(grid_res.value);
    return yetty_yclass_object_free(obj);
}

[[clang::annotate("expose")]]
void yetty_yvterm_grid_set_pty_write(struct yetty_yclass_object *obj,
                                     yetty_yvterm_grid_pty_write_fn fn, void *userdata)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    if (YETTY_IS_ERR(grid_res)) {
        yetty_ycore_error_destroy(grid_res.error);
        return;
    }
    grid_res.value->pty_write_fn = fn;
    grid_res.value->pty_write_userdata = userdata;
}

[[clang::annotate("expose")]]
void yetty_yvterm_grid_set_clear_hook(struct yetty_yclass_object *obj,
                                      yetty_yvterm_grid_clear_hook_fn fn, void *userdata)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    if (YETTY_IS_ERR(grid_res)) {
        yetty_ycore_error_destroy(grid_res.error);
        return;
    }
    grid_res.value->clear_hook_fn = fn;
    grid_res.value->clear_hook_userdata = userdata;
}

/*===========================================================================
 * Model mutation — terminal/renderer facing.
 *=========================================================================*/

[[clang::annotate("expose")]]
struct yetty_ycore_void_result yetty_yvterm_grid_feed(struct yetty_yclass_object *obj,
                                                      const char *bytes, size_t len)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, grid_res, "yvterm grid_feed: from_obj");
    if (len && !bytes) {
        return YETTY_ERR(yetty_ycore_void, "yvterm grid_feed: NULL bytes");
    }
    vterm_input_write(grid_res.value->vterm, bytes, len);
    return YETTY_OK_VOID();
}

[[clang::annotate("expose")]]
struct yetty_ycore_void_result yetty_yvterm_grid_resize(struct yetty_yclass_object *obj,
                                                        uint32_t cols, uint32_t rows)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, grid_res, "yvterm grid_resize: from_obj");
    if (cols == 0 || rows == 0) {
        return YETTY_ERR(yetty_ycore_void, "yvterm grid_resize: invalid dimensions");
    }
    return grid_model_resize(grid_res.value, cols, rows);
}

[[clang::annotate("expose")]]
int yetty_yvterm_grid_is_dirty(struct yetty_yclass_object *obj)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    if (YETTY_IS_ERR(grid_res)) {
        yetty_ycore_error_destroy(grid_res.error);
        return 0;
    }
    return grid_res.value->has_dirty;
}

[[clang::annotate("expose")]]
void yetty_yvterm_grid_cursor(struct yetty_yclass_object *obj, uint32_t *out_row, uint32_t *out_col,
                              uint32_t *out_visible)
{
    struct yetty_yvterm_grid *grid = NULL;
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    if (YETTY_IS_OK(grid_res)) {
        grid = grid_res.value;
    } else {
        yetty_ycore_error_destroy(grid_res.error);
    }
    if (out_row) {
        *out_row = grid ? grid->cursor_row : 0u;
    }
    if (out_col) {
        *out_col = grid ? grid->cursor_col : 0u;
    }
    if (out_visible) {
        *out_visible = grid ? grid->cursor_visible : 0u;
    }
}

/* Absolute row at the top of the screen (rows scrolled off so far). The cursor's
 * absolute output row is this + the visible cursor row — used to place anchored
 * rich content on the rolling-row scroll. */
[[clang::annotate("expose")]]
uint32_t yetty_yvterm_grid_scroll_origin(struct yetty_yclass_object *obj)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    if (YETTY_IS_ERR(grid_res)) {
        yetty_ycore_error_destroy(grid_res.error);
        return 0u;
    }
    return grid_res.value->total_scrolled;
}

/*===========================================================================
 * Rich-content insertion.
 *=========================================================================*/

[[clang::annotate("expose")]]
struct yetty_ycore_uint32_result yetty_yvterm_grid_append_primitive(struct yetty_yclass_object *obj,
                                                                    uint32_t row,
                                                                    const uint32_t *words,
                                                                    uint32_t word_count)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_uint32, grid_res, "yvterm append_primitive: from_obj");
    struct yetty_yvterm_grid *grid = grid_res.value;
    if (row >= grid->visible_rows) {
        return YETTY_ERR(yetty_ycore_uint32, "yvterm append_primitive: row out of range");
    }
    if (word_count && !words) {
        return YETTY_ERR(yetty_ycore_uint32, "yvterm append_primitive: NULL words");
    }
    struct yetty_yvterm_line *line = line_at(grid, row);
    if (line->primitive_count >= UINT16_MAX) {
        return YETTY_ERR(yetty_ycore_uint32, "yvterm append_primitive: too many primitives");
    }
    struct yetty_ycore_void_result ar = ensure_arena(line, line->arena_count + word_count);
    YETTY_RETURN_IF_ERR(yetty_ycore_uint32, ar, "yvterm append_primitive: arena");
    struct yetty_ycore_void_result pr = ensure_primitives(line, line->primitive_count + 1u);
    YETTY_RETURN_IF_ERR(yetty_ycore_uint32, pr, "yvterm append_primitive: primitives");
    uint32_t arena_offset = line->arena_count;
    if (word_count) {
        memcpy(line->arena + arena_offset, words, (size_t)word_count * sizeof(uint32_t));
        line->arena_count += word_count;
    }
    uint32_t index = line->primitive_count;
    line->primitives[index].arena_offset = arena_offset;
    line->primitives[index].word_count = word_count;
    line->primitive_count++;
    mark_dirty_row(grid, row);
    return YETTY_OK(yetty_ycore_uint32, index);
}

[[clang::annotate("expose")]]
struct yetty_ycore_void_result yetty_yvterm_grid_add_primitive_ref(struct yetty_yclass_object *obj,
                                                                   uint32_t row, uint32_t col,
                                                                   uint16_t rel_line,
                                                                   uint16_t index_in_list)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, grid_res, "yvterm add_primitive_ref: from_obj");
    struct yetty_yvterm_grid *grid = grid_res.value;
    if (row >= grid->visible_rows || col >= grid->cols) {
        return YETTY_ERR(yetty_ycore_void, "yvterm add_primitive_ref: out of range");
    }
    uint32_t anchor_row = (uint32_t)row + rel_line;
    if (anchor_row >= grid->visible_rows) {
        return YETTY_ERR(yetty_ycore_void, "yvterm add_primitive_ref: anchor out of range");
    }
    if (index_in_list >= line_at(grid, anchor_row)->primitive_count) {
        return YETTY_ERR(yetty_ycore_void,
                         "yvterm add_primitive_ref: primitive index out of range");
    }
    struct yetty_yvterm_drawable_refs *refs = refs_at(grid, row, col);
    struct yetty_ycore_void_result gr =
        ensure_primitive_refs(refs, (uint16_t)(refs->primitive_ref_count + 1u));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, gr, "yvterm add_primitive_ref: grow");
    refs->primitive_refs[refs->primitive_ref_count].rel_line = rel_line;
    refs->primitive_refs[refs->primitive_ref_count].index_in_list = index_in_list;
    refs->primitive_ref_count++;
    mark_dirty_row(grid, row);
    return YETTY_OK_VOID();
}

[[clang::annotate("expose")]]
struct yetty_ycore_uint32_result yetty_yvterm_grid_attach_composite(
    struct yetty_yclass_object *obj, uint32_t row, struct yetty_ydraw_composite *composite)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_uint32, grid_res, "yvterm attach_composite: from_obj");
    struct yetty_yvterm_grid *grid = grid_res.value;
    if (row >= grid->visible_rows) {
        return YETTY_ERR(yetty_ycore_uint32, "yvterm attach_composite: row out of range");
    }
    if (!composite) {
        return YETTY_ERR(yetty_ycore_uint32, "yvterm attach_composite: NULL composite");
    }
    struct yetty_yvterm_line *line = line_at(grid, row);
    if (line->composite_count >= UINT16_MAX) {
        return YETTY_ERR(yetty_ycore_uint32, "yvterm attach_composite: too many composites");
    }
    struct yetty_ycore_void_result gr = ensure_composites(line, line->composite_count + 1u);
    YETTY_RETURN_IF_ERR(yetty_ycore_uint32, gr, "yvterm attach_composite: grow");
    uint32_t index = line->composite_count;
    line->composites[index] = composite;
    line->composite_count++;
    mark_dirty_row(grid, row);
    return YETTY_OK(yetty_ycore_uint32, index);
}

[[clang::annotate("expose")]]
struct yetty_ycore_void_result yetty_yvterm_grid_add_composite_ref(struct yetty_yclass_object *obj,
                                                                   uint32_t row, uint32_t col,
                                                                   uint16_t rel_line,
                                                                   uint16_t index_in_list)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, grid_res, "yvterm add_composite_ref: from_obj");
    struct yetty_yvterm_grid *grid = grid_res.value;
    if (row >= grid->visible_rows || col >= grid->cols) {
        return YETTY_ERR(yetty_ycore_void, "yvterm add_composite_ref: out of range");
    }
    uint32_t anchor_row = (uint32_t)row + rel_line;
    if (anchor_row >= grid->visible_rows) {
        return YETTY_ERR(yetty_ycore_void, "yvterm add_composite_ref: anchor out of range");
    }
    if (index_in_list >= line_at(grid, anchor_row)->composite_count) {
        return YETTY_ERR(yetty_ycore_void,
                         "yvterm add_composite_ref: composite index out of range");
    }
    struct yetty_yvterm_drawable_refs *refs = refs_at(grid, row, col);
    struct yetty_ycore_void_result gr =
        ensure_composite_refs(refs, (uint16_t)(refs->composite_ref_count + 1u));
    YETTY_RETURN_IF_ERR(yetty_ycore_void, gr, "yvterm add_composite_ref: grow");
    refs->composite_refs[refs->composite_ref_count].rel_line = rel_line;
    refs->composite_refs[refs->composite_ref_count].index_in_list = index_in_list;
    refs->composite_ref_count++;
    mark_dirty_row(grid, row);
    return YETTY_OK_VOID();
}

[[clang::annotate("expose")]]
struct yetty_ycore_void_result yetty_yvterm_grid_clear_rich_line(struct yetty_yclass_object *obj,
                                                                 uint32_t row)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, grid_res, "yvterm clear_rich_line: from_obj");
    struct yetty_yvterm_grid *grid = grid_res.value;
    if (row >= grid->visible_rows) {
        return YETTY_ERR(yetty_ycore_void, "yvterm clear_rich_line: row out of range");
    }
    clear_line_rich(line_at(grid, row), grid->cols);
    drop_refs_to_anchor(grid, row);
    mark_dirty_row(grid, row);
    return YETTY_OK_VOID();
}

[[clang::annotate("expose")]]
struct yetty_ycore_void_result yetty_yvterm_grid_clear_rich_all(struct yetty_yclass_object *obj)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, grid_res, "yvterm clear_rich_all: from_obj");
    struct yetty_yvterm_grid *grid = grid_res.value;
    for (uint32_t row = 0; row < grid->visible_rows; ++row) {
        clear_line_rich(line_at(grid, row), grid->cols);
        mark_dirty_row(grid, row);
    }
    return YETTY_OK_VOID();
}

/*===========================================================================
 * Input, wire, selection — terminal-facing.
 *=========================================================================*/

static VTermModifier grid_map_mods(int mods)
{
    int out = VTERM_MOD_NONE;
    if (mods & 0x01) {
        out |= VTERM_MOD_SHIFT;
    }
    if (mods & 0x02) {
        out |= VTERM_MOD_CTRL;
    }
    if (mods & 0x04) {
        out |= VTERM_MOD_ALT;
    }
    return (VTermModifier)out;
}

static struct yetty_ycore_void_result grid_flush_output(struct yetty_yvterm_grid *grid)
{
    if (!grid->pty_write_fn) {
        return YETTY_OK_VOID();
    }
    char buf[256];
    size_t got;
    while ((got = vterm_output_read(grid->vterm, buf, sizeof(buf))) > 0) {
        struct yetty_ycore_void_result wr = grid->pty_write_fn(buf, got, grid->pty_write_userdata);
        YETTY_RETURN_IF_ERR(yetty_ycore_void, wr, "grid_flush_output: pty write");
    }
    return YETTY_OK_VOID();
}

static struct yetty_ycore_void_result grid_append_utf8(struct yetty_ycore_buffer *out, uint32_t cp)
{
    uint8_t bytes[4];
    size_t len = 0;
    if (cp < 0x80u) {
        bytes[len++] = (uint8_t)cp;
    } else if (cp < 0x800u) {
        bytes[len++] = (uint8_t)(0xC0u | (cp >> 6));
        bytes[len++] = (uint8_t)(0x80u | (cp & 0x3Fu));
    } else if (cp < 0x10000u) {
        bytes[len++] = (uint8_t)(0xE0u | (cp >> 12));
        bytes[len++] = (uint8_t)(0x80u | ((cp >> 6) & 0x3Fu));
        bytes[len++] = (uint8_t)(0x80u | (cp & 0x3Fu));
    } else {
        bytes[len++] = (uint8_t)(0xF0u | (cp >> 18));
        bytes[len++] = (uint8_t)(0x80u | ((cp >> 12) & 0x3Fu));
        bytes[len++] = (uint8_t)(0x80u | ((cp >> 6) & 0x3Fu));
        bytes[len++] = (uint8_t)(0x80u | (cp & 0x3Fu));
    }
    return yetty_ycore_buffer_write(out, bytes, len);
}

/* Default wire sink: raw terminal bytes outside any envelope feed libvterm, and
 * libvterm's query replies are flushed back inside the loop (see Ctrl-R/fzf). */
static struct yetty_ycore_void_result grid_wire_default(void *userdata,
                                                        struct yetty_ywire_wire_statemachine *sm)
{
    struct yetty_yvterm_grid *grid = userdata;
    uint8_t buf[4096];
    while (!yetty_ywire_wire_statemachine_at_end(sm)) {
        struct yetty_ycore_size_result rr =
            yetty_ywire_wire_statemachine_read(sm, buf, sizeof(buf));
        YETTY_RETURN_IF_ERR(yetty_ycore_void, rr, "grid_wire_default: read");
        if (rr.value == 0) {
            break;
        }
        vterm_input_write(grid->vterm, (const char *)buf, rr.value);
        struct yetty_ycore_void_result fr = grid_flush_output(grid);
        YETTY_RETURN_IF_ERR(yetty_ycore_void, fr, "grid_wire_default: flush output");
    }
    return YETTY_OK_VOID();
}

[[clang::annotate("expose")]]
struct yetty_ycore_void_result yetty_yvterm_grid_register_wire(
    struct yetty_yclass_object *obj, struct yetty_ywire_wire_statemachine *sm)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, grid_res, "yvterm grid_register_wire: from_obj");
    struct yetty_ycore_void_result rr =
        yetty_ywire_wire_statemachine_set_default(sm, grid_wire_default, grid_res.value);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, rr, "yvterm grid_register_wire: set_default");
    return YETTY_OK_VOID();
}

[[clang::annotate("expose")]]
int yetty_yvterm_grid_on_char(struct yetty_yclass_object *obj, uint32_t codepoint, int mods)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    if (YETTY_IS_ERR(grid_res)) {
        yetty_ycore_error_destroy(grid_res.error);
        return 0;
    }
    struct yetty_yvterm_grid *grid = grid_res.value;
    if (codepoint == 0) {
        return 0;
    }
    vterm_keyboard_unichar(grid->vterm, codepoint, grid_map_mods(mods));
    struct yetty_ycore_void_result fr = grid_flush_output(grid);
    if (YETTY_IS_ERR(fr)) {
        yetty_ycore_error_destroy(fr.error);
    }
    return 1;
}

[[clang::annotate("expose")]]
int yetty_yvterm_grid_on_key(struct yetty_yclass_object *obj, int key, int mods)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    if (YETTY_IS_ERR(grid_res)) {
        yetty_ycore_error_destroy(grid_res.error);
        return 0;
    }
    struct yetty_yvterm_grid *grid = grid_res.value;
    VTermKey vk = VTERM_KEY_NONE;
    switch (key) {
    case 256:
        vk = VTERM_KEY_ESCAPE;
        break;
    case 257:
        vk = VTERM_KEY_ENTER;
        break;
    case 258:
        vk = VTERM_KEY_TAB;
        break;
    case 259:
        vk = VTERM_KEY_BACKSPACE;
        break;
    case 260:
        vk = VTERM_KEY_INS;
        break;
    case 261:
        vk = VTERM_KEY_DEL;
        break;
    case 262:
        vk = VTERM_KEY_RIGHT;
        break;
    case 263:
        vk = VTERM_KEY_LEFT;
        break;
    case 264:
        vk = VTERM_KEY_DOWN;
        break;
    case 265:
        vk = VTERM_KEY_UP;
        break;
    case 266:
        vk = VTERM_KEY_PAGEUP;
        break;
    case 267:
        vk = VTERM_KEY_PAGEDOWN;
        break;
    case 268:
        vk = VTERM_KEY_HOME;
        break;
    case 269:
        vk = VTERM_KEY_END;
        break;
    default:
        return 0;
    }
    vterm_keyboard_key(grid->vterm, vk, grid_map_mods(mods));
    struct yetty_ycore_void_result fr = grid_flush_output(grid);
    if (YETTY_IS_ERR(fr)) {
        yetty_ycore_error_destroy(fr.error);
    }
    return 1;
}

[[clang::annotate("expose")]]
struct yetty_ycore_void_result yetty_yvterm_grid_set_selection(struct yetty_yclass_object *obj,
                                                               int active, uint32_t anchor_row,
                                                               uint32_t anchor_col,
                                                               uint32_t head_row, uint32_t head_col)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, grid_res, "yvterm grid_set_selection: from_obj");
    struct yetty_yvterm_grid *grid = grid_res.value;
    grid->selection_active = active;
    grid->selection_anchor_row = anchor_row;
    grid->selection_anchor_col = anchor_col;
    grid->selection_head_row = head_row;
    grid->selection_head_col = head_col;
    return YETTY_OK_VOID();
}

[[clang::annotate("expose")]]
struct yetty_ycore_void_result yetty_yvterm_grid_get_selection_text(struct yetty_yclass_object *obj,
                                                                    struct yetty_ycore_buffer *out)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    YETTY_RETURN_IF_ERR(yetty_ycore_void, grid_res, "yvterm grid_get_selection_text: from_obj");
    struct yetty_yvterm_grid *grid = grid_res.value;
    if (!out || !grid->selection_active) {
        return YETTY_OK_VOID();
    }
    uint32_t start_row = grid->selection_anchor_row;
    uint32_t start_col = grid->selection_anchor_col;
    uint32_t end_row = grid->selection_head_row;
    uint32_t end_col = grid->selection_head_col;
    if (start_row > end_row || (start_row == end_row && start_col > end_col)) {
        uint32_t tr = start_row, tc = start_col;
        start_row = end_row;
        start_col = end_col;
        end_row = tr;
        end_col = tc;
    }
    for (uint32_t row = start_row; row <= end_row && row < grid->visible_rows; ++row) {
        uint32_t first = (row == start_row) ? start_col : 0u;
        uint32_t last = (row == end_row) ? end_col : (grid->cols ? grid->cols - 1u : 0u);
        for (uint32_t col = first; col <= last && col < grid->cols; ++col) {
            uint32_t cp = cell_at(grid, row, col)->codepoint;
            if (cp) {
                struct yetty_ycore_void_result ar = grid_append_utf8(out, cp);
                YETTY_RETURN_IF_ERR(yetty_ycore_void, ar, "yvterm grid_get_selection_text: append");
            }
        }
        if (row != end_row) {
            struct yetty_ycore_void_result nr = yetty_ycore_buffer_write(out, "\n", 1);
            YETTY_RETURN_IF_ERR(yetty_ycore_void, nr, "yvterm grid_get_selection_text: newline");
        }
    }
    return YETTY_OK_VOID();
}

/* Word-character class for double-click word selection. ASCII alphanumerics and
 * '_' are word chars; any non-ASCII codepoint (letters, CJK, …) counts too;
 * spaces and ASCII punctuation break words — the xterm-default feel. */
static int grid_is_word_char(uint32_t cp)
{
    if (cp == 0) {
        return 0;
    }
    if (cp >= 0x80u) {
        return 1;
    }
    if (cp >= '0' && cp <= '9') {
        return 1;
    }
    if (cp >= 'A' && cp <= 'Z') {
        return 1;
    }
    if (cp >= 'a' && cp <= 'z') {
        return 1;
    }
    return cp == '_';
}

/* Word boundaries around (row, col): the inclusive [start_col, end_col] run of
 * word chars covering the clicked cell. A click on a non-word cell selects just
 * that cell. Used for double-click word selection. */
[[clang::annotate("expose")]]
void yetty_yvterm_grid_word_bounds(struct yetty_yclass_object *obj, uint32_t row, uint32_t col,
                                   uint32_t *out_start_col, uint32_t *out_end_col)
{
    uint32_t start = col, end = col;
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    if (YETTY_IS_ERR(grid_res)) {
        yetty_ycore_error_destroy(grid_res.error);
    } else {
        struct yetty_yvterm_grid *grid = grid_res.value;
        if (row < grid->visible_rows && col < grid->cols &&
            grid_is_word_char(cell_at(grid, row, col)->codepoint)) {
            while (start > 0 && grid_is_word_char(cell_at(grid, row, start - 1)->codepoint)) {
                --start;
            }
            while (end + 1u < grid->cols &&
                   grid_is_word_char(cell_at(grid, row, end + 1)->codepoint)) {
                ++end;
            }
        }
    }
    if (out_start_col) {
        *out_start_col = start;
    }
    if (out_end_col) {
        *out_end_col = end;
    }
}

/*===========================================================================
 * Renderer accessors — the vterm figure reads the model through these so the
 * data block stays private to this class. Bulk (per-line) to keep the render
 * hot path cheap.
 *=========================================================================*/

[[clang::annotate("expose")]]
void yetty_yvterm_grid_dims(struct yetty_yclass_object *obj, uint32_t *out_cols, uint32_t *out_rows,
                            uint32_t *out_base)
{
    struct yetty_yvterm_grid *grid = NULL;
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    if (YETTY_IS_OK(grid_res)) {
        grid = grid_res.value;
    } else {
        yetty_ycore_error_destroy(grid_res.error);
    }
    if (out_cols) {
        *out_cols = grid ? grid->cols : 0u;
    }
    if (out_rows) {
        *out_rows = grid ? grid->visible_rows : 0u;
    }
    if (out_base) {
        *out_base = grid ? grid->base : 0u;
    }
}

/* The cell array for visible row `row` (length = cols). NULL if out of range. */
[[clang::annotate("expose")]]
const struct yetty_yvterm_text_cell *yetty_yvterm_grid_line_cells(struct yetty_yclass_object *obj,
                                                                  uint32_t row)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    if (YETTY_IS_ERR(grid_res)) {
        yetty_ycore_error_destroy(grid_res.error);
        return NULL;
    }
    struct yetty_yvterm_grid *grid = grid_res.value;
    if (row >= grid->visible_rows) {
        return NULL;
    }
    return line_at(grid, row)->text_cells;
}

[[clang::annotate("expose")]]
int yetty_yvterm_grid_line_dirty(struct yetty_yclass_object *obj, uint32_t row)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    if (YETTY_IS_ERR(grid_res)) {
        yetty_ycore_error_destroy(grid_res.error);
        return 0;
    }
    struct yetty_yvterm_grid *grid = grid_res.value;
    if (row >= grid->visible_rows) {
        return 0;
    }
    return line_at(grid, row)->dirty;
}

/* Composite array anchored on visible row `row`. Sets *out_count; may be NULL. */
[[clang::annotate("expose")]]
struct yetty_ydraw_composite *const *yetty_yvterm_grid_line_composites(
    struct yetty_yclass_object *obj, uint32_t row, uint32_t *out_count)
{
    if (out_count) {
        *out_count = 0;
    }
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    if (YETTY_IS_ERR(grid_res)) {
        yetty_ycore_error_destroy(grid_res.error);
        return NULL;
    }
    struct yetty_yvterm_grid *grid = grid_res.value;
    if (row >= grid->visible_rows) {
        return NULL;
    }
    struct yetty_yvterm_line *line = line_at(grid, row);
    if (out_count) {
        *out_count = line->composite_count;
    }
    return line->composites;
}

/* Composite array on RAW ring slot `slot` (0..slot_count). Distinct from the
 * visible-row accessor above: the text upload + shader address the ring by raw
 * slot via root_row, so the composite pass must read by the SAME slot to scroll
 * in lockstep (live AND scrolled-back). Sets *out_count; may be NULL. */
[[clang::annotate("expose")]]
struct yetty_ydraw_composite *const *yetty_yvterm_grid_slot_composites(
    struct yetty_yclass_object *obj, uint32_t slot, uint32_t *out_count)
{
    if (out_count) {
        *out_count = 0;
    }
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    if (YETTY_IS_ERR(grid_res)) {
        yetty_ycore_error_destroy(grid_res.error);
        return NULL;
    }
    struct yetty_yvterm_grid *grid = grid_res.value;
    if (slot >= grid->line_count) {
        return NULL;
    }
    struct yetty_yvterm_line *line = &grid->lines[slot];
    if (out_count) {
        *out_count = line->composite_count;
    }
    return line->composites;
}

/* Number of raw drawable records (SDF / glyph / TEXT_DRAWABLE_LIST / FONT) stored
 * on RAW ring slot `slot`. The SDF render pass walks these by slot — same raw-slot
 * addressing the composite + text passes use — so figures and text scroll together. */
[[clang::annotate("expose")]]
uint32_t yetty_yvterm_grid_slot_primitive_count(struct yetty_yclass_object *obj, uint32_t slot)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    if (YETTY_IS_ERR(grid_res)) {
        yetty_ycore_error_destroy(grid_res.error);
        return 0u;
    }
    struct yetty_yvterm_grid *grid = grid_res.value;
    if (slot >= grid->line_count) {
        return 0u;
    }
    return grid->lines[slot].primitive_count;
}

/* Words of primitive `index` on RAW ring slot `slot`. *out_word_count is set to the
 * record's u32 length. Returns NULL (and *out_word_count 0) if slot/index are out of
 * range. The returned span aliases the line's arena — read it, do not retain it. */
[[clang::annotate("expose")]]
const uint32_t *yetty_yvterm_grid_slot_primitive_words(struct yetty_yclass_object *obj,
                                                       uint32_t slot, uint32_t index,
                                                       uint32_t *out_word_count)
{
    if (out_word_count) {
        *out_word_count = 0u;
    }
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    if (YETTY_IS_ERR(grid_res)) {
        yetty_ycore_error_destroy(grid_res.error);
        return NULL;
    }
    struct yetty_yvterm_grid *grid = grid_res.value;
    if (slot >= grid->line_count) {
        return NULL;
    }
    struct yetty_yvterm_line *line = &grid->lines[slot];
    if (index >= line->primitive_count) {
        return NULL;
    }
    struct yetty_yvterm_primitive *prim = &line->primitives[index];
    if (out_word_count) {
        *out_word_count = prim->word_count;
    }
    return line->arena + prim->arena_offset;
}

/* Current selection rectangle (raw anchor/head; the renderer normalises to a
 * reading-order stream). active=0 → no selection. */
[[clang::annotate("expose")]]
void yetty_yvterm_grid_selection(struct yetty_yclass_object *obj, int *out_active,
                                 uint32_t *out_anchor_row, uint32_t *out_anchor_col,
                                 uint32_t *out_head_row, uint32_t *out_head_col)
{
    struct yetty_yvterm_grid *grid = NULL;
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    if (YETTY_IS_OK(grid_res)) {
        grid = grid_res.value;
    } else {
        yetty_ycore_error_destroy(grid_res.error);
    }
    if (out_active) {
        *out_active = grid ? grid->selection_active : 0;
    }
    if (out_anchor_row) {
        *out_anchor_row = grid ? grid->selection_anchor_row : 0u;
    }
    if (out_anchor_col) {
        *out_anchor_col = grid ? grid->selection_anchor_col : 0u;
    }
    if (out_head_row) {
        *out_head_row = grid ? grid->selection_head_row : 0u;
    }
    if (out_head_col) {
        *out_head_col = grid ? grid->selection_head_col : 0u;
    }
}

/* Renderer has consumed the model; drop every dirty flag. */
[[clang::annotate("expose")]]
void yetty_yvterm_grid_clear_dirty(struct yetty_yclass_object *obj)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    if (YETTY_IS_ERR(grid_res)) {
        yetty_ycore_error_destroy(grid_res.error);
        return;
    }
    struct yetty_yvterm_grid *grid = grid_res.value;
    for (uint32_t i = 0; i < grid->line_count; ++i) {
        grid->lines[i].dirty = 0;
    }
    grid->has_dirty = 0;
}

/* Raw ring-slot accessors (slot in [0, line_count)) for the text upload, which
 * is slot-indexed so the shader's root_row=base gives O(1) scroll. Distinct from
 * the visible-row accessors above (which resolve the ring). */
[[clang::annotate("expose")]]
uint32_t yetty_yvterm_grid_slot_count(struct yetty_yclass_object *obj)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    if (YETTY_IS_ERR(grid_res)) {
        yetty_ycore_error_destroy(grid_res.error);
        return 0;
    }
    return grid_res.value->line_count;
}

[[clang::annotate("expose")]]
const struct yetty_yvterm_text_cell *yetty_yvterm_grid_slot_cells(struct yetty_yclass_object *obj,
                                                                  uint32_t slot)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    if (YETTY_IS_ERR(grid_res)) {
        yetty_ycore_error_destroy(grid_res.error);
        return NULL;
    }
    struct yetty_yvterm_grid *grid = grid_res.value;
    if (slot >= grid->line_count) {
        return NULL;
    }
    return grid->lines[slot].text_cells;
}

[[clang::annotate("expose")]]
int yetty_yvterm_grid_slot_dirty(struct yetty_yclass_object *obj, uint32_t slot)
{
    struct yetty_yvterm_grid_ptr_result grid_res = yetty_yvterm_grid_from(obj);
    if (YETTY_IS_ERR(grid_res)) {
        yetty_ycore_error_destroy(grid_res.error);
        return 0;
    }
    struct yetty_yvterm_grid *grid = grid_res.value;
    if (slot >= grid->line_count) {
        return 0;
    }
    return grid->lines[slot].dirty;
}

#include "grid.gen.c"
