#include "embedded-assets.h"

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#include <yetty/yplatform/fs.h>
#include <yetty/ytrace/ytrace.h>

#if defined(_MSC_VER) && !defined(S_ISDIR)
#define S_ISDIR(m) (((m) & _S_IFMT) == _S_IFDIR)
#endif
#if defined(_MSC_VER) && !defined(S_ISREG)
#define S_ISREG(m) (((m) & _S_IFMT) == _S_IFREG)
#endif

#ifndef YETTY_BUILD_VERSION
#define YETTY_BUILD_VERSION "dev"
#endif

#ifdef HAS_DATA_MANIFEST
#include <brotli/decode.h>
#include "yhello_data_manifest.h"

#define MAX_PATH_LEN 1024

struct yhello_extract_ctx {
    const char *dest_dir;
    int failed;
};

/* The yetty extractor in src/yetty/yncbin grows the decode buffer with
 * the streaming brotli API because the one-shot path returned ERROR
 * mid-stream on some versions. Mirror that. */
static uint8_t *decompress_brotli(const uint8_t *data, size_t size, size_t *out_size)
{
    BrotliDecoderState *st = BrotliDecoderCreateInstance(NULL, NULL, NULL);
    if (!st) {
        return NULL;
    }
    size_t capacity = size * 10;
    if (capacity < 65536) {
        capacity = 65536;
    }
    uint8_t *output = (uint8_t *)malloc(capacity);
    if (!output) {
        BrotliDecoderDestroyInstance(st);
        return NULL;
    }
    size_t in_remaining = size;
    const uint8_t *next_in = data;
    size_t out_used = 0;
    for (;;) {
        size_t out_avail = capacity - out_used;
        uint8_t *next_out = output + out_used;
        BrotliDecoderResult r =
            BrotliDecoderDecompressStream(st, &in_remaining, &next_in, &out_avail, &next_out, NULL);
        out_used = capacity - out_avail;
        if (r == BROTLI_DECODER_RESULT_SUCCESS) {
            break;
        }
        if (r == BROTLI_DECODER_RESULT_NEEDS_MORE_OUTPUT) {
            capacity *= 2;
            uint8_t *grown = (uint8_t *)realloc(output, capacity);
            if (!grown) {
                free(output);
                BrotliDecoderDestroyInstance(st);
                return NULL;
            }
            output = grown;
            continue;
        }
        free(output);
        BrotliDecoderDestroyInstance(st);
        return NULL;
    }
    BrotliDecoderDestroyInstance(st);
    *out_size = out_used;
    return output;
}

static int mkdir_one(const char *path)
{
    if (yetty_yplatform_mkdir(path) == 0) {
        return 0;
    }
    struct stat st;
    if (stat(path, &st) == 0 && S_ISDIR(st.st_mode)) {
        return 0;
    }
    return -1;
}

static int mkdir_p(const char *path)
{
    char tmp[MAX_PATH_LEN];
    snprintf(tmp, sizeof(tmp), "%s", path);
    size_t len = strlen(tmp);
    if (len > 0 && tmp[len - 1] == '/') {
        tmp[len - 1] = 0;
    }
    for (char *p = tmp + 1; *p; p++) {
        if (*p == '/') {
            *p = 0;
            (void)mkdir_one(tmp);
            *p = '/';
        }
    }
    return mkdir_one(tmp);
}

/* Marker is per-binary so yetty and yhello don't trample each other's
 * extraction state when sharing a data dir. */
static void get_marker_path(const char *dir, char *out, size_t out_size)
{
    snprintf(out, out_size, "%s/.yhello-assets/version", dir);
}

static int marker_matches(const char *dir)
{
    char marker[MAX_PATH_LEN];
    get_marker_path(dir, marker, sizeof(marker));
    FILE *f = fopen(marker, "r");
    if (!f) {
        return 0;
    }
    char buf[64] = {0};
    if (!fgets(buf, sizeof(buf), f)) {
        fclose(f);
        return 0;
    }
    fclose(f);
    buf[strcspn(buf, "\n")] = 0;
    return strcmp(buf, YETTY_BUILD_VERSION) == 0;
}

static void write_marker(const char *dir)
{
    char marker[MAX_PATH_LEN];
    char marker_dir[MAX_PATH_LEN];
    get_marker_path(dir, marker, sizeof(marker));
    snprintf(marker_dir, sizeof(marker_dir), "%s", marker);
    char *slash = strrchr(marker_dir, '/');
    if (slash) {
        *slash = 0;
        (void)mkdir_p(marker_dir);
    }
    FILE *f = fopen(marker, "w");
    if (f) {
        fprintf(f, "%s", YETTY_BUILD_VERSION);
        fclose(f);
    }
}

/* register_data_assets_c (auto-generated by incbin.cmake) hands the
 * callback a 4-arg signature with no userdata slot. Mirror what
 * src/yetty/yncbin/incbin-assets.c does — stash the context in a
 * file-scope pointer right before the dispatch loop, clear it
 * straight after. Not a long-lived global; just an adapter for the
 * callback ABI. */
static struct yhello_extract_ctx *current_extract_ctx = NULL;

static void extract_one(const char *name, const uint8_t *data, size_t size, int compressed)
{
    struct yhello_extract_ctx *ctx = current_extract_ctx;
    if (!ctx || ctx->failed) {
        return;
    }
    /* Manifest registers entries with prefix "data/"; strip it so the
     * file lands at the root of the data dir (which is the convention
     * yetty itself uses — extraction is relative to <data_dir>/). */
    const char *rel = name;
    if (strncmp(rel, "data/", 5) == 0) {
        rel += 5;
    }
    char path[MAX_PATH_LEN];
    snprintf(path, sizeof(path), "%s/%s", ctx->dest_dir, rel);

    struct stat st;
    if (stat(path, &st) == 0 && S_ISREG(st.st_mode)) {
        if (compressed || (size_t)st.st_size == size) {
            ydebug("yhello assets: skip (present) %s", rel);
            return;
        }
    }

    char dir[MAX_PATH_LEN];
    snprintf(dir, sizeof(dir), "%s", path);
    char *slash = strrchr(dir, '/');
    if (slash) {
        *slash = 0;
        if (mkdir_p(dir) != 0) {
            yerror("yhello assets: mkdir failed for %s", dir);
            ctx->failed = 1;
            return;
        }
    }

    const uint8_t *write_data = data;
    size_t write_size = size;
    uint8_t *decompressed = NULL;
    if (compressed) {
        decompressed = decompress_brotli(data, size, &write_size);
        if (!decompressed) {
            yerror("yhello assets: brotli decode failed for %s", rel);
            ctx->failed = 1;
            return;
        }
        write_data = decompressed;
    }

    FILE *f = fopen(path, "wb");
    if (!f) {
        yerror("yhello assets: open failed for %s: %s", path, strerror(errno));
        free(decompressed);
        ctx->failed = 1;
        return;
    }
    if (fwrite(write_data, 1, write_size, f) != write_size) {
        yerror("yhello assets: write failed for %s", path);
        fclose(f);
        free(decompressed);
        ctx->failed = 1;
        return;
    }
    fclose(f);
    free(decompressed);
    ydebug("yhello assets: extracted %s (%zu bytes)", rel, write_size);
}

int yhello_embedded_assets_extract(const char *data_dir)
{
    if (!data_dir || !*data_dir) {
        return 0;
    }
    if (marker_matches(data_dir)) {
        ydebug("yhello assets: marker matches, skip");
        return 0;
    }
    if (mkdir_p(data_dir) != 0) {
        yerror("yhello assets: failed to ensure data dir %s", data_dir);
        return -1;
    }
    struct yhello_extract_ctx ctx = {.dest_dir = data_dir, .failed = 0};
    current_extract_ctx = &ctx;
    register_data_assets_c(extract_one);
    current_extract_ctx = NULL;
    if (ctx.failed) {
        return -1;
    }
    write_marker(data_dir);
    return 0;
}

#else /* no embedded data — dev build without incbin */

int yhello_embedded_assets_extract(const char *data_dir)
{
    (void)data_dir;
    return 0;
}

#endif
