import: defaults.yaml

rendering:
  show-fps: false

scrollback:
  lines: 5000

shell:
  default: "/data/data/com.yetty.terminal/cache/bin/sh"
  env:
    TERM: "xterm-256color"
    COLORTERM: "truecolor"
    HOME: "/data/data/com.yetty.terminal/cache"
    SHELL: "/data/data/com.yetty.terminal/cache/bin/sh"
    PATH: "/data/data/com.yetty.terminal/cache/bin:/system/bin"
