// Auto-generated from sdf-drawables.yaml - DO NOT EDIT
// Generated by: src/yetty/ysdf/gen-sdf-code.py

#pragma once

#include "types.gen.h"
#include <yetty/ydraw-core/drawable-list.h>
#include <yetty/ycore/result.h>

#ifdef __cplusplus
extern "C" {
#endif

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_circle(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_circle *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_box(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_box *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_segment(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_segment *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_triangle(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_triangle *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_ellipse(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_ellipse *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_arc(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_arc *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_rounded_box(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_rounded_box *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_rhombus(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_rhombus *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_pentagon(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_pentagon *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_hexagon(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_hexagon *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_star(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_star *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_pie(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_pie *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_ring(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_ring *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_heart(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_heart *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_cross(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_cross *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_rounded_x(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_rounded_x *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_capsule(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_capsule *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_moon(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_moon *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_egg(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_egg *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_octogon(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_octogon *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_hexagram(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_hexagram *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_pentagram(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_pentagram *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_linear_gradient_box(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_linear_gradient_box *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_radial_gradient_box(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_radial_gradient_box *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_sphere_3d(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_sphere_3d *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_box_3d(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_box_3d *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_torus_3d(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_torus_3d *geom);

struct yetty_ycore_void_result yetty_ydraw_drawable_list_add_cmd_add_cylinder_3d(
    struct yetty_ydraw_drawable_list *list, uint32_t id,
    uint32_t z_order, uint32_t fill_color, uint32_t stroke_color,
    float stroke_width, const struct yetty_ysdf_cylinder_3d *geom);

#ifdef __cplusplus
}
#endif
