// Auto-generated from sdf-drawables.yaml - DO NOT EDIT
// Generated by: src/yetty/ysdf/gen-sdf-code.py

#pragma once

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum yetty_ysdf_type {
    YETTY_YSDF_CIRCLE = 0x7FFFFFFFu,
    YETTY_YSDF_BOX = 0x7FFFFFFEu,
    YETTY_YSDF_SEGMENT = 0x7FFFFFFDu,
    YETTY_YSDF_TRIANGLE = 0x7FFFFFFCu,
    YETTY_YSDF_ELLIPSE = 0x7FFFFFF9u,
    YETTY_YSDF_ARC = 0x7FFFFFF8u,
    YETTY_YSDF_ROUNDED_BOX = 0x7FFFFFF7u,
    YETTY_YSDF_RHOMBUS = 0x7FFFFFF6u,
    YETTY_YSDF_PENTAGON = 0x7FFFFFF5u,
    YETTY_YSDF_HEXAGON = 0x7FFFFFF4u,
    YETTY_YSDF_STAR = 0x7FFFFFF3u,
    YETTY_YSDF_PIE = 0x7FFFFFF2u,
    YETTY_YSDF_RING = 0x7FFFFFF1u,
    YETTY_YSDF_HEART = 0x7FFFFFF0u,
    YETTY_YSDF_CROSS = 0x7FFFFFEFu,
    YETTY_YSDF_ROUNDED_X = 0x7FFFFFEEu,
    YETTY_YSDF_CAPSULE = 0x7FFFFFEDu,
    YETTY_YSDF_MOON = 0x7FFFFFECu,
    YETTY_YSDF_EGG = 0x7FFFFFEBu,
    YETTY_YSDF_OCTOGON = 0x7FFFFFE3u,
    YETTY_YSDF_HEXAGRAM = 0x7FFFFFE2u,
    YETTY_YSDF_PENTAGRAM = 0x7FFFFFE1u,
    YETTY_YSDF_LINEAR_GRADIENT_BOX = 0x7FFFFF7Du,
    YETTY_YSDF_RADIAL_GRADIENT_BOX = 0x7FFFFF7Cu,
    YETTY_YSDF_SPHERE_3D = 0x7FFFFF9Bu,
    YETTY_YSDF_BOX_3D = 0x7FFFFF9Au,
    YETTY_YSDF_TORUS_3D = 0x7FFFFF98u,
    YETTY_YSDF_CYLINDER_3D = 0x7FFFFF96u,
};

struct yetty_ysdf_circle {
    float center_x;
    float center_y;
    float radius;
};

struct yetty_ysdf_box {
    float center_x;
    float center_y;
    float half_width;
    float half_height;
    float corner_radius;
};

struct yetty_ysdf_segment {
    float start_x;
    float start_y;
    float end_x;
    float end_y;
};

struct yetty_ysdf_triangle {
    float vertex_a_x;
    float vertex_a_y;
    float vertex_b_x;
    float vertex_b_y;
    float vertex_c_x;
    float vertex_c_y;
};

struct yetty_ysdf_ellipse {
    float center_x;
    float center_y;
    float radius_x;
    float radius_y;
};

struct yetty_ysdf_arc {
    float center_x;
    float center_y;
    float aperture_x;
    float aperture_y;
    float radius;
    float thickness;
};

struct yetty_ysdf_rounded_box {
    float center_x;
    float center_y;
    float half_width;
    float half_height;
    float radius_top_right;
    float radius_bottom_right;
    float radius_top_left;
    float radius_bottom_left;
};

struct yetty_ysdf_rhombus {
    float center_x;
    float center_y;
    float half_width;
    float half_height;
};

struct yetty_ysdf_pentagon {
    float center_x;
    float center_y;
    float radius;
};

struct yetty_ysdf_hexagon {
    float center_x;
    float center_y;
    float radius;
};

struct yetty_ysdf_star {
    float center_x;
    float center_y;
    float radius;
    float num_points;
    float inner_ratio;
};

struct yetty_ysdf_pie {
    float center_x;
    float center_y;
    float aperture_x;
    float aperture_y;
    float radius;
};

struct yetty_ysdf_ring {
    float center_x;
    float center_y;
    float normal_x;
    float normal_y;
    float radius;
    float thickness;
};

struct yetty_ysdf_heart {
    float center_x;
    float center_y;
    float scale;
};

struct yetty_ysdf_cross {
    float center_x;
    float center_y;
    float half_width;
    float half_height;
    float corner_radius;
};

struct yetty_ysdf_rounded_x {
    float center_x;
    float center_y;
    float width;
    float radius;
};

struct yetty_ysdf_capsule {
    float start_x;
    float start_y;
    float end_x;
    float end_y;
    float radius;
};

struct yetty_ysdf_moon {
    float center_x;
    float center_y;
    float offset;
    float radius_outer;
    float radius_inner;
};

struct yetty_ysdf_egg {
    float center_x;
    float center_y;
    float radius_outer;
    float radius_inner;
};

struct yetty_ysdf_octogon {
    float center_x;
    float center_y;
    float radius;
};

struct yetty_ysdf_hexagram {
    float center_x;
    float center_y;
    float radius;
};

struct yetty_ysdf_pentagram {
    float center_x;
    float center_y;
    float radius;
};

struct yetty_ysdf_linear_gradient_box {
    float center_x;
    float center_y;
    float half_width;
    float half_height;
    float corner_radius;
    float grad_x0;
    float grad_y0;
    float grad_x1;
    float grad_y1;
    uint32_t color0;
    uint32_t color1;
};

struct yetty_ysdf_radial_gradient_box {
    float center_x;
    float center_y;
    float half_width;
    float half_height;
    float corner_radius;
    float grad_cx;
    float grad_cy;
    float grad_radius;
    uint32_t color_inner;
    uint32_t color_outer;
};

struct yetty_ysdf_sphere_3d {
    float position_x;
    float position_y;
    float position_z;
    float radius;
};

struct yetty_ysdf_box_3d {
    float position_x;
    float position_y;
    float position_z;
    float half_size_x;
    float half_size_y;
    float half_size_z;
};

struct yetty_ysdf_torus_3d {
    float position_x;
    float position_y;
    float position_z;
    float major_radius;
    float minor_radius;
};

struct yetty_ysdf_cylinder_3d {
    float position_x;
    float position_y;
    float position_z;
    float radius;
    float half_height;
};

// Word count per SDF primitive type
static inline uint32_t yetty_ysdf_word_count(enum yetty_ysdf_type type)
{
    switch (type) {
    case YETTY_YSDF_CIRCLE:
        return 8u;
    case YETTY_YSDF_BOX:
        return 10u;
    case YETTY_YSDF_SEGMENT:
        return 9u;
    case YETTY_YSDF_TRIANGLE:
        return 11u;
    case YETTY_YSDF_ELLIPSE:
        return 9u;
    case YETTY_YSDF_ARC:
        return 11u;
    case YETTY_YSDF_ROUNDED_BOX:
        return 13u;
    case YETTY_YSDF_RHOMBUS:
        return 9u;
    case YETTY_YSDF_PENTAGON:
        return 8u;
    case YETTY_YSDF_HEXAGON:
        return 8u;
    case YETTY_YSDF_STAR:
        return 10u;
    case YETTY_YSDF_PIE:
        return 10u;
    case YETTY_YSDF_RING:
        return 11u;
    case YETTY_YSDF_HEART:
        return 8u;
    case YETTY_YSDF_CROSS:
        return 10u;
    case YETTY_YSDF_ROUNDED_X:
        return 9u;
    case YETTY_YSDF_CAPSULE:
        return 10u;
    case YETTY_YSDF_MOON:
        return 10u;
    case YETTY_YSDF_EGG:
        return 9u;
    case YETTY_YSDF_OCTOGON:
        return 8u;
    case YETTY_YSDF_HEXAGRAM:
        return 8u;
    case YETTY_YSDF_PENTAGRAM:
        return 8u;
    case YETTY_YSDF_LINEAR_GRADIENT_BOX:
        return 16u;
    case YETTY_YSDF_RADIAL_GRADIENT_BOX:
        return 15u;
    case YETTY_YSDF_SPHERE_3D:
        return 9u;
    case YETTY_YSDF_BOX_3D:
        return 11u;
    case YETTY_YSDF_TORUS_3D:
        return 10u;
    case YETTY_YSDF_CYLINDER_3D:
        return 10u;
    default:
        return 0u;
    }
}

// Primitive size in bytes - use as yetty_ydraw_primitive_size_fn callback
static inline size_t yetty_ysdf_primitive_size(uint32_t type)
{
    return yetty_ysdf_word_count((enum yetty_ysdf_type)type) * sizeof(float);
}

// Affine 2D transform of an SDF primitive's geometry words: translate by
// (offset_x, offset_y) after scaling by (scale_x, scale_y). `geom` points at
// the first geometry word (word 5 of the primitive). Axis-free lengths
// (radii, thickness) scale by the mean of the two factors — exact under
// uniform scale, an approximation otherwise. Direction components, counts,
// ratios, colors and z extents are left untouched.
static inline void yetty_ysdf_geometry_transform(uint32_t type, float *geom, float offset_x,
                                                 float offset_y, float scale_x, float scale_y)
{
    float scale_mean = 0.5f * (scale_x + scale_y);
    (void)scale_mean;
    switch ((enum yetty_ysdf_type)type) {
    case YETTY_YSDF_CIRCLE:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[2] *= scale_mean;
        break;
    case YETTY_YSDF_BOX:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[2] *= scale_x;
        geom[3] *= scale_y;
        geom[4] *= scale_mean;
        break;
    case YETTY_YSDF_SEGMENT:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[2] = geom[2] * scale_x + offset_x;
        geom[3] = geom[3] * scale_y + offset_y;
        break;
    case YETTY_YSDF_TRIANGLE:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[2] = geom[2] * scale_x + offset_x;
        geom[3] = geom[3] * scale_y + offset_y;
        geom[4] = geom[4] * scale_x + offset_x;
        geom[5] = geom[5] * scale_y + offset_y;
        break;
    case YETTY_YSDF_ELLIPSE:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[2] *= scale_x;
        geom[3] *= scale_y;
        break;
    case YETTY_YSDF_ARC:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[4] *= scale_mean;
        geom[5] *= scale_mean;
        break;
    case YETTY_YSDF_ROUNDED_BOX:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[2] *= scale_x;
        geom[3] *= scale_y;
        geom[4] *= scale_mean;
        geom[5] *= scale_mean;
        geom[6] *= scale_mean;
        geom[7] *= scale_mean;
        break;
    case YETTY_YSDF_RHOMBUS:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[2] *= scale_x;
        geom[3] *= scale_y;
        break;
    case YETTY_YSDF_PENTAGON:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[2] *= scale_mean;
        break;
    case YETTY_YSDF_HEXAGON:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[2] *= scale_mean;
        break;
    case YETTY_YSDF_STAR:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[2] *= scale_mean;
        break;
    case YETTY_YSDF_PIE:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[4] *= scale_mean;
        break;
    case YETTY_YSDF_RING:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[4] *= scale_mean;
        geom[5] *= scale_mean;
        break;
    case YETTY_YSDF_HEART:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[2] *= scale_mean;
        break;
    case YETTY_YSDF_CROSS:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[2] *= scale_x;
        geom[3] *= scale_y;
        geom[4] *= scale_mean;
        break;
    case YETTY_YSDF_ROUNDED_X:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[2] *= scale_mean;
        geom[3] *= scale_mean;
        break;
    case YETTY_YSDF_CAPSULE:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[2] = geom[2] * scale_x + offset_x;
        geom[3] = geom[3] * scale_y + offset_y;
        geom[4] *= scale_mean;
        break;
    case YETTY_YSDF_MOON:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[2] *= scale_mean;
        geom[3] *= scale_mean;
        geom[4] *= scale_mean;
        break;
    case YETTY_YSDF_EGG:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[2] *= scale_mean;
        geom[3] *= scale_mean;
        break;
    case YETTY_YSDF_OCTOGON:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[2] *= scale_mean;
        break;
    case YETTY_YSDF_HEXAGRAM:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[2] *= scale_mean;
        break;
    case YETTY_YSDF_PENTAGRAM:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[2] *= scale_mean;
        break;
    case YETTY_YSDF_LINEAR_GRADIENT_BOX:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[2] *= scale_x;
        geom[3] *= scale_y;
        geom[4] *= scale_mean;
        geom[5] = geom[5] * scale_x + offset_x;
        geom[6] = geom[6] * scale_y + offset_y;
        geom[7] = geom[7] * scale_x + offset_x;
        geom[8] = geom[8] * scale_y + offset_y;
        break;
    case YETTY_YSDF_RADIAL_GRADIENT_BOX:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[2] *= scale_x;
        geom[3] *= scale_y;
        geom[4] *= scale_mean;
        geom[5] = geom[5] * scale_x + offset_x;
        geom[6] = geom[6] * scale_y + offset_y;
        geom[7] *= scale_mean;
        break;
    case YETTY_YSDF_SPHERE_3D:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[3] *= scale_mean;
        break;
    case YETTY_YSDF_BOX_3D:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[3] *= scale_x;
        geom[4] *= scale_y;
        break;
    case YETTY_YSDF_TORUS_3D:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[3] *= scale_mean;
        geom[4] *= scale_mean;
        break;
    case YETTY_YSDF_CYLINDER_3D:
        geom[0] = geom[0] * scale_x + offset_x;
        geom[1] = geom[1] * scale_y + offset_y;
        geom[3] *= scale_mean;
        geom[4] *= scale_y;
        break;
    default:
        break;
    }
}

// Compute AABB for an SDF primitive
// data: full primitive data (type + z_order + style + geometry)
// word_count: number of 32-bit words in data
#include <yetty/ycore/types.h>

struct rectangle_result yetty_ysdf_compute_aabb(const float *data, uint32_t word_count);

#ifdef __cplusplus
}
#endif