#include "vterm_internal.h"

// ### The following from http://www.cl.cam.ac.uk/~mgk25/ucs/wcwidth.c
// With modifications:
//   made functions static
//   moved 'combining' table to file scope, so other functions can see it
// ###################################################################

/*
 * This is an implementation of wcwidth() and wcswidth() (defined in
 * IEEE Std 1002.1-2001) for Unicode.
 *
 * http://www.opengroup.org/onlinepubs/007904975/functions/wcwidth.html
 * http://www.opengroup.org/onlinepubs/007904975/functions/wcswidth.html
 *
 * In fixed-width output devices, Latin characters all occupy a single
 * "cell" position of equal width, whereas ideographic CJK characters
 * occupy two such cells. Interoperability between terminal-line
 * applications and (teletype-style) character terminals using the
 * UTF-8 encoding requires agreement on which character should advance
 * the cursor by how many cell positions. No established formal
 * standards exist at present on which Unicode character shall occupy
 * how many cell positions on character terminals. These routines are
 * a first attempt of defining such behavior based on simple rules
 * applied to data provided by the Unicode Consortium.
 *
 * For some graphical characters, the Unicode standard explicitly
 * defines a character-cell width via the definition of the East Asian
 * FullWidth (F), Wide (W), Half-width (H), and Narrow (Na) classes.
 * In all these cases, there is no ambiguity about which width a
 * terminal shall use. For characters in the East Asian Ambiguous (A)
 * class, the width choice depends purely on a preference of backward
 * compatibility with either historic CJK or Western practice.
 * Choosing single-width for these characters is easy to justify as
 * the appropriate long-term solution, as the CJK practice of
 * displaying these characters as double-width comes from historic
 * implementation simplicity (8-bit encoded characters were displayed
 * single-width and 16-bit ones double-width, even for Greek,
 * Cyrillic, etc.) and not any typographic considerations.
 *
 * Much less clear is the choice of width for the Not East Asian
 * (Neutral) class. Existing practice does not dictate a width for any
 * of these characters. It would nevertheless make sense
 * typographically to allocate two character cells to characters such
 * as for instance EM SPACE or VOLUME INTEGRAL, which cannot be
 * represented adequately with a single-width glyph. The following
 * routines at present merely assign a single-cell width to all
 * neutral characters, in the interest of simplicity. This is not
 * entirely satisfactory and should be reconsidered before
 * establishing a formal standard in this area. At the moment, the
 * decision which Not East Asian (Neutral) characters should be
 * represented by double-width glyphs cannot yet be answered by
 * applying a simple rule from the Unicode database content. Setting
 * up a proper standard for the behavior of UTF-8 character terminals
 * will require a careful analysis not only of each Unicode character,
 * but also of each presentation form, something the author of these
 * routines has avoided to do so far.
 *
 * http://www.unicode.org/unicode/reports/tr11/
 *
 * Markus Kuhn -- 2007-05-26 (Unicode 5.0)
 *
 * Permission to use, copy, modify, and distribute this software
 * for any purpose and without fee is hereby granted. The author
 * disclaims all warranties with regard to this software.
 *
 * Latest version: http://www.cl.cam.ac.uk/~mgk25/ucs/wcwidth.c
 */

struct interval {
  int first;
  int last;
};

/* sorted list of non-overlapping intervals of non-spacing characters */
/* yetty: table regenerated from a pinned modern Unicode version by
 * gen-width-tables.py (replacing the original Unicode 5.0 uniset table);
 * see the banner in combining.inc for provenance and the regen command. */
static const struct interval combining[] = {
#include "combining.inc"
};

/* yetty: moved up from the foot of this file (Paul Evans' addition) so
 * mk_wcwidth() can use the generated wide table instead of its original
 * hardcoded Unicode 5.0 ranges. */
static const struct interval fullwidth[] = {
#include "fullwidth.inc"
};

/* yetty: spacing combining marks (category Mc) and virama/halant linkers,
 * generated by gen-width-tables.py from the same pinned wcwidth tables the
 * ucs-detect suite measures against. vterm_unicode_cluster() uses these to
 * fold complex-script clusters to the width wcwidth reports: a base + Mc,
 * or a base + virama + consonant conjunct, both cap at 2 cells. */
static const struct interval spacing_mark[] = {
#include "spacing-mark.inc"
};

static const struct interval virama[] = {
#include "virama.inc"
};


/* auxiliary function for binary search in interval table */
static int bisearch(uint32_t ucs, const struct interval *table, int max) {
  int min = 0;
  int mid;

  if (ucs < table[0].first || ucs > table[max].last)
    return 0;
  while (max >= min) {
    mid = (min + max) / 2;
    if (ucs > table[mid].last)
      min = mid + 1;
    else if (ucs < table[mid].first)
      max = mid - 1;
    else
      return 1;
  }

  return 0;
}


/* The following two functions define the column width of an ISO 10646
 * character as follows:
 *
 *    - The null character (U+0000) has a column width of 0.
 *
 *    - Other C0/C1 control characters and DEL will lead to a return
 *      value of -1.
 *
 *    - Non-spacing and enclosing combining characters (general
 *      category code Mn or Me in the Unicode database) have a
 *      column width of 0.
 *
 *    - SOFT HYPHEN (U+00AD) has a column width of 1.
 *
 *    - Other format characters (general category code Cf in the Unicode
 *      database) and ZERO WIDTH SPACE (U+200B) have a column width of 0.
 *
 *    - Hangul Jamo medial vowels and final consonants (U+1160-U+11FF)
 *      have a column width of 0.
 *
 *    - Spacing characters in the East Asian Wide (W) or East Asian
 *      Full-width (F) category as defined in Unicode Technical
 *      Report #11 have a column width of 2.
 *
 *    - All remaining characters (including all printable
 *      ISO 8859-1 and WGL4 characters, Unicode control characters,
 *      etc.) have a column width of 1.
 *
 * This implementation assumes that uint32_t characters are encoded
 * in ISO 10646.
 *
 * yetty: the combining and wide classifications above are no longer
 * baked in at Unicode 5.0 — both come from the generated interval
 * tables (combining.inc / fullwidth.inc), pinned to one modern Unicode
 * version. See gen-width-tables.py.
 */


static int mk_wcwidth(uint32_t ucs)
{
  /* test for 8-bit control characters */
  if (ucs == 0)
    return 0;
  if (ucs < 32 || (ucs >= 0x7f && ucs < 0xa0))
    return -1;

  /* binary search in table of non-spacing characters */
  if (bisearch(ucs, combining,
               sizeof(combining) / sizeof(struct interval) - 1))
    return 0;

  /* if we arrive here, ucs is not a combining or C0/C1 control character */

  /* yetty: wide lookup now uses the generated East Asian Wide/Fullwidth
   * table (see fullwidth.inc) instead of the original hardcoded
   * Unicode 5.0 ranges, so all tables share one pinned Unicode version. */
  return 1 +
    bisearch(ucs, fullwidth, sizeof(fullwidth) / sizeof(struct interval) - 1);
}


#ifdef USE_MK_WCWIDTH_CJK

/*
 * The following functions are the same as mk_wcwidth() and
 * mk_wcswidth(), except that spacing characters in the East Asian
 * Ambiguous (A) category as defined in Unicode Technical Report #11
 * have a column width of 2. This variant might be useful for users of
 * CJK legacy encodings who want to migrate to UCS without changing
 * the traditional terminal character-width behaviour. It is not
 * otherwise recommended for general use.
 */
static int mk_wcwidth_cjk(uint32_t ucs)
{
  /* sorted list of non-overlapping intervals of East Asian Ambiguous
   * characters, generated by "uniset +WIDTH-A -cat=Me -cat=Mn -cat=Cf c" */
  static const struct interval ambiguous[] = {
    { 0x00A1, 0x00A1 }, { 0x00A4, 0x00A4 }, { 0x00A7, 0x00A8 },
    { 0x00AA, 0x00AA }, { 0x00AE, 0x00AE }, { 0x00B0, 0x00B4 },
    { 0x00B6, 0x00BA }, { 0x00BC, 0x00BF }, { 0x00C6, 0x00C6 },
    { 0x00D0, 0x00D0 }, { 0x00D7, 0x00D8 }, { 0x00DE, 0x00E1 },
    { 0x00E6, 0x00E6 }, { 0x00E8, 0x00EA }, { 0x00EC, 0x00ED },
    { 0x00F0, 0x00F0 }, { 0x00F2, 0x00F3 }, { 0x00F7, 0x00FA },
    { 0x00FC, 0x00FC }, { 0x00FE, 0x00FE }, { 0x0101, 0x0101 },
    { 0x0111, 0x0111 }, { 0x0113, 0x0113 }, { 0x011B, 0x011B },
    { 0x0126, 0x0127 }, { 0x012B, 0x012B }, { 0x0131, 0x0133 },
    { 0x0138, 0x0138 }, { 0x013F, 0x0142 }, { 0x0144, 0x0144 },
    { 0x0148, 0x014B }, { 0x014D, 0x014D }, { 0x0152, 0x0153 },
    { 0x0166, 0x0167 }, { 0x016B, 0x016B }, { 0x01CE, 0x01CE },
    { 0x01D0, 0x01D0 }, { 0x01D2, 0x01D2 }, { 0x01D4, 0x01D4 },
    { 0x01D6, 0x01D6 }, { 0x01D8, 0x01D8 }, { 0x01DA, 0x01DA },
    { 0x01DC, 0x01DC }, { 0x0251, 0x0251 }, { 0x0261, 0x0261 },
    { 0x02C4, 0x02C4 }, { 0x02C7, 0x02C7 }, { 0x02C9, 0x02CB },
    { 0x02CD, 0x02CD }, { 0x02D0, 0x02D0 }, { 0x02D8, 0x02DB },
    { 0x02DD, 0x02DD }, { 0x02DF, 0x02DF }, { 0x0391, 0x03A1 },
    { 0x03A3, 0x03A9 }, { 0x03B1, 0x03C1 }, { 0x03C3, 0x03C9 },
    { 0x0401, 0x0401 }, { 0x0410, 0x044F }, { 0x0451, 0x0451 },
    { 0x2010, 0x2010 }, { 0x2013, 0x2016 }, { 0x2018, 0x2019 },
    { 0x201C, 0x201D }, { 0x2020, 0x2022 }, { 0x2024, 0x2027 },
    { 0x2030, 0x2030 }, { 0x2032, 0x2033 }, { 0x2035, 0x2035 },
    { 0x203B, 0x203B }, { 0x203E, 0x203E }, { 0x2074, 0x2074 },
    { 0x207F, 0x207F }, { 0x2081, 0x2084 }, { 0x20AC, 0x20AC },
    { 0x2103, 0x2103 }, { 0x2105, 0x2105 }, { 0x2109, 0x2109 },
    { 0x2113, 0x2113 }, { 0x2116, 0x2116 }, { 0x2121, 0x2122 },
    { 0x2126, 0x2126 }, { 0x212B, 0x212B }, { 0x2153, 0x2154 },
    { 0x215B, 0x215E }, { 0x2160, 0x216B }, { 0x2170, 0x2179 },
    { 0x2190, 0x2199 }, { 0x21B8, 0x21B9 }, { 0x21D2, 0x21D2 },
    { 0x21D4, 0x21D4 }, { 0x21E7, 0x21E7 }, { 0x2200, 0x2200 },
    { 0x2202, 0x2203 }, { 0x2207, 0x2208 }, { 0x220B, 0x220B },
    { 0x220F, 0x220F }, { 0x2211, 0x2211 }, { 0x2215, 0x2215 },
    { 0x221A, 0x221A }, { 0x221D, 0x2220 }, { 0x2223, 0x2223 },
    { 0x2225, 0x2225 }, { 0x2227, 0x222C }, { 0x222E, 0x222E },
    { 0x2234, 0x2237 }, { 0x223C, 0x223D }, { 0x2248, 0x2248 },
    { 0x224C, 0x224C }, { 0x2252, 0x2252 }, { 0x2260, 0x2261 },
    { 0x2264, 0x2267 }, { 0x226A, 0x226B }, { 0x226E, 0x226F },
    { 0x2282, 0x2283 }, { 0x2286, 0x2287 }, { 0x2295, 0x2295 },
    { 0x2299, 0x2299 }, { 0x22A5, 0x22A5 }, { 0x22BF, 0x22BF },
    { 0x2312, 0x2312 }, { 0x2460, 0x24E9 }, { 0x24EB, 0x254B },
    { 0x2550, 0x2573 }, { 0x2580, 0x258F }, { 0x2592, 0x2595 },
    { 0x25A0, 0x25A1 }, { 0x25A3, 0x25A9 }, { 0x25B2, 0x25B3 },
    { 0x25B6, 0x25B7 }, { 0x25BC, 0x25BD }, { 0x25C0, 0x25C1 },
    { 0x25C6, 0x25C8 }, { 0x25CB, 0x25CB }, { 0x25CE, 0x25D1 },
    { 0x25E2, 0x25E5 }, { 0x25EF, 0x25EF }, { 0x2605, 0x2606 },
    { 0x2609, 0x2609 }, { 0x260E, 0x260F }, { 0x2614, 0x2615 },
    { 0x261C, 0x261C }, { 0x261E, 0x261E }, { 0x2640, 0x2640 },
    { 0x2642, 0x2642 }, { 0x2660, 0x2661 }, { 0x2663, 0x2665 },
    { 0x2667, 0x266A }, { 0x266C, 0x266D }, { 0x266F, 0x266F },
    { 0x273D, 0x273D }, { 0x2776, 0x277F }, { 0xE000, 0xF8FF },
    { 0xFFFD, 0xFFFD }, { 0xF0000, 0xFFFFD }, { 0x100000, 0x10FFFD }
  };

  /* binary search in table of non-spacing characters */
  if (bisearch(ucs, ambiguous,
               sizeof(ambiguous) / sizeof(struct interval) - 1))
    return 2;

  return mk_wcwidth(ucs);
}

#endif

// ################################
// ### The rest added by Paul Evans
// yetty: the fullwidth[] table definition moved above mk_wcwidth().

INTERNAL int vterm_unicode_width(uint32_t codepoint)
{
  if(bisearch(codepoint, fullwidth, sizeof(fullwidth) / sizeof(fullwidth[0]) - 1))
    return 2;

  return mk_wcwidth(codepoint);
}

/* Fitzpatrick skin-tone modifiers — bind to the preceding emoji base. */
static int is_emoji_modifier(uint32_t codepoint)
{
  return codepoint >= 0x1F3FB && codepoint <= 0x1F3FF;
}

/* Regional indicator symbols — a pair forms one flag. */
static int is_regional_indicator(uint32_t codepoint)
{
  return codepoint >= 0x1F1E6 && codepoint <= 0x1F1FF;
}

/*
 * Number of codepoints in the extended grapheme / emoji cluster beginning at
 * codepoints[start], with the cluster's terminal display width written to
 * *width_out. Keeps the sequence-aware width decision inside the vendored
 * libvterm layer (the single width authority) so the state machine advances
 * the cursor by the same amount the wcwidth library (what ucs-detect measures
 * against) reports for the pinned Unicode version:
 *
 *   - combining marks (U+0300… etc.)      absorb, width unchanged
 *   - spacing mark (category Mc)           absorb, cap the cluster at width 2
 *   - virama (halant) + consonant          absorb the joined consonant into
 *                                          the conjunct, cap at width 2
 *   - VS16 (U+FE0F)                        promote a narrow base to width 2
 *   - VS15 (U+FE0E)                        demote to width 1 (text presentation)
 *   - ZWJ (U+200D) + following element     one cluster, width 2 (a ZWJ right
 *                                          after a virama is a conjunct-form
 *                                          request, transparent to width)
 *   - skin-tone modifier (U+1F3FB…1F3FF)   absorb into the base, width 2
 *   - regional-indicator pair              one flag, width 2 (lone RI keeps its
 *                                          own width)
 */
INTERNAL int vterm_unicode_cluster(const uint32_t *codepoints, int start, int npoints,
                                   int grapheme_cluster, int *width_out)
{
  uint32_t base = codepoints[start];
  int i = start + 1;
  int width;
  int pending_virama = 0;

  /* A well-formed cluster never starts with a joiner/combining mark; if one
   * leads (lone ZWJ, stray mark) treat it as zero width and do not swallow a
   * following base into it. */
  if(base == 0x200D || vterm_unicode_is_combining(base))
    width = 0;
  else
    width = vterm_unicode_width(base);

  /* Mode 2027 reset: legacy behaviour — a cluster is the base plus trailing
   * combining marks only, and the width is the plain per-codepoint sum. The
   * extended emoji rules below are skipped, so a ZWJ / skin-tone / flag
   * sequence advances element-by-element as classic wcwidth terminals do. */
  if(!grapheme_cluster) {
    while(i < npoints && vterm_unicode_is_combining(codepoints[i]))
      i++;
    *width_out = width;
    return i - start;
  }

  if(is_regional_indicator(base)) {
    if(i < npoints && is_regional_indicator(codepoints[i])) {
      i++;
      width = 2;
    }
    *width_out = width;
    return i - start;
  }

  while(i < npoints) {
    uint32_t c = codepoints[i];
    if(c == 0xFE0F) {
      width = 2;
      pending_virama = 0;
    }
    else if(c == 0xFE0E) {
      width = 1;
      pending_virama = 0;
    }
    else if(is_emoji_modifier(c)) {
      width = 2;
      pending_virama = 0;
    }
    else if(c == 0x200D) {
      if(pending_virama) {
        /* A ZWJ right after a virama requests an explicit conjunct form; it
         * is transparent to width and keeps the pending virama so a following
         * consonant still folds into this cluster. */
        i++;
        continue;
      }
      /* Absorb the ZWJ and the element it joins; the joined element's own
       * modifiers / further ZWJs are absorbed as the loop continues. */
      width = 2;
      i++;
      if(i < npoints)
        i++;
      continue;
    }
    else if(vterm_unicode_is_virama(c)) {
      /* Defer: the conjunct width is decided by whether a consonant follows. */
      pending_virama = 1;
      i++;
      continue;
    }
    else if(vterm_unicode_is_spacing_mark(c)) {
      /* Spacing mark (Mc): part of this cluster, capped at width 2. */
      width = 2;
      pending_virama = 0;
    }
    else if(vterm_unicode_is_combining(c)) {
      /* Non-spacing mark: absorbed, width unchanged. It breaks a pending
       * virama the same way the wcwidth reference does. */
      pending_virama = 0;
    }
    else {
      /* A base letter. If a virama is pending it joins to form a conjunct
       * capped at 2 and is absorbed here; otherwise this base starts the
       * next cluster. */
      if(pending_virama) {
        width = 2;
        pending_virama = 0;
        i++;
        continue;
      }
      break;
    }
    i++;
  }

  *width_out = width;
  return i - start;
}

INTERNAL int vterm_unicode_is_combining(uint32_t codepoint)
{
  return bisearch(codepoint, combining, sizeof(combining) / sizeof(struct interval) - 1);
}

INTERNAL int vterm_unicode_is_spacing_mark(uint32_t codepoint)
{
  return bisearch(codepoint, spacing_mark, sizeof(spacing_mark) / sizeof(struct interval) - 1);
}

INTERNAL int vterm_unicode_is_virama(uint32_t codepoint)
{
  return bisearch(codepoint, virama, sizeof(virama) / sizeof(struct interval) - 1);
}
