/* yfsvm shader resource set — split out of compiler.c so yetty_yfsvm_core
 * (the compile-bytecode API used by client tools) doesn't transitively pull
 * yetty_yrender / Dawn. This server-only file lives in yetty_yfsvm.
 */

#include <yetty/yfsvm/shader-rs.h>
#include <yetty/yrender/gpu-resource-set.h>

#include <stdbool.h>
#include <string.h>

/* Embedded shader via incbin (generated by cmake) */
extern const unsigned char gyfsvm_shaderData[];
extern const unsigned int gyfsvm_shaderSize;

static struct yetty_ydraw_gpu_resource_set yfsvm_static_shader_rs;
static bool yfsvm_static_shader_rs_initialized = false;

const struct yetty_ydraw_gpu_resource_set *yetty_yfsvm_get_shader_resource_set(void)
{
    if (!yfsvm_static_shader_rs_initialized) {
        memset(&yfsvm_static_shader_rs, 0, sizeof(yfsvm_static_shader_rs));
        yetty_yrender_shader_code_set(&yfsvm_static_shader_rs.shader,
                                      (const char *)gyfsvm_shaderData, gyfsvm_shaderSize);
        yfsvm_static_shader_rs_initialized = true;
    }
    return &yfsvm_static_shader_rs;
}
