labels:
  platform: linux/amd64
  backend: docker

when:
  - event: [push, manual, pull_request, tag]

steps:
  build:
    image: yetty-build:latest
    commands:
      - git lfs install
      - git lfs fetch
      - git lfs checkout
      - make build-android-ytrace-release
