labels:
  platform: linux/amd64
  backend: docker

when:
  - event: [push, manual, pull_request, tag]

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      lfs: true

steps:
  # See android.yml for explanation.
  fix-workspace-perms:
    image: alpine
    commands:
      - chown -R 1000:1000 .

  build:
    image: yetty-build:latest
    commands:
      - make build-desktop-ytrace-release
