labels:
  platform: windows/amd64

when:
  - event: [push, manual, pull_request, tag]

steps:
  build:
    image: powershell
    commands:
      - git lfs install
      - git lfs fetch
      - git lfs checkout
      - cmake -B build-windows-ytrace-release -DCMAKE_BUILD_TYPE=Release -DWEBGPU_BACKEND=dawn -DYETTY_ENABLE_TOOL_QA=OFF -S .
      - cmake --build build-windows-ytrace-release --config Release --parallel
