labels:
  platform: windows/amd64

when:
  - event: [push, manual, pull_request, tag]

steps:
  build:
    image: cmd
    commands:
      - git lfs install
      - git lfs fetch
      - git lfs checkout
      - call "C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64
      - cmake -B build-windows-ytrace-release -G Ninja -DCMAKE_BUILD_TYPE=Release -DWEBGPU_BACKEND=dawn -DYETTY_ENABLE_TOOL_QA=OFF -DCMAKE_TLS_CAINFO=C:/Strawberry/perl/vendor/lib/Mozilla/CA/cacert.pem -S .
      - cmake --build build-windows-ytrace-release --config Release --parallel
